### ISSUE TITLE
Web site

### ISSUE THREAD

**Issue by JustMrPhoenix** [cyd01/KiTTY#1]
Hi,
Today I tried to download a new version of KiTTY and none of the download links seems to work. I end up getting same 404 page
![Page](https://i.imgur.com/RrGzuGQ.png)
P.S. Captcha in feedback form is also broken so I have to put my issue here.

**Comment by lars18th** [comment]
Hi @cyd01 ,

My recomendation is to move all Downloads (Releases), Infos (Wiki) and Forum (Issues) to GitHub and leave only the original web as a simple static homepage.

You agree?

**Comment by cyd01** [comment]
I've already planed to rewrite the original website with static pages (based on markdown).
The releases and forum are already on Github.

**Comment by lars18th** [comment]
This topic can be closed?
IMHO I think so!
