### ISSUE TITLE
Help compiling

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#10]
Hi,

I need some help to setup the development environment.

- I setup Cygwin **with** MinGW.
- I modified the file `/0.70_My_PuTTY/windows/MAKEFILE.MINGW` with:
 -- `TOOLPATH = /usr/bin/i686-w64-mingw32-`
- But I get an error when I compile with `make -f MAKEFILE.MINGW putty.exe`.

See the error:
```
$ make -f MAKEFILE.MINGW putty.exe
/usr/bin/i686-w64-mingw32-gcc  -Wall -O2 -D_WINDOWS -DWIN32S_COMPAT -D_NO_OLDNAMES -I.././ -I../charset/ -I../windows/ -I../unix/ -D_WIN32_IE=0x0500 -DWINVER=0x0501 -D_WIN32_WINDOWS=0x0410 -D_WIN32_WINNT=0x0501 -DAUTO_WINSOCK -DUSE_CAPI -DCOVERITY -DNO_MULTIMON -DNO_HTMLHELP -Wall -O2 -D_WINDOWS -DWIN32S_COMPAT -DFDJ1 -DPERSOPORT -DCYGTERMPORT -DIMAGEPORT -DRECONNECTPORT -DHYPERLINKPORT -DZMODEMPORT -DSTARTBUTTON -DLAUNCHERPORT -DSAVEDUMPPORT -DKEYMAPPINGPORT -DWINCRYPTPORT -DTUTTYPORT -DPORTKNOCKINGPORT -DPUTTYXPORT -DWTSPORT -DPRINTCLIPPORT -DRUTTYPORT -DDISABLEALTGRPORT -DADBPORT -I.././ -I../../ -I../charset/ -I../windows/ -I../unix/ -I../mac/ -I../macosx -I../../base64 -I../../bcrypt -I../../md5 -I../../regex -I../../url -I../../wincrypt -I../../rutty  -c ../aqsync.c
In file included from /usr/i686-w64-mingw32/sys-root/mingw/include/wincrypt.h:769:0,
                 from /usr/i686-w64-mingw32/sys-root/mingw/include/windows.h:95,
                 from ../windows/winstuff.h:11,
                 from ../puttyps.h:10,
                 from ../putty.h:26,
                 from ../aqsync.c:12:
/usr/i686-w64-mingw32/sys-root/mingw/include/ncrypt.h:147:11: error: unknown type name 'BCryptBuffer'
   typedef BCryptBuffer NCryptBuffer;
           ^~~~~~~~~~~~
/usr/i686-w64-mingw32/sys-root/mingw/include/ncrypt.h:148:11: error: unknown type name 'BCryptBuffer'
   typedef BCryptBuffer *PNCryptBuffer;
           ^~~~~~~~~~~~
/usr/i686-w64-mingw32/sys-root/mingw/include/ncrypt.h:149:11: error: unknown type name 'BCryptBufferDesc'
   typedef BCryptBufferDesc NCryptBufferDesc;
           ^~~~~~~~~~~~~~~~
/usr/i686-w64-mingw32/sys-root/mingw/include/ncrypt.h:150:11: error: unknown type name 'BCryptBufferDesc'
   typedef BCryptBufferDesc *PNCryptBufferDesc;
           ^~~~~~~~~~~~~~~~
In file included from /usr/i686-w64-mingw32/sys-root/mingw/include/windows.h:95:0,
                 from ../windows/winstuff.h:11,
                 from ../puttyps.h:10,
                 from ../putty.h:26,
                 from ../aqsync.c:12:
/usr/i686-w64-mingw32/sys-root/mingw/include/wincrypt.h:3149:7: error: unknown type name 'BCRYPT_KEY_HANDLE'
       BCRYPT_KEY_HANDLE hCNGContentEncryptKey;
       ^~~~~~~~~~~~~~~~~
/usr/i686-w64-mingw32/sys-root/mingw/include/wincrypt.h:3253:5: error: unknown type name 'BCRYPT_KEY_HANDLE'
     BCRYPT_KEY_HANDLE hCNGContentEncryptKey;
     ^~~~~~~~~~~~~~~~~
In file included from ../puttyps.h:10:0,
                 from ../putty.h:26,
                 from ../aqsync.c:12:
../windows/winstuff.h:330:18: error: unknown type name 'WSAEVENT'; did you mean 'PSERVENT'?
         (SOCKET, WSAEVENT, long));
                  ^
../windows/winstuff.h:134:40: note: in definition of macro 'DECL_WINDOWS_FUNCTION'
     typedef rettype (WINAPI *t_##name) params; \
                                        ^~~~~~
../windows/winstuff.h:135:13: error: unknown type name 't_WSAEventSelect'
     linkage t_##name p_##name
             ^
../windows/winstuff.h:135:13: note: in definition of macro 'DECL_WINDOWS_FUNCTION'
     linkage t_##name p_##name
             ^~
../windows/winstuff.h:333:18: error: unknown type name 'WSAEVENT'; did you mean 'PSERVENT'?
         (SOCKET, WSAEVENT, LPWSANETWORKEVENTS));
                  ^
../windows/winstuff.h:134:40: note: in definition of macro 'DECL_WINDOWS_FUNCTION'
     typedef rettype (WINAPI *t_##name) params; \
                                        ^~~~~~
../windows/winstuff.h:333:28: error: unknown type name 'LPWSANETWORKEVENTS'; did you mean 'LPSERVENT'?
         (SOCKET, WSAEVENT, LPWSANETWORKEVENTS));
                            ^
../windows/winstuff.h:134:40: note: in definition of macro 'DECL_WINDOWS_FUNCTION'
     typedef rettype (WINAPI *t_##name) params; \
                                        ^~~~~~
../windows/winstuff.h:135:13: error: unknown type name 't_WSAEnumNetworkEvents'
     linkage t_##name p_##name
             ^
../windows/winstuff.h:135:13: note: in definition of macro 'DECL_WINDOWS_FUNCTION'
     linkage t_##name p_##name
             ^~
In file included from ../aqsync.c:12:0:
../putty.h:38:13: warning: 'SetDefaultDllDirectories' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 BOOL WINAPI SetDefaultDllDirectories( DWORD DirectoryFlags ) ;
             ^~~~~~~~~~~~~~~~~~~~~~~~
../putty.h:39:13: warning: 'CryptProtectMemory' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 BOOL WINAPI CryptProtectMemory( LPVOID pData, DWORD  cbData, DWORD  dwFlags );
             ^~~~~~~~~~~~~~~~~~
make: *** [MAKEFILE.MINGW:433: aqsync.o] Error 1

```

Any idea?

**Comment by lars18th** [comment]
Hi @cyd01 ,

Please, can you share some guide about how to compile it?

Thank you!

**Comment by cyd01** [comment]
The compilation is decribed here:
http://www.9bis.net/kitty/?page=How%20to%20compile

**Comment by lars18th** [comment]
> The compilation is decribed here: http://www.9bis.net/kitty/?page=How%20to%20compile

Hi @cyd01 ,

I know it! And I do it. So if you read my message you can see that I prepared the environment as needed, but it doesn't work.

Please, share a more _precise_ description, or try to fix the compilation error.

**Comment by cyd01** [comment]
I thing you use 64bits gcc compiler. I've never succedded to compile 64bits. Can you try recent 32bits gcc ?

**Comment by lars18th** [comment]
> I thing you use 64bits gcc compiler. I've never succedded to compile 64bits. Can you try recent 32bits gcc ?

I'll try.
However, please note that I use "i686-w64-mingw32-gcc" and not the "x86_64-w64-mingw32-gcc" so the target is 32bit and not 64bit. I figure you speak about this, right?

In the meantime, can you please post a _slightly_ more precise description?

**Comment by lars18th** [comment]
Hi @cyd01 ,

I installed a full MSYS with MinGW32 and yes, it compiles (with some errors).

Here the "more precise" description:

- Download the `mingw-builds-install.exe` from here: https://sourceforge.net/projects/mingwbuilds/files/host-windows/releases/4.8.0/32-bit/
- Execute the installer and select the GUI.
- After installing it, only the "packager manager" is installed. Execute `$MinGW\libexec\mingw-get\guimain.exe` and select in Basic Setup: "mingwg-developer-tools", "mingw32-base", "mingw32-gcc-g++" and "msys-base".
- After finish, to open the SHELL execute `$MinGW\msys\1.0\msys.bat` from from this shell you can call to make where the KiTTY source is.
- Execute `cd $KiTTY_DIR/0.70_My_PuTTY/windows` and execute `make -f MAKEFILE.MINGW 9bis`.

I hope you "upgrade" the description page of how to compile it, and advise that MinGW-64 can't compile KiTTY (I don't know the reason).

Regards.

**Comment by cyd01** [comment]
Why did you choose 4.8.0 version ?
It is quite old. May be it can explain the issue. I'm not at work to check, but I thing mine is 6.3.x.
Try to get a more recent one at http://mingw.org/.
Regards.

**Comment by lars18th** [comment]
> Why did you choose 4.8.0 version ?

Because it's the last version in the Sourceforge repository:
https://sourceforge.net/projects/mingwbuilds/files/host-windows/releases/

> It is quite old. May be it can explain the issue. I'm not at work to check, but I thing mine is 6.3.x.
> Try to get a more recent one at http://mingw.org/.

In this homepage the last version of "setup" is "0.6.3 Beta":
https://osdn.net/projects/mingw/releases/p15522

I'm not sure what it's the correct one.
And I feel this the reason to request a _slightly_ more descriptive how to.

Regards.

**Comment by cyd01** [comment]
Hi lars18th.
I'm not sure it is the right place to describe the installation of MinGW. There is a Wiki on their website that explain it: http://mingw.org/wiki/Getting_Started
But what I've done was to get the installer "mingw-get-setup.exe".
I chose to install MinGW in E:\DEV\MinGW directory, and I chose to install some packages I need, especially Msys (base, bash, core, coreutils, diffutils, grep, sed) and MinGW (base, binutils, gcc, g++, almost all lib*, ncurses, pdcurses, pthreads and very important w32api).
I confirm my gcc version is 6.3.0
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=E:\DEV\MinGW\bin\gcc.exe
COLLECT_LTO_WRAPPER=e:/dev/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --with-gmp=/mingw --with-mpfr --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
```
The installation is not very recent: may 2018

One important think you may check with MinGW is you configuration in the /etc/fstab file. Real path should be %YourInstallDir%\msys\1.0\etc\fstab I guess.
Mine is 
```
$ cat /etc/fstab
# /etc/fstab -- mount table configuration for MSYS.
# Please refer to /etc/fstab.sample for explanatory annotation.

# MSYS-Portable needs this "magic" comment:
# MSYSROOT=E:/DEV/MinGW/msys/1.0

# Win32_Path                            Mount_Point
#-------------------------------------  -----------
E:/DEV/MinGW                            /mingw
```

**Comment by lars18th** [comment]
Hi @cyd01 ,

Thank you for your comments!
Now I have a working environment to compile it. :wink: 
It seems that it doesn't work with MinGW-64 inside Cygwin; so the installation of the MSYS it's a requirement.

Futhermore, I do an patch to support the Compression with WinSCP. Please check my PR #12 and merge it. Also I compiled it for the 0.70 (check the binary).

Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Please merge my PR #21 to improve the README. :wink:
