### ISSUE TITLE
Feature Request: Set default global font

### ISSUE THREAD

**Issue by ocomsoft** [cyd01/KiTTY#102]
I changed all the font settings in the registry for all the sessions I imported from putty to a better font but that has all been reset. 

Would it be possible to set a "global" font so all windows use the font.

The courier font that it defaults to is hard to read on some of my monitors on Windows 10

**Comment by cyd01** [comment]
KiTTY Registry is automatically created at very first start 
```
// Check for KiTTY registry key. If not, copy from PuTTY one
void TestRegKeyOrCopyFromPuTTY( HKEY hMainKey, char * KeyName ) { 
	HKEY hKey ;
	if( RegOpenKeyEx( hMainKey, TEXT(KeyName), 0, KEY_READ, &hKey) == ERROR_SUCCESS ) {
		RegCloseKey( hKey ) ;
	} else {
		RegCreateKey( hMainKey, TEXT(KeyName), &hKey ) ;
		RegCloseKey( hKey ) ;
		RegCopyTree( hMainKey, "Software\\SimonTatham\\PuTTY", TEXT(KeyName) ) ;
	}
}
```

You can update all sessions settings with a undocumented feature.
Create a new file named `kitty.ses.updt` with you settings, next to your kitty.exe binary.
The file is 4ko max size, and the format is registry file like. Example to modify proxy credentials:
```
"ProxyUsername"="mylogin"
"ProxyPassword"="mypassword"
```
Start any KiTTY session. `kitty.ses.updt` is replaced by a registry file you just have to run.

**Comment by ocomsoft** [comment]
Thanks for your help.. That is useful to know.  However, it seems the problem was not that I can set the font but that it reverts to Courier New 10pt. I have set them ALL to the another font that works better on all screens BUT later on it's resetting back to this font.

**Comment by CWempe** [comment]
I think this feature request would solve your problem: https://github.com/cyd01/KiTTY/issues/76
