### ISSUE TITLE
Windows 10 Can't set custom font?

### ISSUE THREAD

**Issue by bcookatpcsd** [cyd01/KiTTY#103]
Not sure why I can't seem to set the font.. but I have a freshly formatted Win 10 N install.. 

https://www.google.com/get/noto/ (noto fonts from google..)

https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMono-hinted.zip (looking for noto sans mono condensed - it's in there..)

Install the font in the Windows\Fonts directory (verify that's the location, not the local user font repo)

Download kitty 73.2.2, run it, Window, Appearance, [Change], Noto doesn't appear in the list.. 

But open something like Notepad++ and it works just fine.. 

Even ran kitty -cleanup.. 

Just confused what I might be doing wrong.. 

Also checked Putty, doesn't show in their either.. is there something about the ttf font I'm downloading that isn't right?

**Comment by CWempe** [comment]
Maybe this is related:

https://superuser.com/questions/195646/monaco-font-not-appearing-in-putty-font-list

**Comment by cyd01** [comment]
I've downloaded this [file](https://noto-website-2.storage.googleapis.com/pkgs/NotoMono-hinted.zip).
And installed **NotoMono-Regular.ttf**.
Everything was fine:
![image](https://user-images.githubusercontent.com/34154246/86821167-527a7b80-c08a-11ea-97d7-ea5c216a6e38.png)
