### ISSUE TITLE
Version mismatch 

### ISSUE THREAD

**Issue by opsi-archIT-KIT** [cyd01/KiTTY#104]
In property 'file version' of file 'kitty.exe' (latest release 0.73.2.2 from yesterday) is stated a wrong version.

See screenshot...
![kitty-version-mismatch](https://user-images.githubusercontent.com/13115745/73435037-2a068c80-4348-11ea-8d59-09146ed14ed7.jpg)

**Comment by lars18th** [comment]
Hi @opsi-archIT-KIT ,

With the last version 0.73.2.3 I see the same version in both.

Please, @cyd01 can do you check if the info in the DETAILS propierties is updated?

Regards.

**Comment by opsi-archIT-KIT** [comment]
With release 0.73.2.3 version number is in sync again.
