### ISSUE TITLE
[RFD] Join efforts with forks of KITTY

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#107]
Hi @cyd01 and @adizero,

I discovered this recent fork of KITTY: https://github.com/adizero/KiTTY
It has interesting changes:
- Improves mouse support.
- Improves cursor style support.
- Improves Fn and keypad keys.
- Fixes some bug.
- Docker compilation style.

I suggest to @adizero to provide PRs of his improvements. And to @cyd01 to accept them and merge with the main branch.

I hope new developers want to contribute to improve the most valuable PuTTY fork... KITTY!

**Comment by cyd01** [comment]
Ok for merging new feature.

Just for your information: KiTTY is already compiled into a Docker
container. See [
http://www.9bis.net/kitty/#!pages/HowToCompile.md](http://www.9bis.net/kitty/#!pages/HowToCompile.md)
.
It is even possible to make a 64bits version of the soft.

**Comment by lars18th** [comment]
> Just for your information: KiTTY is already compiled into a Docker container.

So, then perhaps it will interesting to use the Github ACTIONS to provide a continious compilation (like travis-CI).

> It is even possible to make a 64bits version of the soft.

I hope you can provide some betas to test them soon.

Regards.

**Comment by adizero** [comment]
OK, I will try to create the PRs for the improvements in the next few days.

**Comment by lars18th** [comment]
> OK, I will try to create the PRs for the improvements in the next few days.

Great @adizero , and thank you for your collaboration!
(_And please excuse me for writing an off-scope issue in one of your other repositories._)

Regards.

**Comment by lars18th** [comment]
Hi,

I hope the PRs from @adizero #124, #125, #126, #127 and #128 will be soon merged. Almost, the simple to review (126-128).

Thank you @adizero for your contribution! :+1:

**Comment by cyd01** [comment]
Thank all for your help.
