### ISSUE TITLE
Allways Visible in the Window Title

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#108]
Hi @cyd01 ,

When reordering my shortcuts I see this: The PROTECT function adds the word "(PROTECTED)" to the Window Title. However, the ALLWAYS_VISIBLE (on-top-window) doesn't print anything. I feel it will be more _consistent_ to mimic the same functionality. I suggest to add the word "(ON TOP)".

You agree?

**Comment by cyd01** [comment]
Done in next official release

**Comment by lars18th** [comment]
As this is implemented in the version 0.73.2.3 I close this issue.
Thank you! :+1:
