### ISSUE TITLE
cannot call sessions from conmmand line if session is in subfolder

### ISSUE THREAD

**Issue by Vasilich** [cyd01/KiTTY#109]
I use many saved connections, and to sort them, i use subfolders. Unfortunately i cannot manage to use desktop shortcuts for such sessions. All the ways i've tried to start session from subfolder ending up in launching kitty main window.
Is there any chance to support starting such sessions from commadline?
P.S. calling sessions in main folder works perfectly.
P.P.S. i use portable version of kitty

**Comment by cyd01** [comment]
You muse use the **-folder** command-line option.
See the command-line list here: [http://www.9bis.net/kitty/#!pages/CommandLine.md](http://www.9bis.net/kitty/#!pages/CommandLine.md)
