### ISSUE TITLE
"Windows Defender" removes the 0.73.2.3 kitty.exe as a "Trojan_Win32/Wacatac.C!ml"

### ISSUE THREAD

**Issue by AntonOks** [cyd01/KiTTY#111]
"Windows Defender" kicks the 0.73.2.3 kitty.exe now as a "[Trojan_Win32/Wacatac.C!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Wacatac.C!ml)"
Never had virus problems with the previous KiTTY versions so far, but now I lost my favorite and life saver tool....

see also #105

**Comment by bersbersbers** [comment]
I propose you close this as a duplicate, there isn't really any new information over #105.

**Comment by lars18th** [comment]
> I propose you close this as a duplicate, there isn't really any new information over #105.

It seems that a lot of antivirus detect KiTTY as trojan. So we need help. Please, explain how to overcome this problem. I'm sure that @cyd01 will implement the solution if you can explain it.

**Comment by cyd01** [comment]
Duplicate #105
