### ISSUE TITLE
[Crash]Calling ‘User Command’ crashes KiTTY.

### ISSUE THREAD

**Issue by kissglay** [cyd01/KiTTY#114]
Sending ‘User Command’ from system menu or using hotkeys(i.e. CTRL+SHIFT+A and so on), after 2 to 3 times (sometimes 1st time), kiTTY exit without any error messages.

**Comment by cyd01** [comment]
Never reproduced yet!
Is there something special with the user command you are running ?

**Comment by kissglay** [comment]
This problem may result from bug #113
