### ISSUE TITLE
Status of 64bit version

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#117]
Hi @cyd01 ,

Thank you for the release 0.73.2.4. From my point of view with this release all is working (except the the Z-Modem support, delayed at time; and some pending bugs). :+1: 

However, I see that you are compiling 64bit versions in last commits. Why not publish them as BETA to start testing them? Futhermore, we welcome any comment about the 64bit support: Something fails? You need help?

Regards.

**Comment by cyd01** [comment]
64bits version is now added at [FossHub CDN](https://www.fosshub.com/KiTTY.html).

**Comment by lars18th** [comment]
> 64bits version is now added at [FossHub CDN](https://www.fosshub.com/KiTTY.html).

Thank you! I'll try it. However, as I only use the PORTABLE version, can you upload the 64bit portable version too?

Regards.

**Comment by cyd01** [comment]
To be honnest Portable version does not really exist.
In fact there is only one KiTTY version that can be configured in two
different modes.
See the page http://www.9bis.net/kitty/#!pages/Portability.md to find out
how to switch the binary from registry to portable mode.
Be advise that the upload of the 64bits version is not automatic yet. I've
never used Github Actions to automate building. But I'll work on it I
promise. I'm a Gitlab-man rather that Github. It is what we use at work.
Best Regards
Cyd

**Comment by lars18th** [comment]
In the initial tests the 64bit versions seems to run without troubles. :+1:

**Comment by cyd01** [comment]
Ok
I've made a CI to automate building of 32 & 64 bits KiTTY version.
I can download artifacts from Github for myself. But it seems no one else can do it. Do you know if it is possible to publish for other ?

**Comment by lars18th** [comment]
Hi @cyd01 ,

> I can download artifacts from Github for myself. But it seems no one else can do it. Do you know if it is possible to publish for other ?

The artifacts can be downloaded by anyone. I tested it with the last compilation: https://github.com/cyd01/KiTTY/actions/runs/45816868

The CI automation of Github with the Actions section seems to be very powerful. However, it requires some work. Please, first reduce the _interval_ of compilation to 1 time every day... or best, every time after a new commit. I feel you're dispatching at time a new compilation every two hours. Second, I know (from another project) that is possible to trigger a copy of the artifacts to another web using FTP. Perhaps a simple solution can be to copy them to FossHub after the compilation is complete. And only when a new release is done you put it manually in the Releases section.

You agree?
Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

You agree with the close of this issue? I'm using the 64bit version for a week without _any_ trouble. I feel it's ready to daily use.

Your opinion?

**Comment by lars18th** [comment]
Hi @cyd01 ,

After more days using the 64bit version, I need to comment that time to time a serious bug appears: _"Out of memory"_, and the KiTTY crashes. I don't know the reason, but something seems to generate a memoryleak or a related issue.

I only comment it here for your information. Perhaps other users suffer similar errors. So, I recommend to use the 64bit version only for testing.

Regards.

**Comment by cyd01** [comment]
Untill I can find time to work on it, 64 bits version will not be officially published on [Fosshub](https://www.fosshub.com/KiTTY.html) website.
It will be automatically built in [Github actions](https://github.com/cyd01/KiTTY/actions) for testing purpose.

**Comment by lars18th** [comment]
Hi @cyd01 ,

As you have changed to GCC 9.2 in v0.74.2.3, why don't re-enable the 64bit compilation? It will be only for testing... please!

Regards.

**Comment by cyd01** [comment]
Because compilation fails on my Windows 10 with gcc 9.2 64 bits.

**Comment by lars18th** [comment]
> Because compilation fails on my Windows 10 with gcc 9.2 64 bits.

In any case, I'll try for some days with this version https://github.com/cyd01/KiTTY/actions/runs/275024480
At the moment it works (almost for simple actions).

Thank you!
