### ISSUE TITLE
RFE: Open new connection --> CTRL+TAB

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#118]
Hi @cyd01 ,

I request one small change to improve the usability: When opening the NEW CONNECTION with a shortcut (that's using the keyboard _only_), the default focus is in the textbox of the HOST. And this is nice, as you can write the target host directly and connect. However, if you want to change to the list of Saved Sessions, then you need to type `<TAB>;<TAB>;<TAB>;<TAB>`. That's _four_ key strokes. Perhaps some more friendly solution is available.

That's my suggestion:
- With the combination `<CTRL>+<TAB>` from the Host Name textbox you go directly to the Saved Sessions list.

You agree?

**Comment by lars18th** [comment]
Hi,

Please note that `<SHIFT>+<TAB>` does the reverse as `<TAB>`. So from Host Name you can go to the Category tree with one keystroke. My suggestion is to add `<CTRL>+<TAB>` to the current `<TAB>` and `<SHIFT>+<TAB>` shortcuts.

Futhermore, if you want this _new_ `<CTRL>+<TAB>` shortcut can be: "move between _blocks_". For example, in Session: Host Name --> Saved Sessions --> Category tree. And similar for other Windows.

I hope you want to consider it (almost the specific part of Host Name --> Saved Sessions).
Regards.

**Comment by cyd01** [comment]
It seems that navigation between configuration dialog box elements is managed directly by Windows.
I'm not sure it can be possible to intercept `<CTRL>+<TAB>` or `<SHIFT>+<TAB>`.

**Comment by lars18th** [comment]
OK, then I'll search for a solution. Anyway please leave open this issue until we have a definitive answer.

And thank you for this good tool!

**Comment by lars18th** [comment]
Hi @cyd01 ,

As this can not be implemented, then I close the issue.
