### ISSUE TITLE
Virus scan of the latest KiTTY

### ISSUE THREAD

**Issue by m1xed0s** [cyd01/KiTTY#119]
I did a quick scan with Virustotal of the latest KiTTY (0.73.2.4 & 64bit) as shown in screenshots below. Any potential document regards?
![normal](https://user-images.githubusercontent.com/11614958/75256852-1e28b180-57b2-11ea-87b7-941df17b9061.PNG)
![64bit](https://user-images.githubusercontent.com/11614958/75256863-21bc3880-57b2-11ea-88f7-c0fb188b718b.PNG)

BTW, the Cisco Amp for endpoint on my laptop also thinks it is virus... Regarding the kitty64, is it just a 64bit ONLY per-compiled executable OR there are also extra features?

**Comment by lars18th** [comment]
Hi @m1xed0s ,

Please close this issue as this is discussed in #115 . And also note that @cyd01 doesn't have any solution for this false positive. If you know how to overcome this problem then share it with us.

Regards.

**Comment by lars18th** [comment]
> Regarding the kitty64, is it just a 64bit ONLY per-compiled executable OR there are also extra features?

_ONLY_ pre-compiled. No difference at all except for the target platform.
