### ISSUE TITLE
Some session-specific settings do not apply when re-using a connection

### ISSUE THREAD

**Issue by shippy** [cyd01/KiTTY#121]
**Context:** I have two KiTTY sessions. They connect to the same remote, so when they're both active at the same time, they reuse the other's connection.

_Session 1:_ connects to `server01` with port forwarding (configured in Connection/SSH/Tunnel), and minimizes to tray (configured in Window/Behavior). 

_Session 2:_ connects to `server01`, then runs `ssh server02\ntmux a\n` (configured in Data/Command).

**Expected behavior:** the behavior of Session 1 should be the same whether it's launched before or after Session 2.

**Actual behavior:**

- If I launch Session 1 first, then Session 2's remote command doesn't execute.
- If I launch Session 2 first, then Session 1 doesn't minimize to tray.

**Comment by cyd01** [comment]
Do you still have this behavior ?

**Comment by cyd01** [comment]
No response ?
