### ISSUE TITLE
no instant GUI updates after returning from standby

### ISSUE THREAD

**Issue by soletan** [cyd01/KiTTY#129]
For some while I've encountered issues with KiTTY updating its GUI after returning from local device's standby.

For example, I might be leaving my PC for an hour. On return I have to re-login and see all the KiTTY connections still running. When I try to enter some command most of them fail to instantly show what I'm typing or what is sent by the remote server. However, when I click into the window or on its frame the update is performed. This "mode" is kept going so I would have to click into window whenever I'm typing something. For recovery I close the affected connection and re-connect to the same server.

**UPDATE:** I'm using Windows 10 Pro 1903 build 18362.657, currently it's KiTTY 0.73.2.4p portable.

**Comment by cyd01** [comment]
Too much old.

**Comment by soletan** [comment]
But still valid ... this concept of closing bugs because of their age is kind of strange.
