### ISSUE TITLE
Crash on ctrl-clicking URL - KiTTY v0.73.2.6, Windows 10

### ISSUE THREAD

**Issue by thepowersgang** [cyd01/KiTTY#133]
Clicking on a URL will usually crash KiTTY (not always, but most of the time).
Running under the VS2019 debugger shows an invalid memory read of `0xFFFFFFFF` at `0x0046FA3B`
Crashing instruction is `movaps      xmmword ptr [esp+10h],xmm4`

**Comment by thepowersgang** [comment]
Extra information: When I closed the debugger (letting KiTTY crash) the URL opened and the KiTTY instance closed. I have created a crash dump, but it's 25MB compressed so won't upload unless it's requested.

**Comment by lars18th** [comment]
Hi,

I see similar problems with the 64bit version: crash when using some clipboard function and/or the URL. I suggest @cyd01 to check the code. Perhaps some fulty pointer exist.

Or we need to use some profiler to search for faulty code.

I hope it helps.
Regards.

**Comment by cyd01** [comment]
For the moment, I choose to remove 64bits version from the official
[download page](https://www.fosshub.com/KiTTY.html). It is not ready yet.
Cyd

**Comment by lars18th** [comment]
Hi @thepowersgang ,

Please check the last release v0.73.2.11: https://github.com/cyd01/KiTTY/releases/tag/0.73.2.11
Your crash is resolved using this version?

**Comment by thepowersgang** [comment]
Appears to have been fixed. Can't be 100% sure yet, as the crash didn't always trigger - but I opened several links and had no crash or hiccups.
I'll close the issue and re-open if I see it crash with the new version.

**Comment by thepowersgang** [comment]
Was working well for a week or so, but started crashing again (possibly related to rebooting the machine?)

Same address being accessed, but different instruction (still a XMM reg loaded relative to ESP)

`Exception thrown at 0x0046D101 in kitty-0.73.2.11.exe: 0xC0000005: Access violation reading location 0xFFFFFFFF.`

The surrounding instructions seem to be doing a SHA256 calculation, might not be the `movdqa` that is faulting (maybe it's the preceding `sha256msg1`)

```
0046D0A4  sub         esp,3Ch  
0046D0A7  movdqu      xmm3,xmmword ptr [edx]  
0046D0AB  movdqa      xmm7,xmmword ptr ds:[53D650h]  
0046D0B3  pshufb      xmm3,xmm7  
0046D0B8  movdqa      xmm0,xmmword ptr ds:[53D660h]  
0046D0C0  paddd       xmm0,xmm3  
0046D0C4  movdqa      xmm2,xmmword ptr [eax]  
0046D0C8  movdqa      xmm1,xmmword ptr [eax+10h]  
0046D0CD  sha256rnds2 xmm1,xmm2,xmm0  
0046D0D1  pshufd      xmm0,xmm0,0Eh  
0046D0D6  sha256rnds2 xmm2,xmm1,xmm0  
0046D0DA  movdqu      xmm4,xmmword ptr [edx+10h]  
0046D0DF  pshufb      xmm4,xmm7  
0046D0E4  movdqa      xmm0,xmmword ptr ds:[53D670h]  
0046D0EC  paddd       xmm0,xmm4  
0046D0F0  sha256rnds2 xmm1,xmm2,xmm0  
0046D0F4  pshufd      xmm0,xmm0,0Eh  
0046D0F9  sha256rnds2 xmm2,xmm1,xmm0  
0046D0FD  sha256msg1  xmm3,xmm4  
0046D101  movdqa      xmmword ptr [esp],xmm3  ; << This one
0046D106  movdqu      xmm6,xmmword ptr [edx+20h]  
```

**Comment by kaeltis** [comment]
Same issue here, clicking links often crashes KiTTY.

**Comment by cyd01** [comment]
Please send me the url you are trying to click and the settings of your current session (in Window/hyperlinks panel).

**Comment by kaeltis** [comment]
It doesn't happen always, when trying to reproduce it I sometimes need 10 or more tries, but it seems to happen with all links.
The once I tested it with are those in the welcome message when loggin in to a ubuntu 18.04 server:

`https://www.techrepublic.com/article/how-to-install-microk8s-on-macos/`
`https://ubuntu.com/livepatch`

![image](https://user-images.githubusercontent.com/809734/86822212-9e79f000-c08b-11ea-8981-cc232e021b92.png)

**Comment by cyd01** [comment]
Not reproduced. I've clicked 50 times and no crash.
Do you use normal mode or portable mode ?
Do you use 32bits or 64bits version ? I have a doubt with the 64bits version of regex library.

**Comment by lars18th** [comment]
> I have a doubt with the 64bits version of regex library.

Me too. I suffer time to time crashes with the 64bit version without any apparent cause.

**Comment by kaeltis** [comment]
> 
> 
> Not reproduced. I've clicked 50 times and no crash.
> Do you use normal mode or portable mode ?
> Do you use 32bits or 64bits version ? I have a doubt with the 64bits version of regex library.

I'm using the `kitty.exe` from the release builds on a 64bit system with `savemode=dir` in `kitty.ini`
When trying to reproduce it, I was clicking the link and if it didn't crash after about 10 tries I duplicated the session where it would then sometimes crash the first time clicking a link there.

**Comment by cyd01** [comment]
Issue closed due to inactivity
