### ISSUE TITLE
There seems to be no "help" command on command line

### ISSUE THREAD

**Issue by johny-mnemonic** [cyd01/KiTTY#138]
I tried to search for this multiple times, but it seems like the only place where to find list of command line options is the project website and source code.

Would it be possible to add standard "help" option to the list of supported options, so that one doesn't need to go to website to find how to use the tool from command line?

**Comment by MaxPeal** [comment]
@cyd01 any chance to add a help? or at least a --dump-options and --version?

**Comment by lars18th** [comment]
Hi,

I suggest to almos print anything when calling with `/help`. Then in the future, we can try to improve the help including some commands.

You agree @cyd01 ?

**Comment by cyd01** [comment]
**-version** parameter alreay exists:
![image](https://user-images.githubusercontent.com/34154246/100641793-3c6e9f80-3338-11eb-893c-65c7141f93f0.png)

**Comment by cyd01** [comment]
Try this [build](https://www.9bis.net/kitty/files/kitty-debug.exe) containing new `-help` parameter.

**Comment by lars18th** [comment]
Hi @cyd01 ,

> Try this [build](https://www.9bis.net/kitty/files/kitty-debug.exe) containing new `-help` parameter.

Interesting to see the help printed inside the mNotepad (integrated editor). Nothing to say about it, just works! :+1: 

However, please, note that currently it only works with `-help`. Other options like `/help` and `/?` (more common on the Windows world) are missing. Futhermore, the regular `--help` and `-h` used in Unix are also missing.

So, please can you add these other names? Almost the simple `-h` !!!
Thank you!

**Comment by cyd01** [comment]
Ok I will add `-h` option.  
But please note that options starting with `/` is not the **PuTTY** choice (maybe because initially they chose to make a UNIX-compatible software ?). They did not use `--` too.  
I think it could be confusing, if I mix all these `/` and `--` for **KiTTY** specific options, with the `-` for **PuTTY** old ones.

**Comment by cyd01** [comment]
Follow in #255
