### ISSUE TITLE
[bug] v0.73.2.7: Close+Restart doesn't work

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#140]
Hi @cyd01 ,

Using the last version v0.73.2.7 when you have an active connection and you select in the left menu "Close+Restart" the session is _only_ closed, never restarted. However, if after (when you're disconnected) you select the option "Restart Session" then it will reconnect.

Please, can you check this?
Thank you for the huge effort of maintaining this impressive project!

**Comment by cyd01** [comment]
Ok. It work when "Connection/Attempt to reconnect on connection failure" is checked.
Of course it could be improved, but for the moment I think it is enough ...

**Comment by lars18th** [comment]
Hi @cyd01 ,

> Ok. It work when "Connection/Attempt to reconnect on connection failure" is checked.
> Of course it could be improved, but for the moment I think it is enough ...

I feel this restriction (only when the option is on) is quite restrictive. The user can want to close+restart for multiple reasons, despite the option. So, please to improve this... when you can do it! :wink:

**Comment by cyd01** [comment]
Can you test this [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe) please ?

**Comment by lars18th** [comment]
Hi @cyd01 ,

> Can you test this [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe) please ?

I tested it, and it works! :+1: 
Thank you!
