### ISSUE TITLE
Exclude certain files within Sessions folder

### ISSUE THREAD

**Issue by CWempe** [cyd01/KiTTY#143]
I just started to use Kitty and manage my portable session files via git.

So I started a portable version of kitty and created a repository in a subfolder of `Sessions`.

But now I discovered Kitty will handle EVERY file inside `Sessions` as a session file.

![image](https://user-images.githubusercontent.com/1270359/77232371-efc7a780-6ba0-11ea-8b39-a2d63e643810.png)

It would be great if you could exclude custom files and folders from being interpreted as sessions.

Using a symlink might be another approach, but there seems to be an issue as well. https://github.com/cyd01/KiTTY/issues/70

**Comment by lars18th** [comment]
Hi @CWempe ,

Interesting suggestion. I'm not sure about the best option to solve this problem. I hope @cyd01 will implement some simple solution. Until then I suggest one of these options (in order of my preferance):

1. Use some extension (i.e. `.session`) and make it mandatory. However, I suspect this will be complex for a lot of users if no migration tool is provided.
2. Hide all files starting with a dot (i.e. `.gitignore`). However, this not solve the problem of other files like `README`.
3. Use a file called `exclude.kitty` with a list of files (and wildcards) excluded for use as session. However, in this case a lot of code requires to be implemented.

If someone knows other solutions, please post them here.
Regards.

**Comment by ypid-geberit** [comment]
Well, I think a simple solution is to just create the git repo outside of the `Sessions` directory. KiTTY is not the only program that does not like foreign files in its directories where all files are read in.
Potentially just one level up the tree. So git can track `./Sessions/*`. You could potentially exclude all other files except the `Sessions` directory.

**Comment by CWempe** [comment]
@lars18th 

3. `.kittyignore` like `.gitignore`. 😉 


@ypid-geberit 
I thought about that.
1. I would actually like to use two repsositories. One for my work session I share with my co-workers and one for my private sessions. So a level-up repo would not work.
2. A repo outside of kitty would be fine for me if you could use symlinks. But this is not supported at the moment: https://github.com/cyd01/KiTTY/issues/70

**Comment by ypid-geberit** [comment]
> One for my work session I share with my co-workers and one for my private sessions.

Now I get your use case. I guess you could do really advanced stuff like filtering branches/auto rebasing.

But the simplest thing would be to create two directories in `Sessions` and follow https://stackoverflow.com/questions/505467/can-i-store-the-git-folder-outside-the-files-i-want-tracked

**Comment by lars18th** [comment]
Hi,

As you can see this is not an easy issue to resolve. I suggest to discuss about different approaches for a time, and after comment with @cyd01 how to implement it. You agree?

**Comment by CWempe** [comment]
As I am not a developer, I can only give feedback and ideas.
If, how and when you can implement a solution is up to you. 😄

**Comment by cyd01** [comment]
Maybe two settings can help:
1) you can set your own configuration directory. Add these lines to your **kitty.ini** configuration file:

    [KiTTY]
    configdir=ThePathToConfigurationSubDir

2) you can also define your own configuration file: use the environment variable `KITTY_INI_FILE` to point you own **kitty.ini** configuration file.

**Comment by CWempe** [comment]
`configdir` sounds promising.
This will not solve my use case with two repsitories, but but at least one should work this way.

**Comment by ypid-geberit** [comment]
@CWempe Just in case you overlooked it. git is very flexible and you can already have it all. Refer to https://github.com/cyd01/KiTTY/issues/143#issuecomment-602519456 :)

**Comment by cyd01** [comment]
I've starting something else:
In this [special build](https://www.9bis.net/kitty/files/kitty-debug.exe) session files can have a specific extension (ex: .ktx).

Add these lines to your **kitty.ini** configuration file:

    [KiTTY]
    fileextension=.ktx

With this configuration only files with **.ktx** extension will appear.

Look at [that page](https://www.9bis.net/kitty/#!pages/FileAssociation.md), .ktx files can already be associated to KiTTY, and loaded with double clic.

**Comment by CWempe** [comment]
@ypid-geberit 
I don't think this would solve my problem.

```
mkdir /.../Kitty/Sessions/work
cd /.../Kitty/Sessions/work
git init --separate-git-dir /path/to/work-repo.git
```

This would still give me `.git` file and potential `README.md` inside `/.../Kitty/Sessions/work`.

Using `configdir` I can create a repo where `Sessions` is a subfolder and `.git` and `README.md` are located in the parent directory.
But without support for a second repository.

**Comment by ypid-geberit** [comment]
You can delete `.git` and then use `git --git-dir /path/to/work-repo.git status`.

But I agree, `fileextension=.ktx` solves this better. With it also multiple git repos could exist in `Sessions ` without the dotfiles showing up in the GUI.

**Comment by CWempe** [comment]
@CWempe 
Great! I will check that out later.

**Comment by CWempe** [comment]
`fileextension` works.
But it still shows the `.git` folder and its subfolders.
I guess we could have expected that. 😄 

In combination with @ypid-geberit solution I could get rid of the `.git` folder.

I still prefer to have the git folder in the repo itself, though.

But if I am the only one who wants this feature, feel free to dismiss it. ;)

**Comment by CWempe** [comment]
Sorry for complaining again. :(

I just realized `.ktx` files are displayed with their file extension in the Kitty windows.
This feels like a step backwards.

![image](https://user-images.githubusercontent.com/1270359/77577920-f6735900-6ed7-11ea-8148-20adb55b4829.png)

**Comment by cyd01** [comment]
Yes! It is the first version. Of course I will remove the trailing .ktx. But It will be a little bit more tricky than simply filter sessions based on the extension. I will have to check all starting session points: Start button, Open button, double click on session name ...
I need time, and currently with the confinement it is not easy to work on it.

**Comment by systemmonkey42** [comment]
I like the idea around `fileextension=` setting but I would also suggest hiding files and directories beginning with `.`.  

Again, a new `hidehiddenfiles=` option could be used, but (I believe) it is pretty universal that files beginning with `.` are considered *hidden*.

**Comment by lars18th** [comment]
Hi @systemmonkey42 ,

> I like the idea around `fileextension=` setting but I would also suggest hiding files and directories beginning with `.`.

If only session files are shown, why you need to hide files starting with dots? Any `.session.ktx` filename doesn't have sense.
Another question is to hide _directories_ starting with dots. I feel that in this case @cyd01 will aggree with the idea to hide them.

Regards.

**Comment by systemmonkey42** [comment]
Hi @lars18th 
> Another question is to hide _directories_ starting with dots. I feel that in this case @cyd01 will aggree with the idea to hide them.

Yes, I was definitely thinking of directories like the `.git` in the original example.

**Comment by cyd01** [comment]
Ok to remove directories that start with dot
Due to confinement it is quite hard for me to find some to work on KiTTY
but i will do it

**Comment by cyd01** [comment]
Can you test this beta [build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

**Comment by lars18th** [comment]
Hi @cyd01 

> Can you test this beta [build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

In my case this test build hides subdirectories starting with dots. And it not hides session files starting with dots (as expected!). However, I don't know how to enable the `*.ktx` extesion for listing only session files.

Thank you!

**Comment by cyd01** [comment]
It is just few messages above:
Add these lines to your **kitty.ini** configuration file:

    [KiTTY]
    fileextension=.ktx

**Comment by lars18th** [comment]
Hi @cyd01 ,

In the new release this is working. Thank you!
However, when starting KiTTY in portable mode with `[KiTTY] fileextension=.ktx` inside the **kitty.ini**, then *two* default session files are created:  `Default%20Settings` and `Default%20Settings.ktx`.

Please, fix this behaviour.
Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

> Hi @cyd01 ,
> 
> In the new release this is working. Thank you!
> However, when starting KiTTY in portable mode with `[KiTTY] fileextension=.ktx` inside the **kitty.ini**, then _two_ default session files are created: `Default%20Settings` and `Default%20Settings.ktx`.
> 
> Please, fix this behaviour.
> Regards.

Please, can you check and fix this bug? It's very annoying to have duplicated files in the KiTTY directory. Remember: when activating `[KiTTY] fileextension=.ktx` in `kitty.ini`, if you remove all default sessions in the `Sessions` subdirectory, when you start KiTTY then _automatically_ **two** identical files are created with filenames `Default%20Settings` and `Default%20Settings.ktx`. So one with the extension and one without it.

I feel it's an absurd bug. :wink: 
Regards.

**Comment by cyd01** [comment]
Exact.
I've said it is fix in next official release.

**Comment by lars18th** [comment]
> Exact. I've said it is fix in next official release.

Thank you! :wink:

**Comment by psztoch** [comment]
> 
> 
> I've starting something else:
> In this [special build](https://www.9bis.net/kitty/files/kitty-debug.exe) session files can have a specific extension (ex: .ktx).
> 
> Add these lines to your **kitty.ini** configuration file:
> 
> ```
> [KiTTY]
> fileextension=.ktx
> ```
> 
> With this configuration only files with **.ktx** extension will appear.
> 
> Look at [that page](https://www.9bis.net/kitty/#!pages/FileAssociation.md), .ktx files can already be associated to KiTTY, and loaded with double clic.

It is VERY USEFUL feature. Thank you very much.
In my opinion it should be set as default.

I don't like %20 in session filename. What do you think about it?
Space char should not be encoded to %20. :-)

**Comment by CWempe** [comment]
It looks like `Default Settings` is pushed below the subfolders in the root of the session window.

![image](https://user-images.githubusercontent.com/1270359/80013793-b9e34f00-84cf-11ea-96cd-60257771a5e2.png)

I don't mind (I want to get rid of the `Default Settings` anyway), but someone might think this is a bug or regression.

But thanks for the improvements in the last versions. 👍 
I finally can manage my sessions via Git like I wanted.

**Comment by cyd01** [comment]
There is always a `Default Settings` session in root directory.
In `.ktx` mode the filename will be `Default Settings.ktx`. That's the reason why, if you remove the `fileextension` option you will have two "`Default Settings` files".

**Comment by cyd01** [comment]
It is possible to disable this auto creation with this setting:
```
[ConfigBox]
defaultsettings=no
```

**Comment by CWempe** [comment]
1. I wanted to point out that `Default%20Settings.ktx` is listed at the bottom of the list, while `Default%20Settings` is pinned at the top.

2. `defaultsettings=no` still creates `Default%20Settings.ktx`. 🤔 

btw: This Issue can be closed in my opinion.

**Comment by psztoch** [comment]
I have problem with Default settings. After run and close kitty my Default%20Settings.ktx fill is broken:
```
--- Default%20Settings.ktx	2020-04-22 00:00:49.553590200 +0200
+++ Default%20Settings-afterrun.ktx	2020-04-25 16:49:16.055598500 +0200
@@ -79,7 +79,7 @@
 ApplicationKeypad\0\
 NetHackKeypad\0\
 AltF4\1\
-AltSpace\1\
+AltSpace\0\
 AltOnly\0\
 ComposeKey\0\
 CtrlAltKeys\1\
@@ -111,12 +111,12 @@
 DisableBidi\0\
 WinNameAlways\1\
 WinTitle\\
-TermWidth\100\
-TermHeight\33\
-Font\DejaVu%20Sans%20Mono\
+TermWidth\80\
+TermHeight\24\
+Font\Courier%20New\
 FontIsBold\0\
 FontCharSet\0\
-FontHeight\11\
+FontHeight\10\
 FontQuality\3\
 FontVTMode\4\
 UseSystemColours\0\
@@ -193,8 +193,8 @@
 CapsLockCyr\0\
 ScrollBar\1\
 ScrollBarFullScreen\0\
-ScrollOnKey\1\
-ScrollOnDisp\0\
+ScrollOnKey\0\
+ScrollOnDisp\1\
 EraseToScrollback\1\
 LockSize\0\
 BCE\1\
@@ -288,7 +288,7 @@
 WindowState\0\
 SaveWindowPos\0\
 ForegroundOnBell\0\
-Password\n562x\
+Password\1441b\
 CtrlTabSwitch\0\
 Comment\\
 SCPAutoPwd\0\
```

My font settings have been reseted. :-(

**Comment by psztoch** [comment]
I have to put both files Default%20Settings and Default%20Settings.ktx in my Sessions folder if I want to use "fileextension=.ktx". Without "Default%20Settings" file Kitty can't read font parameters.

It is a pity, than I can't put readonly attribution on my Default%20Settings. It will be very useful to protect this file from modification! Today we have got awful error after kitty launch.

**Comment by cyd01** [comment]
The setting to prevent from Default%20Settings creation is :

    [ConfigBox]
    defaultsettings=no

**Comment by lars18th** [comment]
> defaultsettings=no

So, this will stop to rewrite the default settings?

**Comment by psztoch** [comment]
> 
> 
> The setting to prevent from Default%20Settings creation is :
> 
> ```
> [ConfigBox]
> defaultsettings=no
> ```

It is not true. I had got defaultsettings=no.

![image](https://user-images.githubusercontent.com/4523167/80385164-08189980-88a6-11ea-9e50-c1a015693869.png)

**Comment by cyd01** [comment]
You are right, there is a regression.
I've made a quick [fix](https://www.9bis.net/kitty/files/kitty-debug.exe). The file won't be created anymore ... even if the Default Settings session appears in the sessions list. Internally there always is a Default Session.

**Comment by psztoch** [comment]
1. Problem with write error to read only Default%20Settings still occurs.
Kitty modify Default%20Settings after every launch.
This is very annoying, especially when you synchronize sessions, e.g. via Dropbox.
Please, do not touch Default%20Settings. Only on press "Save" button.

2. Problem with broken TermWidth/TermHeight/Font still occours. If I have Default%20Settings and Default%20Settings.ktx with identical content, then Font is not corrupted.
I anticipate that the hardcoded file Default% 20Settings is being read somewhere.

3. Please add exception for space (%20) in filename encoding. :-)

4. Files in SshHostKeys folder should be ended with extension. If you have Session "server.domain.com", you have got file with ".com" extension. This is problem for some antyvirus.

**Comment by lars18th** [comment]
Hi,

Regarding this:

> 3. Please add exception for space (%20) in filename encoding. :-)

I suggest a simple workaround: use "Default-Settings.ktx" (or without extension "Default-Settings"). I prefer filenames without spaces.

And
> 4. Files in SshHostKeys folder should be ended with extension. If you have Session "server.domain.com", you have got file with ".com" extension. This is problem for some antyvirus.

Good idea! I suggest to use the ".shk" extension.

You agree?

**Comment by cyd01** [comment]
I've started to completely rewrite the session filter procedure.
Can you help me to test the first [beta](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

**Comment by psztoch** [comment]
Read only attributes error has been fixed.

But If I have got Default%20Settings.ktx, without Default%20Settings font settings are not readed from Default%20Settings.ktx (default Courier is used).

Kitty can't read font settings from Default%20Settings.ktx. Kitty tries read font settings from Default%20Settings file only.

![image](https://user-images.githubusercontent.com/4523167/81193422-a9e16a00-8fbb-11ea-844b-d2e473cac395.png)

**Comment by CWempe** [comment]
> I've started to completely rewrite the session filter procedure.
> Can you help me to test the first [beta](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

Was this directed to me?
Regarding the issue https://github.com/cyd01/KiTTY/issues/145?

I guess not. 😄 

I tried the beta, but did not find any different behavior.

**Comment by cyd01** [comment]
No. There is new feature. It was rewritten like the original.
Code addition after addition, the source of the sessions selector has become completely unreadable, unmaintainable. I've said I had to rewrite it. Here it is. And I really hope there is no different behavior.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Testing new version v0.73.2.13. Until now it seems to work without troubles.

Thank you! :+1:

**Comment by lars18th** [comment]
Hi,

It seems to me that this point was discussed some time ago, and I think that now is a good time to comment on it again:

- The files inside the directory `SshHostKeys` doesn't have extension. So, the resulting filename can have _virtual extensions_ like `.com`. And this will be not desirable on some OS. Then, I suggest to implement the _optional_ extension `.key` for these files, in the same way as the current `fileextension=.ktx` for session files.

What you think?

**Comment by cyd01** [comment]
Now there is a new **kitty.ini** option to define an extension for server host key files.  
See it in the new default **kitty.ini** file:

    ; hostkeyextension: the extension for server host key files
    ;hostkeyextension=.khk

The special build is [here](https://www.9bis.net/kitty/files/kitty-debug.exe).

**Comment by lars18th** [comment]
> ; hostkeyextension: the extension for server host key files
> ;hostkeyextension=.khk

Great! It works! :+1: 
Thank you.

**Comment by psztoch** [comment]
Maybe .khk should be default value...
