### ISSUE TITLE
[Feature Request] Shift+F3 behavior change if "SFTP Connect" option is set

### ISSUE THREAD

**Issue by Null-Kelvin** [cyd01/KiTTY#144]
Can you change the default behavior for the SFTP connection option so that the contents of the string are passed without additional processing?
That is, now, if you specify scp: //root@1.2.3.4: 22, you get the command sftp: // scp: //root@1.2.3.4: 22 (depending on WinSCPProtocol in kitty.ini)
Such behavior would be very useful in conditions when you need to connect not only to physical servers, but also to routers that do not know how to perform SFTP.
It would also allow using Shift + F3 when using cygtermd, for example, when connecting via MOSH. Now when connecting via MOSH and using Shift + F3, WinSCP receives the ftp: //user@1.2.3.4:21 command and the local proxy settings, which are completely unnecessary in this case.
The ideal option is to send the command to AS IS, but using variables: username, password and port.

And thank you for your awesome program!

**Comment by cyd01** [comment]
I don"t remember how exactly it works, but you can try to use **SFTP Connect** parameter.
Look at **Comment** panel in configuration box, maybe it can help.

**Comment by Null-Kelvin** [comment]
Sorry for my English. 
It's what I'm talking about: **SFTP Connect** option mostly useless right now.
For example, for testing purposes I create file BatSCP.cmd with following code:

```
cd /d %~dp0
START WinSCP.exe "%1" "%2" "%3" "%4" "%5" "%6" "%7" "%8" "%9"
echo "%1" > info.log
echo "%2" >> info.log
echo "%3" >> info.log
echo "%4" >> info.log
echo "%5" >> info.log
echo "%6" >> info.log
echo "%7" >> info.log
echo "%8" >> info.log
echo "%9" >> info.log
```

Then, I set **WinSCPPath** to BatSCP.cmd in kitty.ini

Next, I set **SFTP Connect** parameter to **_user@server:22_**, run connection and press Shift+F3
info.log show:
`"scp://user@server:22"`

Next, I set **SFTP Connect** parameter to **_sftp://user@server:22_** and do it again. WinSCP can't connect, and in info.log we have:
`"scp://sftp://user@server:22"   `

Kitty add protocol by itself, depending on **WinSCPProtocol** parameter in kitty.ini - so **SFTP Connect** can't really change anything.

Next, I'm use [cygtermd as telnet proxy](https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/cygwin-terminal-window.html) and connect to server via MOSH from there. **SFTP Connect** is set to **_user@server:22_**
Press Shift+F3 and look into info.log
```
"ftp://user@server:21" 
"-rawsettings" 
"ProxyMethod" 
"1" 
"ProxyHost" 
"local" 
"ProxyPort" 
"80" 
"" 
```

I suggest to change behavior of **SFTP Connect** option - KiTTY shouldn't do anything with the string in that field and pass it to WinSCP as is - without any additions like protocol, port or anything.
It would be nice, however, if **SFTP Connect** be able to use variables - username, password and address.

Sorry again for my English

**Comment by cyd01** [comment]
Sorry for my English too ;-)

The SFTP Connect option is used simply to replace the "Host Name (or IP
address)" field of the main session configuration panel.
The format must be "user@hostname" (the same as the "Host Name (or IP
address)".
It can't be anything else. And it is right KiTTY add protocol depending on
the *WinSCPProtocol* setting. This is the design.
It is uses for example to connect sftp through a local ssh tunnel you could
have set in Connection/SSH/tunnels panels.

Cyd

Le sam. 4 avr. 2020 à 14:17, Null-Kelvin <notifications@github.com> a
écrit :

**Comment by Null-Kelvin** [comment]
Too bad. I have to make a CMD script to get around this. In any case, thanks for the clarification and excellent program!
