### ISSUE TITLE
[Feature Request] filter sessions including subfolders

### ISSUE THREAD

**Issue by CWempe** [cyd01/KiTTY#145]
It looks like the session filter only works for sessions inside the currently opened folder.

It would be great if the filter would show all results including sub-subfolders.

**Comment by cyd01** [comment]
To achieve it you must set these settings:
```
[KiTTY]
browsedirectory=no
```
Sessions files will be part of a unique folder.

**Comment by CWempe** [comment]
> Sessions files will be part of a unique folder.

What do you mean by that?

When I add this option my folders are gone (not shown).

![image](https://user-images.githubusercontent.com/1270359/86838635-b60fa380-c0a0-11ea-90b0-2dee06f964d7.png)

vs.

![image](https://user-images.githubusercontent.com/1270359/86838563-a09a7980-c0a0-11ea-9ddd-d07dceea5704.png)



btw: I use portable mode

**Comment by cyd01** [comment]
Yes. 
`browsedirectory=no` remove all sub directories. All sessions are at the same level. And filters will act exactly as you want. In fact it is like the registry mode, but with plain text file for sessions saving. To be honest, I really thing the good mode for you is the registry mode combined with the folder drop-down list.

**Comment by CWempe** [comment]
I want to use files and subfolders, because this is the best way for managing my ~200 sessions via git.
So I guess I have to live without this feature.

**Comment by cyd01** [comment]
The fact is that is does not make sense for me. The KiTTY UI (in portable mode) is based on "folders".  Filtering sessions over all folders to render the result on "one-folder" view is quite difficult to modelize.
I really thing the best way for you is to use KiTTY as I do: in registry mode and managing sessions with the drop-down folder list. I also have more than 200 sessions. 
I know portable mode is a most requested feature (I really don't know why), but registry mode is must more usable and maintainable. Take few minutes to read [how sessions filtering really work](https://www.9bis.net/kitty/#!pages/SessionsFilter.md) in registry mode.

**Comment by CWempe** [comment]
I use up to 6 layers of subfolders to organize your network devices by city/site/building/room etc.
And like we discussed in other issues I use git to manage and distribute my sessions between devices.

I never liked the way Putty stored the sessions in the registry. 😆 

But thank you anyway. :)
