### ISSUE TITLE
[Documentation] no folder dropdown menu anymore?

### ISSUE THREAD

**Issue by CWempe** [cyd01/KiTTY#146]
I the screenshots there is a dropdown menu called "Folders" shown.

http://www.9bis.net/kitty/#!pages/SessionsFilter.md

But I do not see this in the latest Kitty version.

Is the documentation outdated or am I missing something?

(I know how to create folders using the text field above.)

**Comment by lars18th** [comment]
Hi @CWempe ,

I'm using the PORTABLE version of KiTTY from the start. This dropdown menu only appears when using the REGEDIT version. Please, check if you're using the portable version.

Regards.

**Comment by cyd01** [comment]
Since it is useless in portable mode, Folder only appears in Classic mode.
