### ISSUE TITLE
Characters truncation

### ISSUE THREAD

**Issue by Psychokiller1888** [cyd01/KiTTY#147]
Hello!

Some special characters are truncated when displayed on kitty:

![https://puu.sh/Fq2xU.png](https://puu.sh/Fq2xU.png)

The check marks are half cut and should display as:

![https://puu.sh/Fq2yj.png](https://puu.sh/Fq2yj.png)

**Comment by cdavoren** [comment]
Having this issue as well.  Unicode display seems to be patchy in general.

**Comment by cyd01** [comment]
PuTTY can only handle monospaced fonts.
I think most unicode characters can't have the same width. That's certainly why there is no monospaced fonts that support all unicode characters.
