### ISSUE TITLE
Crash while viewing file contents

### ISSUE THREAD

**Issue by systemmonkey42** [cyd01/KiTTY#148]
The following crash message appears while viewing a file while connected via kitty.  The file contained binary data.

I traced it to a simple "0x05"

```bash
printf '\05'
```

will crash Kitty,

Version: 0.73.2.8
```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: C:\Local\kitty.exe
File: ../ldisc.c
Line: 160

Expression: len

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------
```

EDIT: 
I realised I'd see 0x05, or `^E` somewhere.   I added text to the `Answerback string` setting and the crash went away.

Kitty only crashes if the answerback string is empty.

**Comment by systemmonkey42** [comment]
I had a quick look at the source.   This can be solved in either of two ways.

* `ldisc.c:160`
Remove the `assert(len)`. The code will actually work perfectly with len = 0, (including the call to script_local()) so the check is completely redundant.
or
* `terminal.c:3545`
Check if `buf->len > 0` before calling `ldisc_send()`.

Any preference?

**Comment by cyd01** [comment]
Can you test this beta [build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

**Comment by lars18th** [comment]
> Can you test this beta [build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

Hi @cyd01 ,

Perhaps this problem, or other similar, can be the cause of the troubles with the 64bit version [#117]. So it's possible that you want to provide for the next version a 64bit binary in DEBUG only? So with sufficient testing perhaps we can isolate the problems with this architecture. You agree?

**Comment by cyd01** [comment]
64bits version is available [here](https://github.com/cyd01/KiTTY/suites/568620182/artifacts/3793938).
It is ready for tests.
