### ISSUE TITLE
Feature Request: Make session names filesystem independent.

### ISSUE THREAD

**Issue by systemmonkey42** [cyd01/KiTTY#149]
The requirement that *session names* are valid *file names* has caught me out many times.  Most recently trying to save a session called `COM4` (which a windows guru would know is a special name that windows won't let you use).

This would allow you to use sanitized filenames with expressive session names.

The obvious suggestion would be to add a `Display=<name>` field to every session file, but that would slow putty loading immensely.

Another option would be to encoded the session name to punycode or replaced more special characters with `%` url encoding.

Trapping special names like `COM4` would be a little trickier.

**Comment by cyd01** [comment]
See [#143]. We are trying to add an extension to saved settings file. That may solve your issue.

**Comment by lars18th** [comment]
Hi,

In order to maintain a reduced list of issues, I suggest to close this and continue in the #140 .
You agree?

**Comment by lars18th** [comment]
Hi @cyd01 ,

You agree to close it?

**Comment by systemmonkey42** [comment]
Ok, closed.
