### ISSUE TITLE
Support emojis in session name

### ISSUE THREAD

**Issue by CWempe** [cyd01/KiTTY#150]
This is just a nice2have! 😉 

But I could see myself organizing my sessions with emojis.

Like:

* 👔 work
  * server
    * Server1
    * Server2
  * 💻 laptop
  * 🔒vpn server
  * 📧 mail server
* 🧍‍♂️private
  * 📺 media pc

But it looks like the font used by the Kitty gui does not support this at the moment.

folder: ![image](https://user-images.githubusercontent.com/1270359/78037553-04a7f600-736c-11ea-8889-297d531f3f6e.png)

kitty session: 
![image](https://user-images.githubusercontent.com/1270359/78037623-15586c00-736c-11ea-867c-fe0bdc121976.png)

When I open the folder in Kitty there is no session shown inside it.
So there must be another issue beside the font.

This should be no problem with Windows 10.
https://davidzych.com/abusing-emoji-in-windows/

**Comment by cyd01** [comment]
Issue closed due to inactivity
