### ISSUE TITLE
Ctrl-Tab and Ctrl-Shift-Tab functionality broken

### ISSUE THREAD

**Issue by systemmonkey42** [cyd01/KiTTY#152]
Kitty already has the patches required to send the XTerm keys for Ctrl-Tab and Ctrl-Shift-Tab 
as part of window.c

Line 6776:
```C
#ifdef MOD_KEYMAPPING
	if( !GetPuttyFlag() ) {
		if (wParam == VK_TAB && shift_state == 2) { 	/* Ctrl-Tab */
			p += sprintf((char *) p, "\x1B[27;5;9~");
			return p - output;
		}
		if (wParam == VK_TAB && shift_state == 3) {	/* Ctrl-Shift-Tab */
			p += sprintf((char *) p, "\x1B[27;6;9~");
			return p - output;
		}
	}
#endif
```

However,  Line 5213 contains code to absorb Ctrl-Tab for the window switching code EVEN when
window switching is disabled.

```C
	if( (wParam == VK_TAB) && (GetKeyState(VK_CONTROL) & 0x8000) ) {					// CTRL + TAB to switch between windows
		if( (message==WM_KEYUP) && conf_get_int(conf, CONF_ctrl_tab_switch) && GetCtrlTabFlag() ) {
			struct ctrl_tab_info info = { (GetKeyState(VK_SHIFT) & 0x8000) ? 1 : -1, hwnd, } ;

			info.next_hi_date_time = info.self_hi_date_time = GetWindowLong(hwnd, 0);
			info.next_lo_date_time = info.self_lo_date_time = GetWindowLong(hwnd, 4);
			EnumWindows(CtrlTabWindowProc, (LPARAM) &info);
			if (info.next != NULL) 
				if( info.next != hwnd )
					SetForegroundWindow(info.next);
		return 0;
		}
		return DefWindowProc(hwnd, message, wParam, lParam);
	}
#endif
```
and Line 5244 contains code to absorb the Ctrl-Shift-Tab key to toggle the use of shortcuts.

```C
		if((wParam==VK_TAB)&&(message==WM_KEYDOWN)&&(GetKeyState(VK_CONTROL)&0x8000)&&(GetKeyState(VK_SHIFT)&0x8000))  // CTRL+SHIFT+TAB => Manage shortcut flag
			{ SetShortcutsFlag( abs(GetShortcutsFlag()-1) ) ; return 0 ; }
```

Can some cleanup be done so Ctrl-Tab and Ctrl-Shift-Tab behave as expected?

Again, if you want a pull request I can fix the ctrl-tab-switch easily, but the code to toggle
shortcuts should probably be removed.

Regards

EDIT: Speling

**Comment by cyd01** [comment]
Ok, I propose to change to change the **enable/disable shortcuts feature** with **CONTROL+SHIFT+F1**.
```c
		if((wParam==VK_F1)&&(message==WM_KEYDOWN)&&(GetKeyState(VK_CONTROL)&0x8000)&&(GetKeyState(VK_SHIFT)&0x8000))  // CTRL+SHIFT+F1 => Manage shortcut flag
			{ SetShortcutsFlag( abs(GetShortcutsFlag()-1) ) ; return 0 ; }
```

And I propose to evaluate keys and feature status in the same **if** structure:
```c
	if( (message==WM_KEYUP) && conf_get_int(conf, CONF_ctrl_tab_switch) && GetCtrlTabFlag() && (wParam == VK_TAB) && (GetKeyState(VK_CONTROL) & 0x8000) ) {					// CTRL + TAB to switch between windows

		struct ctrl_tab_info info = { (GetKeyState(VK_SHIFT) & 0x8000) ? 1 : -1, hwnd, } ;
		info.next_hi_date_time = info.self_hi_date_time = GetWindowLong(hwnd, 0);
		info.next_lo_date_time = info.self_lo_date_time = GetWindowLong(hwnd, 4);
		EnumWindows(CtrlTabWindowProc, (LPARAM) &info);
		if (info.next != NULL) 
			if( info.next != hwnd )
				SetForegroundWindow(info.next);
		return 0;
	}
```
A first beta is available [here](www.9bis.net/kitty/files/kitty-debug.exe).

**Comment by systemmonkey42** [comment]
Hi @cyd01,  thanks for looking into this.

The proposed solution (for the patch to line 5213) does not work because it does not capture the KEYDOWN.

As a result, with `ctrl_tab_switch` enabled, you get the <kbd>Ctrl-Tab</kbd> code sent to the terminal on `WM_KEYDOWN` and a windows switch occurs on `WM_KEYUP`.

You need to capture the <kbd>Ctrl-Tab</kbd> as you did previously, and prevent `WM_KEYUP` being processed if `ctrl_tab_switch` is enabled.

My patch ended up looking as follows;

```C
	if( (wParam == VK_TAB) && (GetKeyState(VK_CONTROL) & 0x8000) ) {					// CTRL + TAB to switch between windows
		if (conf_get_int(conf, CONF_ctrl_tab_switch) && GetCtrlTabFlag()) {
			if( message==WM_KEYUP ) {
				struct ctrl_tab_info info = { (GetKeyState(VK_SHIFT) & 0x8000) ? 1 : -1, hwnd, } ;

				info.next_hi_date_time = info.self_hi_date_time = GetWindowLong(hwnd, 0);
				info.next_lo_date_time = info.self_lo_date_time = GetWindowLong(hwnd, 4);
				EnumWindows(CtrlTabWindowProc, (LPARAM) &info);
				if (info.next != NULL) 
					if( info.next != hwnd )
						SetForegroundWindow(info.next);
			return 0;
			}
			return DefWindowProc(hwnd, message, wParam, lParam);
		}
	}
```

Also, The link you provided to the beta build does not work so I couldn't test if you had already addressed this.

Thanks again.

**Comment by systemmonkey42** [comment]
> Ok, I propose to change to change the **enable/disable shortcuts feature** with **CONTROL+SHIFT+F1**.

This appears to be a good substitute because <kbd>Ctrl-Shift-F1</kbd> does not appear to be key that Kitty would normally sent.  (When I tried, it send <kbd>Shift-F1</kbd>)

**Comment by lars18th** [comment]
Hi @cyd01 ,

> Ok, I propose to change to change the **enable/disable shortcuts feature** with **CONTROL+SHIFT+F1**.

I agree with a shortcut to enable/disable shortcuts features. However, please be carefull as some users (me included) are using custom shortcuts using **CONTROL+SHIFT+Fn** and **CONTROL+SHIFT+ALT+Fn**. I hate to use as shortcuts of the TERMINAL tool that can be insude inside it in shell tools. So for this reason I use only these two basic combinations.

What about to use **CONTROL+ALT+SHIFT+SPACE** for toggle enable/disable?
In any case, please leave the option inside the INI configuration to enforce enabled or disabled (so the shortcut will be then removed).

Regards.

**Comment by systemmonkey42** [comment]
> In any case, please leave the option inside the INI configuration to enforce enabled or disabled (so the shortcut will be then removed).

Totally agree. I have shortcuts permanently disabled in `kitty.ini`  so toggleing them via the <kbd>Ctrl-Shift-Tab</kbd> combination doesn't seem to do anything.

**Comment by cyd01** [comment]
Due to containment it is quite hard to work on my repository and provide debug build.
I've work directly in Github and created a new branch **fix-152**. It is possible to get result in [Github Actions](https://github.com/cyd01/KiTTY/actions/runs/74252442).

**Comment by systemmonkey42** [comment]
Thanks for that
I did a quick test, and it addressed the <kbd>Ctrl-Tab</kbd> issue, both with and without Ctrl-Tab window switching enabled.

<kbd>Ctrl-Shift-Tab</kbd> still does not work.  Have you moved it to another key yet?

**Comment by cyd01** [comment]
[Now yes](https://github.com/cyd01/KiTTY/actions/runs/74262977).
For the moment I've left **F1** in replacement to **TAB**. But before merging to master, we really need to think of the right keys combination.

**Comment by systemmonkey42** [comment]
Works perfectly.

As for the right key combination to replace <kbs>Ctrl-Shift-Tab</kbs> with....  thats the harder question.

Personally I would move it to the system-menu so people could see it, and see the current state via a checkbox.  Then again, I've never found a need for them, or ever enabled them so I'd be the worst person to ask :-)

**Comment by lars18th** [comment]
Hi,

> Personally I would move it to the system-menu so people could see it, and see the current state via a checkbox.

For sure the _first_ method to implement the enable/disable should be this, as for Protect, Always visible, etc.

A _second_ method will be a shortcut. In this case, I suggest this way:
- The shortcut will be off by default (so no _direct_ shortcut linked to it).
- Include a new _user_ shortcut called **ctrlshifttab-enabler**.
Then the user can configure the shortcut if s/he needs it.

You agree?

**Comment by lars18th** [comment]
Futhermore,

Please @cyd01 can you enhance the number of useable shortcut keys?
For example, I can use **CONTROL+SHIFT+ALT+F11**, but not with **+F12** & **+F13**.
Futhermore, if you can support **CONTROL+SHIFT+ALTgr+Fn** and other _special_ combinations like **CONTROL+SHIFT+ALT+SPACE** then it will desirable.

Regards.

**Comment by cyd01** [comment]
For to moment I've removed the shortcut (no CTRL+SHIFT+anything else), and I've created a new menu item with checkbox.

**Comment by systemmonkey42** [comment]
Thanks for that.

I can confirm the menu status follows the kitty.ini shortcut setting, and behaves accordingly.

> Include a new user shortcut called ctrlshifttab-enabler

I think it makes more sense that when shortcuts are disabled, there isn't a shortcut to enable it.
I did notice there isn't a letter bound to the new menu item.  "U" is free.
