### ISSUE TITLE
Feature Request: Perform "Start" instead of "Open" when double-clicking on saved session

### ISSUE THREAD

**Issue by PhilippeCadieux** [cyd01/KiTTY#153]
Hi,

One of the main reason I am now using KiTTY over PuTTY is the ability to "Start" a session instead of "Opening" one... Basically I love to keep the Configuration window open even after opening the terminal so that I can jump quickly into another saved session once I'm done with the current one.

One thing that I think would make it even better however is if we could set it that, when double-clicking on the name of a saved session on the list in the GUI, to make it Start that session instead of Opening it.

It's a small thing and obviously super low priority but it would be a nice day to day QoL change when using the software.

Thanks!

**Comment by cyd01** [comment]
Hi
I've added a new option in  `%APPDATA%/KiTTY/kitty.ini` configuration file:

```
[ConfigBox]
; dblclick: define the default action when double click on a session in session list
;    Allowed values are:
;    - open: press open button
;    - start: press start button
dblclick=start
```

Please test that special [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

**Comment by PhilippeCadieux** [comment]
That works perfectly! Thanks so much for the super quick turnaround! 
I'll stay on that beta build for now until the change gets merged into the main branch. 

Thanks!
