### ISSUE TITLE
Suggestion: Hide session extension in open window

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#154]
Hi @cyd01 ,

The new session file extension support is great. However, when using the `.ktx` extension, now in the list of sessions in the open windows all session names include the extension. I feel this quite annoying, as the _NAME_ is without the extension.

So, please can you hide this part in the list?
Thank you!

**Comment by cyd01** [comment]
The extension is already hidden:
![image](https://user-images.githubusercontent.com/34154246/79121921-bc8ac980-7d96-11ea-8c54-06b73a5f03b6.png)
![image](https://user-images.githubusercontent.com/34154246/79121950-ce6c6c80-7d96-11ea-91d7-9a9c738cadd1.png)
