### ISSUE TITLE
BUG: When selecting a session inside a subfolder, the selection changes

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#155]
Hi @cyd01 ,

This is with the _last_ version 0.73.2.10p 11/04/2020. Please try this by yourself:

- Activate `.ktx` extensions.
- Create an empty subfolder in your sessions directory (use the explorer).
- Copy two or more session to this subfolder.
- Then inside KiTTY open the new session window, go to the subfolder session and _select_ the second (or upper) session, and pick the _LOAD_ button.
- The _correct_ behaviour is to load the configuration of the session and _maintain_ the selected session... However, the session selected changes to the *PREVIOUS ONE*.

The root cause is because a _new_ session is inserted in the list: "Default Settings" (included at top, before the [..] entry). And when opening the subfolder this entry doesn't exists.

Please, can you fix this annoying error?
Thank you!

**Comment by cyd01** [comment]
I did not reproduce.
Please be more explicit with the name of your session. Maybe there is an ordering issue.

**Comment by lars18th** [comment]
Hi @cyd01 ,

> I did not reproduce.
> Please be more explicit with the name of your session. Maybe there is an ordering issue.

That doesn't have sense! It's not related to the name of sessions or the name of the subfolder. It appears _IN EVERY SUBFOLDER_, no matter what the name of the session is.

Please, check this:
1. Are you configuring the `.ktx` extension in the `kitty.ini` ?
2. Have the subfolder any session called `Default%20Settings` or `Default%20Settings.ktx` ? If yes, then remove these files (I speak about these files in subfolders, and not in the root session folder!).

After checking that open KiTTY and go to _any_ subfolder. Then check if the **FIRST** entry has the name "Default sessings" and the second "[..]". If not, then the BUG is here. To check it, select _any_ session and pick "LOAD". Then, in the first entry will appear "Default Settings" that doesn't appear before.

I can belive you don't see this. :fearful:

**Comment by cyd01** [comment]
But if you delete "Default Settings" in subfolders, when you dig into any
subfolder, there will be no "Default settings". The first is [..]:
[image: image.png]
And even after loading any session there is no "Default Settings".

**Comment by lars18th** [comment]
Hi @cyd01 ,

> But if you delete "Default Settings" in subfolders, when you dig into any subfolder, there will be no "Default settings"

And? This is a problem? I feel the "Default Settings" is only for the ROOT. Or are you using more than one?

> The first is [..]: [image: image.png] And even after loading any session there is no "Default Settings".

Yes, the fiest is [..]. But when you load a session, then **appears** "Default Settins" at top. :open_mouth: 
I'm using the last _stock_ release in portable mode. What version are you testing?

**Comment by cyd01** [comment]
Yes I've loaded it and I've got no other session before [..].
[image: image.png]
I'm working on the last debug I've prepared.

**Comment by lars18th** [comment]
> I'm working on the last debug I've prepared.

Hi @cyd01 , so can you share it? Perhaps the change to remove duplicate "Default Settings" files is impacting on this.

Futhermore, I recommend to delete all obsolete branches in the git repository and commit any new testing code to new branches. Working as this it will be easy to trace changes. You agree?

Regards.

**Comment by cyd01** [comment]
The début is always here https://www.9bis.net/kitty/files/kitty-debug.exe
Due to containement i can’t go at work Everyday. I don’t have the more
recent code modifications
Maybe i’ll go there tomorrow

**Comment by lars18th** [comment]
Hi @cyd01 ,

> The début is always here https://www.9bis.net/kitty/files/kitty-debug.exe Due to containement i 

When using this debug version, the result is the same: when loading _any_ session in a subfolder a new entry "Default Settings" is inserted on top before the "[..]".
Futhermore, another change appears with it: after loading the session _all_ session names will change to include the `.ktx` extension. Prior to load the saved session all the names are listed without the extension.

I hope this helps to reproduce/isolate the problem.
Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

I isolated the problem. When you insert in `KITTY.INI`:
```
[ConfigBox]
filter=no
```

Then the problem appears. And when the filter is `yes` or it's removed, then in this case it works as expected.

So, please try it with this option (`filter=no`) to reproduce the trouble.

Regards.

**Comment by cyd01** [comment]
Reproduced.
I've made a quick modification [here](https://www.9bis.net/kitty/files/kitty-debug.exe), but I think I will have to rewrite completely the main session filter. With modifications over modifications The source code is quite unreadable now ...
But since I never use portable mode (I don't need it), it is quite difficult to find time to make it.

**Comment by lars18th** [comment]
> But since I never use portable mode (I don't need it), it is quite difficult to find time to make it.

Just to know it: I **never** use the REGISTRY mode. I only use the PORTABLE mode. The use of a registry can be good for the OS management, but is very poor in user friendly for advanced users. Futhermore, it's a pain when synchronizing over _diferent_ devices. For years I'm using a cloud service to sync all my portable software over my different machines. So the PORTABLE mode is the reason of KiTTY.
