### ISSUE TITLE
[Feature Request]:  Duplicate Session...

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#156]
Hi @cyd01 ,

I request about an intermediate command between "New Session..." and "Duplicate Session". Conceptually it's very simple: the "New Session..." command with the configuration of the current session. Why we want this? This option will be very useful when you connect to _similar_ servers. For example, when connecting to nodes of a cluster. In this case only the target name changes. Then a simple "Duplicate Session" with the option to change the target address will be very useful. I know that I can save the current session, and then load this session and change the address, but this will be more direct.

Please, can you consider this enhancement?

**Comment by lars18th** [comment]
Hi @cyd01 ,

Perhaps this can be more simple to implement: If the user selects "Duplicate Session" **and** the key CTRL is pressed, then a combox is presented to the user with the target address. Then we can change the address at this point, and the KiTTY can continue executing the same code with changing only the value of the address to connect.

What you think?

**Comment by cyd01** [comment]
Quite complicated!
In fact there is no duplicate session option. When pressing ctrl+shift+left button, KiTTY **loads** and **starts** a new session with the same name (with **-load** parameter option in registry mode and with **-load** and **-folder** parameter in portable mode).
So KiTTY starts with the settings saved, and not the current settings.

**Comment by lars18th** [comment]
Hi @cyd01 ,

In this case, I suspect that the limitation is that KiTTY doesn't have a function to "store" all current settings. It's this right?

Then perhaps a workaround is to "copy & save" the current settings in a temporal session. I feel this can be done as the current session can be saved with upgraded changes. What you think?

**Comment by cyd01** [comment]
Yes it is possible to use a "fake" session to store all current settings.
Try with this [build](https://www.9bis.net/kitty/files/kitty-debug.exe).
For the moment the shortcut is **SHIFT+LEFT button**.
That starts a new config box, populated with the current settings, but without any hostname.

**Comment by CWempe** [comment]
I think **SHIFT+LEFT button** creates a conflict with an existing putty feature.
See #206.

**Comment by cyd01** [comment]
Yes it is.
What shortcut do you propose ?
CTRL+SHIFT+LEFT is already affected to duplicate session.
CTRL+LEFT is affected to change icon.

**Comment by cyd01** [comment]
I've removed SHIFT+LEFT button shortcuts.  
It is replace with a new configurable keyboard shortcut (int **%APPDATA%/KiTTY/kitty.ini** file):
```
[Shortcuts]
; Start a new configuration box with current settings but without hostname
opennewcurrent={CONTROL}n
```

**Comment by lars18th** [comment]
Hi @cyd01 ,

Today I downloaded version 0.74.0.6p, and I configured `opennewcurrent={SHIFT}{CONTROL}{ALT}{F2}`. And the shrotcut runs. Thank you!

However, _it doesn't work!_ The new window created doesn't have _any_ of the current used options from the current session. Instead of it, it does _identically_ the same as with the shortcut `opennew`.

Please, can you check it?
Thank you!

**Comment by cyd01** [comment]
No it's the opposite.  
`opennew`: start a config box with default builtin configuration  
`opennewcurrent`: start a config box with the current session settings, excepting the hostname

I've just re-checked.

**Comment by lars18th** [comment]
Hi @cyd01 ,

> I've just re-checked.

I can't understand the reason, but on my PC this doesn't work. In my case, I check it doing this: open a saved session with a PROXY configured; and after login I call to `opennewcurrent`... but in the new session window the PROXY is not configured. It's this the expected behaviour?

In order to improve/fix this issue I suggest that (if you agree):
- Add to the list of commands in the Menu a new entry called "New duplicated session..." (between "Duplicate Session" and "Close+Restart") that calls to this shortcut `opennewcurrent`. Then will be more easy to call it even without shortcuts.
- In the code of the function, instead of remove the "Host Name", you can place the _current_ used hostname but "selected". Then the behaviour will be the same (if you type a new hostname it will replace the current), but you will have the feedback that the configuration is based on the current one.

You agree with these enhancements?
