### ISSUE TITLE
[Feature Request]: "User proxy" and "__nw:" command

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#158]
Hi @cyd01 ,

Similar to the command "winscp()" that triggers the internal cmd `__ws:` for launching the WinSCP tool inside the specified directory (using `__ws:${PWD}`), I suggest to add support for another internal command.

The idea is to clone (aka Duplicate) the current session _inside the same directory_. And that can be done with a new `__nw:` cmd that triggers a Duplicate session using the directory indicated.

I hope you want to consider this.
Regards.

Note: The trick to change the directory after the login is to use the functionality of the current `kitty.exe -cmd` command line parameter. So the functionality to auto-start inside a specified directory is already included.

**Comment by cyd01** [comment]
Please try this build-in function:

    ds() { printf "\033]0;__ds:`pwd`\007" ; }

**Comment by lars18th** [comment]
> Please try this build-in function:
> 
> ```
> ds() { printf "\033]0;__ds:`pwd`\007" ; }
> ```

Great!

However, it doesn't "clone" with the _current_ configuration. The "Duplicate Session" command uses the same background color and other configuration profile. But when using the "__ds:" command these parameters aren't used.

Can you do something to improve this?
Thank you!

**Comment by lars18th** [comment]
Hi @cyd01 ,

Please, remember that the current "__ds:" command doesn't use the _current_ configuration of the session. I feel this can be considered as a bug. You agree?

**Comment by cyd01** [comment]
No **__** special command use the current settings. They built a new session based on **Default Settings** with some parameters of the command line (such as **-cmd**, **-pw**, or **-P**).

**Comment by cyd01** [comment]
I propose you something. 
There already is a **__pw** internal commande that can save the current directory with this build-in function:

    pw() { printf "\033]0;__pw:`pwd`\007" ; }

Get this new [build](https://www.9bis.net/kitty/files/kitty-debug.exe).
With this build, you just have to 

1. call the special build-in function: `pw` to save the current directory internally
1. Click `CTRL+SHIFT+LEFTBUTTON` to duplicate the current session

If the Remote path is known internally, the command `cd remotepath` will be added to the starting auto-command.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Tested with the last release 0.73.2.14. And it's working. Thank you! :+1: 

However, some comments for _convenience_ and _consistency_:

1. The current implementation of the command "__ds" is not consistent. Why this command doesn't use the current configuration as does the "DUPLICATE" menu command? I suggest to make both identical. You agree?
2. The use of remote commands is not very confortable if we can't automatize them. At time is not possible to run a remote script from a shorcut in the portable mode (see #173). So a simple method to execute these commands can be very useful. I don't have a simple and powerful solution, so I suggest to discuss about alternatives... you agree?

Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Regarding the "bug" of the "__ds" command not using the current configuration, you have plans to fix it?

Thank you!

**Comment by cyd01** [comment]
I think it is what you expected: [debug build](https://www.9bis.net/kitty/files/kitty-debug.exe).
Please tell me.

**Comment by lars18th** [comment]
> I think it is what you expected: [debug build](https://www.9bis.net/kitty/files/kitty-debug.exe).
> Please tell me.

Yeah! This really works! Thank you! :+1:

**Comment by lars18th** [comment]
Hi @cyd01 ,

I'm trying to do this also in a Windows SSH session. However, I don't know how to trigger the correct scape sequence inside the CMD Shell: I'm testing with `echo "^[]0;__ds:^G"` and `echo "^[]0;__ds:^G"`. But neither works. Any idea?

**Comment by cyd01** [comment]
I'm really sorry: here are the "special" functions:

    # Start a duplicated session in the same directory and same settings
    ds() { printf "\033]0;__ds:`pwd`\007" ; }

    # Start a duplicated session with same current host and username and same directory.
    dt() { printf "\033]0;__dt:"$(hostname)":"${USER}":"`pwd`"\007" ; }

**Comment by lars18th** [comment]
Hi @cyd01 ,

As I comented before `__ds:` works as expected in this debug release, except that it doesn't use the same password.

However, regarding the `__dt:` I'm not sure about the objective. For example, using it with a connection over PROXY, it doesn't work, as it not uses the proxy and then is useless. Please, can you explain what you want to do it with `__dt:`?

Regards.

**Comment by cyd01** [comment]
dt: someone asked for it. It used the same session to jump from a server to another. He would be able to duplicate the running session at anytime.  
It works with proxy too. The only think I must remove from the configuration structure is the `hostname`. The Proxy settings remain. Personally I use it this way. At work I must use proxy, because my servers are accessible through a server-bastion only.

**Comment by lars18th** [comment]
Hi @cyd01 ,

For the `__dt:` command: it seems to have sense, but I'm not sure about the funcionality. What is changed in "dt" vs "ds"?

Also, I use the proxy functionality a lot too! But regarding the issue: You know why the `__ds:` doesn't use the same password (in this debug release)?

And finally, a "crazy" idea regarding the proxy support: For some servers (a lot of servers) I have a "fixed" proxy/bastion to connect to them. However, for others I use a "dynamic" proxy... that's a different proxy based on the current location or a socks4 tunnel created by another SSH session. So my request is to include in the "Host name" window (and not in the Proxy section) a Listbox of "User configured Proxies". This list will be loaded from the kitty.ini and represents values of the Proxy section that will be replaced in the "loaded" configuration if you select one entry in this list. What you think about this _crazy_ idea?

Regads.

**Comment by cyd01** [comment]
__ds: only the **automatic command** setting is changed with `cd $(pwd)` to automatically jump to current directory. Everything else remain (including hostname, username, password).
With __dt, **hostname** and **username** settings are changewith current `$(hostname)` and `${USER}` value respectively. Of course if you still use password, it can only work if password is the same on every host. A better way is to use private key and agent, and it will work every time.

**Comment by cyd01** [comment]
The proxies I use are also sock4 tunnel built with another ssh session.  
But I only need 3 different proxies, sot that it is not so difficult to set them directly in my server sessions.  But I can look at this new feature request. I don't think it is complicated.

**Comment by lars18th** [comment]
Hi @cyd01 ,

> __ds: only the automatic command setting is changed ...
> With __dt, hostname and username settings are change ...

And both use the same _current_ config? So the only change is that the first includes a command, and the second uses different hostname/user/pass? And why not use an unique command? The "command" is not incompatible with the "hostname", "user" and "pass". I don't see the difference!

> But I only need 3 different proxies, sot that it is not so difficult to set them directly in my server sessions. But I can look at this new feature request. I don't think it is complicated.

That's the key point: 3 different proxies... If each is for a _different_ location, then for each _server_ in a saved session you can use "one of the three". And in this case, doesn't have sense to save 3 sessions changing only the proxy for the same sever!

I hope you want to try to improve this. Thank you!

**Comment by cyd01** [comment]
`$(hostname)` and `${USER}` are the current hostname and username, and not necessary the originals that were set in the session (ex: if you ssh on other VM).  
Anyway you can also set whatever you want: an alias for any server:
```
s1() { printf "\033]0;__dt:"server1.prod.domain.com":"myuser":"."\007" ; }
s2() { printf "\033]0;__dt:"server2.prod.domain.com":"myuser":"."\007" ; }
...
```

**Comment by cyd01** [comment]
[Here](https://www.9bis.net/kitty/files/kitty-debug.exe) is a first step in the implementation of the new Proxy feature.  
Get the new [build](https://www.9bis.net/kitty/files/kitty-debug.exe).  
Activate the feature adding these lines to your `%APPDATA%\KiTTY\kitty.ini` configuration file:

    [ConfigBox]
    proxyselection=yes

There will be a new selection box `Proxy choice`:  
![image](https://user-images.githubusercontent.com/34154246/102139210-d1f05000-3e5d-11eb-874d-5cd60f38b85a.png)

`None` is the default value. If selected, the values set in `Connection\Proxy` are used. If another proxy is selected, `Connection\Proxy` settings will be overwritten by informations of the selected proxy **at session settings load only** (for the moment). If you change your choice you must save the session and reload it to reflect the change in `Connection\Proxy`. That's very ugly, but I need to work on it.

Of course, to be available in **Proxy choice** list box, you need to define your proxies list first. Here is an example of a proxy definition:

```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\9bis.com\KiTTY\Proxies\first]
"ProxyExcludeList"=""
"ProxyDNS"=dword:00000001
"ProxyLocalhost"=dword:00000000
"ProxyMethod"=dword:00000000
"ProxyHost"="localhost"
"ProxyPort"=dword:00001f90
"ProxyUsername"="username"
"ProxyPassword"="password"
"ProxyTelnetCommand"="connect %host %port\\n"
"ProxyLogToTerm"=dword:00000001
```

Save it in a registry file (Ex: `first.reg`), then execute it. For the moment it is available in registry mode only.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Great! :heart: 
However, I can't test it for the moment...

> Save it in a registry file (Ex: first.reg), then execute it. For the moment it is available in registry mode only.

...as I only use KiTTY in PORTABLE mode.

Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

One comment to improve the _usability_:

In the selection box of "Proxy choice" is recommend to include these values:
- `None`: Not use any proxy at all (overides the proxy values in the session, so disabled it).
- `Default proxy`: Uses the proxy values of the session (and none if not proxy defined for the session). **THE DEFAULT VALUE**.
- `Proxy X`: The proxy X defined in the list of the "user proxies" (my suggestion is to call to this list "user proxies" vs "session proxy" that's the regular proxy stored in the session config).

I hope you want to implement it in this way.
Regards.

**Comment by cyd01** [comment]
Here is the new [build](https://www.9bis.net/kitty/files/kitty-debug.exe).  
**None** was explicitely renamed **No proxy**.  
**Default** became the ... default behavior with the name **Session defined proxy**.  
User proxy can now have space and other non alphanumeric character.  
Now the challenge will be to be able to remove proxy choice when some changes are done in the **Connection\Proxy** panel.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Thank you for the debug build!
I'm testing it, and the names changes seems good to me. :+1: 

However, in PORTABLE mode it doesn't work! Or almost it seems to not work to me. As the definition of the "User Proxies" can't be configured from the `kitty.ini` file at time (only with the registry), I expected (almost) that the option "No proxy" will disable the "session config". And it doesn't work. But perhaps is because is not already implemented. Is that so?

In any case, please don't worry about the PORTABLE mode until you finish. I understand that it doesn't have sense to implement the reading/parsing of the INI file until the functionality is completed.

Thank you for this enhancement!

**Comment by lars18th** [comment]
Hi @cyd01 ,

Regarding the new "Proxy choice" option, please think on incorporate a new INI value to select the "default mode". At time, the "Session defined proxy" is the default option. And this is correct. However, perhaps some user prefers to change the "default" selection to "No proxy". I feel this will be easy to implement, so when introducing the PORTABLE support you can add this too.

Please think if this idea has sense.
Regards.

**Comment by cyd01** [comment]
You are right, it's quite easy to add.  
But I wonder if it is really useful. I explain: If "Session defined proxy" is the selected mode, it refers to the settings of the save session. And in the saved session the default for proxy is "none" (unless you specify something else in "Default Settings" session).

**Comment by lars18th** [comment]
Hi @cyd01 ,

It have sense in this scenario: You configure the session with your default proxy (or bastion to rearch the network). And this will be the regular mode to connect to the server. However, when you go inside the network, then you don't need at all the proxy, as you can connect directly. Then is when you want to select "No proxy". Until here you agree, rigth?

However, if the _other_ sceneario? You have configured the proxy in the session because you need the proxy _in some cases_ where you are out of the network. But, if you work regulary inside the network, then instead of select every time the "no proxy" config, you prefer to change the INI config. Futhermore, I see that not only an INI parameter could be desirable, but a command line option too. Then you can launch two shortcuts from your desktop: each one with one default option.

I hope you want to accept this request. I see it useful.
Regards.

**Comment by cyd01** [comment]
Here is an example of Proxy definition file:

```
ProxyExcludeList\\
ProxyDNS\1\
ProxyLocalhost\0\
ProxyMethod\0\
ProxyHost\proxy\
ProxyPort\80\
ProxyUsername\\
ProxyPassword\\
ProxyTelnetCommand\connect%20%25host%20%25port%5Cn\
ProxyLogToTerm\1\
```

**Comment by lars18th** [comment]
> Here is an example of Proxy definition file:

And where to put it? Inside the INI file, or inside another different file?

**Comment by lars18th** [comment]
Hi @cyd01 ,

I changed the name of the isseu to identify that at time the focus is the "user proxy mode".

**Comment by cyd01** [comment]
I've just changed the way the proxy is overwritten.  
Previously it was at session load. That was bad because original settings were lost !  
Now the proxy settings are overwritten at session startup only. It is available in putty.exe but not in plink.exe for the moment.

**Comment by cyd01** [comment]
I've modified a little the Proxy definition. For example, for a proxy `socks4` exposed on your local PC (`localhost`) with a dynamic port `9090`, the definition is:
```
ProxyExcludeList\\
ProxyDNS\1\
ProxyLocalhost\0\
ProxyMethod\1\
ProxyHost\localhost\
ProxyPort\9090\
ProxyUsername\\
ProxyPassword\\
ProxyTelnetCommand\connect%20%25host%20%25port%5Cn\
ProxyLogToTerm\1\
```
The file containing these informations is located in `%KiTTYFolder%\Proxies`.  
Don't forget file names follow PuTTY classic encoding. It means, no alphanum characters are URL encoded. For example the file describing the configuration of of proxy named `Proxy One` is `Proxy%20One`.  
Here is the first [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe) that should support portable mode. Plink is not available yet.

**Comment by lars18th** [comment]
Hi @cyd01 ,

I'm testing it, and it seems that it works like a charm. However, some comments to improve the usability:

1. To document how to use it, perhaps you can explain that we can open any session file and copy the content to a file inside the "Proxies" subfolder. We only need to remove all lines not related to Proxy____________ . From my point of this this is be the most simple way to generate a configuration proxy file. You agree?
2. I suggest to add a new configuration parameter. The use case is this: you can have a session configured (by default) to forward a dynamic port (ie. 9090). And perhaps you have _different_ sessions to different servers using the same port. Then, when you connect to one of these servers _using_ the Proxy definition, then perhaps you want to _disable_ this dynamic forwarding. So, the idea is simple: add the parameter "ProxyRemovePortForwardings" (in the proxies files) to _remove_ what is in this line in the session configuration. For example: with `ProxyRemovePortForwardings\D9090=` in the proxy file, for the Session's "PortForwardings" the forwarding of the 9090 port is disabled is the user proxy is used.
3. Please, try to fix the error described in #209 . The idea is to print the Socks port despite what is configured for the Title window (as it's doing the "(ONTOP)" label).

Thank you for all your efforts with this incredible project!

**Comment by lars18th** [comment]
Hi @cyd01 ,

Regarding the third aspect, I prepared a simple patch. Please see it at https://github.com/cyd01/KiTTY/issues/209#issuecomment-754563801

**Comment by lars18th** [comment]
Hi @cyd01 ,

Regarding all the functions in the last release v0.74.4.3, it works like a charm! Thank you! I love your work with this incredible fork of PuTTY. :+1: :+1: :+1:
