### ISSUE TITLE
[Feature Request]: Command line parameters help

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#160]
Hi @cyd01 ,

One of the most interesting advantages of KiTTY over the stock PuTTY is the portable and extended command-line support.

However, regarding the command-line parameters the current help/documentation is not very user friendly. At time it's required to read the source code and/or visit the homepage of the tool.

Then I suggest a new approach: Include a help in the binary for _all_ supported command line options. The idea is to mimic the common functionality of any unix binary. So in order to implement it, I suggest to add these _two_ parameters:
- `kitty.exe /help` (and `/h`): It opens a modal window with the text of all cmd parameters.
- `kitty.exe --help` (and `-h`): It prints in the console the text of all cmd parameters.

The first is the Window classic mode to show a help, and the second is the unix mode.
Futhermore, I recommend too to add in the About Window a button to show the windows version of the cmd help.

I hope you want to consider this suggestion.
Regards.

**Comment by eladeyal-intel** [comment]
i think this is dupe of #138

**Comment by lars18th** [comment]
> i think this is dupe of #138

Yes, it is! So I close _this_.
