### ISSUE TITLE
[Feature Request]: Dynamic WinSCP protocol

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#161]
Hi @cyd01 ,

Checking the source code I see that the WinSCP protocol used can be defined in the configuration file:
https://github.com/cyd01/KiTTY/blob/b2cffb36da692e10d4aee94c88a7d46e44bb37c2/kitty.c#L3866

However, in some cases it's required to use an _alternative_ protocol. For example, SFTP can be the default, but the SCP can be the only supported by some server.

Then I suggest to add support for a _KEY COMBINATION_. For example:
- The protocols are numbered: 0 (FTP), 1 (SCP), 2 (SFTP).
- The configuration selects one as the default.
- When calling without any key press, the default is used.
- But when calling with < CTRL > the version +1 is used, and when calling with < ALT > the version +2 is used (obviously 3 is v0 and 4 is v1).

With this small change it will be possible to open sessions using SCP to limited servers when using the default configuration of SFTP; or use FTP when telneting to a server without SSH support.

You agree?

**Comment by lars18th** [comment]
Hi @cyd01 ,

To check the status of the CTRL key you can use already incorporated code:
https://github.com/cyd01/KiTTY/blob/6561c7de35dcc4f5e2a206941c88ee2c6f0f46ab/url/urlhack.c#L125

So the implementation can be easy.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Or perhaps you can extend the current "__ws:" cmd to select the used protocol (SFTP, SCP or FTP):
https://github.com/cyd01/KiTTY/blob/b7c2e561631761dc4bc56c53dc694f82999646e6/kitty.c#L2549

Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

I see you're improving the WinSCP integration (commit d70d88423a570f0d6f0f06b2a25811c510a7bba3). Great!
So please, consider this enhancement. I use KiTTY to connect to several OpenWRT devices, and they support only SCP. This key enhancement seems simple to implement and powerful.

I hope you want to implement it.
Thank you to use your time to develop this impresive fork! :+1:

**Comment by cyd01** [comment]
I've removed **WinSCPProtocol** in **kitty.ini** configuration file. It is replace by a new setting in **Connection/SSH** panel in configuration box.
Please try this new [build](https://www.9bis.net/kitty/files/kitty-debug.exe).

**Comment by lars18th** [comment]
Hi @cyd01 ,

Testing it. First trial seems to work. Thank you! :+1: 

One question: The textbox called `SFTP connect`, which functionality has it?

And one comment: When running a session is not possible to change the `WinSCP protocol`. I suggest to leave the option to change it on-the-fly.

Regards.

**Comment by cyd01** [comment]
May be the very last [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe) can help.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Fixed! So thank you! :heart: 

I close this issue, but finallay I ask to change the _NAME_ in the config window from "PSCP&WinSCP" in "Connection/SSH" with some less louder... "WinSCP and PSCP".
Remember that writing in capital letters is like talking in a loud voice. :laughing:
