### ISSUE TITLE
HTTPS support for KiTTY website

### ISSUE THREAD

**Issue by Bunnicula2** [cyd01/KiTTY#162]
My apologies if this is the wrong place to post.

Your website doesn't use HTTPS, but won't run without JavaScript. A MITM attacker could therefore execute random scripts on the website visitors' machines or redirect them to fake/malicious KiTTY download links.

HTTPS support is nowadays free with [Let's Encrypt](https://letsencrypt.org/about/) and similar CAs, and easy to implement with (also FOSS) [Certbot](https://certbot.eff.org/), which is what I use for my web domains.

**Comment by cyd01** [comment]
It is already available: [https://www.9bis.net/kitty/](https://www.9bis.net/kitty/).

**Comment by CWempe** [comment]
I guess a redirect would be best practice, then. :)

The first google entry links to `kitty.9bis.net/` without any protocol prefix.

just my 2 cents. ;)

**Comment by Bunnicula2** [comment]
Sorry, didn't realize. I assumed it didn't since the update check in KiTTY sent me to http://www.9bis.net/kitty/check_update.php?version=0.73.2.4
