### ISSUE TITLE
[Feature request]: obfuscated-openssh support

### ISSUE THREAD

**Issue by lordvandal** [cyd01/KiTTY#163]
Hello,

I hope my message finds you well.

I would like to suggest support for obfuscated-openssh:
- [brl](https://github.com/brl) developed the [initial concept](https://github.com/brl/obfuscated-openssh/blob/master/README.obfuscation) and authored the handshake obfuscation patch for openssh-5.2 ([repo](https://github.com/brl/obfuscated-openssh))
- [zinglau](https://github.com/zinglau) developed the patch further for newer OSes and versions of openssh ([repo](https://github.com/zinglau/obfuscated-openssh-patches))

There is also a PuTTY fork which implements this, [Mr. Hinky Dink's PoTTY](http://www.mrhinkydink.com/potty.htm), with the [source code available for PoTTY 0.63](http://www.mrhinkydink.com/utmods/063/potty63-src.zip).

I hope you will consider my suggestion.
Thank you in advance and kind regards.

**Comment by cyd01** [comment]
0.63 is to much old to be merged. I'm sorry.
