### ISSUE TITLE
[Feature Request] automatically select first item in ConfigBox

### ISSUE THREAD

**Issue by CWempe** [cyd01/KiTTY#165]
1. I have selected a session folder in the ConfigBox:

![image](https://user-images.githubusercontent.com/1270359/80027465-1c464a80-84e4-11ea-8044-28886119bf14.png)

2. I hit `Enter`. The folder opens.

![image](https://user-images.githubusercontent.com/1270359/80027493-26684900-84e4-11ea-98e2-9c90772c0ffa.png)

3. I hit `DOWN`. The first item is selected.

![image](https://user-images.githubusercontent.com/1270359/80027534-32eca180-84e4-11ea-920b-e25fea3e4ddb.png)

4. I hit `DOWN`. The second item is selected.

![image](https://user-images.githubusercontent.com/1270359/80027552-397b1900-84e4-11ea-89d0-1bf4d3c63f8d.png)

In my opinion step 2 is not necessary and adds a key press to every subfolder I want to open.

**Comment by cyd01** [comment]
You mean step 3 is useless ?

**Comment by CWempe** [comment]
Yes, I mean step 3. Sorry.

**Comment by cyd01** [comment]
There will be a fix in next official release.
