### ISSUE TITLE
[Feature Request] Adjust lines scrolled per mouse wheel turn

### ISSUE THREAD

**Issue by waytotheweb** [cyd01/KiTTY#166]
Could this be implemented, scroll lines feature to adjust lines scrolled per mouse wheel turn:

https://git.steamr.com/others/putty/-/commit/0f5c1ef4709e16fe833fc86333b593f459b25348?w=1

**Comment by lars18th** [comment]
Hi,

I feel this functionality is simple and useful. Futhermore, the code is already implemented.
The current implementation uses every time the half screen scroll. So, I see very interesting and user friendly to support the full screen scroll too.

What you think @cyd01 ?

**Comment by cyd01** [comment]
Ok it is integrated. 
See it in next version.

**Comment by waytotheweb** [comment]
Thank you very much, working well.
