### ISSUE TITLE
[Bug] Jump List in Windows not working in portable mode

### ISSUE THREAD

**Issue by CWempe** [cyd01/KiTTY#167]
When I click an a "Recent Session" Kitty opens but the Session is not started.
Like double-clicking `kitty.exe`.

![image](https://user-images.githubusercontent.com/1270359/80199212-5bc68100-8621-11ea-99a5-d5b96985c09f.png)

In case it matters: I installed Kitty via chocolatey.
The shortcut in the Task bar looks like this:

![image](https://user-images.githubusercontent.com/1270359/80199666-e27b5e00-8621-11ea-9551-380db6ddd3eb.png)

My Sesisons are stored in `c:\Users\cwempe\AppData\Local\VirtualStore\ProgramData\chocolatey\lib\kitty\tools\Sessions\`

I did never tested this with older Kitty versions (with registry sessions or without `.ktx' ). So I don't know if this is a new bug or if this even worked before.

**Comment by cyd01** [comment]
It seems you use portable mode.
To start a session with command-line you must specify the folder where the session file is located with the **-folder** option.
Unlike registry mode, you can have several different sessions with the same name in different folders. It is described in [Portability](https://www.9bis.net/kitty/#!pages/Portability.md) documentation page.

**Comment by CWempe** [comment]
Yes, I am using portable mode.

> To start a session with command-line you must specify the folder where the session file is located with the -folder option.

I am not talking about starting a session with command-line.
I want to start it by clicking on one of the recent entries.
If these need the `-folder` option, I think Kitty should provide this automatically , if possible.

**Comment by cyd01** [comment]
Yes clicking a recent entry means to start a session with **-load** option. And I think in you situation KiTTY does not really know where the file is located and I don't know why. I never use portable mode, I've tried to reproduce your issue with a simple portable KiTTY, and in my case it worked.
Maybe there is something special with **chocolatey** (never installed too).

**Comment by CWempe** [comment]
>  I've tried to reproduce your issue with a simple portable KiTTY, and in my case it worked.
Maybe there is something special with chocolatey (never installed too).

I will try to investigate further... 😁

**Comment by CWempe** [comment]
@cyd01 
Maybe we could reopen this issue as there are other users interested in this feature/bugfix.  
If you find the time or motivation to look into this is another topic. :)

**Comment by cyd01** [comment]
That's true

**Comment by cyd01** [comment]
Ok, I've reverted few things in this [debug build](https://www.9bis.net/kitty/files/kitty-debug.exe).
Unfortunately I won't have time to upload a new release before going to holidays. 
But you can test the debug build.
It seems it works fine in normal mode. 
But in portable mode, it seems it works for the default repository only. I did not find out why it can't work for sub-directories.
If someone could help ...
Bye and see you in 3 weeks.

**Comment by sHAsHiLx** [comment]
Tested debug build and found that JumpList working fine.
Also one annoying thing is - when I launch anything from JumpList that windows not focused. When I just clicked on launchbard and just launched kitty - it's focused.

**Comment by CWempe** [comment]
@sHAsHiLx 
Did you use portable mode?

I just tried it and there is no entry in my jump list.

I also created a simple setup.

```
D:\Downloads\kitty_test\kitty.exe
D:\Downloads\kitty_test\kitty.ini
D:\Downloads\kitty_test\Sessions\magneto
```

kitty.ini

```
[KiTTY]
savemode=dir

[ConfigBox]
defaultsettings=yes
```

I open Kitty, select "pin to taskbar", oben the session `magneto`, login and logout.
I right click on the icon in the taskbar, but there is no jump list entry.

Maybe I did something wrong on my system with previous tests.
Will try on another machine later.

**Comment by sHAsHiLx** [comment]
Use it as is. Downloaded provided by cyd01 debug build - and it works great except some thing about focused windows.

**Comment by CWempe** [comment]
> Use it as is. Downloaded provided by cyd01 debug build

So you did not use portable mode.
I don't know if there was even an issue with jump lists in normal mode.

When I disable portable mode, It works for me.
Kitty is loading my putty sessions form registry (I guess).
And I se many working entries in the jump list.


>  - and it works great except some thing about focused windows.

When I open a session from jump list it is focused. 🤨

**Comment by jgbishop** [comment]
I'm also seeing focus issues with jump list items in portable mode (opening an item from the jump list doesn't focus the window properly). Is this worth opening a separate issue?

**Comment by sHAsHiLx** [comment]
![изображение](https://user-images.githubusercontent.com/20460472/88413671-3b56c000-cde4-11ea-8753-acc167e9bd74.png)
when I click on upper element - window get opened focused (in rare cases not focues but mainly focused).

I think this was started when I updated windows to version 2004.

> 
> 
> I'm also seeing focus issues with jump list items in portable mode (opening an item from the jump list doesn't focus the window properly). Is this worth opening a separate issue?

what windows ver for you?

**Comment by jgbishop** [comment]
I'm seeing focus issues on 1909, so I don't think the Windows version is the factor.

**Comment by AndNovAtor** [comment]
> I also created a simple setup.
> ... 
> I open Kitty, select "pin to taskbar", oben the session `magneto`, login and logout.
@CWempem, Did you "pin"IMMEDIATELY after launch kitty_portable.exe or when any SESSION was opened? It matters.
Also, can you try 0.75.0.5 version, with some steps im my https://github.com/cyd01/KiTTY/issues/198#issuecomment-679912647 comment

**Comment by AndNovAtor** [comment]
>It matters
When we start kitty_portable.exe "unpinned", it has this icon:
![image](https://user-images.githubusercontent.com/3628514/91166773-8ca3e900-e6db-11ea-8c18-e05ea66097ec.png)
And I should't press "pin to taskbar" on this state.
Instead, I should run any session - then Kitty has "general" icon:
![image](https://user-images.githubusercontent.com/3628514/91166934-c96fe000-e6db-11ea-92f3-9d4c0f3a1d2e.png)
... and then I press "pin to taskbar"

**Comment by CWempe** [comment]
I tried your way with version `0.74.0.5`. (I guess `0.75.0.5` is a typo)
But I get no JumpList entry at all.

This may be because I installed Kitty via Chocolatey.

**Comment by vrubleg** [comment]
I use Kitty on Windows 7. For some reason newer Kitty versions Jump List of the Kitty in the Start Menu is not filled with used entries. Before some moment, it was working fine. Jump List in the taskbar works fine. (It's surprising that both these jump lists are separate from each other).

**Comment by cyd01** [comment]
Issue closed due to inactivity

**Comment by vrubleg** [comment]
Well, I just didn't know that there is something to discuss.
