### ISSUE TITLE
[Bug] Recent Sessions get overwritten/deleted

### ISSUE THREAD

**Issue by CWempe** [cyd01/KiTTY#168]
The "Recent Sessions" list gets deleted/overwritten often.

## Steps to reproduce

0.

* Installed Kitty using Chocolatey.
* Sessions are stored in `c:\Users\cwempe\AppData\Local\VirtualStore\ProgramData\chocolatey\lib\kitty\tools\Sessions\`
* `fileextension=.ktx`

1. I open Kitty, start a session from a subfolder and close the session.

2. Session is listed in "Recent Sessions".  
![image](https://user-images.githubusercontent.com/1270359/80199212-5bc68100-8621-11ea-99a5-d5b96985c09f.png)

3. Open Kitty, start a session from **the same subfolder** and exit.

4. Two sessions are listed.  
![image](https://user-images.githubusercontent.com/1270359/80200352-cdeb9580-8622-11ea-903a-8a0cbc8a165c.png)

5. Open Kitty, start a session from **a different subfolder** and exit.

6. Only the last session is listed.  
![image](https://user-images.githubusercontent.com/1270359/80200500-03907e80-8623-11ea-82b9-2e23a820ac73.png)

But this also happens sometimes when I start a session from the same subfolder. 🤨

**Comment by cyd01** [comment]
Issue closed due to inactivity
