### ISSUE TITLE
[Feature Request] Support icons in Resent Sessions list

### ISSUE THREAD

**Issue by CWempe** [cyd01/KiTTY#169]
I try to assign different icons for my sessions.

So it would be great if the Recent Sessions list would use these Icons.

Mockup:

![image](https://user-images.githubusercontent.com/1270359/80201293-32f3bb00-8624-11ea-8f77-19a73a475dc5.png)

I use icons paths relative to the working directory to keep my session files portable between systems.  
So I don't know if this feature would even work vor me.
Maybe Kitty can add the working dir path to a relative icon path if necessary. ;)

Or does Kitty already support this feature and my relative paths are the issue?

**Comment by cyd01** [comment]
Issue closed due to inactivity
