### ISSUE TITLE
[Recommendation] "Enable VT100 line drawing even in UTF-8 mode" by default

### ISSUE THREAD

**Issue by tobwen** [cyd01/KiTTY#170]
Many users have problems with ncurses based application showing line drawing as `lqqqk` in UTF-8 mode. On the web, you can find ancient hints to use _ISO 8859-1_ (and similar), but this introduced other problems.

After waiting years, _PuTTY_ introduced the switch `Enable VT100 line drawing even in UTF-8 mode`, which finally changed this problem. But they didn't make it a default.

Activating this feature in _kITTY_ by default would help **many** users, who don't know this switch.

**Comment by cyd01** [comment]
People can check it in their **Default Settings** session.
