### ISSUE TITLE
[Bug] F13-F20 function keys broken in Xterm R6 mode

### ISSUE THREAD

**Issue by dhcpme** [cyd01/KiTTY#171]
Hi @cyd01 ,

Since v0.73.2.6, the F13-F20 function keys have been returning the wrong values in Xterm R6 mode.

According to `showkey`...

- F13 (SHIFT+F3) returns `^[[1;2R` instead of `^[[25~`
- F14 (SHIFT+F4) returns `^[[1;2S` instead of `^[[26~`
- F15 (SHIFT+F5) returns `^[[15;2~` instead of `^[[28~`
- F16 (SHIFT+F6) returns `^[[17;2~` instead of `^[[29~`
- F17 (SHIFT+F7) returns `^[[18;2~` instead of `^[[31~`
- F18 (SHIFT+F8) returns `^[[19;2~` instead of `^[[32~`
- F19 (SHIFT+F9) returns `^[[20;2~` instead of `^[[33~`
- F20 (SHIFT+F10) returns `^[[21;2~` instead of `^[[34~`

Thank you!

**Comment by lars18th** [comment]
Hi,

And futhermore we can't use them as shortcuts, and in this case the F12 is included.

I hope this will be fixed at any time.

**Comment by crash5** [comment]
If I'm right the F keys starts from F1, so if you want F13, you have to type Shift+F1.

**Comment by lars18th** [comment]
> If I'm right the F keys starts from F1, so if you want F13, you have to type Shift+F1.

I feel you are not right: my keyboard has F12 and F13; and I can use Shift+F1 and Shift+F12 and Shift+F13. All combinations are different.

**Comment by lars18th** [comment]
Please read this: http://aperiodic.net/phil/archives/Geekery/term-function-keys.html

What I request to fix first is the problem using shorcuts with F12, as the F12 key is standard in all platforms, but the KiTTY can't use it. After, the translation to different dialects can be targeted.

**Comment by bonzo-the-fifth** [comment]
I wanted to check in on this issue, as it still seems to be happening with the current version of kitty (0.74.2.3 as of the time of this comment). F13-F20 still do not seem to work properly in versions later than 0.73.2.6.

Let me know if additional information is needed for testing or error verification.

**Comment by cyd01** [comment]
Issue closed due to inactivity
