### ISSUE TITLE
Showing About Box Blocks Network Transmission

### ISSUE THREAD

**Issue by hexxellor** [cyd01/KiTTY#172]
Opening the about box seems to be a blocking operation and until you close the box the data you're sending/receiving seems to be stopped.

To reproduce (just one example):
1. Connect to a site with SSH
2. Under the SSH tunnels configuration set up a local port to listen (Set to dynamic) essentially to be a SOCKS server.
3. Start sending or receiving through that port.
4. While that's happening, open the about box and notice everything stops until you close the about box (The one from the system menu).

![About](https://user-images.githubusercontent.com/892633/80282953-f97d8700-86d9-11ea-8915-26b72b8774e8.png)

**Comment by cyd01** [comment]
Issue closed due to inactivity
