### ISSUE TITLE
[Feature Request] Shortcut user command 

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#173]
Hi @cyd01 ,

I want to call to _one_ user command with a shortcut. As it's impossible to assign a shortcut to _any_ or _all_ user command scripts, I suggest to enable the option for a shortcut with the user command called `shortcut-user-cmd`. With this magic name, if the user enables this shortcut then the corresponding script with this specific name will be executed.

What you think?

**Comment by lars18th** [comment]
Hi @cyd01 ,

You feel this is complex to implement? You think this has sense?
I only need _ONE_ shorcut for _ONE_ script.
Please, consider it.
Thank you!

**Comment by cyd01** [comment]
I thing there is already shortcuts for user commands:
![image](https://user-images.githubusercontent.com/34154246/80987922-0c5b2e80-8e33-11ea-9471-28047ffc6a06.png)

**Comment by lars18th** [comment]
Hi @cyd01 ,

> I thing there is already shortcuts for user commands:

Yes and not! :wink: 
http://www.9bis.net/kitty/#!pages/Shortcuts.md
```
In the menu you can add as many commands as you want. Shortcuts (Ctrl+Shift+A ...), only available in regitry mode, are set up in the order of creation.
```
So, as _"only available in regitry mode"_, remember that I use _only_ the PORTABLE mode.

My request is to add a new entry in the list:
http://www.9bis.net/kitty/#!pages/MenuShortcuts.md
named `user-cmd` that calls to a fixed user command with the same. This will be available to users that use the PORTABLE mode, without touching a lot the code.

I hope you want to consider it.

**Comment by lars18th** [comment]
Hi @cyd01 ,

To be clear about the objective: My idea is put **all** useful function scripts ("wscp()", "pw()", and more) inside ONE user script; and activate them with this requested user shorcut cmd. Then it will be possible to enable all functions from the keyboard. For sure this special script will be different from others, and I'll continue using single users scripts. But I need a _simple_ shortcut to ENABLE all the internal functions used by KiTTY.

Perhaps you have another interesting idea. So please, comment your opinion.
Thank you for this nice PuTTY fork!

**Comment by lars18th** [comment]
Hi @cyd01 ,

Any chance for the "User Command Shortcut" functionality to be supported with the PORTABLE mode?

Thank you!

**Comment by lars18th** [comment]
Hi @cyd01 ,

Just to be sure: You don't want to implement it (aka "wontfix") because it's difficult/impossible to do it, or because you found it's useless?

Please, comment.
Regards.

**Comment by cyd01** [comment]
I don't find the feature useless, you need it.  
What I found useless, is the use of the Portable mode. Unfortunately I don't have so much time to spend on it.

**Comment by lars18th** [comment]
> I don't find the feature useless, you need it.

Thank you! :wink: 

> What I found useless, is the use of the Portable mode. Unfortunately I don't have so much time to spend on it.

That's a shock! The PORTABLE mode is the best functionality ever created in KiTTY! That's the reason because a lot of users have discovered this amazing PuTTY fork. Please, think only on this fact: if you use the portable mode and you synch your portable directory, then in _all_ of your computers share the same configuration. That's the reason for the portable mode (and not the USB ancient capability that perhaps you think on).

So please, when you have sufficient time, try to add it to the portable mode... _please_ :angel:

**Comment by lars18th** [comment]
Hi @cyd01 ?

The problem with the portable mode is the effort to store the values in files?
Then perhaps will be useful to use an external library to read/write the INI files automatically.
Please, check https://github.com/compuphase/minIni
If you create a simple wrapper that uses the registry and/or files in abstract, then perhaps will be more easy to support both modes.

What you think?

**Comment by lars18th** [comment]
Hi @cyd01 ,

I see that you added a "wont fix" label. Please, can you indicate if this is because it's hard to implement in the PORTABLE mode, or because another reason? I don't want to ask for stupid and time consuming requests. So, I only need to understand if this has sense or not.

Thank you for continue working on this amazing PuTTY fork! :+1:

**Comment by cyd01** [comment]
Issue closed due to inactivity

**Comment by lars18th** [comment]
Hi @cyd01 ,

> Issue closed due to inactivity

I suggest to reconsider this decision. The PORTABLE mode is a must-have for KiTTY.
