### ISSUE TITLE
[Question] iconfile index

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#174]
Hi,

I'm thinking on painting the KiTTY icon with different colours (to differentiate different uses: 64bit, pageant, original KiTTY, etc.). However, I need to know if the **kitty.ini** entry `iconfile` can handle indexes. Then it will possible to include multiple icons in a binary.

Regards.

**Comment by cyd01** [comment]
There are already [KiTTY icons](https://www.9bis.net/kitty/#!pages/kitty_icon.md) with different colors: blue, red, green, yellow.
And you can already point any session to an external icon file in **Window/Appearance** panel.
I really think it's enough.

**Comment by lars18th** [comment]
> There are already [KiTTY icons](https://www.9bis.net/kitty/#!pages/kitty_icon.md) with different colors: blue, red, green, yellow.

Hi, I don't know this.
However, what I need to change the INDEX of the icon in the configuration?

**Comment by CWempe** [comment]
Here is the documentation on how to use these icons.

https://www.9bis.net/kitty/#!pages/ThatsAllFolks.md

**Comment by lars18th** [comment]
Hi @CWempe ,

> Here is the documentation on how to use these icons.
> 
> https://www.9bis.net/kitty/#!pages/ThatsAllFolks.md

Thank you for the tip!

![kitty-icons](https://user-images.githubusercontent.com/9989964/81902280-28dc3100-95c0-11ea-83b7-dd6fa523a268.png)

However, regarding my original request, my idea it to provide different coloured versions of the first (big) icon: not only in blue, but including versions in red, brown, green, etc.

@cyd01 , if I prepare different versions based in different colours, then you will agree to incorporate it?

**Comment by CWempe** [comment]
I would like colored versions of the new icon.

But I am not sure if they should replace the old icons or be integrated in addition to the old icons.

**Comment by cyd01** [comment]
Of I can replace old PuTTY-style icon with new colored ones.
But maybe there will never be enought ...
Don't you think the best should be defining a specific icon for session you need it ?
See **External icon file**:
![image](https://user-images.githubusercontent.com/34154246/81927578-2986be80-95e4-11ea-9628-b173c07194f6.png)

**Comment by cyd01** [comment]
The best way is to use external icon file.
