### ISSUE TITLE
background image option is missing from kitty-0.73.2.12.exe or kitty_portable-0.73.2.12.exe

### ISSUE THREAD

**Issue by kuzmeech** [cyd01/KiTTY#175]
Background image option is suddenly missing: 
old 0.70.0.3:
![image](https://user-images.githubusercontent.com/2181438/81140776-a0fb8480-8f38-11ea-9840-fc429f06a4ce.png)
vs new 0.73.2.12:
![image](https://user-images.githubusercontent.com/2181438/81140843-d86a3100-8f38-11ea-9cc0-0a4d67a0d412.png)

0.70.0.3 picks up background image setting from saved profiles, same profiles show no image if loaded with 0.73.2.12

Thank you

**Comment by cyd01** [comment]
Please read [O.71](https://www.9bis.net/kitty/#!pages/0.71.md) message.

**Comment by kuzmeech** [comment]
Thank you for replying and a link! So it's a new spin-off.
