### ISSUE TITLE
[crash] 0.73.3.12p change settings

### ISSUE THREAD

**Issue by ashemedai** [cyd01/KiTTY#176]
Reproduce steps:

1. Have session open to a host (via ssh, but I doubt that matters)
2. Right-click KiTTY title bar, select `Change Settings...`
3. Observe Windows 10's error reporter pop up

Analyzing via windbg:

```
ntdll!KiRaiseUserExceptionDispatcher+3a
00007ffe`b7ebfeba 8b8424c0000000  mov     eax,dword ptr [rsp+0C0h]

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ffeb7ebfeba (ntdll!KiRaiseUserExceptionDispatcher+0x000000000000003a)
   ExceptionCode: c0000008 (Invalid handle)
  ExceptionFlags: 00000000
NumberParameters: 0
Thread tried to close a handle that was invalid or illegal to close
```

Edit: The same problem happens when you hover over `Saved Sessions` from the right click menu.

**Comment by cyd01** [comment]
Already reported #113.
