### ISSUE TITLE
Icons and lines on left-hand side of window

### ISSUE THREAD

**Issue by hjohnst6** [cyd01/KiTTY#177]
I have just reinstalled Kitty after rebuilding my PC. When I connect to a remote host I get little ssh icons and vertical lines in the first column when the server is sending prompts (e.g. for passwords) and this seems to be causing my multi-factor authentication (which offers an additional prompt after the password) to fail. Any idea how I can stop this from happening? I'm guessing it is some kind of line echo setting but I can't find any setting that stops it from happening. Thanks.

**Comment by lars18th** [comment]
Hi,

This is the **default** new behaviour introduced by stock PuTTY in version 0.73 and up. You can't remove it. It's for security issues. The idea is simple: **ALL** messages generated by the terminal client (putty) are preceded by a warning icon. If you see something like `password: ` without a preceding icon, then it's a fake message generated by a potential hijacker.

Regards.

**Comment by cyd01** [comment]
Nothing to add.
