### ISSUE TITLE
Release 0.73.2.13 Configuration session box not filtering on folder selection

### ISSUE THREAD

**Issue by pjhitchman** [cyd01/KiTTY#178]
Hi
In release 0.73.2.13 the session box is not being filtered according to the Folder selection.
Screen shots in attachment.
[kitty_sessions.docx](https://github.com/cyd01/KiTTY/files/4608590/kitty_sessions.docx)

I see there was a note about changing this, is there something I can do to fix this at my end?

Thanks
Pete

**Comment by cyd01** [comment]
I've made no change for selection in registry mode.
And I've tried to reproduce without success.
Can you [contact me](https://www.9bis.net/kitty/#!pages/contact.md) ? I need more informations to test.

**Comment by pjhitchman** [comment]
I run Kitty in portable mode.

**Comment by cyd01** [comment]
Ok!
I think you use **browsedirectory=no** settings ?
I never use portable, so that I completely forgot that setting !

**Comment by cyd01** [comment]
Can you test this [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

**Comment by pjhitchman** [comment]
Thanks
Yes I use the browsedirectory=no setting.
I tried out that build and it fixed the issue.
