### ISSUE TITLE
[Feature Request] Mixed mode (registry & portable)

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#179]
Hi @cyd01 ,

Please see this capture screen from another PuTTY fork:

![dynamic-mode](https://user-images.githubusercontent.com/9989964/81656390-46ca5a00-9437-11ea-8a28-42c1394ae283.png)

This enhancement works in this way: 

- When the user changes for FILE to/from REGISTRY, the program will _reload_ the settings from the selected source.

The idea is to access to the registry sessions _even_ in the portable mode. And this will provide this "mixed" mode: Based on the PORTABLE mode, when selecting the registry all local original PuTTY session will appear in the list. However, only the initial mode is used to SAVE a session. So this functionality is only used to READ sessions. In any case, this will be useful in these scenarios:

1. When the user uses the portable mode to share sessions between different machines, but he wants to maintain some _local_ sessions.
2. To share some sessions with the original PuTTY or different forks that use the registry.

What you think about this enhancement?
Part of the source code is in this commit:
https://git.steamr.com/others/putty/-/commit/851ea99d682d675e84f604b49df299afb6840376

Regards.

**Comment by cyd01** [comment]
too much complicated, and not so many people asked for it.
