### ISSUE TITLE
https://www.fosshub.com/KiTTY.html not reachable

### ISSUE THREAD

**Issue by tjyang** [cyd01/KiTTY#182]
- WHAT:  
fosshub blocked by some corporate VPN connections.
I had to drop corporate VPN just to download kitty.
![image](https://user-images.githubusercontent.com/378638/81913631-d7b74780-9595-11ea-9cc6-c777d3b4bbdc.png)

- WHY:  To make kitty more of legit software to allow download via corporate VPN network, usually block out some sites.

**Comment by Dubbeldrank** [comment]
You need to contact your IT departement about this, they are the ones blocking i guess.

**Comment by tjyang** [comment]
@Dubbeldrank, thanks for response. The point is have kitty hosted on popular site that doesn't need to bother user and IT dept to make an exception.

**Comment by EqUaTe** [comment]
You can download it from GitHub, but I agree with @Dubbeldrank , this is not an issue for @cyd01 to resolve. Your IT department are using something that classifies FOSSHub as a site they don't like. It's on them really. IMO this issue should be closed.

**Comment by tjyang** [comment]
I am closing this issue. But I hope you guys hear my concern. Why hosting kitty binary on a site that need potential users to jump through hoops ?
