### ISSUE TITLE
[Feature Request] Add one time Auto-login password

### ISSUE THREAD

**Issue by Boia11** [cyd01/KiTTY#183]
Hi,
anyone use kitty for "Auto-login password" feature have problem with A2F authorization code request because KiTTY reply with "Auto-login password" set.
I thinks that it's possible to add a feature for block recursive auto-login in this particular session (simple flag under "Auto-login password" textbox
It's a good idea?

**Comment by leiocalyx** [comment]
I second this:
```
login as: user
Keyboard-interactive authentication prompts from server:
| Password:
| Verification code:
Send automatic password (Using keyboard-interactive authentication)
End of keyboard-interactive prompts from server
Access denied
Keyboard-interactive authentication prompts from server:
| Password:
```
Tried setting up `libpam-google-authenticator` but KiTTY seems to think that the second field is a password field as well, and I can't log in using the one time code.

**Comment by cyd01** [comment]
Please try to use [RuTTY](https://sourceforge.net/p/rutty/wiki/Home/) patch instead.
You can find it in `Session/Scripting` panel of the main configuration box.
