### ISSUE TITLE
Ctrl-click with hyperlink=yes doesn't do anything

### ISSUE THREAD

**Issue by genotrance** [cyd01/KiTTY#184]
I enabled hyperlink=yes in the kitty.ini and URLs are now underlined on hover, as I prefer. However, ctrl-click doesn't do anything. I tried default browser as well as custom path to firefox but both didn't do anything.

Using v0.73.2.15.

**Comment by cyd01** [comment]
Did you check **Use ctrl+click to launch kyperlinks** ?
![image](https://user-images.githubusercontent.com/34154246/82202292-fd2fb280-9901-11ea-8db7-bdaa41614c36.png)

**Comment by genotrance** [comment]
Yes it is checked.

**Comment by Dubbeldrank** [comment]
Shift+click does open url's here but crashes Putty, i'm running on AMD Ryzen and it seems like a known problem.

**Comment by cyd01** [comment]
shift+click is not a KiTTY hyperlink feature. 
To follow link, you choose either:
- simple left click
- ctrl+left click if *Use ctrl+click to launch hyperlinks* option is checked.

Please try this [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe). I've refactored a little the **ctrl+mouse button** Windows event. There was a conflict between hyperlink click and icon change features (ctrl+left click too).

**Comment by eesau** [comment]
Use ctrl+click to launch hyperlinks is broken in v0.74.2.3 (has been for a couple of version now). If not checked, links are opened with left click, if checked ctrl-left click does not open the link. I also have Underline hyperlinks when howered upon checked and that works correctly, ie. links are underlined only if ctrl is down when hovered.

**Comment by cyd01** [comment]
Can you test this [build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

**Comment by eesau** [comment]
Test buid is working correctly.
