### ISSUE TITLE
kitty suddenly closes session for some ip addresses

### ISSUE THREAD

**Issue by bdfy** [cyd01/KiTTY#185]
kitty suddenly closes session for this ip addresses after input any login:

![ff](https://user-images.githubusercontent.com/673961/82142593-16732900-9846-11ea-86d2-6ac45d5ffa27.png)
for last putty all ok.

**Comment by cyd01** [comment]
Maybe your server does not accept unknow ssh client like KiTTY.
Try to modify setting to act like openSSH. Add these lines to your `%APPDATA%/KiTTY/kitty.ini` configuration file:
```
[KiTTY]
sshversion=OpenSSH_5.5
```

**Comment by kennyiv** [comment]
I've experienced the same error. I've been trying to get RSA 2048 keys to work with Kitty portable. I tried on versions 0.70.0.8 and 0.73.2.16. The keys do work on PuTTY and the kiTTY full install. I did specify the ssh-version like suggested but sshd threw: `Bad protocol version identification ''`

**Comment by cyd01** [comment]
Is it possible to have a Unix user on these servers to reproduce the issue ?

**Comment by kennyiv** [comment]
The issue doesn't seem to occur when connecting to local IP's. I created a new instance of Debian locally and can connect without issue to a user/root using an ssh-key. However when I attempt to connect using KiTTY outside my network I get one of two errors. The 'SSH-2.0OpenSSH_' error occurs when using KiTTY portable, and 'server refused our key' from KiTTY and KiTTY_nocompress. The ssh-keys used work in PuTTY.

**Comment by cyd01** [comment]
Can you send the content of the event log ?

**Comment by bdfy** [comment]
The problem is resolved: kitty just does not switch the connection type to ssh when entering port 22 (default raw)

**Comment by kennyiv** [comment]
I can confirm, the problem is resolved by manually switching KiTTY from connection type Raw to SSH, Thanks.
