### ISSUE TITLE
Changing windows with ctrl+tab creates ;5;9~

### ISSUE THREAD

**Issue by skirunner** [cyd01/KiTTY#186]
Whenever I am changing the KiTTY window with CTRL+TAB (I am using a session manager MTPutty), I get in all open sessions this automatically put into the console: **;5;9~**

I've downloaded the version: 0.73.2.15 and there it was present, also in the .16
In the version 0.73.2.3 this was working without issues.

**Comment by cyd01** [comment]
It seems it is a MTPutty issue.
I've checked: ctrl+tab works fine in KiTTY
