### ISSUE TITLE
'chanlog' on website

### ISSUE THREAD

**Issue by bish0polis** [cyd01/KiTTY#188]
On several pages on the website at https://www.9bis.net/kitty , I see references to 'chanlog'.   It maybe should be 'changelog', and a search/replace in there may effectively fix it all up.

**Comment by EqUaTe** [comment]
Dupe of #122

**Comment by DumbJoe** [comment]
two years later looks like they either dont care or forgotten about it...or maybe that's their stylized "changelog"?
