### ISSUE TITLE
Windows Jump list is not working when savemode=dir

### ISSUE THREAD

**Issue by appkoders** [cyd01/KiTTY#189]
When kitty uses directory to save sessions the windows jump list is not working. It would just open kitty and would not open the selected session.

How to reproduce:
1. Add the following lines to your kitty.ini. You can execute `kitty.exe -convert-dir` to convert your saved sessions.
```
[KiTTY]
savemode=dir
```

2. Connect to any session.
3. Pin kitty to taskbar and then exit to update the jump list. 
4. Right click on kitty on taskbar and select any of the sessions you previously connected. 

It should try to connect to the session but it only opens the kitty configuration/session list.

**Comment by cyd01** [comment]
Portable mode is not compatible with jumplist at the moment.

**Comment by CWempe** [comment]
See discussion here: https://github.com/cyd01/KiTTY/issues/167
