### ISSUE TITLE
App crash with -kload

### ISSUE THREAD

**Issue by cybermcm** [cyd01/KiTTY#19]
Currently using portable version v0.71.0.1 with Windows 10 1903
Starting kitty portable without command line option -> works
Starting kitty with -kload (e.g. C:\kitty\kitty_portable.exe -kload C:\kitty\sessions\test) -> app crashes

Using v0.70.0.10 -> -kload works...

**Comment by cyd01** [comment]
Ok 
Found something weird ! -kload crashes in portable mode only.
Switch your kitty.ini configuration file to registry mode, and it works.

**Comment by cyd01** [comment]
A fix is available at http://www.9bis.net/kitty/data/beta/kitty.exe

**Comment by cybermcm** [comment]
Thank you for this quick fix, I can confirm that it is working again with 0.71.0.2 (build date 2019-05-31)
