### ISSUE TITLE
adding a X-Server starter for WinNT

### ISSUE THREAD

**Issue by blackcrack** [cyd01/KiTTY#191]
Hi,

would nice if you add at X11-forwardning a entry for seach and add a x11-Server for WinNT like something :
(Make with Gimp!)
![x11-binary](https://user-images.githubusercontent.com/7925717/83492075-064c8200-a4b3-11ea-84b3-2ebdba9a486c.png)

to have a possibility to let start a X11-Server by call..
the possibility has exist allready in Putty for start Xming.exe by call,
at this step could it be start and add a path to the x-server binary

there need only a patch at the right place at
https://github.com/github/putty

then there would be the possibility to start x-server for win when it is needed
and it is easy to binding in.

**Comment by eugenov** [comment]
[https://github.com/cyd01/KiTTY/issues/142](https://github.com/cyd01/KiTTY/issues/142)

**Comment by cyd01** [comment]
Issue closed due to inactivity
