### ISSUE TITLE
[BUG] Double click on session exits folder

### ISSUE THREAD

**Issue by Inchworm333** [cyd01/KiTTY#193]
When I go into one of my folders and then double click on a saved session, the folder closes and goes back to the Default folder.

**Comment by cyd01** [comment]
Not reproduced.
On my side double click on session starts the session.

**Comment by Inchworm333** [comment]
It does start the session for me as well. However if you have dblclick=start and double click on a saved session in a different folder, it opens that session but the configuration window goes back to the default folder.

**Comment by cyd01** [comment]
Ok I understand: that is true, in this case, the configuration window does not close. I'll check.
