### ISSUE TITLE
Saving hostname to "Default Settings" causes kitty_portable to no longer start since v0.73.2.17

### ISSUE THREAD

**Issue by Nazuyuki** [cyd01/KiTTY#195]
Save anything (ip or domain name) to hostname field into to Default Settings profile and the portable version of kitty no longer starts since v0.73.2.17. Clicking on the exe does nothing. The only way to get it to start again is to delete the Default Settings session under "Sessions" folder.

**Comment by cyd01** [comment]
Crash fixed in 0.74.0.2
