### ISSUE TITLE
Klink usage generates error : Incoming packet was garbled on decryption

### ISSUE THREAD

**Issue by sang0ma** [cyd01/KiTTY#196]
Putty resolution of this issue relates to the openssl version compiled against. The current plink version does not cause these errors.
Perhaps klink just needs a recompile against latest plink sources

**Comment by cyd01** [comment]
klink was just rebuild against last 0.74 PuTTY plink source (PuTTY 0.74 is released on 2020-06-27).

**Comment by sang0ma** [comment]
Thank you. No more error message
