### ISSUE TITLE
Jumplist broken in kitty portable since v0.73.2.17

### ISSUE THREAD

**Issue by Nazuyuki** [cyd01/KiTTY#198]
Right clicking on kitty on the task bar should bring up recent sessions but it no longer does in kitty_portable.
Jumplist/RecentSessions file is created but seems to be ignored.

**Comment by cyd01** [comment]
Yes
Portable mode is not compatible with jumplist.

**Comment by Nazuyuki** [comment]
It works as intended before 0.73.2.17 in portable.
![image](https://user-images.githubusercontent.com/41258823/86628964-aad15080-bf98-11ea-80de-791c2d301113.png)

Is this no longer supported?

**Comment by CWempe** [comment]
It never worked for me. (see https://github.com/cyd01/KiTTY/issues/167)
Did you maybe change the location of your `kitty.exe` or of your `Sessions` folder? I guess with the right combination (or both in the same directory) it could work.

But I would love to use this feature!

**Comment by CWempe** [comment]
I think I understand now.

The Jump List entries have been created in portable mode with previous versions.
(But for me they did not work.)

It looks like @cyd01 now disabled the creation of the entries, because there were broken anyway. (for me at least)

@Nazuyuki 
The entries worked for you? Where is your `kitty.exe` and your `Sessions` folder stored?

**Comment by Nazuyuki** [comment]
Same place where kitty_portable.exe is.

I just tried with v0.73.2.16 and it worked fine. You just have to pin kitty_portable to taskbar, connect to any session, close kitty and right click on kitty in the taskbar and the jump list appears just fine.

**Comment by AndNovAtor** [comment]
I confirm that jumplist ALWAYS worked for portable version before some version, but didn't **UPDATE** after some version (when I started some "new"/different session, jumplist staewd "same").
Now I use 0.75.0.5 and I made some changes:
1) everytime I update kitty exe file, I firstly unpin it from taskbar, update exe file, start kitty, run some session and while some session running - pin on taskbar.
2) My kitty is placed in the dir in system drive (C:). Recently I manualy set "write permissions" for the directory "system" user group "Users" ( shows like "Users (<PC-name>\Users)" )
3) updated to 0.75.0.5 version
(Btw, I always rename kitty_portable.exe to kitty.exe)
But jumplist "barely" works - when I start any copy of kitty exe file from different locations, it show last jumplist state. So, It's maybe windows "limitation" and portable version limitation.
So... @Nazuyuki, maybe you can try something of my 1) - 3)...
