### ISSUE TITLE
Crytical Update?

### ISSUE THREAD

**Issue by ThomasCr** [cyd01/KiTTY#2]
Hi, is KiTTY also hit from current bugs found on PuTTY?

https://lists.tartarus.org/pipermail/putty-announce/2019/000027.html

**Comment by cyd01** [comment]
Yes it is.

**Comment by lars18th** [comment]
Hi,

As the 0.71 release is onroad I suggest to close this issue.

**Comment by cyd01** [comment]
0.71 is online.
Thanks for your help.
