### ISSUE TITLE
Troubles when sending BREAK "Special Command" 

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#20]
Hi @cyd01 ,

When sending the BREAK "Special Command", in the first time the size of the font changes (and the window resizes). And the second time the KiTTY process hangs.

Please, can you check it?
Thank you!

**Comment by cyd01** [comment]
Hi
I'm sorry, but I was not able to reproduce the issue.
Can you give me more informations ?
Which mode (registry, portable), which protocol (raw, telnet, ssh ...), do
you use personal commands, personal shortcuts ... ?

Cyd

**Comment by lars18th** [comment]
> Hi I'm sorry, but I was not able to reproduce the issue. Can you give me more informations ?

Try this:

1. Create a new empty folder in your PC.
2. Copy PORTABLE versions of 0.71 & 0.70 with different names.
3. Start a session only setting "user@server" (set your credentials) in each clients (0.71 & 0.70).
4. Resize the window of each client (this will change the number of rows/lines).
5. Then Select "Special Command-->Break" in booth clients.

You see the difference now?

**Comment by cyd01** [comment]
No.
I'm sorry but there is no difference.

**Comment by lars18th** [comment]
> No.
> I'm sorry but there is no difference.

So, then I'll check it in another Windows PC and/or with a different server... 
Please, leave the issue open until I'll have more info.

**Comment by lars18th** [comment]
Hi @cyd01 ,

With the last version 0.71.0.5 I see the same problem:
- Log to one SSH server.
- After log-in I select Special Command -> Break and the Font size changes (increases) and the window resizes.
- If I continue to calling to the Break command, every time the Font size increases.

Are you sure you don't see this problem?

**Comment by cyd01** [comment]
Honestly I did not test it since the first time you told me.
And I yes I've reproduced.
I've remap all the item id of my special menu (>A000).
Here is the result: https://www.9bis.net/kitty/data/beta/kitty.exe

**Comment by lars18th** [comment]
Hi @cyd01 ,

> Honestly I did not test it since the first time you told me. And I yes I've reproduced. I've remap all the item id of my special menu (>A000). Here is the result: https://www.9bis.net/kitty/data/beta/kitty.exe Le lun. 1 juil. 2019 à 09:36, Lars The <notifications@github.com> a écrit :

Great! This BETA version fixes the problem. Thank you! :+1: 

Just one comment: Instead of commiting to GIT only the source code of the releases, you can commit every change too... So I suggest you commit this last change. I remember you're new to GitLab! :wink: 

Regards.

**Comment by lars18th** [comment]
Problem fixed in 0.71.0.6p, so I close this issue.
