### ISSUE TITLE
resize font w/ mouse when xterm-style mouse reporting is on

### ISSUE THREAD

**Issue by eladeyal-intel** [cyd01/KiTTY#200]
When "Disable xterm-style mouse reporting" is not selected 

the control+mouse wheel shortcut for changing font size (#26)  is disabled.

I think it should be enabled with  control-scrollwheel. (or maybe control-shift=scrollwheel )

**Comment by cyd01** [comment]
Issue closed due to inactivity

**Comment by eladeyal-intel** [comment]
😞
