### ISSUE TITLE
kitty-bin-0.74.0.2.zip currently on virustotal: 14 engines detected this file

### ISSUE THREAD

**Issue by cebaa** [cyd01/KiTTY#202]
https://www.virustotal.com/gui/file/0b3be8742b912ca3ed57862ae7520b896629bf145d8244b55a05d702343755af/detection

Current detection list:

```
ALYac       Trojan.GenericKD.34163371
Arcabit     Trojan.Generic.D2094AAB
BitDefender Trojan.GenericKD.34163371
Cylance     Unsafe
Emsisoft    Trojan.GenericKD.34163371 (B)
eScan       Trojan.GenericKD.34163371
GData       Trojan.GenericKD.34163371
K7AntiVirus Trojan ( 0051918e1 )
K7GW        Trojan ( 0051918e1 )
MAX         Malware (ai Score=81)
McAfee      Artemis!2468F2628DDC
Panda       Trj/FakeST.A
Rising      PUA.Presenoker!8.F608 (CLOUD)
Sophos AV   Generic PUA AF (PUA)
```

**Comment by AlyoshaVasilieva** [comment]
Appears to be detecting klink.exe: https://www.virustotal.com/gui/file/91345c5bccf5e70cb0e7f09ebb1cb72999e3d8d1951581e1182f78c303a8439a/detection

**Comment by cyd01** [comment]
Basically plink.exe seems to be detected too: https://www.virustotal.com/gui/file/01678a1d46c240b2e2ea071a5d0d84573632aa835d3240e87c3b99b20537e049/detection
No idea how to fix it. I know [UPX](https://upx.github.io/) (compression process) add frequently false positive detections. But klink is not compressed.

**Comment by cyd01** [comment]
Old version

**Comment by cebaa** [comment]
This is happening with the latest version at this time (v0.74.3.1) as well:

https://www.virustotal.com/gui/file/d10f10b775e1cfa5518270ed50bee2253fb9a4e67a680a10cd9181976b5f0b38/detection

The detection list:

```
BitDefenderTheta  Gen:NN.ZexaF.34590.d0Y@aKrC5bo
Jiangmin          Trojan.Shelma.ggg
K7AntiVirus       Trojan (0051918e1)
K7GW              Trojan (0051918e1)
McAfee            Artemis!A8E3D4593FED
Microsoft         Program:Win32/Wacapew.C!ml
Panda             Trj/FakeST.A
SentinelOne       (Static ML) Static AI  -  Suspicious  Archive
```
