### ISSUE TITLE
Package manager support: Winget

### ISSUE THREAD

**Issue by Neo-Desktop** [cyd01/KiTTY#203]
Considering that [winget](https://github.com/microsoft/winget-cli) is the official microsoft package manager it would be beneficial for KiTTY to be registered as a package there.

Thank you for your consideration.

**Comment by cyd01** [comment]
I won't do that for the moment.  
I'm sorry.

KiTTY is already available in [scoop](https://www.9bis.net/kitty/#!pages/scoop.md) and [chocolatey](https://chocolatey.org/packages/kitty).
