### ISSUE TITLE
disable autoreconnect on mouse or key press on kitty window

### ISSUE THREAD

**Issue by raven428** [cyd01/KiTTY#204]
Hello. After disconnection by request or timeout Kitty tries to reconnect on mouse or key press to this window like activate `Restart session` from `Alt-Space` menu. How to disable this behavior? I'd like to press `Restart session` to reconnect, not just mouse or key press to disconnected window. Thank you.

**Comment by raven428** [comment]
Ping :)

**Comment by cyd01** [comment]
I've made some modifications.
Get this [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe) and disable **Automatic reconnection** feature by adding these lines to your **%APPDATA%/KiTTY/kitty.ini** file:
```
[KiTTY]
autoreconnect=yes
```
Reconnection should only work with menu.
