### ISSUE TITLE
I can't use my ed25519 key to login

### ISSUE THREAD

**Issue by AlphaJack** [cyd01/KiTTY#205]
Since I can't directly use my OpenSSH private key, I tried converting it with PuTTYgen.  
I am prompted for my passphrase, but after I enter it correctly (otherwise KiTTY prompts me again) the window closes without any error.  
On my server `sshd` logs I only see:
```
Accepted publickey for jack from 192.168.1.100 port 50526 ssh2: ED25519 SHA256:HASHHASHHASHHASHHASHHASH
```

1. Create an ed25519 key pair with `ssh-keygen -o -a 100 -t ed25519 -f ~/.ssh/id_ed25519 -C "comment"` and deploy the public key on the server
2. Convert the private key in PuTTY format
3. Select the .ppk from KiTTY
4. Enter your passphrase
5. See the window closing

OS: Windows 7 SP1
KiTTY: 0.74.0.2

**Comment by dsl101** [comment]
I just switched to using ed25519. The latest version of [puttygen](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) can create them, and is working fine (with passphrase) for me. Did you try that? Perhaps the problem is the conversion from ssh-keygen private key to .ppk...

**Comment by AlphaJack** [comment]
I tried creating a keypair with puttygen, but I got the same result.  
The second time I read "zsh: bad option str" the second before the window closed. I checked for remote commands and fixed the problem by removing the flags I was using ("-t --no-profile" worked with the old keypair, I don't know why).  
Thank you
