### ISSUE TITLE
Shift+MouseSelect opens new Kitty window

### ISSUE THREAD

**Issue by CWempe** [cyd01/KiTTY#206]
Since a few days, I noticed a new Kitty windows pops up every time I select something in the console with mouse-left while holding Shift.

Is this a new feature?
Did I set something wrong in  my settings? (I did not change anything, I think)

![image](https://user-images.githubusercontent.com/1270359/88388892-b5238500-cdb5-11ea-9189-53d7f11a668c.png)

Version: 0.74.02
Mode: portable

**Comment by CWempe** [comment]
Looks like it is an issue with a newer beta release (10/07/2020) I had installed.

![image](https://user-images.githubusercontent.com/1270359/89525114-02581b80-d7e6-11ea-9c63-5d90da57d7fa.png)

It works with the latest stable (02/07/2020):

![image](https://user-images.githubusercontent.com/1270359/89525136-097f2980-d7e6-11ea-84bc-d358f9849d05.png)

**Comment by CWempe** [comment]
This is properbly because of 
https://github.com/cyd01/KiTTY/issues/156

**Comment by Dibbyo456** [comment]
Having the same issue.

**Comment by cyd01** [comment]
Get the new beta build. The SHIFT+Left button is removed.

**Comment by CWempe** [comment]
Thanks. (Did not tried it yet)
