### ISSUE TITLE
[Bug] "Default Settings" is created in subfolders

### ISSUE THREAD

**Issue by CWempe** [cyd01/KiTTY#207]
* open a session from a subfolder (portable mode). (e.g.: `test1/server1.ktx`)
* right-click on session windows and open "New Session..."
* New kitty window opens and shows the content of the subfolder.
  * `test1/Default%20Settings.ktx` got created and is listest in the session list.

This is properbly because I commented the follwoing option:

```
[ConfigBox]
; defaultsettings=no
```

But I don't think we want "Default Settings" in sub folders, at all. 😉

**Comment by cyd01** [comment]
It will be fixed in next official release

**Comment by cyd01** [comment]
Fixed in 0.74.0.5
