### ISSUE TITLE
Window does not close on exit

### ISSUE THREAD

**Issue by CWempe** [cyd01/KiTTY#208]
One out of four session windows do net closed after I exit the session.

![image](https://user-images.githubusercontent.com/1270359/88395845-fcb00e00-cdc1-11ea-8872-ab06086b0311.png)

This happens with different devices (linux servers, cisco switches) and sometimes it works for the same device it did not work before.

I guess this could be because of an unclean exit.

![image](https://user-images.githubusercontent.com/1270359/88395879-06397600-cdc2-11ea-8910-efa5916634a7.png)

But I do not know how this would happen so often with different devices.
I never experienced this with putty (same setting).
It could be because I am working from home over VPN.
But I do have a very stable connection an no other issues.

**Comment by cyd01** [comment]
No I don't think it is related to VPN.
I think it is an "automatic reconnection" feature issue. Why, because the strike KiTTY icon appears only when KiTTY detect a end of connection and choose to try to reconnect. 
It never occurs in PuTTY beacause PuTTY does not have this feature.

**Comment by cyd01** [comment]
Do you still have the issue ?

**Comment by CWempe** [comment]
Yes, but I had not the latest Version installed.
Probably v0.74.3.1.

I will see how it works with v0.74.3.4 next week.

**Comment by CWempe** [comment]
The few times I used Kitty the last few days, the window always closed after `exit`.

So I consider this issue fixed.

Thanks

**Comment by cyd01** [comment]
You have a very strange issue. Is there a kind of device where the issue is always there ?

**Comment by CWempe** [comment]
It does not happen always.

I just checked two devices.
An older Cisco Switch and a newer one.
Both had this issue like 5 out of 10 times.

Does Kitty have any kind of debug log?
Maybe that could help.

But I understand if you cannot fix this without reproducing the issue.

**Comment by cyd01** [comment]
Issue closed due to inactivity
