### ISSUE TITLE
IDEA: Title window with SOCKS port

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#209]
Hi @cyd01 ,

This request is only to improve usability. At time in the Window Title Bar you write some status information. So my request is very simple: If a socks port redirection is in use then write the port used in the Title Bar.

I feel this will be quite easy to implement. Futhermore, if more than one are configured, write only the first (in fact, using more than one doesn't have sense, so it's a very uncommon use case). And regarding the length of the text, si quite small: `[SOCKS :1080]` is an example.

You agree with it?
Thank you!

**Comment by lars18th** [comment]
Hi @cyd01 ,

I use a lot KiTTY to connect to some remote SSH servers. And when connected I use them as SSH bastions enabling the internal SOCKS4 server. So I want to enhance the current UI of the SSH Dynamic Forwarding. My idea is to provide some shorcuts to enable/change/disable the Dynamic Port Forward in use. However, this implies some effort to implement it. So as initial step I suggest to print in the Window Title the Dynamic Port Forward, like this `user@server: ~ (ONTOP)(SOCKS :1080)` .

Inside the source code the print can be done here:
https://github.com/cyd01/KiTTY/blob/b9f427b1766554a7c6c00c31c940279a98e9f695/0.74_My_PuTTY/windows/window.c#L7354

And it can be done using a new global var (i.e. `window_portfwd`), than can be set/released in `portfwd.c` file. This var will be unique and store the _first_ dynamic port forwarding in use (if more than one are in use, to prevent errors). So the value can be updated every time the list of forwarding ports is changed.

What you think?
Regards.

**Comment by cyd01** [comment]
I've modified a little the Window/Behavior panel.
With `%%d` option you can add the dynamic ports list in the window title. Test the debug build.

**Comment by lars18th** [comment]
> I've modified a little the Window/Behavior panel.
> With `%%d` option you can add the dynamic ports list (those you use for socks) in the window title. Test the debug build.

Great! But I'm testing v0.74.1.1 (where is the _debug build_?), I see only %%f, %%h, %%p, %%P, %%s, %%u and %%w options.

**Comment by cyd01** [comment]
Don't worry, I've found someone to make some tests.
I'm releasing a new version.

**Comment by lars18th** [comment]
Hi @cyd01 ,

I'm testing the last release. Now I see the option, but it doesn't work:

1. The option `%%d` always generates one empty line (but `%%f` works).
2. This solution using the Window title seems (in my opinion) useless, because:
 a) If the remote machine changes the Window Title, then I can't see the SOCKS port.
 b) The print of the SOCKS ports is variable over a session.

So, I suggest (if you can, and if you want) to implement something similar to the `(ONTOP)` message.
I hope you agree. :wink:

**Comment by lars18th** [comment]
Hi @cyd01 ,

One comment:

> The option %%d always generates one empty line (but %%f works).

This is true if the socks port is declared "4Dxxxx". When using AUTO with "Dxxxx" then it works.
So almost, this bug exist: you need to support AUTO, IPv4 only, and IPv6 only ports.

Thank you for improving this excelent project! :+1:

**Comment by lars18th** [comment]
Hi @cyd01 ,

Thank you! Last version v0.74.2.2 fixes the bug with "4Dxxxx".

However, one _last_ suggestion bofore closing this issue/suggestion: When connecting the Titlebar shows the FORWARD if it's configured, even without touching the configuration. But after the session is stablished the title changes (yes, that's the default behaviour, so already saved in all of my sessions). So instead of _replace_ the full title, why not add this forward at end? The (ONTOP) is doing this, so why should be different for (SOCKS)?

And one last question: If the SOCKS port will be changed during the session, then the title will reflect the change?

Thank you for listening and implementing a lot of our requests. :wink: 
Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Please, can you consider this last part of the request?

>  So instead of replace the full title, why not add this forward at end? The (ONTOP) is doing this, so why should be different for (SOCKS)? And please, print it as (:1080) and not without double dots (1080) as this number can be annoying for someone.

Thank you!

**Comment by lars18th** [comment]
Hi @cyd01 ,

I appreaciate a lot your work on this PuTTY fork. KiTTY is the **best** PuTTY fork!

But, I'm not fully satisfied with the current implementation of this enhancement. With the current implementation the print of the SOCKS port is based on what you're printing in the Title. But this info requires to be on or off besides what is printed in the title. So please, can you replace the current code for printing to do it in the same way as with the `(ONTOP)` label? And please, add the double dots (as `(:1080)`) to be more easy for the user to understand it.

Thank you for commenting.
Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

I prepared a dirty (in the sense of hardcoded) patch that implements what I'm describing. See it:

https://github.com/cyd01/KiTTY/blob/3deb60e5898be2b25d7786a657c1d152130670e5/0.74_My_PuTTY/windows/window.c#L7516
```
	}
	if( GetProtectFlag() ) if( strstr(buffer, " (PROTECTED)")==NULL ) { strcat( buffer, " (PROTECTED)" ) ; }
	if( conf_get_bool(conf, CONF_alwaysontop) ) if( strstr(buffer, " (ONTOP)")==NULL ) { strcat( buffer, " (ONTOP)" ) ; }
+	if( 1 ) if( strstr(buffer, " (SOCKS: ")==NULL ) { make_title( fmt, " (SOCKS: %s)", "%%d") ; strcat( buffer, fmt ) ; }
	set_title_internal( tw, buffer ) ;
	free(title);
	free(buffer);
```

With this line the socks ports are printed inside the title window **every time**. Futhermore, if you change the ports, the title is updated. So it works as expected. The only action required is to add the configuration part (to replace the `if(1)`). I suggest to include inside the configuration window, in the "Connection/SSH/Tunnels" section a new checkbox called _"[ ] Print Dynamic ports in the Title"_. And this option will be independent of the title configured by the user. Futhermore, the user can continue to use inside his custom title the "%%d" option for the ports. However, this will me more user friendly as a global/fixed config when no custom title is configured.

I hope you agree to include this in the next release. I don't provide a PR as it's just a single line. And I prefer to not change the configuration as you know how to modify it.

Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

After starting to use my patch, I have a request for you:

- Inside the "Port forwarding" Window you print the socket status with a `[C]` or `[X]` before the number.
- The code of this is here: https://github.com/cyd01/KiTTY/blob/3deb60e5898be2b25d7786a657c1d152130670e5/kitty.c#L3491

So my request is if you can use this code too inside the function "make_title()" when printing the "%%d" port:
https://github.com/cyd01/KiTTY/blob/3deb60e5898be2b25d7786a657c1d152130670e5/0.74_My_PuTTY/windows/window.c#L7438

With this we can have inside the Title this useful information, all in one place! :wink: 
What you think?

**Comment by lars18th** [comment]
Hi @cyd01 ,

Thank you for including my suggestions in the last release v0.74.4.3. It works really well. Thank you! :+1: 

So, I close this issue.

**Comment by lars18th** [comment]
Hy @cyd01 ,

One question: You feel it will be easy to implement someting like this in the Title?
- `my.server.com (SOCKS: 1080+)`: when the port is free and in use.
- `me.server.com (SOCKS: 1080~)`: when the port is in use by other process.

If you feel it's complex, then I'll close this issue. But please, think about it.
Regards.

**Comment by cyd01** [comment]
I've made sometimes that seems correspond to your need: [here](www.9bis.net/kitty/files/kitty-debug.exe).

In fact port is never free or not. And we can't know if it is in use by any process.  
A port is only open or not open. But the port can be bind only once on a network card. So the first session that opens (bind) the port, open it for every others. So we can say if 
- a port is open in the current process (+)
- a port is open in another process (KiTTY or any other running process) (~)
- a port is not open at all (nothing)

**Comment by lars18th** [comment]
> I've made sometimes that seems correspond to your need: [here](www.9bis.net/kitty/files/kitty-debug.exe).

Thank you! You're very effective at listening to other developers' ideas. :wink: 

However, the link is broken, so I can't test it. :cry:

**Comment by cyd01** [comment]
Strange 
Try this one : http://www.9bis.net/kitty/files/kitty-debug.exe

**Comment by cyd01** [comment]
> 
> 
> > I've made sometimes that seems correspond to your need: [here](www.9bis.net/kitty/files/kitty-debug.exe).
> 
> Thank you! You're very effective at listening to other developers' ideas. 😉
> 
> However, the link is broken, so I can't test it. 😢

**http://** was missing :-(

**Comment by lars18th** [comment]
> Strange
> Try this one : http://www.9bis.net/kitty/files/kitty-debug.exe

This works, thank you!
And the `~` is doing what is expected: The socket is opened but no in use. However, without any mark it implies: it's working. But, I prefer in this way instead of adding `+` because is more simple/clear. So, from my point of view is ready to merge it. :+1: 

Regards.

**Comment by lars18th** [comment]
Working like a charm in v0.74.4.5.
So, thank you @cyd01 I close the issue.
