### ISSUE TITLE
Close+Restart fail

### ISSUE THREAD

**Issue by JulioMoraga** [cyd01/KiTTY#211]
0.74.0.2: Option Close+Restart doesn't work. Does nothing

**Comment by chrapuch** [comment]
It restarts for me, but is not accepting input, so I can't type my password. My workaround is to hit Duplicate Session.

**Comment by cyd01** [comment]
I think it is fixed. Can you confirm ?

**Comment by chrapuch** [comment]
Yes, it's working for me. Thanks!
