### ISSUE TITLE
Hyperlink URL parser does not include closing parenthesis

### ISSUE THREAD

**Issue by armak** [cyd01/KiTTY#213]
The default regular expression in KiTTY (version 0.74.0.3, but also occurs in older versions) does not include closing parentheses of URLs. For an example
![image](https://user-images.githubusercontent.com/4991927/89779018-2f266e80-db17-11ea-978e-c0e09106dc09.png)
Note that all but the last character in the string is underlined, and indeed when clicked the URL is wrong and directs to an incorrect page.

**Comment by cyd01** [comment]
Please can you test this [build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

**Comment by armak** [comment]
This build seems to work indeed :)
