### ISSUE TITLE
Not all kinds of "ssh://" URLs are supported, crash sometimes

### ISSUE THREAD

**Issue by Serik0** [cyd01/KiTTY#216]
Following commands using URLs are handled correctly:

- `kitty.exe ssh://user@10.0.0.1`

- `kitty.exe ssh://10.0.0.1`

But these ones are handled incorrectly:

- `kitty.exe ssh://user2@10.0.0.1` - no error, program crashed

- `kitty.exe ssh://user:1q2w3e@10.0.0.1`  - after ~30 seconds error window is shown:

```
Unable to open connection to
user
Host does not exist
```

Additionally, command `kitty.exe user:1q2w3e@10.0.0.1` opens a connection but the string "user:1q2w3e" is used as login.

**Note:** using passwords is safe and very needed when managing a big bunch of test hosts located in internal network.

**Comment by cyd01** [comment]
The command Line option to set password is -pass

    kitty.exe -pass password user@hostname

**Comment by Serik0** [comment]
> The command Line option to set password is -pass
> 
Yes, but this option is not applicable to the case when we use Kitty as URL handler.

**Comment by cyd01** [comment]
I've made an evolution. It will be included in next official release, but you can find a beta build [here](https://www.9bis.net/kitty/files/kitty-debug.exe).

The complete syntax is:

    kitty.exe ssh://user:password@hostname:port/command

remarks:

1. if password contains **@** character, you must double it: **@@**
1. command is a startup command that not exits (unless you specify explicitly **exit**), and it is **base64 encoded**

**Comment by Serik0** [comment]
Wow, cool!

**Comment by cyd01** [comment]
Fixed in 0.74.0.5
