### ISSUE TITLE
'Close window on exit' panel is partially outside window

### ISSUE THREAD

**Issue by harjoc** [cyd01/KiTTY#217]
The 'Close window on exit' panel that's at the bottom of the main window is only partially visible, possibly because the KiTTY window is too small. A screenshot is attached. This is with an official KiTTY 0.74.0.4 build, on first run. My Windows 10 has text scaling at 110% configured in the display settings, I can try reverting it to 100% to see if it that's what causes the UI issue.
![kitty-crop](https://user-images.githubusercontent.com/1830239/90957390-e31fe600-e495-11ea-9554-b57d22af5f33.png)

**Comment by cyd01** [comment]
Text scaling is not managed in KiTTY for the moment, that's true.
But there is a workaround.
You can set your own window height.
Add these lines to your configuration file (%APPDATA%/KiTTY/kitty.ini):
```
[ConfigBox]
; windowheight: the size of the configuration box
windowheight=800
```
