### ISSUE TITLE
HItting CTRL+Tab or CTRL+Shift+Tab leaves string "5;9;" and   "6;9" respectively in the terminal window.

### ISSUE THREAD

**Issue by PabitraPati** [cyd01/KiTTY#218]
Installed the latest version kitty-0.74.0.5
Configured it with [MtPutty ]([https://ttyplus.com/]) ( putty location in Mtputty points to Kitty location on my system)
Started multiple windows and 

tried shifting from one window to other kitty window (tab in Mtputty), 
Pressing **CTRL+Tab** to shift to right kitty window leaves terminal with the string "5;9;"  (_refer screenshot  **LeftTab-Mtputty.png**_)
Pressing **CTRL+Shift+Tab** to shift to left kitty window leaves terminal with the string "6;9;" (_refer screenshot  **RightTab-Mtputty.png**_)

On Mtputty the string is not visible. Shown as blank screen, but on pressing one backspace, you can see the string (refer screenshot mtputty.png)

Checked the key bindings of Mtputty which was correct. (_refer screenshot **Hotkeys.png**_)

Now tried the same on standalone kitty  but the same was seen there as well ( _**Refer  Kitty.png**_)

**RightTab-Mtputty,png**
 ![RightTab-Mtputty](https://user-images.githubusercontent.com/8273486/91532985-bdc72800-e92c-11ea-81d3-4f334bae153f.png)

**LeftTab-Mtputty.png**
![LeftTab-Mtputty](https://user-images.githubusercontent.com/8273486/91533013-cddf0780-e92c-11ea-8709-e442af55b13c.png)

**Hotkeys.png**
![Hotkeys](https://user-images.githubusercontent.com/8273486/91532997-c3247280-e92c-11ea-8bc3-5f13cf2b31d4.png)

**Kitty.png**
![Kitty](https://user-images.githubusercontent.com/8273486/91533005-c9b2ea00-e92c-11ea-879a-e69244ec3f51.png)

**Comment by cyd01** [comment]
Maybe you forget to check "Switch PuTTY Windows with Ctrl+TAB" in "Window/Behaviour" panel of the configuration box.

**Comment by PabitraPati** [comment]
Oh Yes, Thanks @cyd01. That did work.
in previous version I didn't have to set this. So was not aware of this. 
Closing the ticket.
