### ISSUE TITLE
import color scheme

### ISSUE THREAD

**Issue by eladeyal-intel** [cyd01/KiTTY#223]
There are many color shceme files available on line but there seems to be no simple (GUI) way to import them into a KiTTY session.

Some examples

http://ciembor.github.io/4bit/
https://github.com/cowsay/PuTTY-Color-Schemes
https://putty.org.ru/themes/index.html

**Comment by cyd01** [comment]
Get any `.reg` file and replace `HKEY_CURRENT_USER\Software\SimonTatham\PuTTY` with `HKEY_CURRENT_USER\Software\9bis.com\KiTTY`.

**Comment by eladeyal-intel** [comment]
I was thinking more in the way of providing a filename and importing it via GUI. BTW I use the portable version and nothing is registry. Also I like different color scheme per session so this gets complex to do on scale.

**Comment by cyd01** [comment]
That what I did.
I've imported all .reg files from https://github.com/cowsay/PuTTY-Color-Schemes (don't forget to rename registry key).
Then, I've created all session files by exporting the registry to portable mode with `-convert-dir` option.

**Comment by eladeyal-intel** [comment]
I really enjoy kitty and dumped putty in my PCs for kitty portable. I have lots of sessions and whenever I add a session my workflow is to copy one of the existing sessions and change only the color scheme. My workflow for now is editing the session file manually by adding the Colour lines. What I'd live to see is replacing/augmenting the color editor in the settings screen with either a more capable Colour scheme editor, or maybe better, a way to import just the color scheme, with hopefully multiple formats supported. Or maybe a menu  of color schemes you can pick from (where each scheme is stored in a different file maybe).

I think it can be a great improvement and I think the effort is not that high, but of course I understand not everyone share this view. My workflow is that every server gets its own different color scheme and this way I never use the wrong server by mistake. Others probably have different workflows.
