### ISSUE TITLE
Cache ssh key passphrase for session

### ISSUE THREAD

**Issue by dsl101** [cyd01/KiTTY#224]
Maybe I'm missing how to set this, but I couldn't find it [here](http://www.9bis.net/kitty) or in the configuration options.

I often have to open several sessions to a remote server accessed via ssh key with a passphrase. It's really tedious to type the passphrase in to every window as it opens. Would it be possible for KiTTY to have an option to cache the passphrase in memory for the duration of a session (e.g. while there is at least one terminal open to a specific host)?

I don't think it would reduce security significantly (e.g. I already have an active, open session to the remote host), and it's a particularly noticeable missing feature when using the 'duplicate session' CTRL+SHIFT+Click.

**Comment by cyd01** [comment]
It is exactly the [PuTTY agent (Pageant)](https://the.earth.li/~sgtatham/putty/0.74/htmldoc/Chapter9.html#pageant) job.

**Comment by dsl101** [comment]
Using Pageant is clunky. The options are to start it a login loading all the keys, where it will prompt for _all_ passphrases (whether or not they'll be used), or manually add each key as it's required—a long-winded process compared to using KiTTY's menu to start a terminal session. Unless there's a way to get KiTTY to trigger Pageant to load a key on first launch of a terminal?

This would be a much better feature if built directly into KiTTY... :)

**Comment by dsl101** [comment]
Just in case I can persuade you this is worth some effort, here's one way I could see it working better:

1. Add a checkbox configuration setting in KiTTY under Connection→SSH→Auth called 'Store passphrase in Pageant'
2. On starting a session, KiTTY calls Pageant to see if the key is there
3. If not, and if that checkbox is ticked, rather than open the terminal and prompt for the passphrase, KiTTY calls Pageant to load the key, which will cause Pageant to prompt for the passphrase
4. Once Pageant has the key loaded, KiTTY can use it as normal

Tx
