### ISSUE TITLE
Saved Password for SSH does not work after another day.

### ISSUE THREAD

**Issue by ajaybnl** [cyd01/KiTTY#225]
I use kitty to connect to Raspberry Pi 4.

I filled username and password for ssh in Kitty. But after another day, SSH says wrong password. 

If i re-fill the password in kitty's conf and save default conf, the password again works good in ssh.

Please solve this problem, I'm having Version kitty-0.74.0.6.

**Comment by cyd01** [comment]
Did you find what is wrong with you installation ?

**Comment by ajaybnl** [comment]
There's no problem with my installation. I have this problem from 1st day
(this is my 2nd installation on a new windows os, the 1st time i have this
same problem was on another pc with same kitty software)

Check your kitty (where it saves ssh user id and password?)

**Comment by cyd01** [comment]
I really think there is some wrong with you only.
No one has never complained about it after you opened the issue. 
Please attach a [Savedump](https://www.9bis.net/kitty/#!pages/Savedump.md) in this thread. I'll try to check all your settings.

**Comment by cyd01** [comment]
No more information?
