### ISSUE TITLE
Dialog pages not looking good on Japanese locale

### ISSUE THREAD

**Issue by nanaya** [cyd01/KiTTY#226]
I hope it's fine opening this here even though it's putty problem.

On Japanese locale, the font looks kinda crap (not to mentioned radio boxes etc getting cropped). I wonder if it's easily fixable.

![](https://s.myconan.net/2020-09/kitty64_2020-09-17_16-39-05.png)

![](https://s.myconan.net/2020-09/kitty64_2020-09-17_16-42-17.png)

Slightly different but copyright symbol isn't shown correctly here:

![](https://s.myconan.net/2020-09/kitty64_2020-09-17_16-44-41.png)

**Comment by cyd01** [comment]
Issue closed due to inactivity
