### ISSUE TITLE
Hyperlink detection causes runaway underline

### ISSUE THREAD

**Issue by dlong500** [cyd01/KiTTY#227]
Using v0.74.1.1 (and at least the previous several versions) the hyperlink detection causes a runaway underline that continues indefinitely.  When this occurs it also appears to introduce a noticeable delay when typing.  The hyperlinks don't seem to be clickable either (pressing Ctrl does change the cursor to a hand when hovering, but clicking on one appears to do nothing at all).
See included screenshot.  I should add that I'm using the 64-bit build (though it seems unlikely that would affect this specific UI issue).
![kitty_0 74 1 1_Screenshot 2020-09-17 190122](https://user-images.githubusercontent.com/430481/93545579-c5c42780-f92e-11ea-98c5-9eb80c0c45bf.png)

**Comment by cyd01** [comment]
Can you test this [build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?
Here the result, with the default regex:

![image](https://user-images.githubusercontent.com/34154246/94485392-27fa1380-01de-11eb-99cb-404be24c106d.png)

**Comment by dlong500** [comment]
That build does not exhibit the problem, but then I went and tested the 64-bit 0.74.2.3 build and the problem is still present, so maybe it actually *does* have something to do with 64-bit code... go figure.  What's the next step?  I'm happy to a bit of testing.  Can you reproduce the issue on the 64-bit build?

**Comment by cyd01** [comment]
Please do not use the 64 bits version. It is not officially published. It seems there are many issues with it: crashes and others.

**Comment by dlong500** [comment]
I completely understand that it is not official.  I'm happy to do some testing though in order to improve it.  Honestly for my cases it seems to be working great except for this particular issue.

**Comment by cyd01** [comment]
I've tried 4 different regex libraries. 
But all of them failed with 64bits version.
I've no more idea, I'm sorry.

**Comment by cyd01** [comment]
Issue closed due to inactivity
