### ISSUE TITLE
When ONTOP the Configuration Window is "under"

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#229]
Hi @cyd01 ,

Please, try this: Open a session, set the ONTOP mode, and open the configuration... Then _MOVE_ the Configuration Window close to the Terminal. I see that the Configuration Window is _under_, but from my point of view, any child window requires to be _over_ the main window. I found it quite confusing!

This is the expected behaviour, or it's a bug?

**Comment by lars18th** [comment]
No comment about this behaviour?

**Comment by cyd01** [comment]
It's an original PuTTY feature.
Maybe you can ask first to the original PuTTY team: putty@projects.tartarus.org

**Comment by lars18th** [comment]
Hi @cyd01 ,

If this is the expected behaviour, then nothing to say. I close then this issue.

Thank you!
