### ISSUE TITLE
Dockerfile of cyd01/cross-gcc image

### ISSUE THREAD

**Issue by lygoing** [cyd01/KiTTY#231]
hi. @cyd01 

My current environment network needs to configure the proxy, I want to get the original Dockerfile, so I can do some customization! Can you provide it? 

thanks.

**Comment by cyd01** [comment]
I'm not at work, so I don't have it now.
But the image can already manage Proxies. You just have to mount your certificates into `/usr/local/share/ca-certificates/` directory (with `-v` option) and add your proxies environment variables with `-e` option. It should work.
I'll send it to you when I will be back.

**Comment by lygoing** [comment]
☕ Thank you very much, I think I need it.

**Comment by cyd01** [comment]
I've found someone to send me the Dockerfile.
Just get the last image from Docker hub. The Dockerfile is into the image, here: `/etc/Dockerfile`.
