### ISSUE TITLE
Start winscp disable.

### ISSUE THREAD

**Issue by lygoing** [cyd01/KiTTY#233]
hi everybody.

There are some conditions, need help.

![image](https://user-images.githubusercontent.com/5944432/94389768-4848b480-0183-11eb-8e57-fea12a3a4d1f.png)

Where is the setting incorrect?

Best Regard.

**Comment by lygoing** [comment]
This is my kitty directory.

![image](https://user-images.githubusercontent.com/5944432/94389978-f05e7d80-0183-11eb-8996-a9c829af2524.png)

**Comment by cyd01** [comment]
If it is disabled, it simply means that KiTTY did not find `WinSCP.exe`.
But it is strange because it in the same directory and of course KiTTY try to look for it in that directory.
What you can do is to define the full path to WniSCP.exe in you `kitty.ini` configuration file.

    [KiTTY]
    ; WinSCPPath: the full path to the winscp.exe binary: 
    WinSCPPath=C:\OneDrive\KiTTY\WinSCP.exe

**Comment by lygoing** [comment]
![image](https://user-images.githubusercontent.com/5944432/94509815-ccfd0680-0247-11eb-9e1e-bf29cb6eff1b.png)

I'm sure that the winscp path is correct and in the same directory as Kitty, but the problem remains. 
This may be caused by other issues.

Best Regard.

**Comment by lygoing** [comment]
Can I provide other more accurate logs?

**Comment by lygoing** [comment]
Winscp is not damaged, I can run it.

**Comment by cyd01** [comment]
Please make a memory dump (https://www.9bis.net/kitty/#!pages/Savedump.md)
and attach it to the message.
Thanks

**Comment by lygoing** [comment]
Hi, @cyd01 

I just replaced the latest version (0.74.2.3) of the exe, "Start WinSCP" enabled. 😂

Sorry, I cannot reproduce the issue now.

It is worth mentioning that I installed WinSCP, but now I uninstall it. I now use the portable version to make it in the same directory as Kitty. Could it be that the windows registry has an impact on this?

Kind Regards.

**Comment by lygoing** [comment]
This may not be considered an issue. I may have bad luck. 😂
