### ISSUE TITLE
Explain recent changes in PuTTY source code with cryptographic functionality

### ISSUE THREAD

**Issue by n0rc** [cyd01/KiTTY#234]
I think there is clarification needed regarding a recent change in PuTTY's source code in order to fix #113:

I looked at 659bc96519c0b6c826eaab5f47a85c8cdd2dd65c and saw the `RandomActiveFlag` that was introduced to fix the bug. This is used to [effectively ignore](https://github.com/cyd01/KiTTY/blob/c4b6dabb2814403fb2f4ddc549d06a48bc953c10/0.74_My_PuTTY/sshrand.c#L45) PuTTY code that [adds entropy to the PRNG](https://github.com/cyd01/KiTTY/blob/c4b6dabb2814403fb2f4ddc549d06a48bc953c10/0.74_My_PuTTY/sshrand.c#L50) by setting `RandomActiveFlag` to 0 [per default](https://github.com/cyd01/KiTTY/blob/c4b6dabb2814403fb2f4ddc549d06a48bc953c10/kitty_commun.c#L93).

@cyd01 [mentioned earlier](https://github.com/cyd01/KiTTY/issues/113#issuecomment-695206800) that he thinks this code from PuTTY is not necessary:

> It points a PuTTY code line, not a KiTTY one.
> I've removed it. It is about noise (for cryptographic random number) and seems not necessary.

Can we please get a proper explanation for that?

My main concern is that the whole bug from #113 is very likely _not_ caused by PuTTY's code but by the build chain used: PuTTY itself did never crash with the code and the _same KiTTY code without the above modifications_ ran without issues when using the corresponding GitHub Actions builds (see discussion in #113 starting [here](https://github.com/cyd01/KiTTY/issues/113#issuecomment-690083501)).

So please give some insight on why changing PuTTY's code here (especially by ignoring code related to cryptographic functionality) is the right approach to fix this bug rather than fixing the build chain issues?

*(I already posted my concerns [here](https://github.com/cyd01/KiTTY/issues/113#issuecomment-701707882) but unfortunately that issue was closed before I could comment.)*

**Comment by cyd01** [comment]
You are right!
PuTTY source code compiled with my build chain crashes too.

**Comment by n0rc** [comment]
> Did you test it ?

What do you mean? I did test your last release but it included the mentioned code parts.
Is there any release without your code modifications but built with your upgraded gcc?

**Comment by cyd01** [comment]
You can act with the previously mentioned parameter.

```
[Debug]
randomactive=yes
```
> My current GCC version is

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=D:\DEV\MinGW\bin\gcc.exe
COLLECT_LTO_WRAPPER=d:/dev/mingw/bin/../libexec/gcc/mingw32/9.2.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-9.2.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-static --enable-shared --enable-threads --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --enable-libgomp --disable-libvtv --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --disable-build-format-warnings --prefix=/mingw --with-gmp=/mingw --with-mpfr=/mingw --with-mpc=/mingw --with-isl=/mingw --enable-nls --with-pkgversion='MinGW.org GCC Build-2'
Thread model: win32
gcc version 9.2.0 (MinGW.org GCC Build-2)
```

**Comment by Antorell** [comment]
I just tried the latest version [v0.74.3.5](https://github.com/cyd01/KiTTY/releases/tag/v0.74.3.5) with and without [Debug] randomactive=yes, Putty doesn't crash anymore.

**Comment by cyd01** [comment]
thanks

**Comment by cyd01** [comment]
If no more report, it will be closed

**Comment by n0rc** [comment]
@cyd01 I took from your replies that you don't have time to deal with this bug / issue any longer – that is completely understandable.

However, I would suggest that you roll back the changes you did in the crypto part of PuTTY's source code regarding #113 . It looks like that just changing your build setup already solved this problem and the crypto code changes are not necessary at all.

I'm fully aware that I can re-enable the crypto part with the `randomactive=yes` option but this is like having an opt-in to use the original crypto code from PuTTY. I strongly suggest to make this an opt-out at least (if needed at all) as long as it is not fully clear what the consequences of these code change are.

So please revert the crypto change so that everyone who uses KiTTY can rely on using untouched crypto code from PuTTY.

**Comment by cyd01** [comment]
You are right. The quickest thing I can do before reverting the code is to make an opt-out. I'll do it very soon.

**Comment by cyd01** [comment]
I've made it. It is available in [debug build](https://www.9bis.net/kitty/files/kitty-debug.exe).  
It will be available in next official release ... next year.
