### ISSUE TITLE
When reconnecting the kitty window (which is being hidden in the tray) will cause the active window to lose focus

### ISSUE THREAD

**Issue by char101** [cyd01/KiTTY#238]
When reconnecting the kitty window which is being hidden in the tray area will activate for a very short term thus taking the focus from current active window.

## Steps to reproduce
1. run kitty, enable reconnection, minimize to tray
2. disconnect Internet connection
3. reconnect Internet connection
4. the kitty window will flash for a bit and the currently focused window will lose focus.

Verified using focus.exe from https://www.happydroid.com/focus to monitor the focused windows.

**Comment by ml-cms** [comment]
We have the same annoying problem

**Comment by cyd01** [comment]
Did you try to change your bell setting in **Terminal/Bell panel** ?

**Comment by char101** [comment]
I just tried to change it from alert sound to none and then disconnecting and reconnecting the Internet connection. The result is the same:  the kitty window which is hidden in the tray still steal focus when it is reconnecting.

**Comment by cyd01** [comment]
Can you test this [build](https://www.9bis.net/kitty/files/kitty-debug.exe).
Is the focus still stolen ?

**Comment by char101** [comment]
Yes the focus is still stolen with that build.

**Comment by cyd01** [comment]
I did not reproduce. Can you send me a [memry dump](https://www.9bis.net/kitty/#!pages/Savedump.md) of the session that steal the focus ?
I need to be exactly in the same situation.

**Comment by char101** [comment]
I hooked the kitty process to winapioverride and found that these two functions are called when it steal focus

https://github.com/cyd01/KiTTY/blob/master/0.74_My_PuTTY/windows/window.c#L3336

```
BringWindowToTop( hwnd ) ;
SetForegroundWindow( hwnd ) ;
```

Maybe a check can be added there if the window is hidden in the tray.

**Comment by leifclaesson** [comment]
For what it's worth, I'm seeing the exact problem with 0.74.2.7, it's not just @char101.
Searching through the source code there are multiple places where SetForegroundWindow is called.
I'm not sure which one is causing this but it definitely shouldn't be periodically stealing focus when trying (and failing!) to reconnect to a server that is done. Actually, I can't think of a single situation where it's appropriate to steal focus.
If I'm looking at the window, great. If not, I'm looking at something else, and the window should stay where I left it.

**Comment by char101** [comment]
I may have used the wrong term here. Flashing seems to meant that the taskbar icon is flashing, while what I meant was the kitty window appear and disappear for a very short time (although I guess it isn't what is happening here). The actual problem is that the currently foreground window (e.g. the editor I'm typing in) will suddenly lose focus.

**Comment by cyd01** [comment]
I thought to something else.
Can you download this [last build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

**Comment by cyd01** [comment]
That's exactly what @char101 has proposed.

**Comment by char101** [comment]
> Can you download this [last build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

Unfortunately the focus is still lost with this build.

**Comment by cyd01** [comment]
Are you sure ?
I've double checked, and it is not called anymore.

**Comment by char101** [comment]
I have just tested it again (kitty-debug.exe, Last-Modified: Tue, 03 Nov 2020 22:10:29 GMT) and now it does not steal focus anymore. Thanks.

**Comment by cyd01** [comment]
Keep this debug build.
I don't known when I will upload a new release on [Fosshub](http://www.fosshub.com/KiTTY.html).

**Comment by char101** [comment]
I already downloaded the new release from the release page on github though, so no need to wait for fosshub.
