### ISSUE TITLE
[Feature Request] Several additional settings for the configuration box window

### ISSUE THREAD

**Issue by FajeSu** [cyd01/KiTTY#239]
Hi!

Please add settings similar to below in the `[ConfigBox]` section of the `kitty.ini` file:

- `left` - X-axis position of the configuration box window
- `top` - Y-axis position of the configuration box window
- `categoryTreeHeight` - height of the session settings tree view named "Category"

Also add the ability to minimize configuration box window to the taskbar, please.

**Comment by cyd01** [comment]
`left` and `top` are available in this [build](https://www.9bis.net/kitty/files/kitty-debug.exe).
For `categoryTreeHeight`, it's a little more complicated because of the **action buttons**.

**Comment by FajeSu** [comment]
Thank you!
1. Is this build portable?
2. Is it possible to glue action buttons to the bottom of the window?

**Comment by cyd01** [comment]
1. you are right: there is no portable build. There is only one KiTTY that can be configured in portable mode or not
2. not easily, need some devs

**Comment by FajeSu** [comment]
2. I hope you succeed. I will wait.

And what do you say about this:
> Also add the ability to minimize configuration box window to the taskbar, please.

**Comment by cyd01** [comment]
Issue closed due to inactivity
