### ISSUE TITLE
Password is sent automatically when it shouldn't be sent

### ISSUE THREAD

**Issue by strguntbr** [cyd01/KiTTY#24]
Some of the servers I need to access have 2 factor authentication enabled. Which means I get a 'password' prompt and after a successful verification of the password on the server side, I get a 'verification code' prompt.
KiTTY is automatically sending the password on the verification code prompt and thus does not give me the chance to enter the correct verification code.

I found a workaround to that misbehaviour by userpasssshnosave to yes in the registry which (I guess) completely disables the automatic resending of the password.

Furthermore I tried to fix that misbehaviour in code by checking if the prompt starts with the phrase 'Password' and only automatically sending the password in that case, but I guess depending on the actual server configuration this will not work for anyone. So I'm wondering how this problem was solved in earlier versions of KiTTY (where this was working properly!)

My changes which, fixed the problem for me can be found at https://github.com/strguntbr/KiTTY (but please note that I have not been writing (or even reading) C++ code in the last ~15 years, and I was just playing trial and error to get it working for me - please don't convict me for those changes, in case they are complete bullshit ;)

**Comment by bobvandevijver** [comment]
I've experienced exactly this same issue, so I would like to see it fixed as well :)

**Comment by chrapuch** [comment]
I have the same issue. We use a special PAM module with SSH, so first it asks for a UN, then Auth Code, then Password, so strguntbr's patch is not enough for me sadly. So yeah, still looking for a fix. Thanks.

**Comment by KresoPuska** [comment]
I have the same problem with 2FA (Google authenticator).
My servers are setup to first ask for verification code and then for password, but KiTTY somehow does not relay my inputs to the servers. This stopped working with 0.71
PuTTY works fine to connect to same servers.

**Comment by odin81** [comment]
Hi, I have the same issue. The password is sent with 2FA activated, so I'm not able to type in the verification code. I have to use putty for that server, there it works fine.

**Comment by KresoPuska** [comment]
Adding option "UserPassSSHNoSave=yes" into kitty.ini section "[KiTTY]" has finaly solved the agony.

Open kitty.ini and add the line into section "KiTTY]"...
`[KiTTY]`
`UserPassSSHNoSave=yes`

**Comment by chrapuch** [comment]
> Adding line "UserPassSSHNoSave=yes" into kitty.ini section "[KiTTY]" has finaly solved the agony.
> 
> Open kitty.ini and add the line into section "KiTTY]"...
> `[KiTTY]`
> `UserPassSSHNoSave=yes`

Unfortunately it doesn't work for me. After using my Yubikey, KiTTY is storing its value and re-using as password. FYI, password is NOT saved, it's empty.
```Using username "username".
Keyboard-interactive authentication prompts from server:
| Use your Yubi:
| Password:
Send automatic password (Using keyboard-interactive authentication)
End of keyboard-interactive prompts from server
Access denied
Keyboard-interactive authentication prompts from server:
| Use your Yubi:
```

**Comment by KresoPuska** [comment]
> 
> 
> > Adding line "UserPassSSHNoSave=yes" into kitty.ini section "[KiTTY]" has finaly solved the agony.
> > Open kitty.ini and add the line into section "KiTTY]"...
> > `[KiTTY]`
> > `UserPassSSHNoSave=yes`
> 
> Unfortunately it doesn't work for me. After using my Yubikey, KiTTY is storing its value and re-using as password. FYI, password is NOT saved, it's empty.
> 
> ```
> Keyboard-interactive authentication prompts from server:
> | Use your Yubi:
> | Password:
> Send automatic password (Using keyboard-interactive authentication)
> End of keyboard-interactive prompts from server
> Access denied
> Keyboard-interactive authentication prompts from server:
> | Use your Yubi:
> ```

In my kitty.ini I actually have two lines ...
`UserPassSSHNoSave=yes`
`userpasssshnosave=yes`
Maybe it's the second line which is doing the trick (I haven't tried that).

**Comment by chrapuch** [comment]
HA! You are right! There is a bug in kitty.c, it should be case insensitive, but is not.
```
	if( ReadParameter( INIT_SECTION, "userpasssshnosave", buffer ) ) { 
		if( !stricmp( buffer, "no" ) ) SetUserPassSSHNoSave(0) ;
		if( !stricmp( buffer, "yes" ) ) SetUserPassSSHNoSave(1) ;
	}
```

**Comment by lars18th** [comment]
Hi @cyd01 ,

Please, can do you check with case insensitive with the INI parameters?

In any case, I suggest to close this issue as the original problem is fixed.
Thank you to all!
