### ISSUE TITLE
Window title gets (re)set to wrong text every time window is minimized/maximized/restored

### ISSUE THREAD

**Issue by daanzu** [cyd01/KiTTY#240]
This happens every time for me. The text that it gets set to is always the same for a given configuration, but some configurations differ between each other (and some are the same). Every time it happens, I have to trigger the terminal to resend the title-setting to get it right again.

**Comment by nmassman** [comment]
I'm also seeing this issue. It looks to be related to the "enhanced title feature" and the problem seems to go aware if you create a 'kitty.ini' file in the same directory as kitty.exe and add the following lines:
`[KiTTY]
wintitle=no`

**Comment by cyd01** [comment]
Issue closed due to inactivity
