### ISSUE TITLE
Handling "ssh://" URLs from browser and WinSCP broken?

### ISSUE THREAD

**Issue by HighPriest** [cyd01/KiTTY#241]
Kitty_portable 0.74.2.3

Launching ssh://address from a browser yields no results.
After doing kitty_portable.exe -sshhandler everything seems to be correct in the registry.

Ways to replicate:
- Start cmd.exe and launch kitty_portable.exe ssh://address - Session launches correctly
- Start a browser and type in the same ssh://address - After confirmation dialog nothing happens
- Add kitty_portable.exe as default ssh client in WinSCP
  - Register WinSCP as the default app
  - Launching ssh://address from a browser yields no results once again

**Comment by cyd01** [comment]
I think it is a Browser issue.  
It works as expected on my PC:  
![image](https://user-images.githubusercontent.com/34154246/101072543-79d46680-359e-11eb-9822-4c16d2f5c327.png)

**Comment by HighPriest** [comment]
Both vanilla putty and winscp associations work correctly.
Also, setting anything in CLASSES_ROOT doesn't work for me. The app isn't launched, nor does show up in the default apps for this protocol.
I have tried these locations for protocol associations:
CLASSES_ROOT
HKEY_LOCAL_MACHINE\SOFTWARE\Classes
HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations
and setting kitty as the terminal client in Integration->Applications

Tested from both Chrome and IE.

After unregistering WinSCP and setting Kitty as the default handler in all the above places, the client doesn't even start.

When Kitty is set as the default terminal app in WinSCP, opening a like makes the Kitty config panel appear, without any session information.

I would like to point out again that it's a portable version of kitty.

**Comment by CWempe** [comment]
I think I have the same/a similar issue.

I want to open `ssh://` links with kitty. (Win10, Chrome)
But when I click such a link Putty still opens.

I did `kitty -sshhandler` (normal and as Admin)
The Registry looks correct to me:

```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\ssh]
@="URL:SSH Protocol"
"URL Protocol"=""
"EditFlags"=dword:00000002
"BrowserFlags"=dword:00000008
"FriendlyTypeName"="@ieframe.dll,-907"

[HKEY_CLASSES_ROOT\ssh\DefaultIcon]
@="C:\\ProgramData\\chocolatey\\lib\\kitty\\tools\\kitty.exe,0"

[HKEY_CLASSES_ROOT\ssh\shell]
@=""

[HKEY_CLASSES_ROOT\ssh\shell\open]

[HKEY_CLASSES_ROOT\ssh\shell\open\command]
@="\"C:\\ProgramData\\chocolatey\\lib\\kitty\\tools\\kitty.exe\" %1"
```

I restartet Chrome, tried Firefox and Windows "Run".
Is a reboot necessary?

**Comment by CWempe** [comment]
Looks like Windows 10 is to blame. 😠 
You can define a default app in the settings GUI, which seems to ignore the registry.

![image](https://user-images.githubusercontent.com/1270359/139833607-ccba5414-58ef-49f8-8943-c2403ab90588.png)

I guess @HighPriest has WinSCP not installed. so there is no app linkd to the ssh protocol in the windows setting.

I had WinSCP installed.
Now I changed the settings there:

![image](https://user-images.githubusercontent.com/1270359/139834522-865caa6a-75e3-4f74-9ad0-0eaff05f744c.png)

![image](https://user-images.githubusercontent.com/1270359/139834930-5d06019c-1a72-4cdb-b91b-e009652d672c.png)

The correct command wa salready present in the dropdown menu.

![image](https://user-images.githubusercontent.com/1270359/139835061-4669a8da-a17d-468f-8c11-4c86412161b9.png)

```
kitty.exe -cmd "cd '!/'" !U@!@ -P !# -title "!N"
```

**Now it works for me!** 👍

**Comment by CWempe** [comment]
I noticed you might want to edit the command in WinSCP, because there are some parameters (like `-cmd "cd '!/'"` and `-title "!N"`) you do not need are can cause problems.

This should be enough.
But I did not test it yet.

```
kitty.exe !U@!@ -P !#
```
