### ISSUE TITLE
Remember window positon seems to be permanently enabled 

### ISSUE THREAD

**Issue by m-hume** [cyd01/KiTTY#242]
This appears to have been the case for all rememberable versions but also exists in 0.74.2.2 (full version ie not portable)
For a saved session, under Window -> Appearance there is checkbox titled "Remember Window Positions"
No matter whether checked or not the last position of the window is recorded (when the session is closed) and restored the next time the session is opened.
Quite sure this is not the intended operation

**Comment by cyd01** [comment]
Sorry.
I don't have this behavior on my side.
