### ISSUE TITLE
A2F problem without using Autopassword

### ISSUE THREAD

**Issue by fernandonajera** [cyd01/KiTTY#243]
I've run into the exact same problem as in #183, but I do **not** use the "Auto-login password" option.

So:
* I enter my username
* I enter my password
* When the host asks for the A2F, Kitty decides to send the password again (!), which obviously doesn't work.

![image](https://user-images.githubusercontent.com/7221617/97102379-3cc6ab80-16a5-11eb-8e4a-893cdd7e3152.png)

Is there any way to disable this sending of the password automatically? Because I just cannot log into the host with Kitty.
I tried the options of the RuTTY patch but I couldn't make a difference.

**Comment by fernandonajera** [comment]
And I found the solution in #151: https://github.com/cyd01/KiTTY/issues/151#issuecomment-610939028

So I change my question: is this option available in the UI somewhere? If not, would you consider making it visible?

**Comment by cyd01** [comment]
No it is not.
It's a global option.  You must sent it in your `kitty.ini` configuration file.

**Comment by cyd01** [comment]
I've work a little on this issue.
Please try this [build](https://www.9bis.net/kitty/files/kitty-debug.exe).
