### ISSUE TITLE
[Feature Request] Run command if kageant empty

### ISSUE THREAD

**Issue by 1mm0rt41PC** [cyd01/KiTTY#244]
I use [KeepassXC to store my SSH keys](https://keepassxc.org/docs/#faq-ssh-agent).
I would like to trigger KeepassXC to unlock the database to add ssh keys to kageant.
Is it possible to have an option in https://github.com/cyd01/KiTTY/blob/master/kitty_ini.txt to run a cmd.exe command to unlock the keepassxc database if there is no key that matches?
```ini
; Command to execute if no key matches
cmdtrigger=C:\Program Files\KeePassXC\KeePassXC.exe
```

**Comment by cyd01** [comment]
Issue closed due to inactivity
