### ISSUE TITLE
When using 2FA credentials, the command set to be auto-executed is sent as password

### ISSUE THREAD

**Issue by aldago** [cyd01/KiTTY#245]
When we log into our SSH servers we are prompted for a 2FA code. After this, we set up kitty to automatically run a script. We have been running kitty 0.71.0.6 without problems, but with latest version, the script command is sent as 2fa code, so we got a failed attempt, and when we manually input the code, the auto command is not executed.

We've tried adding UserPassSSHNoSave=yes to kitty.ini but it doesn't seem to work.

Also, this seems to happen with 0.74.x branch. Latest 0.73 works fine

**Comment by RomelSan** [comment]
Is it still happening with version 0.74.3.3 ?

**Comment by cyd01** [comment]
I've work a little on this issue.
Please try this [build](https://www.9bis.net/kitty/files/kitty-debug.exe).

**Comment by RomelSan** [comment]
The build is working.  

![Kitty](https://user-images.githubusercontent.com/11341002/100914918-b4a4a480-34a1-11eb-912c-2521d0179910.PNG)  

Let me know if you need more data.

**Comment by cyd01** [comment]
Thank you for reporting.
That help very much.
Can you test if it is OK on weak connection, when you lose the contact. It was reported that the fix has broken the auto-reconnect mechanism.

**Comment by RomelSan** [comment]
Glad to help.  
When I lose contact, on reconnect i just press enter and it auto connects.  

![Kitty Disconnect](https://user-images.githubusercontent.com/11341002/100916749-2b42a180-34a4-11eb-89cd-845465529128.PNG)  

![Kitty Reconnect](https://user-images.githubusercontent.com/11341002/100916786-3ac1ea80-34a4-11eb-85d4-9a6edd53844a.PNG)  

Of course it asks again for the 2FA code.  
On normal SSH session without 2FA, I just press enter and it reconnects fine.

**Comment by cyd01** [comment]
Thanks for your help

**Comment by cyd01** [comment]
It seems it is fixed
