### ISSUE TITLE
KiTTY prints something related to password to `kitty.log` when using password authentication

### ISSUE THREAD

**Issue by gparent** [cyd01/KiTTY#246]
**How to reproduce:**

1. Use SSH password auth
2. Try to auth to anything
3. See the `password=<gibberish>` line in `kitty.log`.

**Potential cause:** 
My guess is remove this:
https://github.com/cyd01/KiTTY/blob/8124638abad1fecf00cf77ebe1a1d76e9c0f2eb6/kitty.c#L963

**Comment by cyd01** [comment]
Done
