### ISSUE TITLE
Feature Request: Ligatures

### ISSUE THREAD

**Issue by markfaine** [cyd01/KiTTY#247]
Is there any way you could support ligatures?  It's the only thing that ever makes me consider using a different terminal but those terminals usually don't have the other features I need that KiTTY has.

See:  https://github.com/tonsky/FiraCode 
for an example.

**Comment by eladeyal-intel** [comment]
Ligatures work for me on Windows 10

**Comment by cyd01** [comment]
Issue closed due to inactivity
