### ISSUE TITLE
Possibility of releases including non-UPX packages for executables other than the main KiTTY one

### ISSUE THREAD

**Issue by jaynemo** [cyd01/KiTTY#249]
Hi boss,

I've been setting up a new install and reinstalling KiTTY among other things via Chocolatey. Unfortunately, that install, which pulls down all the packed executables from the latest release, is [presently failing](https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1563), because the recent klink.exe versions, at least, are picked up by Windows Defender. Before the problems that had led to my current need to reinstall, I'd been looking at this and running a few things in VirusTotal, and noticed that without the UPX packing, only one or two low quality virus scanners picked up the klink.exe as problematic.

Obviously these false positives are completely inscrutable, and if Defender is picking them up because klink is being used by some malware that's something that's very hard to solve permanently if the author of the malware updates to a new klink version, but it seems like the UPX packing (which really should just be transparent to virus scanners) may be an issue in this.

Would it be possible to provide non-UPX compressed executables, perhaps with that same _nocompress suffix, for the other executables? If it isn't something that you want to do but are open to, I could have a look at the build scripts- I had some success running a build with a recentish MINGW installer.

I suppose another alternative would be to just not pack any executables. That does feel like giving in to incompetent virus scanner developers, but then the disk/network savings are less critical nowadays than in the past...

Thanks

**Comment by cyd01** [comment]
KiTTY uncompressed version is already provided: https://www.fosshub.com/KiTTY.html

**Comment by majkinetor** [comment]
Kitty itself isn't flagged at this moment as I explained at #252.

**Comment by cyd01** [comment]
I close this issue because all executables (including KiTTY on [Fosshub page](https://www.fosshub.com/KiTTY.html)) are provided in uncompressed version.

**Comment by DumbJoe** [comment]
> I close this issue because all executables (including KiTTY on [Fosshub page](https://www.fosshub.com/KiTTY.html)) are provided in uncompressed version.

Portable version isn't or else why is virustotal detecting 4 threats...?
