### ISSUE TITLE
BUG: opennewcurrent doesn't load the _current_ configuration

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#250]
Hi @cyd01 ,

As commented here https://github.com/cyd01/KiTTY/issues/156#issuecomment-685650019 the shortcut "opennewcurrent" is doing the same as "opennew", that's it's opening the KiTTY Configuration window with all default parameters and no target, instead of load the running configuration.

So please, can you review the code? The idea is to include in the configuration window the same configuration as it's in the current session.

Thank you!

**Comment by lars18th** [comment]
Hi @cyd01 ,

Can you reproduce this bug?

**Comment by cyd01** [comment]
opennew: start a config box with default builtin configuration
opennewcurrent: start a config box with the current session settings, excepting the hostname

I've just re-checked.

**Comment by lars18th** [comment]
Sorry, duplicated from: https://github.com/cyd01/KiTTY/issues/156#issuecomment-736387969

**Comment by cyd01** [comment]
I've started a session on a server that listen ssh on port **2022**.  

Here is the screen copy when I chose "New Session..."  
![image](https://user-images.githubusercontent.com/34154246/101070168-447a4980-359b-11eb-996d-892ce2db9df3.png)
The proposed port is **22** as it is defined in my **Default Settings** session.

Now I've done the same with **opennewcurrent** shortcut. Here is the screen copy:  
![image](https://user-images.githubusercontent.com/34154246/101069558-75a64a00-359a-11eb-8fbe-76c3da5c2bec.png)
As you can see the port is **2022** as it is defined in my running session.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Thank you for the response. However, as I commented before _this behaviour doesn't appear in my environment_. And I don't know the reason. However, to see where is the problem, I suggest _first_ to include the "New duplicated session..." entry in the menu (see https://github.com/cyd01/KiTTY/issues/156#issuecomment-736387969). This will isolate the problem with the shortcuts, as perhaps this is the problem (and I feel that other user will agree to have this menu entry). Futhermore, as a simple enhancement I suggest too to put the _current_ target in the hostname box _but selected_.

Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

I discovered the difference: In your test you use "a manual introduced host and port", and in my test I use "a saved session". When using a saved session _nothing_ from the current session is "copied". I discovered this checking it manually to connect to a new host with a non-default 22 port. And yes, in this case the command works. But this is not the completed expected behaviour: the idea is to copy _all_ running values (that are a combination of the session loaded, the user changes, the default values plus the in-session modifications) and use _all of them_ for a new session.

I hope you want to implement/fix this.
Regards.

**Comment by cyd01** [comment]
No I did not use "a manual introduced host and port". I've started a saved session.

**Comment by cyd01** [comment]
I've made a [build](https://www.9bis.net/kitty/files/kitty-debug.exe) with the new menu item: "New duplicated session...".  
I'm doing some more tests. But it seems I should not only remove `host` setting, but `username` and `password` too. And maybe `port`.

**Comment by lars18th** [comment]
> I've made a [build](https://www.9bis.net/kitty/files/kitty-debug.exe) with the new menu item: "New duplicated session...".

Thank you! I tested it... and the same result: when using a saved session nothing is duplicated (default port 22, for example, instead of the one used). But when using "manually" it works (almost for the port). You know why? I'm using the **PORTABLE** mode in Windows 7 64bit.

Futhermore, I suggest to maintain this new menu item, and use the approach to select all the data in the "Host Name" box leaving _all_ data copied untouched. Please, don't remove/modify any of the data (host, username, password of port). If you "copy" it, _all_ data should be there!

Thank you for targeting this issue.
Regards.

**Comment by cyd01** [comment]
I must remove hostname. Otherwise the configuration structure is launchable, and KiTTY will start it rather than opening the configuration box. I don't really want to add another boolean flag in the config structure to manage it.

**Comment by lars18th** [comment]
Hi @cyd01 ,

If you can solve this in a some way, then it will be desirable. Think on this: if you see the Hostname introduced but selected, you _instantly_ note that is not a new configuration, but the _current_ configuration. So, that's a big upgrade! Very user friendly.

Perhaps you can implement it in a such way: store the current hostname (and username, both in the same string) inside a config variable called `hostname_copy`, then you can clear the hostname when calling to the function of Copy_Current_Config and the session will not be autostarted (as the hostname is empty). But inside the Window, when you create it you can check the var `hostname_copy` and if it isn't empty then you insert the value in the Box and select it.

What you think?
Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

This issue is fixed and commented in #255. Futhermore, the last request is discused in #259.
So, for clean up I close this issue.
