### ISSUE TITLE
Suggestion: Shortcut command to Open inside one Editor the kitty.ini file

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#251]
Hi @cyd01 ,

Perhaps this will sound bad for someone, but I feel it will be useful. The idea is to call to notepad with a shortcut to open directly the `kitty.ini` config file.

What you think?
Regards.

**Comment by cyd01** [comment]
Start the internal editor with SHIFT+F2.
The search in the file menu for "ini file".

**Comment by lars18th** [comment]
> Start the internal editor with SHIFT+F2. The search in the file menu for "ini file". 

Yeah! Thank you! It's the shortcut `editor=` in my case reassigned to a different key.

So, I close this issue.
Regards.
