### ISSUE TITLE
correct synatx to define only left option as alt in kitty on macos

### ISSUE THREAD

**Issue by emninger** [cyd01/KiTTY#253]
In the kitty instructions there is said:

> #: Use the option key as an alt key. With this set to no, kitty will
> #: use the macOS native Option+Key = unicode character behavior. This
> #: will break any Alt+key keyboard shortcuts in your terminal
> #: programs, but you can use the macOS unicode input technique. You
> #: can use the values: left, right, or both to use only the left,
> #: right or both Option keys as Alt, instead.
> 

Now, i do not see, what would be the correct syntax to define ONLY the left option key as alt. I tried in several ways but unfortunately to no extent. 

Thanks a lot in advance for any pointer.

**Comment by emninger** [comment]
>

**Comment by cyd01** [comment]
I seems you've been confused with another [KiTTY](https://github.com/kovidgoyal/kitty) project.
