### ISSUE TITLE
FEATURE REQUEST : port sequence

### ISSUE THREAD

**Issue by MetallianFR68** [cyd01/KiTTY#254]
Hi,

I just discovered KITTY which is a great improvement over Putty.

When I buy a new VPS, the default SSH port is 22
One of the first thing I do is changing this to 8022, 7922, 9122 or something like that to hide port 22
What would be useful is a setting where I could set a port sequence.
First Kitty tries on port 22. If this one is closed, it tries the following ports until it finds one that is open to SSH connection.

Is that be possible ?

**Comment by cyd01** [comment]
It's a very complicated modification. That will change many things in the original PuTTY source code. And above all I'm not sure it is worth it. Changing the default `ssh` port does not hide anything. The port is open. Did you looked at [Port knocking](https://www.9bis.net/kitty/#!pages/PortKnock.md) feature ? I think it is a much better security approach.

**Comment by MetallianFR68** [comment]
I tried and nos use port knocking
Thanks for you answer
