### ISSUE TITLE
Minor UI bug – Load button loads current selection but then moves to the next saved session

### ISSUE THREAD

**Issue by mollix** [cyd01/KiTTY#256]
### How to reproduce:
Using the UI, in the "Load, save or delete a stored session", when more than one session exists
Click on the 1st session, it becomes highlighted
Click "Load" button
The 1st session is loaded
**The highlight is removed from the 1st session and the 2nd session in the list becomes highlighted**

### Expected behavior:
When clicking on the "Load" button, the selected session should remain highlighted

### Note:
Please note that upon clicking on "Open" or on "Start", it's the 1st session that is started.

Thanks,

Mike

**Comment by cyd01** [comment]
I think I've a way to resolve this very old bug.
Can you check this [build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

**Comment by mollix** [comment]
Hi Cyd, sorry for the late reply. I've downloaded 0.74.3.4p and tested and though it's no longer happening on the "main" session list, the bug is still present when loading sessions from the sub-folders.

**Comment by cyd01** [comment]
Are you sure. It works on my side.  
Here is a screen copy of my sessions in a sub-directory  
![image](https://user-images.githubusercontent.com/34154246/101066450-b7cd8c80-3596-11eb-8f59-88666b64e73b.png)  
And the same just after selecting **TEST2** session and clicking **Load**  
![image](https://user-images.githubusercontent.com/34154246/101066567-dc296900-3596-11eb-9d30-0c1d9de0bf3d.png)

**Comment by mollix** [comment]
Hi Cyd,

See the video KiTTY_load_session.MOV and kitty.ini attached.

Prior to taking this, I renamed my original kitty.ini, had KiTTY recreate it, updated it only to change filter=yes to filter=no
![30CAED6F-FC0C-4E22-B34A-7200E393EF25](https://user-images.githubusercontent.com/16938161/101265560-70213f00-3715-11eb-8fb7-662bb24eec07.png)

I have a video of it but I don’t know how to attach it so I’ve sent it to kitty@9bis.com

**Comment by cyd01** [comment]
That's it !  
To fix the issue I've modified the filtering function.

**Comment by mollix** [comment]
So the filtering is currently set to no, so the other choices don't disappear when loading a saved session. Still when I load one, the selection moves to the next one. Did you get the video I sent to kitty@9bis.com?

```
; filter: enable/disable filter in saved sessions selection box
filter=no
```

**Comment by cyd01** [comment]
#255
