### ISSUE TITLE
The errors I get when using klink.exe through batch script

### ISSUE THREAD

**Issue by thphongv108** [cyd01/KiTTY#257]
**1.  Klink.exe does not display linux color commands.**
Example: 

    echo -e "\e[38;5;82m Hello \e[0m" 

Then what will be output to the screen:   [38;5;82m Hello [0m

**2. When I use "ctrl + c" keystrokes to break commands in SSH what I get is  "Terminate batch job (Y / N)?"**
I just want to interrupt on ssh, I don't want to stop my batch file.

**3. "Clear" command does not seem to work when using klink.exe**
You see, the command "clear" doesn't work, it doesn't clear the menu selection every time the loop is repeated

Please download the image description that I attach. 
[Error images.zip](https://github.com/cyd01/KiTTY/files/5633676/Error.images.zip)

Thanks to Team

**Comment by cyd01** [comment]
It is not a Plink/Klink issue.  
You should run it into a command interpreter that accept color mode. Windows **cmd.exe** seems not to work.  
Try [MinTTY](https://mintty.github.io/) (included in [PortableGit](https://git-scm.com/download/win) for example.

Here is a screen copy:  
![image](https://user-images.githubusercontent.com/34154246/101068335-e0ef1c80-3598-11eb-88ba-4aab20fca52a.png)

**Comment by thphongv108** [comment]
Windows cmd.exe seems not to work. ==>openssh running on cmd.exe is normal 👍 
![image](https://user-images.githubusercontent.com/72030787/101101779-555aa780-35fb-11eb-842c-1e82247728b2.png)

Plink.exe from cygwin
![image](https://user-images.githubusercontent.com/72030787/101103943-a1f2b280-35fc-11eb-9eca-d9365a6a5c00.png)
