### ISSUE TITLE
KiTTY on Linux

### ISSUE THREAD

**Issue by etkaar** [cyd01/KiTTY#258]
Will there be a Linux port one day or is this out of question?

**Comment by cyd01** [comment]
It's out of question.
KiTTY has diverged to much from PuTTY original. It is too much Windows specific now.

**Comment by hardhub** [comment]
> It's out of question. KiTTY has diverged to much from PuTTY original. It is too much Windows specific now.

@cyd01 Is it possible to remove windows specific things from its code in some experimental fork? How much work do you expect there? Can Windows specific code be replaced by Wine code?

P.S. Original build of KiTTY works fine on Wine except speed, it is slow, not enough responsive.
