### ISSUE TITLE
[Feature request] New Duplicate Session... with selected Host Name

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#259]
Hi @cyd01 ,

This request is commented before in another issue. However, I want to paste here some info for future review. I'm not sure if you want to implement this, but from my point of view it's very relevant because:

- Without an specific feedback the user can't distinguish between the regular Open New Session and New Duplicate Session.
- It's more clear and easy to use if the Host Name includes the current host and the text is selected, because the name can be complex and perhaps only requires to change _one_ character. Example: `node01.cloud-0A.remote-net.org` and you want to open a session in the `node02`. In this case you prefer to see the hostname fully selected.

Here some useful info to implement the selection with a TextBox: http://www.functionx.com/vccli/controls/textbox.htm
You need to call to `void SelectAll();` with the TextBox object of the Host Name... after pasting the value (that you can pass in another different _hidden_ value to not create interferences with your current code).

I hope you agree.
Regards.

**Comment by cyd01** [comment]
It's not possible to add hostname. Blank hostame is the only way to start a saved in the configuration box. Otherwise PuTTY starts directly the session and try to connect to the host.  
And I guess, PuTTY original code does not use standard Microsoft Windows objects such as TextBox. The team re-defined every graphical object to be able to have a compatible code for Linux compilation.

**Comment by lars18th** [comment]
Hi @cyd01 ,

> It's not possible to add hostname. Blank hostame is the only way to start a saved in the configuration box. Otherwise PuTTY starts directly the session and try to connect to the host.

Yes, and for this reason I suggest to pass another _parameter_ called "hostname-alt". Then when "hostname" is empty, you only need to check if "hostname-alt" has data, and if this is true, then "paste the value to the TextBox and select it".

> And I guess, PuTTY original code does not use standard Microsoft Windows objects such as TextBox. The team re-defined every graphical object to be able to have a compatible code for Linux compilation.

Ohhh! And you can't select the text inside the TextBox of the HostName? Then almost copy the "hostname-alt" to the clipboard. In this case, we can use the shortcut to paste it inside the box... 

I hope you can find a solution. And thank you for you efforts! 👍 
Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Please, can you explore my last suggestion? The idea is to pass an additional parameter ("hostname-alt") to a new session, and if you can't paste this inside the TextBox, then almost copy it to the clipboard. Then, the user can do "< CTRL > + < V >" inside the TextBox and obtain the current hostname. Remember that the idea is to work with "clusters", and in this case the hostnames can be long with some numbers; so the idea is to change only some digit.

Thank you!

**Comment by lars18th** [comment]
Hi @cyd01 ,

You've implemented it perfectly in the new release. :100: 
So I close this issue.
Regards.
