### ISSUE TITLE
Feature request: zoom font size with <ctrl> + mouse-wheel

### ISSUE THREAD

**Issue by tjaacks** [cyd01/KiTTY#26]
There are some PuTTY forks which support zooming the font size using \<ctrl\> + mouse-wheel, e.g. [PuTTYTray](https://github.com/FauxFaux/PuTTYTray). I would love to see this feature in KiTTY as well. It is quite useful when using KiTTY in presentations and tutorials.

**Comment by lars18th** [comment]
Please @cyd01 consider this enhancement!

Personally I use this combination of < CTRL > + < Mouse Wheel > to change the size with Chrome and Windows (for Icons in the desktop). So I found it very useful.

**Comment by lars18th** [comment]
Hi @cyd01 ,

To integrate this functionality ( < CTRL > + < Mouse Wheel > equivalent to the Menu "Font Up"/"Font Down") you only need to insert at this point:
https://github.com/cyd01/KiTTY/blob/b2632ef83f47f7f5dc89949c33b7487a1ecaef96/0.73_My_PuTTY/windows/window.c#L5491

This code from https://github.com/FauxFaux/PuTTYTray/blob/9dc8d3a636082ba4dbb48de71e59c8e2b9a0e593/windows/window.c#L3879
```
          // region tray-zoom

        } else if (control_pressed) {
          conf_get_fontspec(conf, CONF_font)->height +=
              MBT_WHEEL_UP == b ? 1 : -1;
          // short version of IDM_RECONF's reconfig:
          term_size(term,
                    conf_get_int(conf, CONF_height),
                    conf_get_int(conf, CONF_width),
                    conf_get_int(conf, CONF_savelines));
          reset_window(2);

          // endregion

        } else {
```

I hope you'll want to integrate it. It's quite simple and very powerful. :wink: 
Regards.

**Comment by cyd01** [comment]
Get the very last [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe).
Excuse me in advance ... I did not make so many tests ... I'm about to fly for Christmas holidays.
See you next year.

**Comment by lars18th** [comment]
> Get the very last [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe).

Thank you for the trial! However, it doesn't work... because I don't finished to see the code:

- When using your patches, you need to call the function `ChangeFontSize()` from:
https://github.com/cyd01/KiTTY/blob/71d79d4716e7f459c979097b6bdc62e68dd65212/kitty.c#L4530

**Comment by lars18th** [comment]
So the patch will be something like:

```
          // region tray-zoom

        } else if (control_pressed) {
          ChangeFontSize(hwnd, MBT_WHEEL_UP == b ? 1 : -1);

          // endregion

        } else {
```

**Comment by cyd01** [comment]
But it is not really beautiful.
Font resizing is not so reactive, but I'll do it.

**Comment by lars18th** [comment]
> But it is not really beautiful. Font resizing is not so reactive, but I'll do it.

The current menu has this functionality: "Font UP" and "Font DOWN". It's already inside the KiTTY. So this is only _another_ way to call it (more simple and fast, from my point of view).

Thank you for this very good project! :+1:

**Comment by lars18th** [comment]
Hi @cyd01 ,

This function works like a charm in the last version 0.73.1.5.
Thank you! :+1: 

Please, remember to close this issue as it's resolved.
Regards.

**Comment by cyd01** [comment]
Thanks for reporting

**Comment by tjaacks** [comment]
Thanks a lot for integrating this, @lars18th and @cyd01!
