### ISSUE TITLE
kitty.exe -convert-reg destroys session data 

### ISSUE THREAD

**Issue by trybowski** [cyd01/KiTTY#262]
Hello all,
starting point: I keep session data in _session_ directory where kitty resides. Registry for kitty is empty.

When I run **kitty.exe -convert-reg** the session data which is copied to registry in registry is broken:
1) not all entries are copied
2) some entries are copied, but content is replaced with default values

It is somehow linked to the fact that session files are in a subfolder. 
Background: there are two session files: _abc.domain.pl_ and _def.domain.pl_. They differ only with “hostname” value inside. Literally. Everything else is bit-by-bit the same, including whitespace, line endings etc. The files don't have any specific extension (the _pl_ above is a TLD).

I have narrowed it down to:
Case 1: the two files reside in sessions/XYZ. When I copy settings to registry, _abc.domain.pl_ is always copied correctly and _def.domain.pl_ is always broken (default values are used). It doesn't matter if _folder_ directive in files matches the subfolder name or not.

Case 2: Using I moved the _abc.domain.pl_ session file out of subfolder into _sessions_. From now on, the _abc_ would get broken, and _def_ works. Again, it doesn't matter if _folder_ directive in files matches the subfolder name or not.

Case 3: I moved all session files out of subfolders — all work correctly.

In my original scenario, about half of the sessions were lost completely, but I didn't get to reproduce that.

**Comment by cyd01** [comment]
`-convert-reg` is not fully operational. It is dangerous to use it.   
I've removed it from [usage](https://www.9bis.net/kitty/#!pages/CommandLine.md) documentation.
