### ISSUE TITLE
Bug: Deleting `[..]` one folder deep, deletes all saved sessions and folders, and reverts "Default Settings" file

### ISSUE THREAD

**Issue by redactedscribe** [cyd01/KiTTY#263]
I imagine it is unintentional due to how unusual I find this behavior, but when inside a folder, it is possible to delete `[..]`.

1. Back up your sessions.
2. Create a session in the root if none are present.
3. Create a folder, e.g. "X".
4. Navigate into the folder.
5. Highlight `[..]` and press the `Delete` button: all sessions from "X" have been deleted.
6. Navigate back to the root: all sessions and folders from root have also been deleted, and the "Default Settings" session has been reverted to its factory defaults.

If these steps were performed inside of `Folder1 > Folder2`, only `Folder1`'s and `Folder2`'s contents would be deleted, not the root's. So the function performs correctly, but it is dangerous.

I had backups, but someone may accidentally delete the majority of their sessions. This wouldn't be so bad if the session files were sent to the recycle bin for example, but overall, I don't think it should be allowed to delete `[..]`, or at least present a list of what will be deleted, not only "[..]".

Thanks!

```
Windows 10 20H2
KiTTY 0.74.4.1p
```

**Comment by cyd01** [comment]
You are right. It should not be allowed to delete `[..]`. [Here](https://www.9bis.net/kitty/files/kitty-debug.exe) is a quick patch.  
Of course this function is dangerous, but don't forget there is also a warning: **Are your sure you want to delete xxx directory ?**

**Comment by redactedscribe** [comment]
I realize this was a quick patch, so it is not going to be working fully. Here are some thoughts outlining how I believe KiTTY should behave (since the patch left me concerned that there may be a move away from what I think already works well):

- **New Folder** should create the folder and display it in the list.
- **Del Folder** should attempt to delete the folder you are inside if none is selected in the list, else prefer the selected one. If the  buttons **Delete** and **Delete Folder** are to remain together next to the session list (unlike in my ASCII example, see below), then maybe they can be merged into one and KiTTY be aware what it is that is attempting to be deleted.
- The **Up Folder** button may not be necessary if `[..]` can remain a feature in the list (with one less button, i.e. "Up Folder" & `↑`, this would improve how much text could be used  in my example i.e. `N` to `New`). Simply not letting the user delete `[..]` would be enough instead of removing it from being displayed in the list, and this keeps browsing the folder structure quick.
- If the **Folder drop-down** is meant to be a switcher, then ideally the drop-down list could be displayed with a tree-like structure. I think it'd be fine for it to just display the current folder's name and not be capable of switching (to keep this patch simple).

- Perhaps the folder drop-down should be located below the filter field? The related buttons could be in a row to its right.
```ascii
[__filter______] [ Clear ]
[__folder______] [↑][N][X]
|  list...     | [ Load  ]
|              | [ ...   ]
```
`↑` = Up Folder, `N` = New Folder, `X` = Delete Folder. Maybe tooltips can be added should these 1-letter buttons not be obvious.

At the very least I hope this provides some inspiration on how to tackle this problem.

Thanks.

**Comment by redactedscribe** [comment]
@cyd01 Some bugs on [your latest release](https://github.com/cyd01/KiTTY/releases/tag/v0.74.4.2):

- When saving a session to a user-created folder, it is saved to both the Default folder _and_ the user-created one. Deleting a session deletes it from _both_ folders. Double-clicking a _session_ (one that was saved inside a folder) _whilst in the root Default folder_, will open its associated folder. One would expect a double-click of a _session_ to Open (launch) it as before (double-clicking sessions inside folders works as expected).
- The **Clear** button clears _and_ returns to the Default folder. Is this ideal? Previously, clearing the filter of text remained inside the current folder.
- **Del Folder** does nothing when inside a folder, other than return to the Default folder and move the Folder to the bottom of the drop-down list.
- **Up Folder** does nothing.
- When creating a **new folder**, I suggest that KiTTY should switch to it as it is not otherwise clear that this function did anything. In comparison to previous the behavior, it was obvious that a folder was created (it showed up in the list immediately). Or instead, just immediately populate it in the list as before.
- Finally, perhaps it looks different on your system, but here, it appears the UI elements need refinement in terms of alignment.

Thanks.

**Comment by cyd01** [comment]
But which mode do you finally use ?  
- ` [..]` suggested you choose the portable mode, because of the directory structure that implies
- **Clear**, **Del Folder**, **Up Folder** buttons are classic mode only feature

It feels like you mixed the two features.

I can precise few things:
- In classic mode (i.e. saving in registry), **Folder** term was not a smart choice. In fact you should consider it as a **tag**.  All sessions have the **default** tag ... by default, and each one can have one another tag, but only one tag (it is not a list). So the **Folder drop-down** is only used to filter sessions based on this tag.  
- Yes the **clear** button acts like you describe it. Its function is to remove all filters (characters in **Saved Sessions** input field, and tag in **Folder** drop-down).
- **Del Button** tries to remove the current tag (and return to the default one) ... unless one session stills has this tag. In this case the tag re-appears
- **Up Folder** can be used to re-order tags in the Folder drop-down

**Comment by redactedscribe** [comment]
I see. I only ever use portable mode; I did not know there was any difference other than portability between the two. The patch you provided was for the classic mode, hence some confusion. I'll have to look into this more later, because as you say, I've likely misunderstood things.

**Comment by cyd01** [comment]
There is no patch for classic or other patch for portable. In fact there only one KiTTY. It can simply be configured in one mode or another.  
See that [page](https://www.9bis.net/kitty/#!pages/Portability.md) to see how to switch to portable mode.
