### ISSUE TITLE
[Feature Request] Improve Usability of the Saved Sessions Filter / Session Folders

### ISSUE THREAD

**Issue by redactedscribe** [cyd01/KiTTY#264]
In the list of saved sessions, if one selects a session, then clicks Load, all other sessions are filtered/hidden except for folders, the loaded session, and the "Default Settings" session. To be able to load a different session, one must first clear the "filter" (text field above), or load "Default Settings", to reveal the full list. I typically find loading the default settings the quickest way: only a double-click.

However when inside a folder, "Default Settings" is not present so I must instead clear the filter (or navigate to the root which could be a couple levels up). Clearing the filter always involves multiple steps and a combination of mouse and keyboard: Triple-click to select all isn't supported, so I must highlight via Select All: focus the field, Ctrl+A, Del. An alternate, faster method would be drag-highlighting over the session name, then Del.

Ideally we could have a small `[X]` / `[Clear]` button to the right of the text field, then regardless whether one is in a folder or in the root, there is always a fast and unified way to reveal all sessions: Click `[Clear]` and you're done.

Perhaps the "Default Settings" session could be linked to a `[Defaults]` button and placed in the list of already present session buttons? This way it would also be available when inside folders, not only when in the root. The more nested a folder becomes, the more convenient a dedicated `[Defaults]` potentially is.

Thanks!

```
Windows 10 20H2
KiTTY 0.74.4.1p
```

**Comment by cyd01** [comment]
The behavior you have described is the [filter feature](https://www.9bis.net/kitty/#!pages/SessionsFilter.md). Of course it is very useful for KiTTY configured in registry mode (all the sessions are in one selection box). If you choose to configure KiTTY in portable mode, the usefulness is not so important. So that there is a flag to turn the feature off. Add these lines to your `kitty.ini` configuration file:

    [ConfigBox]
    filter=no
