### ISSUE TITLE
Embed icon in EXE file

### ISSUE THREAD

**Issue by CWempe** [cyd01/KiTTY#266]
I install Kitty via Choclotey.
This creates a so called shim (dont know what that is) to install Kitty on Windows.

The result is that the link in the start menu does not have the Kitty icon, because the shim does not have one.
See: https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1463

It looks like the official icon is not embeded inside the `kitty.exe` and therfore cannot be added to the shim.

I verified that Windows cannot find an icon in the exe.

Here is a comparison with the `putty.exe`.
![image](https://user-images.githubusercontent.com/1270359/103814792-9878c200-5062-11eb-988d-10cbb2a359bb.png)

This is no big deal for me because the link in the task menu has the correct icon. 😄 
But maybe this can be fixed easily.

**Comment by cyd01** [comment]
I suggest you to close the issue since I have proposed a [solution ](https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1463) at chocolatey website.

**Comment by CWempe** [comment]
Thanks
