### ISSUE TITLE
Feature request: provide 64 bit binaries

### ISSUE THREAD

**Issue by bersbersbers** [cyd01/KiTTY#267]
I spent ~2 hours figuring out the following: `kageant.exe -c connect.bat` will invoke `connect.bat` as a 32-bit process, as `kageant.exe` itself is 32 bit. This means that `connect.bat` does not see the same `%WINDIR\System32` (compare https://serverfault.com/q/208399/) - and in fact, `qprocess.exe` is missing in the 32-bit version.

The problem does not appear in the 64-bit version of `pageant.exe`, which I now reverted to using. Please provide 64-bit builds of KiTTY - thank you ;)

**Comment by lars18th** [comment]
Hi @bersbersbers ,

The current code is not full 64-bit compatible. So, for this reason @cyd01 has disabled it in the releases. However, perhaps for some external tools it will be desirable to release it as "alfa".

**Comment by cyd01** [comment]
For the moment I won't work on any 64bits version.
