### ISSUE TITLE
KiTTY is not accepting keyboard input when reconnecting

### ISSUE THREAD

**Issue by chrapuch** [cyd01/KiTTY#268]
Hi @cyd01 ,
I'm afraid the #197  (_Reconnect hangs on password entry_) is back. 

It is NOT yet present in **v0.74.3.3**, but is present in **v0.74.3.4**. And it is in all versions since then, even the latest **v0.74.4.3**.

_Originally posted by @chrapuch in https://github.com/cyd01/KiTTY/issues/255#issuecomment-747950122_

**Comment by Lamieur** [comment]
Still there in 0.74.4.7. I stopped following which ones work and just use 0.73.2.3 which was the last known good release at the time #197 came up.

About the unreproducible tag, I've tested the new version for just one day and some hosts didn't exhibit this behavior. For me it was an AIX host, which is in the same Kerberos domain as my Linux hosts, but it's not OpenSSH, there's LAM and not PAM, stuff like that.

So for me it doesn't work on RHEL7 with their OpenSSH 7.4, Kerberos auth (either actual unix domain + nscd/nslcd or AD domain + sssd) - can't think of other things that could make a difference. If Cyd can't reproduce, maybe we can find something common between our servers that triggers this, to let him reproduce and fix this finally?

**Comment by chrapuch** [comment]
For me it's:
- Centos 6 (OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013)
- Centos 7 (OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017)
- Ubuntu WSL (OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020)

In WSL:
1. Start SSH server
2. Connect with KiTTY
3. Restart sshd on WSL terminal: `sudo pkill sshd ; sudo /etc/init.d/ssh restart`
4. KiTTY session breaks and not accepting any input

Please see the GIFs of working and not working examples. 

WORKING
![6nwfXLxYVl](https://user-images.githubusercontent.com/53754255/111968762-ca45e480-8af9-11eb-93f6-c260042f4a39.gif)

NOT WORKING
![ES7dBB4sy4](https://user-images.githubusercontent.com/53754255/111968757-c914b780-8af9-11eb-8dd3-fb896cd586f4.gif)

FYI, the last working version is v**0.74.3.3**, the first NOT working version is v**0.74.3.4**

**Comment by cyd01** [comment]
I've tried something. Can you check this [build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

**Comment by chrapuch** [comment]
> 
> 
> I've tried something. Can you check this [build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

Yes. And it is working as expected! 😃

**Comment by cyd01** [comment]
Ok, I'll do a new release.
