### ISSUE TITLE
Moving to new laptop. 

### ISSUE THREAD

**Issue by netaware-NJ** [cyd01/KiTTY#274]
I am moving to a new laptop and i exported the registry key 9bis.com under current user however all my settings and sessions are not coming to new laptop.
Can you please assist?

**Comment by lars18th** [comment]
Hi @netaware-NJ ,

Perhaps you want to use KiTTY with the PORTABLE mode. What I'm doing is this: I put _all_ files (binaries and config files) in a subdirectory of my own. Then I synch this folder using a Cloud service over _all_ my computers (desktop & laptops). And with this I have all configuration in synch over all my computers without importing/exporting. So, your problem will be gone using this way.

Please, belive me: the PORTABLE mode for a software tool is the best solution for the multi-site computing.

**Comment by cyd01** [comment]
Please copy the two files in %APPDATA%/KiTTY direrctory.

- kitty.ini: the configuration
- kitty.sav: the registry backup

Put them in the same place in your new laptop.  
Rename `kitty.sav` in `kitty.reg` and double-clic on it.
