### ISSUE TITLE
[Suggestion] In Kageant add to the menu "Open KiTTY"

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#275]
Hi,

I don't request to add a large patch about Systray support. I'm only suggesting to add a simple menu entry labeled "Open KiTTY". This will open the New Window (default window) of KiTTY.

The use case is when you close all sessions. In this case if you have the Kageant open in the systry, then you can use it to launch KiTTY. So why no?

Regards.

**Comment by cyd01** [comment]
You need something different than "New session" menu item ?

**Comment by lars18th** [comment]
> You need something different than "New session" menu item ?

No, just that!

**Comment by cyd01** [comment]
But it's already present:  
![image](https://user-images.githubusercontent.com/34154246/107403432-647f3980-6b05-11eb-9fac-66e7a7e8c5c3.png)

**Comment by lars18th** [comment]
> But it's already present:

Sorry, false! I'm using the PORTABLE version, and I launch it with `KiTTY.exe -runagent -c KiTTY.exe`. And in my case, I don't see the two first options!

Any idea?

**Comment by lars18th** [comment]
Hi @cyd01 ,

Launching the `kageant.exe` in PORTABLE mode has the same behaviour. So no "New Sesion" or "Saved Sessions...".
Please, try it to reproduce the issue.

Thank you for your effort!

**Comment by cyd01** [comment]
That's what I did. The screen copy I've joined came from the portable version too.  
I'll check the `-runagent` option.

**Comment by lars18th** [comment]
I just copied this binary https://github.com/cyd01/KiTTY/releases/download/v0.74.4.6/kageant.exe in an empty directory (without anything in the Registry) and it doesn't show the two first entries of the menu.

I can't understand it!

**Comment by lars18th** [comment]
Then, I feel the problem is because I'm using this on my `kitty.ini` file:
```
[KiTTY]
fileextension=.ktx
```
Any idea to solve the problem?

**Comment by lars18th** [comment]
Hi @cyd01 ,

I'm sure this is not working. Please, try this:

- Create an empty subdirectory in your computer.
- Download last release of `kitty_portable.exe` and `kageant.exe` and put in this subdirectory.
- Inside this subdirectory execute `kitty_portable.exe -runagent -c kitty_portable.exe`. Accept and close. This will create "Default Settings". Close kagent too (and verify that it **doesn't show** the two menu entries of new sessions).
- Launch `kagent.exe`. Re-check that it continues without showing the new menu entries.

What I'm missing? It doesn't work at all! :confused:

**Comment by cyd01** [comment]
KiTTY only recognize itself with name ... `kitty.exe` !  
For `kitty_portable.exe` I've made a quick [fix](https://www.9bis.net/kitty/files/kitty-debug.exe).

**Comment by lars18th** [comment]
> KiTTY only recognize itself with name ... `kitty.exe` !
> For `kitty_portable.exe` I've made a quick [fix](https://www.9bis.net/kitty/files/kitty-debug.exe).

I can't understand it! I downloaded this `kitty-debug.exe` and I run in the same folder `kitty-debug.exe -runagent -c kitty-debug.exe`, and the new entries doesn't show. Inside the folder I have the regular `kitty.ini` with the `fileextension=.ktx`.

I hope that almost you have identified the root cause of the problem, then you'll fix it at some point.
Thank you!

**Comment by lars18th** [comment]
Ohh!!! :fearful: 
If I rename the `kitty-debug.exe` to `kitty_portable.exe` then it works...
However, please, why not add one entry in `kitty.ini` to identify the kitty binary? like:
```
[KiTTY]
fileextension=.ktx
kittybinary=mypersonalkitty.exe
```

Regards.

**Comment by cyd01** [comment]
As `Pageant` looks for `putty.exe` only and nothing else (in `windows\winpgnt.c`):
```
        strcpy(r, "putty.exe");
        if ( (fp = fopen(b, "r")) != NULL) {
            putty_path = dupstr(b);
            fclose(fp);
        } else
            putty_path = NULL;
```
I suggest that `Kageant` do the same with `kitty.exe` ... (and with `kitty_portable.exe` too till it is available):
```
	} else {
		strcpy(r, "kitty.exe");
		if ( (fp = fopen(b, "r")) != NULL) {
			putty_path = dupstr(b);
			fclose(fp);
		} else {
			strcpy(r, "kitty_portable.exe");
			if ( (fp = fopen(b, "r")) != NULL) {
				putty_path = dupstr(b);
				fclose(fp);
			} else putty_path = NULL;
		}
	}
```

**Comment by lars18th** [comment]
Thank you @cyd01 ! Now it's working.
