### ISSUE TITLE
savemode feature is broken in the version 0.74.4.3

### ISSUE THREAD

**Issue by nkcfan** [cyd01/KiTTY#276]
I have a kitty.ini as below, and all the sessions are saved as files in `C:\Users\[username]\AppData\Roaming\KiTTY\Sessions` folder.

```
[KiTTY]
savemode=dir
```

I cannot see the saved session in the "Saved Sessions/New Folder" list in "KiTTY Configuration" window from the version 0.74.4.3.
It worked till the version 0.74.4.2

**Comment by cyd01** [comment]
There is not enough information to try to reproduce your issue.

**Comment by nkcfan** [comment]
I updated the description.

**Comment by cyd01** [comment]
Add a memory dump (https://www.9bis.net/kitty/#!pages/Savedump.md).
I need to check all your settings.

**Comment by nkcfan** [comment]
I found this issue relating to https://github.com/cyd01/KiTTY/issues/316
After changing kitty.ini as following (replacing my username), I can see the sessions. The relative path does not work, and environment variables such as `%APPDATA%\KiTTY` does not work either.
Test version v0.74.4.13
```
[KiTTY]
savemode=dir
configdir=C:\Users\[username]\AppData\Roaming\KiTTY
```
