### ISSUE TITLE
"Assertion failed" fatal error when clicking on "Clear" button

### ISSUE THREAD

**Issue by PrSunflower** [cyd01/KiTTY#278]
### Description

With KiTTY v0.74.4.6 whenever I click on the "Clear" button I get an error message:

```
Microsoft Visual C++ Runtime Library
Assertion failed!

Program: ...
File: ../tree234.C
Line: 537

Expression: !(equal_permitted && !e)
For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
```

_Screenshot:_

<img width="304" alt="assertion failed" src="https://user-images.githubusercontent.com/59576952/107918087-76882e80-6f82-11eb-9c8f-2b6069430b41.png">

<br>

This issue doesn't happen with KiTTY v0.74.4.5.

<br>

### System info

- HP Probook
- Intel Core i5-8265U
- Windows 10 Pro version 1903 64-bit

**Comment by cyd01** [comment]
Please get this [build ](https://www.9bis.net/kitty/files/kitty-debug.exe).  
Rename it as `kitty.exe`.  
Run it and press `clear` button.  
There should be a `kitty.log` file near your `kitty.exe` binary. Add it to the discussion.
Thanks for your help.

**Comment by PrSunflower** [comment]
Hi @cyd01 , thanks for replying.

_Side note:_ I updated my previous comment because I forgot to mention that the issue happens with KiTTY v0.74.4.6 but not  v0.74.4.5.

Thank you for your debug build, I ran it and got the same error on my computer. Here are the contents of the `kitty.log` file you requested:

```
01 ../config.c 1404
02 ../config.c 1406
03 ../config.c 1408
04 ../config.c 1410
05 ../config.c 1412
06 ../config.c 1414
07 ../config.c 1416
08 ../config.c 1418
09 ../config.c 1420
10 ../config.c 1422
11 ../config.c 1424

```


Hope this helps 😉. Thanks a lot for developing KiTTY!

**Comment by cyd01** [comment]
Strange. The crash did not occur in the function I imagine.  
Please can you run this new [build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?  There will be a new `kitty.log` file.
Thanks

**Comment by PrSunflower** [comment]
Hi, thanks for investigating the issue.

Here you are:

```
11 ../config.c 1436
01 ../config.c 821
02 ../config.c 824
03 ../config.c 826
04 ../config.c 831
```

**Comment by cyd01** [comment]
I think I’ve found but I’m not at work this week. I’ll try to fix it when
I’ll be back

Le lun. 22 févr. 2021 à 08:31, Pr. Sunflower <notifications@github.com> a
écrit :

**Comment by PrSunflower** [comment]
No problem. Bonnes vacances ! 🏖

**Comment by cyd01** [comment]
Please try this [build](https://www.9bis.net/kitty/files/kitty-debug.exe).

**Comment by cyd01** [comment]
> 
> 
> Hi, thanks for investigating the issue.
> 
> Here you are:
> 
> ```
> 11 ../config.c 1436
> 01 ../config.c 821
> 02 ../config.c 824
> 03 ../config.c 826
> 04 ../config.c 831
> ```
> 
> Just curious: have you tested version 0.74.4.6 on many machines / received good feedback from other users? Like,... is my computer an isolated case?

I've enabled the new [Proxy choice feature](https://www.9bis.net/kitty/#!pages/ProxyChoice.md). In this case the error did not occur.

**Comment by PrSunflower** [comment]
Indeed, this version works well without the "Clear" bug! 🥳

Thanks a lot, keep it up!
