### ISSUE TITLE
Shortcuts Syntax

### ISSUE THREAD

**Issue by mortalis13** [cyd01/KiTTY#279]
Hi.
What's the syntax for the `[Shortcuts]` section in the `.ini` file?
Didn't find any documentation.
The page http://www.9bis.net/kitty/#!pages/MenuShortcuts.md doesn't have any examples.
Tried `SHIFT+F1` for example with no result.

Thanks.

**Comment by cyd01** [comment]
Try this
```
[Shortcuts]
list={SHIFT}{F1}
{SHIFT}{F1}=WhateverYouNeed
```

**Comment by mortalis13** [comment]
Awesome.
Thanks.

And could I also use the `Ctrl` plus letters and numbers?

**Comment by lars18th** [comment]
> And could I also use the `Ctrl` plus letters and numbers?

Yes!

**Comment by mortalis13** [comment]
Then how?
None of these combinations works.
```
fullscreen={Ctrl}{Q}
fullscreen={Ctrl+Q}
fullscreen=Ctrl+Q
fullscreen={CONTROL}{Q}
fullscreen={CONTROL+Q}
fullscreen=CONTROL+Q
```

**Comment by cyd01** [comment]
Try {CONTROL}q

**Comment by mortalis13** [comment]
Thanks!
