### ISSUE TITLE
Use specific options with "ssh://" URLs from browser

### ISSUE THREAD

**Issue by ravenbasix** [cyd01/KiTTY#282]
Hello,
I'm trying to launch some specific options with an ssh connection through the URL shortcut like this:
`ssh://id@xxx.yyy "cd /dir; /bin/bash /dir/file.sh arg1"`

But obviously:
`Unable to open connection to xxx.yyy%20%22cd%20. Host does not exist`

Is there any way to use options, session or anything through those browser links?
Thanks

**Comment by cyd01** [comment]
You must base64 your command `cd /dir; /bin/bash /dir/file.sh arg1` then add it as a URL path after `/`:  

    ssh://id@xxx.yyy/Y2QgL2RpcjsgL2Jpbi9iYXNoIC9kaXIvZmlsZS5zaCBhcmcxCg==

**Comment by ravenbasix** [comment]
Awesome. Works like a charm! Thanks for the quick answer
