### ISSUE TITLE
Open KiTTY , delete a font, "Out of memory"

### ISSUE THREAD

**Issue by Machou** [cyd01/KiTTY#284]
Hello,

i'm on Windows 10, i have find a bug with KiTTY.

When you launch KiTTY as Administrator and an standard instance with SSH, and you delete the font use with KiTTY on Windows 10, KiTTY crash, and we have a "Out of memory".

Maybe possible to can fix this please ?

**Comment by cyd01** [comment]
I think it is a PuTTY issue. I did not make any modification on font management in KiTTY. Did you test it with original PuTTY ?

**Comment by Machou** [comment]
Nop i don't test with puttty :P i'm on linux now, so i can't test, i will test in few days if you want

**Comment by cyd01** [comment]
However it's a so specific use case, so that I don't think I'll fix it. It will not be worth it.

**Comment by Machou** [comment]
Okay =)
