### ISSUE TITLE
The “Check for update” button error

### ISSUE THREAD

**Issue by alexxis** [cyd01/KiTTY#29]
The “Check for update” button opens the page with the address: “http://www.9bis.net/kitty/check_update.php?version=0.71.0.5”. And my browser shows a blank page with the title "403 Forbidden", the h1-tag "Forbidden" and the text "You don't have permission to access /kitty/check_update.php on this server."

**Comment by cyd01** [comment]
Thanks for reporting this issue.
It's fixed, now.
