### ISSUE TITLE
Kitty blurry with fractional scaling

### ISSUE THREAD

**Issue by ruffson** [cyd01/KiTTY#291]
I was trying out Kitty (`0.19.3-1`) on Fedora33 with Wayland and fractional scaling at 125%.

And sadly it looks very blurry. Is there a workaround for it right now or is it on the agenda to tackle this in the future?

I attached a screenshot comparing Kitty (left) to GNOME Terminal (right) and Alacritty (bottom):
![kitty vs gnome vs alacritty](https://user-images.githubusercontent.com/1185812/115520962-f7b5b780-a28a-11eb-8921-3f27a5cbc102.png)

**Comment by clavinet** [comment]
perhaps you got those kitties mixed up and you were looking for
https://github.com/kovidgoyal/kitty

**Comment by ruffson** [comment]
> perhaps you got those kitties mixed up and you were looking for
> https://github.com/kovidgoyal/kitty

Oh man that is so embarrassing. Thank you for clearing that up. So sorry!
