### ISSUE TITLE
KiTTY version 0.74.4.11 Windows portable: "c" button entering  issue

### ISSUE THREAD

**Issue by lospejos** [cyd01/KiTTY#292]
KiTTY version 0.74.4.11 Windows portable
Windows 10 x86_64

Connected to ssh server. In command line trying to enter "zxcvb".
Commend line displays: "zxvb" (note missing "c" letter).

If string "zxcvb" copied from file, it was pretty well pasted into KiTTY command line with "c" letter.

Please assist.

Thanks

**Comment by cyd01** [comment]
Maybe you have redefined the "c" shortcut in your `kitty.ini` configuration file.  
Try to remove it.

**Comment by lospejos** [comment]
> Maybe you have redefined the "c" shortcut in your kitty.ini configuration file.

Yes, you were right.
I changed in my kitty.ini `shortcuts` parameter from `yes` to `no`, and problem with typing `c` disappeared.
