### ISSUE TITLE
Enable Tunnel to socket

### ISSUE THREAD

**Issue by honsberg** [cyd01/KiTTY#295]
my internet provider changed the mariadb from port to socket an disables connections to 3306.
the new way to connect to the database is an socket at /var/lib/mysql/mysql.sock 

first, with openssh on windows 10 the tunnel is working:
`ssh -L 33063:/var/lib/mysql/mysql.sock ssh-6xxxic@intelxxxxtdata.de`

i tryed with putty/kitty but:
![grafik](https://user-images.githubusercontent.com/12712721/116702357-45d46480-a9c9-11eb-912f-9a4c4d54be8b.png)

applying the change in registry is possible, 
![grafik](https://user-images.githubusercontent.com/12712721/116702518-7ae0b700-a9c9-11eb-812b-0aeea4f4d2b1.png)

but i cannot connect.

**Comment by cyd01** [comment]
You should use `socat`.  
See [here](https://coderwall.com/p/c3wyzq/forwarding-tcp-traffic-to-a-unix-socket).
