### ISSUE TITLE
klink.exe auto reconnect

### ISSUE THREAD

**Issue by raopuneeth** [cyd01/KiTTY#3]
Hello! Can we get some usage guidance or docs for klink.exe, the command line tool? Does it have all the features as KiTTY? Does it have the auto reconnect features? I understand i can make it use the same kitty.ini file, but cant seem to get the reconnect feature work somehow.

Thank you!

**Comment by cyd01** [comment]
No klink has not the reconnect feature.
Reconnect feature is based on Windows message events. Unfortunately klink is not a Windows program.

**Comment by lavdnone** [comment]
Is this still the case?
appears so after swap of plink with same settings
klink 0.74.3.1
