### ISSUE TITLE
KiTTY 0.71.0.5 Crashes on Input

### ISSUE THREAD

**Issue by Gizmokid2005** [cyd01/KiTTY#30]
Windows 10 Pro 1803
KiTTY 0.71.0.5 Portable (both direct and from PortableApps)

Anytime I try to launch any session, the ssh window will open, and as soon as it receives any focus/input from cursor or keyboard, it just closes, no errors, no 'crash' but the process ceases to exist anymore. I scanned the registry and didn't find any entries for KiTTY outside of the windows' built-in "most recently used" type entries.

PuTTY still seems to work just fine.

None of the 0.71.0.5 builds work (kitty, kitty_portable, kitty_uncompressed), all plagued with this same issue.

Let me know if I can provide anything to help track this down.

**Comment by Gizmokid2005** [comment]
I just confirmed the same issues with 0.71.0.6 as well.

**Comment by lars18th** [comment]
Hi @Gizmokid2005 ,

Please, try it _without_ any `kitty.ini` file. I remember that at the starting migration from 0.70 to 0.71 I suffer a similar problem. The solution has to "clear" the INI file from some legacy entries.

In any case, please @cyd01 can you provide some PORTABLE DEBUG binary? With a portable version that generates a full log perhaps will be easier to identify the cause of the issues like this.

Regards.

**Comment by Gizmokid2005** [comment]
I tried it without a kitty.ini file, and same issue. It generates the below default kitty.ini once launched.

`[Agent]
#messageonkeyusage=no
#askconfirmation=auto
[ConfigBox]
height=21
filter=yes
#default=yes
#defaultsettings=yes
#noexit=no
#windowheight=600
[KiTTY]
capslock=no
conf=yes
cygterm=no
icon=no
#iconfile=kitty.exe
#numberoficons=45
paste=no
print=yes
scriptfilefilter=All files (*.*)|*.*
size=no
shortcuts=yes
mouseshortcuts=yes
hyperlink=no
transparency=no
#configdir=
#downloaddir=
#uploaddir=
#remotedir=
#PSCPPath=
#PSCPOptions=-scp -r
#PlinkPath=
#WinSCPPath=
#CtHelperPath=
#antiidle== \k08\
#antiidledelay=60
#sshversion=OpenSSH_5.5
#WinSCPProtocol=sftp
#autostoresshkey=no
#UserPassSSHNoSave=no
#ctrltab=yes
#KiClassName=PuTTY
maxblinkingtime=5
#autoreconnect=yes
#ReconnectDelay=5
#scriptmode=yes
#adb=yes
savemode=dir
#bcdelay=0
#commanddelay=0.05
#initdelay=2.0
#internaldelay=10
#readonly=no
slidedelay=0
winroll=yes
wintitle=yes
[Print]
height=100
maxline=60
maxchar=85
[Folder]
[Launcher]
reload=yes
[Shortcuts]
#switchlogmode={SHIFT}{F5}
#showportforward={SHIFT}{F6}
print={SHIFT}{F7}
printall={F7}
`

**Comment by cyd01** [comment]
Try to disable auto reconnect:

    [KiTTY]
    autoreconnect=no

**Comment by Gizmokid2005** [comment]
@cyd01 With autoreconnect=no I still run into the same issue :(

**Comment by sigzero** [comment]
This is very strange. If I launch a session from Kitty -launcher I see the following:
1 - Terminal opens and displays the server message
2 - I paste in my password
3 - The terminal closes without errors.

If I do that very same thing by launching kitty directly and then opening the ssh session, I can paste the password and it does log me in normally.

It only happens for me when I use the -launcher switch. This does not happen with 0.7.0.0.9p.

Version:  0.71.0.6

**Comment by cyd01** [comment]
I did not reproduce your issue.
Do you use registry or portable mode ?

**Comment by sigzero** [comment]
I use portable mode.

**Comment by Gizmokid2005** [comment]
It appears for me, that the recent update 0.72.0.3 has finally solved this problem for me.

I don't know what changed, but I had issues up to 0.72.0.2 still, but now all is well again.
