### ISSUE TITLE
Problem with unicode

### ISSUE THREAD

**Issue by ljramalho** [cyd01/KiTTY#305]
Seems there is a problem with some unicode glyphs.

Using the patched "Hack Nerd Font", some characters don't print, leaving a "box" instead of the correct glyph.

Example, the commands.

echo  $'\ue5ff'     <--print correcly

but 

echo $'\uf115'      <--does NOT!

But they work in PuTTY x64.

Thank you

**Comment by cyd01** [comment]
Which PuTTY version did you test ?
- 0.74
- 0.75

**Comment by ljramalho** [comment]
I've tested it with the very latest PuTTY stable version 0.75 - x64.

Thanks

**Comment by cyd01** [comment]
I think this is the answer indeed.  
I guess that more unicode support was integrated in PuTTY 0.75.  
I'll close the issue. Please reopen it when I'll finish to include PuTTY 0.75 in KiTTY if it is still there.
