### ISSUE TITLE
zmodem ？

### ISSUE THREAD

**Issue by huai168an** [cyd01/KiTTY#306]
zmodem=yes，but not working，no zmodem options
version：0.74.4.13
os：win7 sp1

**Comment by lars18th** [comment]
Z-Modem is dropped: #13

**Comment by xcyyb** [comment]
I found an extended management tool for PuTTY, XModem, YModem, and ZModem work well. If you need to use ZModem to transfer files, you can try it. https://github.com/hfcjx/PuTTYAttach
