### ISSUE TITLE
Fatal Error: User request session restart...

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#31]
Hi @cyd01 ,

I detected this problem with the last version 0.71.0.6p... and I feel it's best to describe how to reproduce it:

- Open KiTTY and start a saved session.
- When the password login is shown, then open the Pageant and Load a key for this server.
- After that select "Close+Restart"
- The you get an error window: KiTTY Fatal Error: User request session restart...

The expected behaviour is that: as you've forgotten to load the key before, then you try to restart the session after... but the current behaviour of KiTTY is to trigger this error instead of restarting the session.

Please, can you fix this incorrect behaviour?
Thank you for this amazing PuTTY fork!

**Comment by lars18th** [comment]
Hi @cyd01 ,

Can you reproduce the problem?

**Comment by lars18th** [comment]
Hi @cyd01 ,

With the last version (0.72.0.1) the problem continues.
Please, try to reproduce the problem... it's quite simple to do it.

Regards, and thank you for the last version! :+1:

**Comment by cyd01** [comment]
This one was reproduced from the first day.
I simply did not find to work on it.

**Comment by lars18th** [comment]
Okay, I hope someday you can fix it. :smile:

**Comment by lars18th** [comment]
Hi @cyd01 ,

Problem fixed in last version v0.73.1.2 https://github.com/cyd01/KiTTY/releases/tag/v0.73.1.2
Thank you!
