### ISSUE TITLE
[Feature request] New key formats (PuTTY key format too new)

### ISSUE THREAD

**Issue by p1r473** [cyd01/KiTTY#310]
Since Putty 0.75 came out with some new key formats, (EdDsa: Ed25519, Ed448) I can't connect with Kitty since using the newer Putty keys
Unable to load key file "..private.ppk" (PuTTY key format too new)
![image](https://user-images.githubusercontent.com/9235633/129462765-92d8a007-c60f-40f3-b490-c51817fd6456.png)

**Comment by nate2014jatc** [comment]
You can work around this by manually telling PuTTYGEN to use key format V2, and still use modern key types.

**Comment by p1r473** [comment]
I tried that, it didnt work unfortunately
![image](https://user-images.githubusercontent.com/9235633/133466873-7cc51d90-fbc6-4c9e-91b3-3bedcf60c12a.png)

**Comment by p1r473** [comment]
I tried that, and neither Kitty nor Putty can use that 
![image](https://user-images.githubusercontent.com/9235633/133467140-117c4d04-f81c-470d-835d-a3bc19fead6d.png)
![image](https://user-images.githubusercontent.com/9235633/133467100-bfad7b1a-c535-4251-b048-b71813f38b33.png)

**Comment by nate2014jatc** [comment]
That particular issue may be caused by your SSH server being out of date. It doesn't look like the error I received.
I'll take a screenshot when I can get to my laptop.

**Comment by p1r473** [comment]
I have all the latest packages through apt, so I think my SSH server is latest build on my Pi 4

**Comment by f1mishutka** [comment]
> You can work around this by manually telling PuTTYGEN to use key format V2, and still use modern key types.

Thank you for this suggestion, helped for me!

**Comment by rob4226** [comment]
Couldn't get ed25519 or ed448 to work in KiTTY unfortunately 😞 but they do work nicely in the latest PuTTY (.76).

**Comment by nate2014jatc** [comment]
I'm using ED25519 on KiTTY right now.
Did you remember to manually select the old key format and save it as a new file?

**Comment by rob4226** [comment]
I tried to in puttygen, but I didn't see that option.  Where can you select a different format? Thank you

**Comment by nate2014jatc** [comment]
Under "Keys > Parameters for saving key files" select "PPK version: 2"
Then save your key.
You can then open the file in a text editor and verify that it says "PuTTY-User-Key-File-2:" on the first line.

**Comment by rob4226** [comment]
Awesome! Thank you, that worked!!

**Comment by nate2014jatc** [comment]
Glad to hear that!

**Comment by p1r473** [comment]
Fixed in latest version
