### ISSUE TITLE
Autoreconnect stuck on Error message

### ISSUE THREAD

**Issue by MacGyver27** [cyd01/KiTTY#32]
Hi,

My scenario is to use kitty as a tunnel initiator from the host. While having **autoreconnect** set up the kitty will hang on a error message window and won't reconnect.. E.g. if there is a short network disconnect, error will say it cannot resolve the host and requires manual confirmation in order to proceed and then it will autoreconnect. It is counterproductive and there should be another check-box to suppress any kind of errors and just try to reconnect in a infinite loop.

![image](https://user-images.githubusercontent.com/6546231/61704624-6a0b0800-ad44-11e9-85e9-9c83586a7796.png)

This would be much appreciated, thanks Michal

**Comment by lars18th** [comment]
Hi @cyd01 ,

That's an interesting suggestion. More or less a _simple_ option to "RECONNECT WITHOUT MESSAGES". The idea is to reconnect at best effort.

You agree?

**Comment by MacGyver27** [comment]
There is still hope!!! Thing is that I have open tunnel to my server at home and sometimes network fluctuates or need to perform a reboot of the server and the tunnel is not re-established.
So introducing another checkbox to do reconnecting infinitely in the background without any error message. It is enough to try it once per minute for example. Appreciate your attention here, Michal

**Comment by lars18th** [comment]
For "permanent" SSH Tunnels I prefer to use other tools. However, I feel your suggestion has sense.

We need to wait to @cyd01 . Perhaps he want to implement it.

**Comment by MacGyver27** [comment]
Anyway I also have noticed, when such an interrupt happens, you confirm the error, session gets automatically re-established again but no longer with the tunnel port forwarding.. it needs to be manually closed and opened again from the scratch..

**Comment by cyd01** [comment]
It's a known limitation.
Currently tunnel forwardings are not re-established after automatic
reconnect.

**Comment by lars18th** [comment]
> It's a known limitation. Currently tunnel forwardings are not re-established after automatic reconnect.

I suffer this problem. Can do you do something to overcome this limitation? I usually use KiTTY to stablish some socks tunnels over wifi networks, and it will be very useful if the forwardings are re-established automatically (that's without using the recent option of "Close+Restart").

Regards.

**Comment by MacGyver27** [comment]
Yeah.. plus this feature request would be nice so we dont find ourselves cut off :/ Appreciate your time.

**Comment by cyd01** [comment]
> 
> 
> Hi @cyd01 ,
> 
> That's an interesting suggestion. More or less a _simple_ option to "RECONNECT WITHOUT MESSAGES". The idea is to reconnect at best effort.
> 
> You agree?

I'm not sure I understand what you mean with **RECONNECT WITHOUT MESSAGES**.
When you check the two **Connection/Attempt to reconnect...** options the connection errors messages are already disabled => no modal pop-up anymore.

**Comment by lars18th** [comment]
Hi @cyd01 ,

That's my response to the first post of @MacGyver27 : 

>  E.g. if there is a short network disconnect, error will say it cannot resolve the host and requires manual confirmation in order to proceed and then it will autoreconnect.

Personally I don't see that errors. But he say that appear.

In any case, my _last_ request to try to overcome the limitation of no tunnel forwardings automatic re-establishement. I feel it will be very useful to solve this problem.

Regards.

**Comment by MacGyver27** [comment]
@cyd01 There is a VPN session and when it fluctuates (sometimes happens for some reason) the kitty session disconnects with the error:
![image](https://user-images.githubusercontent.com/6546231/75537512-8f1cd300-5a17-11ea-9e72-cbd4248ee063.png)
And it needs manual intervention so I end up cut off until session is manually restarted from scratch.
> When you check the two Connection/Attempt to reconnect... options the connection errors messages are already disabled => no modal pop-up anymore.

Not true. I have them both checked and I am getting this error pop up..

> I'm not sure I understand what you mean with RECONNECT WITHOUT MESSAGES.

That there will be third checkbox for suppressing such popups about any network related failures and will be silently in infinite loop in the background trying to reestablish the session.. so no manual intervention will be needed and once VPN is reestablished again it will recreate the tunnel with all port forwardings as well..

Hope it is all clear now.. Thanks, Michal

**Comment by cyd01** [comment]
Ok
I've made a little fix in oder to avoid the pop-up message (replace by a
message in event log).
Can you test it: https://www.9bis.net/kitty/files/kitty-debug.exe
Thanks for your help
Cyd

**Comment by MacGyver27** [comment]
Thank you for having a look into it! I have played with it and here are my results:

1) No more error message on network disconnect - ✔️
2) Session will automatically reconnect once network become available - ✔️
3) Remote port forwarding:
   - after network disconnect still can see on the server remote port in LISTENING state (as well as sshd process id) - ❌
      - it should also terminate all port forwardings to the remote server as you would close the session manually (tested and if you close kitty it terminates sshd process on the remote server).. no idea why it is not doing that (they way I simulate is I disable network adapter in control panel so everything should be down)
      - so session will automatically reconnect but remote port forwarding is not working due to conflict or something.. during simulated disconnect need to kill that "hung" sshd for that remote port forwarding, then it will properly re-initiate forwardings with the session

So I suspect when you have short disconnect this scenario will occur and you wont be able to use port forwarding. So they need to be "properly" terminanted - not sure why still can see it on the remote side after disconnect - maybe it will time out eventually. However this port forwarding conflict needs to be addressed while reconnecting again - so when it finds that port still being open latest session will takes precedence:

**Reconnecting -> Connected -> Check port availability for forwardings -> Check if they belong to sshd process -> IF True -> Kill all conflicts -> Reestablish port forwardings**

Thanks! Michal

**Comment by cyd01** [comment]
It's an already known issue. Port forwarding and X11 forwarding are not re-initiated. I'm sorry.

**Comment by MacGyver27** [comment]
Aren't we in the programming world anymore? Where exactly is the limitation?.. if you don't mind explaining.. should i get in touch with the putty guy? Thx

**Comment by lars18th** [comment]
Hi @MacGyver27 and @cyd01 ,

As the reconnection behaviour is enhanced in the last versions, _and_ the only problem commented here that continues not-fixed is the "port forwarding reestablishment", then I suggest (if you agree) to close this issue and continue in #71 .

I'm sure it will be preferable to join efforts maintaining the issue list in a reasonable size.
I hope you agree.
Regards.

**Comment by MacGyver27** [comment]
I agree as long the change for suppressing errors popups will become in the official version. Thanks

**Comment by lars18th** [comment]
> I agree as long the change for suppressing errors popups will become in the official version. Thanks

I feel all changes in the test version compiled by @cyd01 18 days ago are now in the _official_ version. Please, try it. :wink: 

Regards.
