### ISSUE TITLE
Start WinSCP + Space in path of SSH key breaks

### ISSUE THREAD

**Issue by noamgat** [cyd01/KiTTY#328]
Hi,

My ssh key for a certain connection is inside google drive. Therefore the path of it is "G:\My Drive\...\key".
For KiTTY it works correctly. However when I try to do "Start WinSCP" I see that the path is G:\My , so I'm pretty sure there are missing quotation marks somewhere in the code path.

**Comment by cyd01** [comment]
Do you test it ?

**Comment by noamgat** [comment]
Yes, it works! Sorry for not answering earlier. Thanks!
