### ISSUE TITLE
Need kitty-bin-0.xx.y.zz.zip 

### ISSUE THREAD

**Issue by KarenArzumanyan** [cyd01/KiTTY#332]
For the previous version ([0.74.4.13](https://github.com/cyd01/KiTTY/releases/tag/v0.74.4.13)), the [kitty-bin-0.74.4.13.zip](https://github.com/cyd01/KiTTY/releases/download/v0.74.4.13/kitty-bin-0.74.4.13.zip)  archive is available for download.
It was very convenient.
Where can I download such an archive for the new version ([v0.76.0.1](https://github.com/cyd01/KiTTY/releases/tag/v0.76.0.1)) now?

**Comment by Dubbeldrank** [comment]
I have the same question.

**Comment by AntonOks** [comment]
This change breaks related package manager setups, like i.e. scoop, which you mention here http://www.9bis.net/kitty/?#!pages/scoop.md 

@cyd01 Whats the rational behind the change to not offer GitHub releases anymore, as you did in the past? Or is something broken and therefore just "temp. for now and will be fixed soon"?
I don't get idea and/or benefit of sending people to fosshub.com... beside they pay money for hits/downloads?!

**Comment by pjhitchman** [comment]
Email I got yesterday said:
"Pre-release v0.76.0.1 - v0.76.0.1"
So I assume we have to wait a bit.

**Comment by AntonOks** [comment]
> Email I got yesterday said: "Pre-release v0.76.0.1 - v0.76.0.1" So I assume we have to wait a bit.
v0.76.0.1 is (currently) not flagged as a pre-release (anymore?). Anyhow, seems like there is hope... so let's wait and pray ;)

**Comment by cyd01** [comment]
@AntonOks thanks for reporting.  
Of course it's temp. As you can see, my "Github Actions" script did not work anymore. I do not know why yet. Maybe something changed with "Actions" ?  
Anyway I can manually build the zip file and upload it to the releases page.

**Comment by AntonOks** [comment]
> 
> 
> @AntonOks thanks for reporting. Of course it's temp. As you can see, my "Github Actions" script did not work anymore. I do not know why yet. Maybe something changed with "Actions" ? Anyway I can manually build the zip file and upload it to the releases page.

Seems more to be related to docker or the / your container, I'd guess...
Anyhow, THANK YOU very much!!!
