### ISSUE TITLE
Opening WinSCP is unavailable.

### ISSUE THREAD

**Issue by aomsweet** [cyd01/KiTTY#334]
Kitty Version: `0.74.4.13`, `0.76.0.1`
OS Version: `Windows 10 21H1 64bit`

![image](https://user-images.githubusercontent.com/70388114/141036460-abf7b125-ecea-40ce-a84f-f0132a67fdcb.png)
![image](https://user-images.githubusercontent.com/70388114/141036540-231362ca-7564-47ae-b652-c7fb9a91b71b.png)
![image](https://user-images.githubusercontent.com/70388114/141036616-f4df9a53-7e9d-4efb-8293-c704f8e3fcd1.png)

Kitty's default rules, as long as `kitty.exe` and `WinSCP.exe` are in the same directory, I did this, but opening WinSCP is unavailable. I know that the absolute path of WinSCP.exe can be specified in the configuration file, but I cannot do that. Because it can't be used on other computers. 

Best Regards.

**Comment by cyd01** [comment]
I've made the same configuration as yours.  
WinSCP started correctly.  
Can you send me a [memory dump](https://www.9bis.net/kitty/#!pages/Savedump.md) just after trying to start WinSCP to check your variables.

**Comment by aomsweet** [comment]
Hi, @cyd01 
Thanks for your reply, but I am sorry that I cannot reproduce the problem. Just now, I did nothing and the WinSCP column became available, but it didn’t work before. I tried to restart the computer and delete the kitty.ini configuration. But it doesn't work.
