### ISSUE TITLE
[Bug] KiTTY (0.76.0.1): Background color error

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#337]
Hi @cyd01 ,

With the new version the background color, when changed from the configuration, is not painted at start. Instead a white background is used, and for every new line painted the correct one is used. So until you start to use the scroll the white background it's in use for the lines not painted already.

Please, can you fix it? This is quite annoying.
Thank you.

**Comment by cyd01** [comment]
I'll change definitively the setting in next release.  
Disable it by adding

    [KiTTY]
    backgroundimage=no

to your %APPDATA%/KiTTY/kitty.ini configuration file.

**Comment by lars18th** [comment]
Done. It fixes the problem. Thank you! 👍 
However, I don't know why this entry `backgroundimage=yes` was in my `kitty.ini` file because I don't use it.
After all, no problem if you remove definitively this from KiTTY.

Regards.
