### ISSUE TITLE
No connection possible with 0.76.0.1

### ISSUE THREAD

**Issue by meyergru** [cyd01/KiTTY#339]
When I start the new version, I always get an error popup saying:

![grafik](https://user-images.githubusercontent.com/17402664/141460603-be4aab04-a4a7-4541-871e-3836cbe6ea80.png)

just when I want to connect (i.e. I can see the configuration window, then enter a target and try to connect). The terminal window opens, but I get no visible answer before the popup. There is nothing apparent in the log. First, I thought that this is caused by some saved settings, but after deleting all of them, the error remains. It also occurs with KiTTY portable. PuTTY 0.76 works fine, however, as does 0.74.

What is tree234.c responsible for?

The machine is on Windows 10, fully updated.

**Comment by cyd01** [comment]
Can you test this [debug](https://www.9bis.net/kitty/files/kitty-debug.exe) snapshots ?

**Comment by meyergru** [comment]
Just did. That works.

**Comment by cyd01** [comment]
Ok. 
It will be reported in next official build
