### ISSUE TITLE
The "Check Update" button does not see a new release of KiTTY

### ISSUE THREAD

**Issue by alexxis** [cyd01/KiTTY#34]
I see a new release at github (**v0.71.0.7**). But if I press "Check update"-button in the program, I see in my browser a page with the text "Your version is up to date" and the address "http://www.9bis.net/kitty/check_update.php?version=0.71.0.6". After 10 seconds page redirects me to the new address: "http://www.9bis.net/kitty/#!index.md" where I see the string "Current version" and the button with the text "**Version: 0.71.0.6**".

**Comment by alexxis** [comment]
It works now.

**Comment by cyd01** [comment]
Maybe some delays between CDN and website updates ??
