### ISSUE TITLE
[KiTTY 0.76.0.2] Fatal application error

### ISSUE THREAD

**Issue by xanda-escuyer** [cyd01/KiTTY#342]
KiTTY crashes when invoked for ADB shell terminal. Windows event log is as follows (XML attached):-

Level	Date and Time	Source	Event ID	Task Category
Error	24/11/2021 13:26:14	Application Error	1000	(100)	"Faulting application name: kitty.exe, version: 0.76.0.1, time stamp: 0x618684f1
Faulting module name: kitty.exe, version: 0.76.0.1, time stamp: 0x618684f1
Exception code: 0xc0000005
Fault offset: 0x0009bb09
Faulting process id: 0x1f44
Faulting application start time: 0x01d7e136da5cb653
Faulting application path: C:\PROGRA~2\KiTTY\kitty.exe
Faulting module path: C:\PROGRA~2\KiTTY\kitty.exe
Report Id: 182b313b-4d2a-11ec-aa25-00247e3cd26f"

Platform:-
Windows 7 Ultimate x64
Intel Core2 Duo CPU  L9400  @ 1.86GHz

[KiTTYcrash.zip](https://github.com/cyd01/KiTTY/files/7596099/KiTTYcrash.zip)

**Comment by lars18th** [comment]
Hi @xanda-escuyer ,

I don't see any crash, but the support for ADB is discussed already in this thread #336 .

Please, continue on it if you want.
Regards.

**Comment by xanda-escuyer** [comment]
Hello,
Many thanks for reply.
We've rolled back to 0.74.4.13 in the meantime.
Thanks.

**Comment by lars18th** [comment]
> Hello, Many thanks for reply. We've rolled back to 0.74.4.13 in the meantime. Thanks.

Yes, that's the only sulution to use ADB with KiTTY at time.

I suggest if you want to close this issue too, and continue in the other, please!
