### ISSUE TITLE
Can allowing Alt + Space be made a separate preference?

### ISSUE THREAD

**Issue by Roy-Orbison** [cyd01/KiTTY#36]
When in a session window, the context menu/right-click keyboard key seems to have no effect, which would be okay except that Alt + Space to bring up the standard program menu also fails when `shortcuts=no` is set. Can this combination be re-enabled with a separate preference, or just exempt from the `shortcuts` one?

**Comment by lars18th** [comment]
Hi @cyd01 ,

I confirm than using the `shortcuts=no` the keys Alt + Space doesn't open the Window Menu.
It's good that this menu can be opened without touching the mouse (only with the keyboard), as then it will be easy to select any entry (for example one user script).

**Comment by Roy-Orbison** [comment]
This is fixed:

![image](https://user-images.githubusercontent.com/28617290/71637440-62f10a00-2c93-11ea-8d31-e7be7ec04435.png)
