### ISSUE TITLE
windows closes if dns resolution fails after network reconnect

### ISSUE THREAD

**Issue by clem4962** [cyd01/KiTTY#360]
I use kitty so my window will reconnect after a blip in an unreliable internet connection. However, after my broken connection returns, I sometimes (temporarily) get a dns error on the hostname, and kitty will then close its window, meaning I have to start again. It would be helpful if the window could survive this without closing, eg by remaining in its previous disconnected state?

Eg to simulate behaviour (using hosts file):

set a hostname in hosts file for some remote server
connect ssh session using kitty
break internet connection
remove hostname from hosts file
restore internet connection
perform some activity in the window to trigger reconnnection
Error will occur: Unable to open connection to XXXXX Host does not exist
Click OK -> Window will close

**Comment by yndx-melkov** [comment]
The problem will go away if `Connection->Attempt to reconnect on connection failure` is turned on (this matches `FailureReconnect` in registry or kitty.ini).

However if you have deliberately disconnected from your network, `Kitty` will perform useless DNS requests and connection attempts every few seconds. That may be visible and annoying.

So we don't use `FailureReconnect`. In that case, there's a slight difference in how `Kitty` handles a connection failure and a DNS failure (at least with SSH).

`start_backend()` function (located in window.c) calls `backend_init()` that actually calls `ssh_init()` (ssh.c), that finally calls `connect_to_host()`. The last one does a _synchronous_ DNS request, so if there's a DNS error, it would return an error. However (if DNS is OK), it sets up a new network connection _asynchronously_, therefore `backend_init()` would most likely return success even if the connection is going to fail a few milliseconds later.

There's a logic `start_backend()` that would display a message box and exit the program if `backend_init()` returns an error and  `FailureReconnect` is not set, even if we are manually recovering a previously existing connection. But as I have pointed above, that error value is inconsistent, and it is rather the case when DNS is OK was working only by chance.

So the bug fix is to disable the message box and `exit()`, also perform some de-initializations.
```
--- orig\window.c	2023-03-06 21:40:49 +0300
+++ KiTTY-0.76.1.5\0.76b_My_PuTTY\windows\window.c	2023-03-25 15:49:03 +0300
@@ -685,22 +685,22 @@
 		    start_backend() ;
 		    return ;
 		}
-	    } else {
+	    } else if( !is_backend_first_connected ) {
 	        MessageBox(NULL, msg, str, MB_OK);
 	    }
         }
 	sfree(str);
 	sfree(msg);
+	SetSSHConnected(0) ;
+	queue_toplevel_callback(close_session, NULL);
+	session_closed = true;
 	if( GetAutoreconnectFlag() && conf_get_int(conf,CONF_failure_reconnect) && is_backend_first_connected ) {
 	    SetConnBreakIcon(wgs.term_hwnd) ;
-	    SetSSHConnected(0) ;
-	    queue_toplevel_callback(close_session, NULL);
-	    session_closed = true;
 	    lp_eventlog(&wgs.logpolicy, "Unable to connect, trying to reconnect...") ; 
 	    SetTimer(wgs.term_hwnd, TIMER_RECONNECT, GetReconnectDelay()*1000, NULL) ; 
 	    return ;
 	}
-	else
+	else if( !is_backend_first_connected )
 #else
 	char *str = dupprintf("%s Error", appname);
         char *msg = dupprintf("Unable to open connection to\n%s\n%s",

```
