### ISSUE TITLE
Can't specify cygtermd localproxy within saved session

### ISSUE THREAD

**Issue by chrissv** [cyd01/KiTTY#371]
I followed the instructions in http://www.9bis.net/kitty/#!pages/cygtermd.md and I can invoke KiTTY using cygtermd via the shortcut just fine.
But I want to do the same thing by just opening a session.

I found an entry in the configuration which looks like it should fit my needs:

![image](https://user-images.githubusercontent.com/3324281/153732650-848b9bb6-95c7-480f-b8a6-dfc6c1428a0d.png)

I tried this, but it didn't work (the widow opened, but in a couple of seconds the title of the window shows "(inactive)" and there is no output in the terminal?

Should this work? Am I missing any other settings to make this work?

**Comment by lars18th** [comment]
Hi @chrissv ,

My suggestion with complex configurations like this is to try them first with the command line. Then, when it works, you can configure it in the GUI. That's my strategy.

Nevertheless, I found your problem. You need to mark the option "Consider proxying local host connections". Without this option my already configured session doesn't work and prints the same message as you: "(inactive)". But with it, it works like a charm! So please test it.

Regards.

**Comment by chrissv** [comment]
> My suggestion with complex configurations like this is to try them first with the command line. Then, when it works, you can configure it in the GUI. That's my strategy.

My strategy as well. I had it working with the command line

> Nevertheless, I found your problem. You need to mark the option "Consider proxying local host connections". Without this option my already configured session doesn't work and prints the same message as you: "(inactive)". But with it, it works like a charm! So please test it.

YES! That was the solution, thanks!
