### ISSUE TITLE
Portable KiTTY window closes if Window title contains "%%l"

### ISSUE THREAD

**Issue by alexxis** [cyd01/KiTTY#372]
I have 5 forwarded ports in that case. If I have one or two forwarded ports everything works properly.

**Comment by cyd01** [comment]
I'm not sure I've found the root cause, but can you test this [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?  
Thank you for you help.

**Comment by alexxis** [comment]
Hm... Thank you for your beta build. The first attempt to launch showed the same behavior of the program - it closed. But the second launch attempt was successful. But two more "buts". The third and fourth launch attempts were unsuccessful and reproduced the problem.

**Comment by cyd01** [comment]
I've made a new [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe).  
Can you check it ?

**Comment by alexxis** [comment]
The same bug is in v0.76.1.9.

**Comment by alexxis** [comment]
A new version of the KiTTY (v0.76.1.11) fixes this issue. Thank you very much! 👍
