### ISSUE TITLE
klink not portable

### ISSUE THREAD

**Issue by anonymous1184** [cyd01/KiTTY#374]
With the following configuration:

```ini
[KiTTY]
savemode=dir
```

`klink` still saves the ssh keys in the registry when using the command line parameter:

```cmd
klink -auto-store-sshkey git@github.com -T
```

Also, does not saves the keys without the parameter but the setting in `kitty.ini`:

```ini
autostoresshkey=yes
```

And the file `%LocalAppData%\PUTTY.RND` gets created.

---

All the binaries are renamed to the "original" names:

- kageant -> pageant
- kitty_portable -> putty
- klink -> plink
- kscp ->pscp

Does the naming have any impact?

**Comment by anonymous1184** [comment]
Thanks for looking into this.

While preparing a screenshot to showcase that the `.ini` was actually there and with the proper contents I issued a `type` command in a terminal and immediately knew what was wrong... file had a BOM (UTF-8, but also fails with UTF-16LE).

As soon as I changed the encoding to ANSI (CP1252) it worked properly. PuTTY executable does read the `.ini` file with BOM.

And the `PUTTY.RND` still gets created in the `%LocalAppData%` folder by either of the executables.

**Comment by ltGuillaume** [comment]
> And the `PUTTY.RND` still gets created in the `%LocalAppData%` folder by either of the executables.

Yeah, I'd like this to be addressed, too.

**Comment by cyd01** [comment]
Can you test [0.76.0.10](https://github.com/cyd01/KiTTY/releases/tag/v0.76.0.10) ?

**Comment by ltGuillaume** [comment]
@cyd01 Works!
