### ISSUE TITLE
Sending "backspace" key while antiidle=\k08\

### ISSUE THREAD

**Issue by VShawn** [cyd01/KiTTY#383]
> When I have an open SSH session and am editing code (in VIM, for example), if I take a break to work on something else, when I come back, I find that I have lost characters due to the "keepalive" keypress sending something equivalent to a backspace. https://github.com/1Remote/PRemoteM/issues/240

_Originally posted by @Sloppyedwards in https://github.com/1Remote/PRemoteM/issues/240 

Is there a way to prevent this?

**Comment by cyd01** [comment]
Clear the **Anti-idle string** in Connection panel.
