### ISSUE TITLE
Compile fails (likely just my rookie mistake)

### ISSUE THREAD

**Issue by 3dom3k** [cyd01/KiTTY#388]
Hi,

I lack experience in compiling, so maybe it is just my rookie fault. I appologize, if it is off-topic question, but I don't know a better place where to ask.

I have Windows 10 x64, Cygwin x64, all works well.

I have installed cygwin packages:
- mingw64-x86_64-gcc-core
- mingw64-x86_64-gcc-g++

I have cloned the kiTTY sources and run the make, which builds .o files, but the final command `x86_64-w64-mingw32-gcc -mwindows -s -o putty.exe .......` fails with some messages like:
- config.o:config.c:(.bss+0x40): multiple definition of `TrayIcone'
- cmdline.o:cmdline.c:(.text+0x2d1): undefined reference to `decode64'

As it can be seen in an attached [kitty-compile-220607-130000.out.txt](https://github.com/cyd01/KiTTY/files/8861121/kitty-compile-220607-130000.out.txt)
output of compilation (at around 80% of it's size).

What am I doing wrong. Do I miss some libs (cygwin packages)? in my cygwin setup?

Thank you for help.

**Comment by cyd01** [comment]
I've never succeeded in compiling KiTTY under Cygwin.  
Personally I use  [MinGW32](https://osdn.net/projects/mingw/).

As it is very complicated to compare compiler installation between two different Windows PCs, I've provided an easy way to compile a new KiTTY version with an Docker image. See the [How to compile](https://www.9bis.net/kitty/#!pages/HowToCompile.md) documentation. It is the system used in [Github Actions](https://github.com/cyd01/KiTTY/actions).

**Comment by 3dom3k** [comment]
OK. Thanks for explanation. Have a nice day.
