### ISSUE TITLE
[RFE] Getting password from LDAP/AD Server

### ISSUE THREAD

**Issue by tjyang** [cyd01/KiTTY#39]
Hi 
Since this is more liberal  version of Putty.  I like to suggest adding authenticaion via remote ldap or Active directory server.  I am no C/Windows coder myself. Just a wish ;)

**Comment by mihugo** [comment]
In addition it would be nice if pagent like app could store user/passwords combos and be passed to sessions.  The use case here is a password that changes frequently but is used for many servers.  Clearly using shared keys makes more sense like pagent works already  but for various reasons those are not being used and hence passing password in a pagent like app to the session when the user is specified

**Comment by cyd01** [comment]
I'm sorry but I have no much time to spend on KiTTY (it's not my real job you know).
As password is not a good idea (regarding security perspective) I really suggest you to use private key authentication. I won't consider this evolution request.
