### ISSUE TITLE
Malware Detected by MalwareBytes

### ISSUE THREAD

**Issue by drencorxeen** [cyd01/KiTTY#4]
![image](https://user-images.githubusercontent.com/14010507/55210103-e08f6300-51b3-11e9-9df1-e2ce822c4e04.png)

Malwarebytes is detecting Malware in the binaries. :(

**Comment by JaredF** [comment]
This is probably a false positive.  Malwarebytes may be comparing the KiTTY binaries to PuTTY and reporting that there are deltas between the two.

Someone reported the same issue here:  https://forums.malwarebytes.com/topic/243660-why-malware-bytes-is-treating-kittyexe-fork-of-putty-as-quarantinable/

Here is MWB's info page on this finding in general:  https://blog.malwarebytes.com/detections/machinelearning-anomalous-100/
