### ISSUE TITLE
[RFE] Getting password from self-hosted bitwarden server

### ISSUE THREAD

**Issue by tjyang** [cyd01/KiTTY#40]
* WHY:
    * Some org has use bitwarden tool (100% open-source) to manage their admin passwords.
* Reference: 
    *  https://bitwarden.com/

**Comment by cyd01** [comment]
There are so many password managers.
KiTTY can be integrated to all. And above all don't forget, login with password is not a good idea. You should use private keys instead.
So that I've decided not to manage external password manager.
But feel free to propose a merge request.
