### ISSUE TITLE
build lossage

### ISSUE THREAD

**Issue by Devon7** [cyd01/KiTTY#406]
mingw-builds-install.exe fails with Ⓧ Cannot download repository.txt [0]

Is there a workaround?

		Peace
			--Devon

P.S.  [README.md](https://github.com/cyd01/KiTTY/#readme)
⋮
How to install the MSYS/MinGW32 environment
⋮
    Download the mingw-builds-install.exe from https://sourceforge.net/projects/mingwbuilds/files/host-windows/releases/4.8.0/32-bit/

**Comment by Devon7** [comment]
https://StackOverflow.com/questions/30069830/how-to-install-mingw-w64-and-msys2
Asks the same question.

**Comment by cyd01** [comment]
Please follow the [build instructions](https://www.9bis.net/kitty/#!pages/HowToCompile.md).
