### ISSUE TITLE
[Question] How to import settings from the Registry to the portable version?

### ISSUE THREAD

**Issue by nettnikl** [cyd01/KiTTY#409]
## Why
I have around 50 somewhat complicated entries in my registry, and have to switch to portable version in future.

## What
I'd like to store the current settings stored to the registry to a file/folder so that it can be read by the portable version.
How can i do that?

**Comment by offhub** [comment]
Make sure to backup your settings before you do this:

https://www.9bis.net/kitty/#!pages/Portability.md

> Portability
> 
> By default, KiTTY uses the Windows registry database to save its configuration (sessions, host keys, parameters). It's possible to save it into a tree directories structure and to avoid writing anything into the registry.
> 
> To do that you just have to create a file called kitty.ini in the same directory where you put KiTTY binary, and add these two lines:
> 
> ```
> [KiTTY]
> savemode=dir
> ```
> 
> At the very first use, it is possible to copy all the configuration from the registry for users who already created sessions with normal KiTTY mode. You just have to run the software on the command line with the parameter -convert-dir:
> 
> `kitty.exe -convert-dir`
> 
> This option will create 6 sub-directories:
> 
>     Commands
>     Folders
>     Launcher
>     Sessions
>     Sessions_Commands
>     SshHostKeys
> 
> containing all the configuration.
> ...

**Comment by nettnikl** [comment]
Thank you very much!
Exactly what i was looking for!
