### ISSUE TITLE
[RFE] Packaging kitty using WiX toolset

### ISSUE THREAD

**Issue by tjyang** [cyd01/KiTTY#41]
* WHY:
     * Enterprise user expect .msi to push out and maintain binary.
* HOW;
     * Hope I don't have to do it myself but if no taker,  this is something I can work on as sysadmin doing occasional packaging for Windows.

* Reference:
     * R1: https://wixtoolset.org/

**Comment by cyd01** [comment]
A package to install a single .exe file ? I think it is useless.
And above all, KiTTY is already part of a package manager I really like: [scoop.sh](https://scoop.sh/)
Here is the syntax:
```
scoop bucket add extras
sccop install kitty
```
