### ISSUE TITLE
Dead links in website

### ISSUE THREAD

**Issue by brunocu** [cyd01/KiTTY#410]
Dead links

https://github.com/cyd01/KiTTY/blob/ca0146d16f16f457ea54640a5994e73881c0b653/docs/pages/download.md?plain=1#L34-L36

Alternate tab manager I like and works with KiTTY (no affiliation):

[MTPuTTY ](https://ttyplus.com/multi-tabbed-putty/)

**Comment by cyd01** [comment]
I've updated the website.
