### ISSUE TITLE
[Solved] Ctrl+TAB & Ctrl+Shift+TAB print characters

### ISSUE THREAD

**Issue by rex-banner** [cyd01/KiTTY#411]
When using a tabbed interface  (Putty Connection Manager or SuperPutty for example), I intensively use Ctrl+TAB & Ctrl+Shift+TAB to switch between sessions.
I was using an old Kitty release 0.73.1.1 which was ok.
After migrating to 0.74.x or 0.76.x releases, my SSH sessions are now polluted with characters :
> when ctrl-tabbing, 
`[me@myhost ~]$ ;5;9~`
> when ctrl-shift-tabbing : 
`[me@myhost ~]$ ;6;9~`

**Comment by cyd01** [comment]
I don't use these tabs managers. Maybe they interact with the Windows management.  
The only I can propose it to disable it:

    [KiTTY]
    ctrltab=no

**Comment by rex-banner** [comment]
In fact, the option already exists to hangle Ctrl+Tab : Windows > Behaviour > "Switch PuTTY windows with Ctrl + TAB"
(in regedit, CtrlTabSwitch=1 )
:)
