### ISSUE TITLE
screen tool and window title bar not changed to screen's title - question

### ISSUE THREAD

**Issue by alpha0x64** [cyd01/KiTTY#417]
When I run _screen_ tool (Screen is a full-screen window manager) on PuTTY then after invoke it, window title bar on PuTTY changes to the following pattern name: `[screen 0: bash] my<ID>@servername:~`, and when create/switch to new window then `[screen 1:bash] ...` and so on. On KiTTY unfortunately I do not have information about _screen_ window in windows title bar, when I run _screen_ in KiTTY nothing happened, window title bar not changing and therefore I do not know where I am.

Is it possible to add _screen_ title information in window title bar on KiTTY?

This is not issue, just question. I had to create this question due I could not find similar "problem".

**Comment by yndx-melkov** [comment]
It works identically in putty and kitty for me. The title is usually set by `PS1` shell variable, which in turn is (usually) set by .bashrc and depends on the value of `TERM` variable.

Is the `Connection->Data->Terminal-type string` setting the same in putty and kitty?

**Comment by alpha0x64** [comment]
Status Update: This can be closed, I checked after some weeks on other machine (maybe also with new version of KiTTY) and working fine as expected. Sorry to confuse.
