### ISSUE TITLE
Enable Wiki of this github project ?

### ISSUE THREAD

**Issue by tjyang** [cyd01/KiTTY#42]
* WHAT:  Current wiki is enabled but only to project members.
![image](https://user-images.githubusercontent.com/378638/63223550-e561ad00-c17c-11e9-887c-6188d09ea37b.png)

* WHY: Just a suggestion so others(end users) can contribute notes about kitty.

**Comment by lars18th** [comment]
Hi @cyd01 ,

I recommend to enable the WIKI support in the GitHub too. With this change other users can document about KiTTY. And I feel this will reduce your required time to document the project. Futhermore then will be possible to move the documentation from http://www.9bis.net/kitty/ to the Wiki.

I hope you want to consider it.
Regards.

**Comment by lars18th** [comment]
Hi,

As the Wiki is created and ready, I suggest to close this issue.

You agree?

**Comment by tjyang** [comment]
Yes.  Thanks for enable wiki.
