### ISSUE TITLE
Auto-command/Login script populates wrong field - but it used to work, same version?

### ISSUE THREAD

**Issue by thattallguy201** [cyd01/KiTTY#427]
KiTTY v 0.76.0.10
I have an external file with a login script that works. Previously, I was able to enter the name of the file and as soon as the name was completed the contents would be encrypted and put into the "login script content" field.
![image](https://user-images.githubusercontent.com/17980140/199393271-5bc783e6-02e5-4d3e-a7d8-25dc90304ac9.png)
This session script now works, but from another machine (same executable) I am unable to repeat this; when I enter the filename the "Command" field is populated with the unencrypted script, and needless to say it does not work.
![image](https://user-images.githubusercontent.com/17980140/199393785-0bdc3d81-5d5f-4b35-8aa0-cc93283bcb20.png)
What am I doing wrong? Is there some setting that this scripting is incompatible with?

**Comment by cyd01** [comment]
Is you filename ends with `.sh` ?  
If yes, KiTTY considers it as a simple command to send to the server (not a login script with challenge/response) and populate `Command` field.  

If you want to point a login script I suggest you to rename it with another extension.  
The dialog box accepts `*.scr`, `*.txt` and of course `*.*`:  
![image](https://user-images.githubusercontent.com/34154246/201037718-81342fc6-2944-4d5b-983f-a85b65998208.png)

**Comment by thattallguy201** [comment]
That has done the job! Many thanks.
