### ISSUE TITLE
Can't connect over IPv6

### ISSUE THREAD

**Issue by lexfrei** [cyd01/KiTTY#43]
Just not working in KiTTY

![image](https://user-images.githubusercontent.com/1366514/63357969-fe33b380-c372-11e9-8efc-0728b857bc50.png)
![image](https://user-images.githubusercontent.com/1366514/63357985-0390fe00-c373-11e9-9d24-8f95eba4dfe0.png)

**Comment by DanielBrot** [comment]
You must put the IPv6 Address in square brackets Like [2001:4860:4860::8888]. Then you should connect.

**Comment by lars18th** [comment]
Hi @lexfrei ,

The solution provided by @DanielBrot solves the problem?

**Comment by lexfrei** [comment]
Yep.
It looks weird for me, not intuitive. But works

**Comment by lars18th** [comment]
OK @lexfrei ,

Then I suggest that you close this issue because it's fixed.
However, I suggest to @cyd01 to document it too.

Regards.
