### ISSUE TITLE
update from putty4far2l

### ISSUE THREAD

**Issue by unxed** [cyd01/KiTTY#431]
Please adopt the following patches:

https://github.com/unxed/putty4far2l/commit/23cad487b9b154293579f8752db971ba8b88e7e0
https://github.com/unxed/putty4far2l/commit/24991b08a05162133b49d2ebbf837853b013f28e

They are needed to fix command execution in far2l's internal VT on recent far2l versions and add support for color depth detection:
https://github.com/elfmz/far2l/issues/1389

**Comment by cyd01** [comment]
Can you check this [bete build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

**Comment by unxed** [comment]
> Can you check this [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?

whose patches
https://github.com/unxed/putty4far2l/commit/23cad487b9b154293579f8752db971ba8b88e7e0
https://github.com/unxed/putty4far2l/commit/24991b08a05162133b49d2ebbf837853b013f28e
seem to work ok!

but kitty crashes on reconnection attempt in case of connection loss. is #432 properly adopted in this build?

**Comment by cyd01** [comment]
> > Can you check this [beta build](https://www.9bis.net/kitty/files/kitty-debug.exe) ?
> 
> whose patches [unxed/putty4far2l@23cad48](https://github.com/unxed/putty4far2l/commit/23cad487b9b154293579f8752db971ba8b88e7e0) [unxed/putty4far2l@24991b0](https://github.com/unxed/putty4far2l/commit/24991b08a05162133b49d2ebbf837853b013f28e) seem to work ok!
> 
> but kitty crashes on reconnection attempt in case of connection loss if far2l is running. is #432 properly adopted in this build?

" is #432 properly adopted in this build" ==> Yes it is

**Comment by unxed** [comment]
can't reproduce as latest master refuses to build, complaining on absence of script_ahk.c

**Comment by unxed** [comment]
one more required check added
#433

**Comment by cyd01** [comment]
Thanks for your help.

**Comment by cyd01** [comment]
I think I could close this issue.
