### ISSUE TITLE
pscp integration

### ISSUE THREAD

**Issue by ShadowNev** [cyd01/KiTTY#44]
Hi
kitty_portable.exe
and
kscp.exe 
starnge behavior on Win10 
on last and some previous builds

![Screenshot_1](https://user-images.githubusercontent.com/42059626/63850743-731f7280-c99d-11e9-848f-fa35f7089355.jpg)

**Comment by lars18th** [comment]
Hi @cyd01 ,

Please can you close this ancient issue?

Regards.
