### ISSUE TITLE
Window title is missed

### ISSUE THREAD

**Issue by alexxis** [cyd01/KiTTY#450]
I use the portable kitty. And my window titles are missed. App icon is present.

**Comment by alexxis** [comment]
But I see one window title **host: %%h, port: %%p, session: %%s, f-ports: %%l** from _Window -> Behavior -> Window Title_ among other empty window titles.

**Comment by alexxis** [comment]
It seems I see empty field from _Window -> Behavior -> Window Title_ instead default window title. I saw ip-address before.

**Comment by Fredrik-69** [comment]
I see what you mean. KiTTY Portable here as well. The Window title is okay at connection but if you minimize the window, the title is lost. I can restore it by a single press on ENTER so it is something with window internal refresh that is failing.

![window_title](https://user-images.githubusercontent.com/68969282/211000391-148cf14f-592a-4a6f-9137-051952fd9db7.jpg)

**Comment by alexxis** [comment]
> I see what you mean. KiTTY Portable (0.76.1.2p) here as well. The Window title is okay at connection but if you minimize the window, the title is lost. I can restore it by a single press on ENTER so it is something with window internal refresh that is failing.
> 
> ![window_title](https://user-images.githubusercontent.com/68969282/211000391-148cf14f-592a-4a6f-9137-051952fd9db7.jpg)

Yes, you're right! The window title is lost after its minimizing.

**Comment by dlong500** [comment]
This affects all versions of KiTTY, not just the portable version.  See #451.

**Comment by cyd01** [comment]
Title management was disable due to memory crashes I did not have time to analyse:
https://github.com/cyd01/KiTTY/releases/tag/v0.76.1.2
