### ISSUE TITLE
Window title doesn't work

### ISSUE THREAD

**Issue by kiber-io** [cyd01/KiTTY#451]
Hi!
KiTTY ver: 0.76.1.2
Faced with the fact that windows title does not change any variables to real values, leaving them raw in the title.
For example, I want to set a simple title: `%%u@%%s` but in the end I get this
![изображение](https://user-images.githubusercontent.com/60169133/211321432-9a32da99-9d70-46a6-ac6c-04796f131545.png)
This is when the "Disable remote-controlled window title changing" function is disabled (because I want to uniquely separate connection windows by title, I need my own title there, for example, the name of the session).
If you enable this function, the header shows information from the server (correctly)
![изображение](https://user-images.githubusercontent.com/60169133/211321923-40fd9e7c-60c7-4a7f-a613-dd66b80bef74.png)
They don't work on custom variables. I tried to write with 1 percent sign, and edit with my hands in the session config - the result is always the same:(
In the session file, it looks like this if you set the header via gui: `WinTitle\%25%25u@%25%25s\`.
In the interface so:
![изображение](https://user-images.githubusercontent.com/60169133/211322721-6d8b6b5c-14c3-4c17-919b-5874f424a817.png)
This is a problem both in the portable version and in the regular one.

**Comment by msebald** [comment]
I can confirm this issue. Same problem here since the last upgrade to 0.76.1.2p.

**Comment by jtulp** [comment]
Me too, with "kitty_nocompress.exe" 7.16.1.0 worked fine, latest version shows "%%s".

**Comment by Fredrik-69** [comment]
Well, the release notes say:
_Switch back to original window title managment, prior to major refacto._

...which seem to be accomplished in file windows.c on line 7668 with the following statement:
  #ifdef MOD_PERSO1

So, something with the code for "original window title managment" isn't working.

**Comment by dlong500** [comment]
This really needs to get patched soon.  Another headache is that when remotely connecting to another system via ssh in a kitty instance the title may keep remote system text so it's hard to determine which system to which the shell is actually connected.

**Comment by kiber-io** [comment]
@dlong500
If I understood correctly, then the Terminal -> Functions -> Disable changing the title of the window with remote control is responsible for this

**Comment by dlong500** [comment]
@kiber-io That setting may relate to changing the window title when remoting into another system, but this new regression is what breaks all sorts of window title functionality. It goes blank, doesn't update properly, shows unresolved variables, etc.  Basically the window title is completely unreliable at this point.

**Comment by cyd01** [comment]
Title management was disable due to memory crashes I did not have time to analyse:
https://github.com/cyd01/KiTTY/releases/tag/v0.76.1.2
