### ISSUE TITLE
kiTTY ignore shortcuts=no

### ISSUE THREAD

**Issue by ThomasFTL** [cyd01/KiTTY#454]
I have the latest version and I set shortcuts=no. But F7 still brings up the print dialog.

**Comment by p1r473** [comment]
Do you have a separate .ini file in the same dir as your .exe?
On Windows there's an .ini file (if you installed) in %APPDATA%

**Comment by cyd01** [comment]
I've double checked. The feature works.

**Comment by Kaizer69** [comment]
I confirm same problem. shortcuts=no is ignored on Windows 11.
On Windows 10 works perfectly
