### ISSUE TITLE
[Security] Need configuration option to disable severe security issues

### ISSUE THREAD

**Issue by systemmonkey42** [cyd01/KiTTY#455]
Kitty supports a number of internally handled commands in the form of escape sequences.  These include
functions such as window title, however others allow a remote attacker to execute code on your local system.

The following is a brief list of the codes I know about; (there may be more)
```
Putty codes:
__pw:<dir>                 Set directory for next file send (with __rv)
__rv:<path>                Sends a file. If the path is relative, __rv sets the base directory.
__pl:<cmd>                 Launch a plink connection running <cmd>
__ti                       Report terminal title to current session
__in:<msg>                 Writes <msg> to debug log
__ws:<path>                Launch WinSCP browsing <path>
__wt:<host>:<user>:<path>  Launch WINSCP browsing <path> on <user>@<host>
__ie:<url>                 Launch Browser with <url>
__ds:<path>                Duplicate current session, auto cd to <path>
__dt:<host>:<user>:<path>  Duplicate current session on <user>@<host>.  Auto cd to <path>
__ls:<path>                Run SCRIPT file
__cm:<cmd>                 Launch an external command.
```

* The `__pl:` command will lauch a local copy of plink with parameters
* The `__ds:` command will launch another copy of kitty, connect to the same host, and inject keyboard input
* The `__cm:` command will allow the remote used to launch `cmd.exe` and run any command
* The `__ie:` will launch a browser.

Clearly any one of these could give a remote attacker the ability to take control of a session you are logged into, or remotely execute commands on your local pc.

These need a global configuration option which will disable them by default, allowing you to safely connect to shared servers.

Other commands like `__pw` and `__rv` or `__ws` should probably have a configuration option as well, but probably a separate one so they can be enabled while disabling the serious explots.

Cheers

**Comment by yndx-melkov** [comment]
Does the bug #483 contain a mitigation for this bug?

**Comment by systemmonkey42** [comment]
@yndx-melkov

Yes, apparently it does.   This works because the "__rv" style commands are actually specially formatted 'set-window-title' commands.

Unfortunately like the author of #483, I also use the "__ws" and "__rv" commands, so an apparently unrelated setting which breaks remote command execution isn't really the ideal solution.

**Comment by cyd01** [comment]
I propose a new setting for the `kitty.ini` configuration file:

```
[KiTTY
; localcmd: manage local commands (starting with __)
localcmd=yes
```

If you switch to `localcmd=no` this behavior is disabled.

Can you test the [very last release](https://github.com/cyd01/KiTTY/releases/tag/v0.76.1.11) ?

**Comment by systemmonkey42** [comment]
A generic setting for all `__` won't work because it's too general and blocks commands people actually use along with the commands which only really have a malicious use. anyone using simple winscp integration will need to enable the malicious commands

Have a separate setting for safe commands like __ti, useful commands like __pw/rv/ws (which only run commands preconfigured in the ini file), and a specific option for anything which allows the remote user to launch an arbitrary command or connection.  

Defaults should be different in each case.

**Comment by systemmonkey42** [comment]
A generic setting for all `__` won't work because it's too general and blocks commands people actually use along with the commands which only really have a malicious use. anyone using simple winscp integration will need to enable the malicious commands

Have a separate setting for safe commands like __ti, useful commands like __pw/rv/ws (which only run commands preconfigured in the ini file), and a specific option for anything which allows the remote user to launch an arbitrary command or connection.  

Defaults should be different in each case.

**Comment by lars18th** [comment]
Hi @cyd01 ,

Thank you for that! This improves a lot the security. However, it then reduces the flexibility. Therefore I suggest to add a third mode:  `localunsecurecmd=ask`. The idea is this: when a command is "sended" then a modal window appears asking to execute or not the command. And perhaps you can print the full command. I feel this has a good balance between security and functionality.

What you think?

**Comment by AkechiShiro** [comment]
@cyd01 was this fixed ? If so why is it still open ?

**Comment by cyd01** [comment]
Yes it is fixed
