### ISSUE TITLE
cmd() command does not work anymore

### ISSUE THREAD

**Issue by c1tyguide** [cyd01/KiTTY#459]
Function to run  windows commands from session window by:
`cmd() \n { \n if [ $# -eq 0 ] ; then echo "Usage: cmd command" ; return 0 ; fi \n printf "\033]0;__cm:"$@"\007" \n } ;`
such as: 
`>cmd notepad`
does nothing on 0.76.1.3p 
But works as needed on 0.76.0.12p

**Comment by c1tyguide** [comment]
And also v0.76.0.12p works good on any OpenSuse Linux, but not on any Ubuntu

**Comment by cyd01** [comment]
Title management was disable due to memory crashes I did not have time to analyse:  
https://github.com/cyd01/KiTTY/releases/tag/v0.76.1.2
