### ISSUE TITLE
Port number is not recognized as URL part

### ISSUE THREAD

**Issue by marjune163** [cyd01/KiTTY#461]
Version: 0.76.1.3

Step to reproduce:
```bash
echo URL: http://172.16.0.1:8080/
```

Expected result:
the whole URL should be underlined and clickable

Actual result:
The URL end up after hostname
![image](https://user-images.githubusercontent.com/11329183/218269082-96033e66-a7bc-4fd5-a9ad-aebbb889ce02.png)

**Comment by marjune163** [comment]
It would be nice to also recognize the IPv6 hostname. :)

**Comment by cyd01** [comment]
> ```shell
> echo URL: http://172.16.0.1:8080/
> ```

Stupid mistake. It will be fixed in next release.
