### ISSUE TITLE
putty_portable.exe crashing.

### ISSUE THREAD

**Issue by trivthebofh** [cyd01/KiTTY#47]
On Windows 10 x64 putty_portable.exe is crashing. Tried on several different computers. Reverted back to previous version and it starts fine.

Faulting application name: kitty_portable.exe, version: 0.72.0.0, time stamp: 0x5d752237
Faulting module name: kitty_portable.exe, version: 0.72.0.0, time stamp: 0x5d752237
Exception code: 0xc0000005
Fault offset: 0x000b4940
Faulting process id: 0x1904

Might be related to DEP? When I made an exception I was able to get it to run, once.

**Comment by jgehrcke** [comment]
Same here.

```
Fault bucket 1853975779600186831, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: kitty_portable.exe
P2: 0.72.0.0
P3: 5d7e69fb
P4: kitty_portable.exe
P5: 0.72.0.0
P6: 5d7e69fb
P7: c0000005
P8: 000b4960
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER152.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1B1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1D1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1CF.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1E0.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_kitty_portable.e_ff1f564812ba73f88117bbc328b2bd1e28be85b_c69d1740_26359172-f453-4619-bcf4-8535eadb73cc

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2f78be8a-cb1d-4fbf-a569-7fd468145972
Report Status: 268435456
Hashed bucket: 9120f3e58c8027ea69baa526153f3dcf
Cab Guid: 0
```

**Comment by trivthebofh** [comment]
Just tested 0.72.0.3 and still have the same issue. Apologies for the incompleteness, the first version I ran into this issue with was 0.72.0.1.

**Comment by drujd** [comment]
Same problem here.
