### ISSUE TITLE
Kitty's icon in taskbar auto change

### ISSUE THREAD

**Issue by shaynez** [cyd01/KiTTY#487]
Sometimes, the icon in taskbar will change to putty's icon, I am not sure whether trigger by some shortcut key or Kitty's auto behavior.

**Comment by studytimesz** [comment]
I found how to reproduce this behavior!  if  keep press CTRL, and click mouse, the icon will change, click once, change once. if you open touchpad and use emacs, you may trigger it sometimes...
I don't think this is a bug, but a feature, I just wanna how to disable this feature, thanks a lot. @cyd01

**Comment by cyd01** [comment]
Unfortunately this is the default behavior.  
This is one of the rare shortcuts that cannot be disabled by configuration.

**Comment by psoni2628** [comment]
A bit of a heavy-handed workaround that works for me is to simply disable all keyboard shortcuts. By default, they are enabled. I didn't use keyboard shortcuts anyway for Kitty so this is fine for me.

In your `kitty.ini`, add the following lines below.

```
[KiTTY]
shortcuts=no
```
