### ISSUE TITLE
Unable to login with 2FA

### ISSUE THREAD

**Issue by c-rilaun** [cyd01/KiTTY#49]
If 2FA is enable (with Google pam for example), you are unable to type the verification code. 
Works fine with Putty, maybe just a settings ?

Screenshot : [https://ibb.co/Vg57p3g](https://ibb.co/Vg57p3g)

**Comment by c-rilaun** [comment]
Same issue as #24 - sorry, thought nobody repport this.

**Comment by cyd01** [comment]
Maybe solve with 
- #243 
- #245

**Comment by cyd01** [comment]
Duplicate of #243 
Duplicate of #245
