### ISSUE TITLE
Kitty does not use Pageant

### ISSUE THREAD

**Issue by axb-lists** [cyd01/KiTTY#50]
sometime during the last updates, Kitty stopped using Putty's Pageant.
I'm running Kitty under Wine Windows7 (32bit)
fwiw: Winscp does see and use Pageant so keys are ok & working.
tried to use kitty with -runagent and that doesn't work either.
Anyway I can help debug this?

PS: Also tried using your kageant.exe - no luck

**Comment by axb-lists** [comment]
Using a backuped, old, Pageant 0.61 and Kitty uses pageant as expected

**Comment by axb-lists** [comment]
tried with Pageant 0.63 and it doesn't work - I'm stumped

**Comment by cyd01** [comment]
But why don't you use recent Pageant ?
0.61 is quite old! It was released in july 2011.
Personally I use the last Pageant: [https://the.earth.li/~sgtatham/putty/latest/w64/pageant.exe](https://the.earth.li/~sgtatham/putty/latest/w64/pageant.exe)
or Kageant (Pageant for KiTTY): [https://github.com/cyd01/KiTTY/releases/download/v0.72.0.2/kageant.exe](https://github.com/cyd01/KiTTY/releases/download/v0.72.0.2/kageant.exe)

**Comment by axb-lists** [comment]
as mentioned before, because for some reason Kitty won't use the newer versions running under CrossoverOffice 18.5.0 (Wine 4.0)

**Comment by axb-lists** [comment]
Seems the issue is wider than expected and not only related to Kitty.
When I run Pageant in a W98 Wine bottle Kitty sees it.
I'm working with Wine developers to find the problem.
