### ISSUE TITLE
After lost connection "host does not exist"

### ISSUE THREAD

**Issue by momala454** [cyd01/KiTTY#51]
Hello,
every time i put my windows 10 on hibernation, then power on, the active kitty windows to a specific server show a popup "unable to open connection to XXXX host does not exist".
If i click OK, the windows auto reconnect without problem, and it doesn't happens with other domains.
I can't unfortunately give you the domain, but it's a subdomain on debian, hosted on cloudflare (with the subdomain pointing to the real server of course)

**Comment by dominch** [comment]
This happens also for sleep or any connection changes, just logout, shut wifi off, login and You will reproduce that easily. For me that happens each day when I need to move from home to office (from one wifi to another). Some connections require few seconds to establish, so I get this message frequently. 

Interestingly when You have alert about lost connection and You switch to kitty window and hit any key there - then program will crash (each time). 

I think program should just remove that alert (it's useless at all) and try to reconnect with some interval. When some server is off then it just show "inactive" in window title and with any key it will try to reconnect. 

I hope cyd will have some time to look at that, momola454: You can edit title to be more precise - hibernation is not clou here, but lost connection.

**Comment by dominch** [comment]
@cyd01 - any news on this issue?

**Comment by cyd01** [comment]
I think this is fixed in release [v0.73.2.5](https://github.com/cyd01/KiTTY/releases/tag/v0.73.2.5): no more popup on reconnect.
Can someone check ?

**Comment by momala454** [comment]
yes thanks
