### ISSUE TITLE
Display pinned/recent items when on Start Menu in Windows 10

### ISSUE THREAD

**Issue by youk** [cyd01/KiTTY#52]
Would it be possible to display pinned/recent items in the context menu for KiTTY shortcut in Start Menu? Just like other programs do, Pageant for example:

![kitty](https://user-images.githubusercontent.com/5240048/65486670-b93cf880-dead-11e9-8f08-94cf91f02756.png)

**Comment by cyd01** [comment]
Issue closed due to inactivity
