### ISSUE TITLE
[HELP] Is there a way to store auto-login username and password PER SESSION / per IP adress?

### ISSUE THREAD

**Issue by 3Domse3** [cyd01/KiTTY#528]

**Comment by mariuszjedrzejewski** [comment]
What do you exactly mean?
It's default feature: each separate session defined in KiTTY (and also PuTTY) has own setting in Session -> Connection -> Data -> Login details: Auto-login username, you can store in this field everything you need.

![image](https://github.com/cyd01/KiTTY/assets/52701904/4d2378cd-1a80-4c76-998a-cbe2d6d0eadc)

Another one feature is in basic Session -> Host Name (or IP address) field: you can enter value in pure SSH form - username@server.com, and save session with name of your choice. Later it will use stored username in the same way as described above.

![image](https://github.com/cyd01/KiTTY/assets/52701904/82b6499b-b46f-47d0-bfa0-d33efb24cc65)

**Comment by 3Domse3** [comment]
@mariuszjedrzejewski 
I can't try it right now but this looks exactly like the feature I'm searching. Thank you very much for your detailed reply :D
