### ISSUE TITLE
Kitty Portable crashing launching a session with session logging enabled

### ISSUE THREAD

**Issue by Paco1960** [cyd01/KiTTY#53]
This issue happens with kitty portable version 0.72.0.3p,  but **not** using 0.70.0.10p.
When I enable "Logging" as "SSH packets and raw data" and uncheck "Omit known password fields" (to recover a forgotten password : ) ) and lauch the session, kitty crash immediately.
Same with "Omit known password fields" checked.
Log file contains only this three lines:
```
Event Log: Looking up host "nn.nn.nn.nn" for SSH connection
Event Log: Connecting to nn.nn.nn.nn port 22
Event Log: We claim version: SSH-2.0-PuTTY_KiTTY

```
where nn.nn.nn.nn is the host destinantion address.

**Comment by cyd01** [comment]
I've tried to reproduce, with no success. No crash.
I've used these settings:
![image](https://user-images.githubusercontent.com/34154246/66021427-0abb3800-e4eb-11e9-9444-2f16a1049268.png)
