### ISSUE TITLE
load ini etc from custom dir

### ISSUE THREAD

**Issue by jmlucjav** [cyd01/KiTTY#56]
Hi,

My scenario is this: 

1. I install kitty via choco, so it's installed in some place, I don't care where
2. I keep my Sessions, kitty.ini etc in a custom directory (shared across several pc with dropbox)
3. I would like to invoke kitty with some command line param so it picks up the ini/Sessions etc from my custom directory

I have been looking through the command line options,and it seems it is not possible?

thanks

**Comment by cyd01** [comment]
Use  KITTY_INI_FILE variable to point to a specific ini configuration file.

**Comment by jmlucjav** [comment]
ok, just in case somebody else needs it...let's say you have the portable config like this 
`mykittydir/kitty.ini
mykittydir/Sessions/
mykittydir/...
`
works after you set KITTY_INI_FILE= path/to/mykittydir/kitty.ini and have 
`configdir=path/to/mykittydir` in it too, that value is critical.
