### ISSUE TITLE
No guidance for Timestamp field

### ISSUE THREAD

**Issue by nseverson** [cyd01/KiTTY#57]
There is currently no guidance for variable substitution in the timestamp field (Session->Logging->Timestamp).
Per the source code, available symbols include:

`%m/%d/%Y %H:%M:%S.%f`

**Comment by cyd01** [comment]
You are right, it is not documented ... yet.
You can look at this page to get information: [https://linux.die.net/man/3/strftime](https://linux.die.net/man/3/strftime)

**Comment by svdrummer** [comment]
http://www.extraputty.com/features/timestamp.html

**Comment by cristiebee** [comment]
> This is a better format to know what to do. Have a look at this, as it is the same.
> http://www.extraputty.com/features/timestamp.html

not the same. kitty uses %f for milliseconds, extraputty uses _MIL

**Comment by svdrummer** [comment]
> > This is a better format to know what to do. Have a look at this, as it is the same.
> > http://www.extraputty.com/features/timestamp.html
> 
> not the same. kitty uses %f for milliseconds, extraputty uses _MIL

You have a link for us then? The rest seems to work fine.

**Comment by kenyroj** [comment]
Hi

Is this feature still working? I use Kitty 0.76.8. I add a timestamp setting and the config file as follow

> LogTimestamp\%H%m%S\

But I cannot see the timestamp on my console.

**Comment by cyd01** [comment]
Maybe you forget i `\` character.

    LogTimestamp\%H%m%S\
