### ISSUE TITLE
Cursor won't change in vim insert mode

### ISSUE THREAD

**Issue by DavBE** [cyd01/KiTTY#58]
Hi,

In Vim, the cursor won't change when in insert mode in Kitty. I tried different combinations of

let &t_SI = "<Esc>[5 q"

in my .vimrc but the cursor will always be a block.

Any way to change this behavior ?

Regards,

David

**Comment by kadabusha** [comment]
Hi, David.
Is the vim behavior the same as on screenshot below? No matter whether you are in selection mode or in visual, mouse pointer remains the arrow. 
In case of original putty 0.73 the issue is completely the same.

I had such an issue on FreeBSD 11.2 case no ~/.vimrc exists, though creation of even empty vimrc solves the issue.
![image](https://user-images.githubusercontent.com/47604788/67156952-d12d5e00-f32d-11e9-8219-be5c88196847.png)

**Comment by DavBE** [comment]
Hi kadabusha,

Yes, same as on screenshot. I'm running Vim 8 on Ubuntu 16.04. Same behaviour with or without empty/not empty .vimrc

David

**Comment by kadabusha** [comment]
@DavBE 
Try "add to ~/.vimrc: set mouse-=a" - [©](https://gist.github.com/u0d7i/01f78999feff1e2a8361)

it also works on my system (though it's offtopic for Kitty here)

**Comment by DavBE** [comment]
@kadabusha 
Doesn't change anything. I think it really is related to kitty.

**Comment by kadabusha** [comment]
@DavBE try setting checkbox in Preferences of Kitty:
Terminal - Features - Disable x-term-style mouse reporting

**Comment by DavBE** [comment]
@kadabusha
Cursor is still a green rectangle, it won't change.

**Comment by lars18th** [comment]
Hi @DavBE ,

I feel this KiTTY fork implement it: https://github.com/adizero/KiTTY
Please try it. If it really works, then comment here to try to join them.

Regards.

**Comment by lars18th** [comment]
Hi @DavBE ,

This optin is included in the last versions of KiTTY. Then please, try them, and if they work for you, then close this issue.

Regards.

**Comment by DavBE** [comment]
Hi @lars18th ,

Doesn't seem to work. Do I have to enable an option in the configuration ?

Regards,

David

**Comment by lars18th** [comment]
> Doesn't seem to work. Do I have to enable an option in the configuration ?

Try to change the Type of terminal in the Terminal/Keyboard configuration. Or ask to @adizero as s/he has implemented this support (PR #128). I feel with some configuration this will work now. However, perhaps @cyd01 needs to document how to enable (and use) it.

I hope it helps.
Regards.

**Comment by adizero** [comment]
There is no configuration, it is always enabled. Try something like this in shell (should switch cursor to blinking beam): `echo -ne "\e[5 q"`

For Vim try this (to have blinking beam, box or underscore in different Vim modes):
`vim --cmd 'let &t_SI="\e[5 q" | let &t_EI="\e[1 q" | let &t_SR="\e[3 q"'`

If you are launching from withing GNU Screen or Tmux you have to escape the escape sequences to reach to the outer terminal.

GNU Screen:
shell oneliner: `echo -ne "\eP\e[5 q\e\\"`

Tmux:
shell oneliner:`echo -ne "\ePtmux;\e\e[5 q\e\\"`

**Comment by DavBE** [comment]
@adizero thank you so much!

I'm running Vim within GNU Screen so I ended up adding the following to my `~/.vimrc` :

```
let &t_SI="\eP\e[5 q\e\\"
let &t_EI="\eP\e[1 q\e\\"
let &t_SR="\eP\e[3 q\e\\"
```

Regards,

David

**Comment by dagolinuxoid** [comment]
@adizero  I used terminus for the reason recently and it changes shape of a cursor instantly on escape. the  `let &t_SI="\e[5 q" | let &t_EI="\e[1 q" | let &t_SR="\e[3 q"` sequence works great for `Ctrl+C` but there is a significant delay when you hit `Esc` (escape) on returning from insert mode(line)/replace mode(underscore)  to normal mode(block).

**Comment by adizero** [comment]
The delay in Vim can be controlled with `timeout/ttimeout/timeoutlen/ttimeoutlen` settings. Try something like this: `set timeout timeoutlen=1000 ttimeoutlen=0`. The zero timeout on key bindings can cause issues when connecting from slow terminals. Maybe `ttimeoutlen=100` is safer (that is what I personally use). The `ttimeoutlen` number means how many ms will Vim wait for ambiguous incomplete keybindings (for example after pressing `Esc` in insert mode).

**Comment by dagolinuxoid** [comment]
@adizero  Thank you. Actually I get used to `Ctl + c` since it works in firefox console under vim mode and my `Caps Lock` remapped to `Ctrl` so it's easy to press.
