### ISSUE TITLE
[0.71RC3 & RC5 Portable] Different output on first connection

### ISSUE THREAD

**Issue by dsl101** [cyd01/KiTTY#6]
Connecting to a local VM via ssh, this is what I normally see on 0.70:

![image](https://user-images.githubusercontent.com/900542/57126271-4ad38e80-6d84-11e9-8024-acb8d4af50f4.png)

and with 0.71RC3Portable, I get this:

![image](https://user-images.githubusercontent.com/900542/57126285-59ba4100-6d84-11e9-888f-3d85ee5f24af.png)

Is that big left indent correct? I presume its due to the fixes on the security side of things. Login to a different machine with public key rather than password looks better:

![image](https://user-images.githubusercontent.com/900542/57126599-7014cc80-6d85-11e9-9f00-a9ffc251db86.png)

Initial testing from here on, the terminal looks OK, including running things like `ncdu` and `glances`.

**Comment by dsl101** [comment]
No change with RC5.

**Comment by lars18th** [comment]
Hi,

Just to help to @cyd01 , I suggest to **first** try to use the regular (default) PuTTY 0.71 to check it the bug/error is inside it. I don't know if this is the case, but personally I check it before post here.

The effort of Cydia is remarkable. We'd do well to help as much as we can. :wink: 
Regards.

PD: @dsl101, if this error is found only in KiTTY, please don't think that my comment is rude. :angel:

**Comment by dsl101** [comment]
Noted. But in this case, it's not possible to test on PuTTY as it doesn't offer the option to save the password—that's a specific feature and reason I use KiTTY :)

When prompting for username / password, both PuTTY and KiTTY behave normally.

**Comment by lars18th** [comment]
Ok @dsl101 ,

My previous comment is mostly generic to everyone! :wink:

**Comment by cyd01** [comment]
I've made a fix.
Can you check this beta build: https://www.9bis.net/kitty/data/beta/kitty.exe

**Comment by dsl101** [comment]
Yup—all looks good now. Tx.
