### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by paulofrazao** [cyd01/KiTTY#60]
Is the background option under been removed? I no longer have it. I tried to manually add the option in the.ini file and no luck

**Comment by cyd01** [comment]
The backgroundimage patch does not work anymore.
See [0.71 information page](https://www.9bis.net/kitty/#!pages/0.71.md).

**Comment by piksel** [comment]
@cyd01 I'm willing to take shot at re-enabling (probably re-implementing) this. Anything to note before I get too deep?

**Comment by cyd01** [comment]
Hi
I think there is no many things to do to make it working again. But I did not known enough things in Graphic management to make it. 
The background image patch came from a patch named **Covidimus** I've added into KiTTY at very begining of the KiTTY story around **2004**. At each new PuTTY version I've succeeded in adapting the patch to fit to new improvements ... until the **0.71** version.
Please note taht I did not remove the patch. It is still available. Just add the following settings to your `%APPDATA%/KiTTY/kitty.ini` configuration file:

    [KiTTY]
    debug=yes
    backgroundimage=yes

As you will see, the patch still working except at the start of the session. It is necessary to resize the Windows or to call a "clear" function inside the session to make the background image visible.
