### ISSUE TITLE
Save position and size not working properly on dual monitor setup

### ISSUE THREAD

**Issue by PieterBreugelmans** [cyd01/KiTTY#62]
Setup
- Hardware: Lenovo Thinkpad T480
- External monitors: 2 x Dell UltraSharp U2414H connects using DisplayPort via Levono USB-C dock
- OS: Windows 10 Version 1809 (OS Build 17763.805)

I use my laptop in 'desktop' mode, meaning with the lit closed and using only my 2 external monitors. These are arranged as such:

| Monitor 2 | Monitor 1|
| ---      | ---       |

That way the Windows taskbar is shown vertically on the left side of monitor 1, thus somewhat in the middle of the two, and I use monitor 2 as my primary display.

The issue is with the Save position and size on exit option in KiTTY:
- On monitor 1, KiTTY behaves correctly. A new session opens in a similar position as the previously closed one.
- On monitor 2, KiTTY will never open a new session nor the KiTTY configuration window. Instead, any new session gets an X,Y position of (0,0) so it goes into the upper left corner of monitor 1. This behavior occurs even when the KiTTY configuration window exists on monitor 2.

I can imagine that the (0,0) is somewhat of a fail safe position, not allowing negative values for either of them. However, a display setup as mine does have negative X positions for rendering any UI on monitor 2.

To illustrate I'm using a tool like:
http://breakthrusoftware.com/html/onlinedocs/kb/installkb/ScreenCoordTool.html

```
******************************
Extended Displays
******************************
Primary Display: \\.\DISPLAY1
\\.\DISPLAY1, {X=0,Y=0,Width=1920,Height=1080}
\\.\DISPLAY2, {X=-1920,Y=0,Width=1920,Height=1080} (** -X)
```

KiTTY should consider and allow negative X values for its positioning of the UI components on monitor 2. This applies to both the KiTTY configuration and session windows.

Note: The way KiTTY behaves now, I always need to drag the window to monitor 2 (my primary) which is quite annoying.

**Comment by cyd01** [comment]
Ok, I've made a beta version that allows negative X and Y values.
Get it [here](https://www.9bis.net/kitty/files/kitty-debug.exe).
Tell me if it is ok for you.

**Comment by PieterBreugelmans** [comment]
Thanks for sharing this beta version so quickly. I've done some preliminary tests and for new session it appears to do the job correct. I initially tried it with an existing one but that rendered outside the visual desktop. In the saved session file I noticed the following extreme values:

TermXPos\-32000\
TermYPos\-32000\

Perhaps these previously saved sessions got corrupted in terms of previous window position.

I'll conduct some more testing and will revert back with my results.

**Comment by cyd01** [comment]
I remember why I've disabled negative values.
I guess you use portable version. Imagine you copy (or share) your settings
files to a computer that don't have the same devices (one monitor only for
example). At session start KiTTY window could not be visible. It is a
problem. That's the reason.

**Comment by PieterBreugelmans** [comment]
Yes that is correct. Portable version though not specifically for sharing sessions across different devices. 

You do make a good point though, even on the same device it is somewhat a 'risk'. Like in my case, a laptop and external monitors, when storing negative values it'll also cause problems on those occasions that I'm solely using the laptop screen without external monitors. Would this not also be a concern for positive values extended beyond the laptops' screen dimensions? Effectively, then KiTTY would require a kind of detection mechanism that checks to see if the rendered session window is within the visible area of the desktop upon launch.

**Comment by lars18th** [comment]
Hi @PieterBreugelmans and @cyd01 ,

I suggest to close this issue as it's resolved in the last version.

Regards.
