### ISSUE TITLE
Setting auto-login in settings does not persist

### ISSUE THREAD

**Issue by aharbis** [cyd01/KiTTY#63]
Just downloaded KiTTY for the first time, and wanted to take advantage of the auto-login feature. I configured the auto-login for a session, and connected and it worked as expected. However, when I close KiTTY and re-open it, if I open the auto-login settings, they are blank. Is there some extra step I am missing? Shouldn't this configuration persist closing the application?

Additionally it is unclear how I would set up different user/pass pairs for different servers I want to connect to.

**Comment by cyd01** [comment]
You forgot to save your session after setting your login/password.
