### ISSUE TITLE
File version mismatch

### ISSUE THREAD

**Issue by opsi-archIT-KIT** [cyd01/KiTTY#64]
Please maintain attribute "file version" of kitty.exe. With 0.73.0.1 the file version is still 0.72. See following screenshot:

![kitty-version-mismatch](https://user-images.githubusercontent.com/13115745/67694460-a6817c00-f9a3-11e9-8427-7622d64cb8fe.jpg)

For installation success we are checking "file version" in our deployment system (OPSI, https://opsi.org) with internal package version.

**Comment by cyd01** [comment]
It's will be fixed in next official release. Probably 0.73.1.1

**Comment by opsi-archIT-KIT** [comment]
Thanks for fixing
