### ISSUE TITLE
Session Logging

### ISSUE THREAD

**Issue by waukeerules** [cyd01/KiTTY#65]
I am using SuperPuTTY with KiTTY portable with the following logging settings:

![image](https://user-images.githubusercontent.com/12787084/67705741-9490e080-f985-11e9-92e2-db1487bcb7e8.png)

Using these specific configurations, I do not see any logs generated from KiTTY. If I launch KiTTY by itself the logs do appear (without SuperPuTTY). If I set the logging directory to a specific C:\ location it works. It's very possible this is a SuperPuTTY issue. Has anyone else seen this behavior? 

If you're at all curious as to why I am using these specific settings. I have a script that generates SuperPuTTY sessions that reference a portable KiTTY saved session profile (multiple user credentials). When sending the KiTTY session profiles to my co-workers - I'd like to only update the specific usernames and avoid updating the log directory settings. 

Tested versions 0.72.0.6 & 0.73.0.1 (although I think this specific issue has always existed).

**Comment by cyd01** [comment]
I never use SuperPutty (I prefer PuTTYTabManager).
Can someone help ?

**Comment by waukeerules** [comment]
Are there any debugs I can enable in KiTTY to better troubleshoot the issue?

**Comment by lars18th** [comment]
Hi @waukeerules ,

Plase change the title of the issue to "SuperPuTTY: Session Logging". Then it will be more easy to trace this problem.

Thank you!
