### ISSUE TITLE
F7 key does not work anymore, it brings up a Print dialog instead

### ISSUE THREAD

**Issue by tssajo** [cyd01/KiTTY#66]
Hello,

In v0.73.0.1 release notes you said:
"bugfix: print clipboard menu was disabled on 64bits system (I don't remember why)"

Now in that version when I hit the F7 key then an unwanted Print dialog box pops up. This is terrible. It makes `mc` ( Midnight Commander ) unusable because the F7 key is hijacked.

I don't ever want to print anything from KiTTY.
How can I disable this Print popup hotkey assignment permanently?
Please let me know. Thanks!

In the meantime I am downgrading KiTTY... :(

**Comment by cyd01** [comment]
Add these settings to your %APPDATA%/KiTTY/kitty.ini configuration file:
```
[KiTTY]
shortcuts=no
```

**Comment by tssajo** [comment]
Thank you!

**Comment by dlepold** [comment]
I had the same problem. 
Yet having a standalone version of Kitty i had to search the .ini file first. 
There i found these lines : 

```
; Print current clipboard content (default if SHIFT+F7)
;print=

; Print all window buffer content (default is F7)
;printall=
```

Now i simply changed the second one to:
`printall=CONTROL+SHIFT+F7`

So using F7 in the terminal, for example for nice- in Htop, wouldn't start the printer any more :) 
- and it works perfectly :) 
Thx for the hint to @cyd01 
- though i didn't like to disable shortcuts generally.

**Comment by Janovlk** [comment]
Hello,

I'm on Windows and when I put the `printall=CONTROL+SHIFT+F7` into INI file, the Print dialog opens simply by pressing the `C` key.
When I change it to `printall=SHIFT+F7`, similarly the `S` key brings up the Print dialog.

It needs `printall={SHIFT}{F7}` , as I figured out.

Or you can disable shortcuts putting `shortcuts=no`. You can always switch them back from Shortcuts toggle in Kitty menu.

**Comment by cyd01** [comment]
I can't reproduce, please be more precise.

I've tried `printall={SHIFT}{F7}` and `printall={CONTROL}{SHIFT}{F7}` and there were no problem with `C` key nor `S` key.

**Comment by Janovlk** [comment]
Yes, as I stated, when key names are in curly brackets it work okay. Only when key names are NOT in brackets, like Mr. dlepold post suggests, it has a side affect I mentioned.
