### ISSUE TITLE
blank screen on latest kitty 

### ISSUE THREAD

**Issue by Tagar** [cyd01/KiTTY#67]
Getting blank screen on latest kitty .. resizing fixes this

I recently upgraded to 0.73.0.1 from a much older version (don't remember which one), and didn't have this issue with the older release

**Comment by cyd01** [comment]
Do you enable debug mode ?
If yes, try to disable it.

**Comment by Tagar** [comment]
@cyd01 I don't have debug mode enabled ( actually I didn't know kitty had one).
I am using `screen` all the time - not sure if latest kitty doesn't work nicely with screen.

**Comment by cyd01** [comment]
Yes it works. 
Please send me a [memory dump](https://www.9bis.net/kitty/#!pages/Savedump.md), I would like to check some thing.

**Comment by lars18th** [comment]
Hi @cyd01 ,

This is an ancient issue without response. So please close it.

Regards.

**Comment by cyd01** [comment]
Root cause was related to the background image broken patch (see 0.71 issues).
