### ISSUE TITLE
where are the sources?

### ISSUE THREAD

**Issue by Spongman** [cyd01/KiTTY#69]
where are the sources to all the `.a` libs? many of these have licenses that are not being followed. for example, base64 reference to a missing file 'license.fr', libjpeg is missing its README file, libregex is GPL, who knows what mini.a is, could be a keylogger for all i know...

**Comment by cyd01** [comment]
I've added almost all my source files for .a libraries (including mini my .ini file manager).
bcrypt.c is still missing and will be added soon.
I've added the README file for libregex and libjpeg.

**Comment by lars18th** [comment]
Hi @cyd01 ,

This issue can be closed now?

**Comment by cyd01** [comment]
Yes I think everything is in now.

**Comment by lars18th** [comment]
> Yes I think everything is in now.

Then, please close it! (you @cyd can close _any_ issue). :wink:
