### ISSUE TITLE
kitty-0.71RC7.exe standard: No prompt to "cache the server's host key"

### ISSUE THREAD

**Issue by m-hume** [cyd01/KiTTY#7]
Connecting to a new server does not prompt to "cache the server's host key"
It just connects

**Comment by m-hume** [comment]
kitty-0.71RC5.exe exhibits the same problem

**Comment by m-hume** [comment]
On further testing it looks like existing host keys (in the registry) are not checked on negotiation with the server.
To quote the expected dialogue (from kitty0.70) "WARNING - POTENTIAL SECURITY BREACH!"
Thanks for the hard work but back to 0.70 till this is fixed

**Comment by cyd01** [comment]
Can you be more precise ?
I got the Warning message with a wrong key:
![image](https://user-images.githubusercontent.com/34154246/58049357-f0407d80-7b4c-11e9-84ee-cca066e460b5.png)

**Comment by cyd01** [comment]
Just a question: Do you use classic or portable mode ?

**Comment by cyd01** [comment]
Ok found something on classic mode. I work on it.

**Comment by m-hume** [comment]
Good Man!

**Comment by m-hume** [comment]
Nicely done @cyd01 
kitty-0.71RC8.exe now checks existing server signatures (in the registry) and notifies the user if not existing or has changed
**tout bon**!
