### ISSUE TITLE
Auto-Reconnect not working properly when using a proxy

### ISSUE THREAD

**Issue by csarn** [cyd01/KiTTY#71]
I'm connecting to a server through a proxy, and I'm also forced to use a VPN. When  I wake up my machine, there is no network connection possible until I connect to the VPN (not sure if that is relevant).
I would expect KiTTY to try to reconnect my session until it succeeds, but instead there is a popup dialog informing me that KiTTY is unable to reach the proxy (DNS resolution of proxy only becomes possible when VPN is up). Then the reconnect only happens when I click "ok" on that dialog. Avoiding such manual steps is the reason I switched from PuTTY to KiTTY.

I'm using KiTTY 0.73.0.1p.

**Comment by usefulz** [comment]
It sounds like your VPN is providing a custom DNS server that makes your server accessible by name only through the VPN.  If that's not correct, please post the log when this happens.  Feel free to redact any specific public IPs or usernames.

**Comment by csarn** [comment]
> It sounds like your VPN is providing a custom DNS server that makes your server accessible by name only through the VPN

That is correct. Could KiTTY be changed to retry name resolution on resolution failures instead of creating a popup dialog?

**Comment by lars18th** [comment]
Hi @cyd01 ,

I feel this issue #71 are related to #51 and #32. Perhaps a simple _new_ option to ENFORCE_RECONNECT every time after a time lapse will be sufficient, if the new connection will restart from scratch: that's doing the DNS name resolution, connection to the proxy, opening new sockets, etc.

You agree?

**Comment by dominch** [comment]
+1

**Comment by lars18th** [comment]
Hi to all,

To solve this issue, it will be sufficient to store the PROXY address resolution (instead of the initial address name), or it will be necessary to overcome the informing window?

Please, comment about it as this issue is quite old.
Thank you.

**Comment by dominch** [comment]
Issue was solved soon after this #, I using now 0.73.2.8 and there is no more "cannot connect" window after computer wake up from sleep. It silently waits for network and occasionally checks for connection.  I'm using Kitty for proxy tunneling and since fix I can forget about reconnecting and reopenning kitty for that, it just works!

**Comment by csarn** [comment]
I entered the IP address of the proxy instead of hostname, and since then I haven't had this problem.

**Comment by csarn** [comment]
Okay, it seems I have since gone back to proxy via hostname, with Kitty 0.73.2.18p and still have not had this problem. So I'll close it as fixed. Thanks!
