### ISSUE TITLE
[Feature Request] Support for cert store (SmartCards)

### ISSUE THREAD

**Issue by pojebunny** [cyd01/KiTTY#72]
Hi.
I've noticed that there were some issues with "putty crypt" recently and I do not know if it's related.
But I'd like to use Kitty with keys stored in TPM (or smartcards/ubikeys), which is allowed by PuttyWinCrypt.

Is that a possible/planned feature?

**Comment by lars18th** [comment]
Hi @pojebunny ,

You don't need this at all!
The process that controls the certificates is the Pageant tool. Even the KiTTY prohect has it's own pageant binary, you can use any other. Futhermore, the pageant tool doesn't uses the registry, so it's completly independent of any PuTTY fork.

From my point of view the best PAGEANT fork with Smartcard support is: https://github.com/NoMoreFood/putty-cac
Try it! I'm using it with KiTTY for years with success.

Regards.
