### ISSUE TITLE
KiTTY fails to run on Windows 2000

### ISSUE THREAD

**Issue by InterLinked1** [cyd01/KiTTY#73]
Whenever attempting to run any KiTTY executable, all the way back to 0.70.0.9, running the file throws:

The procedure entry point WTSRegisterSessionNotification could not be located in the dynamic link library wtsapi32.dll

I am able to run older versions of PuTTY without issue, so I'm wondering why this bug happens with KiTTY.

**Comment by cyd01** [comment]
I think notifications are not available in Windows 2000.
