### ISSUE TITLE
Background image feature not working

### ISSUE THREAD

**Issue by miaXcova** [cyd01/KiTTY#75]
I have been at this for half of the day and I can't seem to get that feature to work.  I have tried launching both the standalone version and regular version and tried changing the kitty.ini file settings to:
backgroundimage=yes
I tried adding this to my registry:
![image](https://user-images.githubusercontent.com/13664277/70360775-77391700-184d-11ea-949f-e2ba769977b7.png)

Here is a screenshot of my settings:
![image](https://user-images.githubusercontent.com/13664277/70360683-33461200-184d-11ea-8870-effa2107b936.png)

Thanks for the help.  I am so looking forward to replacing putty with this.  I can't believe I haven't stumbled across this program before.

edit:  I was sent here by @SolitudeSF from the thread [here](https://github.com/kovidgoyal/kitty/issues/163#issuecomment-562718885).

**Comment by cyd01** [comment]
This "great" feature is broken from 0.71 PuTTY version: [http://www.9bis.net/kitty/#!pages/0.71.md](http://www.9bis.net/kitty/#!pages/0.71.md)
