### ISSUE TITLE
Feature request: save only non-default session settings in portable mode

### ISSUE THREAD

**Issue by bersbersbers** [cyd01/KiTTY#76]
I like the portable mode (`savemode=dir`). And I like to think of the files in the `Sessions` subfolder as entries to an ssh_config file, which I like to edit manually (I have many sessions). However, this is complicated by KiTTY saving *all* settings in each file. I would prefer only having the non-default settings saved to each file.

**Comment by cyd01** [comment]
But default settings are not static. You can redefine the Default Settings session.

**Comment by bersbersbers** [comment]
@cyd01 correct. I would probably want parameter changes in the "Default Settings" to be inherited by all the other sessions, (unless they have changed the value of the same parameters themselves, obviously).

Or am I missing your point? Maybe this clarifies it a bit:
I would prefer only having the non-default settings (**as compared to the Default Settings at the time of saving**) saved to each file.

**Comment by lars18th** [comment]
I think similar to @bersbersbers .
From my point of view saving _all_ values in the configuration of each Session is not the best option. This is for example, the cause of troubles with the path of the `rz.exe` tool when using the ZModem option. I prefer to stablish a pyramid structure where a session derivates from an upper configuration; and in this case, from the Default Settings.

I hope you want to consider this.
Regards.

**Comment by cyd01** [comment]
But what happen if you decide to change some Default Settings after saving you other session ? 
It won't be efficient if KiTTY have to rescan all sessions files to test for settings that should be added, because it will be changed in Default Settings session !

**Comment by CWempe** [comment]
> But what happen if you decide to change some Default Settings after saving you other session ?
> It won't be efficient if KiTTY have to rescan all sessions files to test for settings that should be added, because it will be changed in Default Settings session !

Why would Kitty need to rescan all sessions?

If I open a session where some options are missing (becaus they should be inherited from `Default Settings`) Kitty would just need to scan `Default Settings` to look for the missing options.

If I change something in `Default Settings` and open the other Session Kitty still just needs to look for the (now updated) values in `Default Settings`.

I think the most difficult part would be to implement this "inherit from Default Session" behavior in the GUI.
How do you tell the GUI to explicitly store value `XY` (override default) for a session, even if `XY` is the current default value.
You would need a checkbox like `use default` for each option to tell the GUI not to store this option in the session file.

Personally, I do not need support in the GUI for this feature.


But what does Kitty actually do when there are options in the session file missing?
Does it use hard coded default values? Or does it look in `Default Settings`?
Maybe this feature is already implemented. 😆

**Comment by bersbersbers** [comment]
Well, if you change some default setting, then it shall apply to all _future_ sessions anyway. It might be a little unintuitive for some if it also applied to _past_ sessions, I agree, but it would in fact be what I would like to happen. So in my use case, you would not even need to traverse all existing sessions.

Also, I expect conflicts like this to occur rarely. How many people ever save the default settings? And if so, how many of these would *not* want their settings to be applied retrospectively? (And remember, this would only be for settings that had the current sefault value at the time of saving: settings that had a non-default setting at that point in time would already be saved with that value.)

**Comment by bersbersbers** [comment]
> > But what happen if you decide to change some Default Settings after saving you other session ?
> > It won't be efficient if KiTTY have to rescan all sessions files to test for settings that should be added, because it will be changed in Default Settings session !
> 
> Why would Kitty need to rescan all sessions?

I believe Cyd considers, when you change Setting1 from PreviousValueA to NewValueB in the Default Settings, going through all saved sessions, checking if they contain Setting1, and if not, adding Setting1=PreviousValueA so that the saved sessions continue to behave as they did at the time of saving. That might explain his rescanning need. (As explained, it's not what I'd want to happen - the point of, e.g., #102 is exactly to be able to modify saved sessions without explicitly touching them.

**Comment by CWempe** [comment]
> I believe Cyd considers, when you change Setting1 from PreviousValueA to NewValueB in the Default Settings, going through all saved sessions, checking if they contain Setting1, and if not, adding Setting1=PreviousValueA so that the saved sessions continue to behave as they did at the time of saving. That might explain his rescanning need.

But isn't this scenario already possible?

Lets say Putty (or Kitty) adds a new feature.

![image](https://user-images.githubusercontent.com/1270359/86888590-b3da3300-c0fa-11ea-9207-b972180b3747.png)

Would this break all existing session files, because the option is not defined in them? 😕

**Comment by bersbersbers** [comment]
> Would this break all existing session files, because the option is not defined in them? 😕

No - no one is saying that.

This is not about anything "breaking". What Cyd is concerned about is this scenario:

- Default Session: Setting1 == PreviousValueA
- Save a New Session with Settings1 == PreviousValueA as SessionX.
- What we are asking for: do not include Settings1 in SessionX.
- Now: Default Session: Setting1 <-- NewValueB
- User opens SessionX
- Current behavior, and what the user might expect: SessionX.Setting1 == PreviousValueA (explicitly)
- What we are asking for will result in: SessionX.Setting1 == NewValueB (inherited)

According to my understanding, Cyd is thinking about explicitly setting SessionX.Setting1 <-- PreviousValueA when when you change Default.Setting1 and SessionX.Setting1 does not exist, to match (potential) user expectations that a saved session will never change behavior.

**Comment by CWempe** [comment]
Ok. Now I understand the issue Cyd is concerned about.

I agree it is not efficient to rescan and modify all sessions after the `Default Session` is updated.

So the tell the session to use a default value for one option I see two ways.

* delete the option in the session file/registry you want to fall back to default
* define something like `SessionX.Setting1 == #default#` as the value

**Comment by lars18th** [comment]
Hi @CWempe ,

I think the main question is everyone's point of view:

- @cyd01 thinks that _all_ configuration requires to be inside the session descriptor.
- Others (and I include myself) think that the _default configuration_ is a _parent_ of the session configuration.

So the question is to define which mode is preferable: the "self contained" mode or the "parent" mode (aka linked mode).

I hope this helps.
Regards.

**Comment by CWempe** [comment]
> * Others (and I include myself) think that the _default configuration_ is a _parent_ of the session configuration.

That's my point of view, too.

**Comment by MrM40** [comment]
If an option doesn't exit in the session-file, which value is used? Is it taken from registry or hard-coded? 
If `savemode=dir` then the value should be taken from the Default Settings file **instead** of registry/hard-coded.
Anything else should just be the same as it is today. Don't bring in discussions about what should happen with existing session etc.,  just keep the current logic, don't over complicate this improvement ;-)

**Comment by lars18th** [comment]
Hi @MrM40 .

I don't think that discussing about _linked mode_ versus _self contained_ configurations is not relevant. The root cause of this issue and others is based on this assumption: the default configuration is only used when generating a new configuration. And from my point of view this is not the best option. I prefer to save in the configuration only _some values_ and take the rest from the _current_ default configuration.

I hope this helps to improve this amazing PuTTY fork!
Regards.

**Comment by MrM40** [comment]
But According to my test, when option **A** is missing in a entry-file, the default hard-coded value of **A** is used :-(
What we want (as I see it) is the value of option **A** should instead be taken from the "Default Settings" session file (or as a 2nd priority, from the "Default Setting" in registry).
This is what I read you also write (and what I meant to write in my first post, but assumable is can be misunderstood).

**Comment by bersbersbers** [comment]
I agree that the two are you are saying the exact same things, essentially :)

**Comment by CWempe** [comment]
Maybe the issue is the naming of the file.

If `default settings` would be called something like "settings template" it would be clear these are not the "default settings".

I know the original putty named the file this way I do not think we should rename it.
But this might be the cause of the confusion.

Maybe the solution to this issue should be named like "fallback settings" to make think more clear.

**Comment by MrM40** [comment]
Why are you complicating things? It is very simple and there are no confusion.
You have a session file e.g. ´server1.ktx`. It only contain 1 property; `HostName\server01domain.com\`.
To day kitty will set the value of all the other 331 properties from the value specified in the hard-code.
Instead it should take the 331 properties from the session file `Default%20Settings.ktx`.
There are no reason to rename the default session file, make a new session file  file or anything else.
If `server1.ktx` contain all 332 properties, fine, then all those will be used and none will be picked from `Default%20Settings.ktx`.

**Comment by MrM40** [comment]
Created a script to solve this "little" issue.
All sessions will share a common session-file with common properties.
You call `StartKittySession.exe [hostname]` e.g. `StartKittySession.exe srv01.local`
The specific-session-file, e.g. `srv01.local.txt` will only include the few session-specific properties like `UserName`, `Password` and `PublicKeyFile`. The `HostName` will automatically be parsed from the argument.
This script automatically create a temporary sessionfile `%temp%\KittySession.ktx` which kitty will use. (this file is automatically deleted when the session has started, in case you cannot find it).
`StartKittySession.exe` come together with an ini file where you specify path to the kitty.exe etc.
More info and source here: https://github.com/MrM40/OpenKittySession
Feel free to add more session-specific properties to the project, I just added the ones  I use myself.
I create shortcuts to all my `StartKittySession.exe [hostname]` in `shell:programs` :-)

**Comment by cyd01** [comment]
Issue closed due to inactivity

**Comment by lars18th** [comment]
Hi @cyd01 ,

From my point of view, the PORTABLE mode requires to improve the session settings storage. If you want to discuss it, then please open a new issue to comment about it. If not, then don't worry, and please continue supporting this amazing PuTTY fork. ❤️ 

Regards.
