### ISSUE TITLE
KiTTY should not say it's PuTTY

### ISSUE THREAD

**Issue by bersbersbers** [cyd01/KiTTY#77]
It can be quite confusing when switching from PuTTY to KiTTY when some components of KiTTY still say they're PuTTY. For example, `kageant.exe` still says "Pageant (PuTTY authentication agent)" in the tray icon hover text, probably through here:

https://github.com/cyd01/KiTTY/blob/6561c7de35dcc4f5e2a206941c88ee2c6f0f46ab/0.73_My_PuTTY/windows/winpgnt.c#L754-L760

**Comment by cyd01** [comment]
Ok
I'll change it in next release
