### ISSUE TITLE
Kitty Portable 0.73.1.2 crashes when loading existing config

### ISSUE THREAD

**Issue by salamihawk** [cyd01/KiTTY#78]
Hello,

I can start kitty_portable.exe and even connect to hosts manually by typing in the information and clicking "Open," but if I try to access any one of the 200+ hosts I have configured (in the sessions folder), Kitty will crash without any error message. Even when I try to load one of the configurations to look at it Kitty will pause for a second and crash.

My configurations are simple: a mix of IP address or Hostnames, mostly SSH port 22, but some outliers, all connections are logged to a compressed folder on my desktop, connections are sorted into folders.

The previous version I was using works just fine, 0.70.0.6p from 03/10/2018

**Comment by cyd01** [comment]
Please send me the content of a session that crash

**Comment by salamihawk** [comment]
Hi cyd, sorry for the late reply. Here's a saved session file that crashes:

Present\1\
HostName\10.250.250.10\
LogFileName\PuTTY-&H.log\
LogType\1\
LogFileClash\0\
LogFlush\1\
LogHeader\1\
SSHLogOmitPasswords\1\
SSHLogOmitData\0\
Protocol\ssh\
PortNumber\22\
CloseOnExit\1\
WarnOnClose\1\
PingInterval\0\
PingIntervalSecs\0\
TCPNoDelay\1\
TCPKeepalives\0\
TerminalType\xterm\
TerminalSpeed\38400,38400\
TerminalModes\CS7=A,CS8=A,DISCARD=A,DSUSP=A,ECHO=A,ECHOCTL=A,ECHOE=A,ECHOK=A,ECHOKE=A,ECHONL=A,EOF=A,EOL=A,EOL2=A,ERASE=A,FLUSH=A,ICANON=A,ICRNL=A,IEXTEN=A,IGNCR=A,IGNPAR=A,IMAXBEL=A,INLCR=A,INPCK=A,INTR=A,ISIG=A,ISTRIP=A,IUCLC=A,IUTF8=A,IXANY=A,IXOFF=A,IXON=A,KILL=A,LNEXT=A,NOFLSH=A,OCRNL=A,OLCUC=A,ONLCR=A,ONLRET=A,ONOCR=A,OPOST=A,PARENB=A,PARMRK=A,PARODD=A,PENDIN=A,QUIT=A,REPRINT=A,START=A,STATUS=A,STOP=A,SUSP=A,SWTCH=A,TOSTOP=A,WERASE=A,XCASE=A\
AddressFamily\0\
ProxyExcludeList\\
ProxyDNS\1\
ProxyLocalhost\0\
ProxyMethod\0\
ProxyHost\proxy\
ProxyPort\80\
ProxyUsername\\
ProxyPassword\\
ProxyTelnetCommand\connect%20%25host%20%25port%5Cn\
ProxyLogToTerm\1\
Environment\\
UserName\username\
UserNameFromEnvironment\0\
LocalUserName\\
NoPTY\0\
Compression\0\
TryAgent\1\
AgentFwd\0\
GssapiFwd\0\
ChangeUsername\0\
Cipher\aes,chacha20,blowfish,3des,WARN,arcfour,des\
KEX\ecdh,dh-gex-sha1,dh-group14-sha1,rsa,WARN,dh-group1-sha1\
HostKey\ed25519,ecdsa,rsa,dsa,WARN\
RekeyTime\60\
GssapiRekey\2\
RekeyBytes\1G\
SshNoAuth\0\
SshBanner\1\
AuthTIS\0\
AuthKI\1\
AuthGSSAPI\1\
AuthGSSAPIKEX\1\
GSSLibs\gssapi32,sspi,custom\
GSSCustom\\
SshNoShell\0\
SshProt\3\
LogHost\\
SSH2DES\0\
PublicKeyFile\\
RemoteCommand\\
RFCEnviron\0\
PassiveTelnet\0\
BackspaceIsDelete\1\
EnterSendsCrLf\0\
RXVTHomeEnd\0\
LinuxFunctionKeys\0\
NoApplicationKeys\0\
NoApplicationCursors\0\
NoMouseReporting\0\
NoRemoteResize\0\
NoAltScreen\0\
NoRemoteWinTitle\0\
NoRemoteClearScroll\0\
RemoteQTitleAction\1\
NoDBackspace\0\
NoRemoteCharset\0\
ApplicationCursorKeys\0\
ApplicationKeypad\0\
NetHackKeypad\0\
AltF4\1\
AltSpace\0\
AltOnly\0\
ComposeKey\0\
CtrlAltKeys\1\
TelnetKey\0\
TelnetRet\1\
LocalEcho\2\
LocalEdit\2\
Answerback\KiTTY\
AlwaysOnTop\0\
FullScreenOnAltEnter\0\
HideMousePtr\0\
SunkenEdge\0\
WindowBorder\1\
CurType\0\
BlinkCur\0\
Beep\1\
BeepInd\0\
BellWaveFile\\
BellOverload\1\
BellOverloadN\5\
BellOverloadT\2000\
BellOverloadS\5000\
ScrollbackLines\10000\
DECOriginMode\0\
AutoWrapMode\1\
LFImpliesCR\0\
CRImpliesLF\0\
DisableArabicShaping\0\
DisableBidi\0\
WinNameAlways\1\
WinTitle\\
TermWidth\80\
TermHeight\24\
Font\Consolas\
FontIsBold\0\
FontCharSet\0\
FontHeight\12\
FontQuality\3\
FontVTMode\4\
UseSystemColours\0\
TryPalette\0\
ANSIColour\1\
Xterm256Colour\1\
TrueColour\1\
BoldAsColour\1\
WindowClosable\1\
WindowMinimizable\1\
WindowMaximizable\1\
WindowHasSysMenu\1\
DisableBottomButtons\1\
BoldAsColourTest\1\
UnderlinedAsColour\0\
SelectedAsColour\0\
Colour0\187,187,187\
Colour1\255,255,255\
Colour2\0,0,0\
Colour3\85,85,85\
Colour4\0,0,0\
Colour5\0,255,0\
Colour6\0,0,0\
Colour7\85,85,85\
Colour8\187,0,0\
Colour9\255,85,85\
Colour10\0,187,0\
Colour11\85,255,85\
Colour12\187,187,0\
Colour13\255,255,85\
Colour14\0,0,187\
Colour15\85,85,255\
Colour16\187,0,187\
Colour17\255,85,255\
Colour18\0,187,187\
Colour19\85,255,255\
Colour20\187,187,187\
Colour21\255,255,255\
Colour22\187,187,187\
Colour23\0,0,0\
Colour24\0,0,0\
Colour25\187,0,0\
Colour26\0,187,0\
Colour27\187,187,0\
Colour28\0,0,187\
Colour29\187,0,187\
Colour30\0,187,187\
Colour31\187,187,187\
Colour32\0,0,0\
Colour33\187,187,187\
RawCNP\0\
UTF8linedraw\0\
PasteRTF\0\
MouseIsXterm\0\
RectSelect\0\
PasteControls\0\
MouseOverride\1\
Wordness0\0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\
Wordness32\0,1,2,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1\
Wordness64\1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,2\
Wordness96\1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1\
Wordness128\1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\
Wordness160\1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\
Wordness192\2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2\
Wordness224\2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2\
MouseAutocopy\1\
MousePaste\explicit\
CtrlShiftIns\explicit\
CtrlShiftCV\none\
LineCodePage\\
CJKAmbigWide\0\
UTF8Override\1\
Printer\\
CapsLockCyr\0\
ScrollBar\1\
ScrollBarFullScreen\0\
ScrollOnKey\0\
ScrollOnDisp\1\
EraseToScrollback\1\
LockSize\0\
BCE\1\
BlinkText\0\
X11Forward\0\
X11Display\\
X11AuthType\1\
X11AuthFile\\
LocalPortAcceptAll\0\
RemotePortAcceptAll\0\
PortForwardings\\
BugIgnore1\0\
BugPlainPW1\0\
BugRSA1\0\
BugIgnore2\0\
BugHMAC2\0\
BugDeriveKey2\0\
BugRSAPad2\0\
BugPKSessID2\0\
BugRekey2\0\
BugMaxPkt2\0\
BugOldGex2\0\
BugWinadj\0\
BugChanReq\0\
StampUtmp\1\
LoginShell\1\
ScrollbarOnLeft\0\
BoldFont\\
BoldFontIsBold\0\
BoldFontCharSet\0\
BoldFontHeight\0\
WideFont\\
WideFontIsBold\0\
WideFontCharSet\0\
WideFontHeight\0\
WideBoldFont\\
WideBoldFontIsBold\0\
WideBoldFontCharSet\0\
WideBoldFontHeight\0\
ShadowBold\0\
ShadowBoldOffset\1\
SerialLine\COM1\
SerialSpeed\9600\
SerialDataBits\8\
SerialStopHalfbits\2\
SerialParity\0\
SerialFlowControl\1\
WindowClass\\
ConnectionSharing\0\
ConnectionSharingUpstream\1\
ConnectionSharingDownstream\1\
SSHManualHostKeys\\
ScriptFileName\\
ScriptMode\0\
ScriptLineDelay\0\
ScriptCharDelay\0\
ScriptCondLine\%3A\
ScriptCondUse\0\
ScriptCRLF\1\
ScriptEnable\0\
ScriptExcept\0\
ScriptTimeout\30\
ScriptWait\\
ScriptHalt\\
WakeupReconnect\0\
FailureReconnect\0\
HyperlinkUnderline\0\
HyperlinkUseCtrlClick\1\
HyperlinkBrowserUseDefault\1\
HyperlinkBrowser\\
HyperlinkRegularExpressionUseDefault\1\
HyperlinkRegularExpression\%20(((((https%3F%7Cftp%7Csvn)%3A%5C%2F%5C%2F)%7Cwww%5C.)(([0-9]+%5C.[0-9]+%5C.[0-9]+%5C.[0-9]+)%7Clocalhost%7C([a-zA-Z0-9%5C-]+%5C.)%2A[a-zA-Z0-9%5C-]+%5C.(com%7Cnet%7Corg%7Cinfo%7Cbiz%7Cint%7Cgov%7Cname%7Cedu%7C[a-zA-Z][a-zA-Z]))(%3A[0-9]+)%3F((%5C%2F%7C%5C%3F)[^%20%22]%2A[^%20,;%5C.%3A%22%3E)])%3F)%7C(mailto%3A%5C%2F%5C%2F[a-zA-Z0-9%5C-_%5C.]+@[a-zA-Z0-9%5C-_%5C.]+%5C.[a-z]{2,}))\
TransparencyValue\0\
SendToTray\0\
Maximize\0\
Fullscreen\0\
SaveOnExit\0\
Icone\1\
IconeFile\\
SFTPConnect\\
Scriptfile\\
ScriptfileContent\\
AntiIdle\\
LogTimestamp\\
Autocommand\\
AutocommandOut\\
Folder\Default\
LogTimeRotation\0\
TermXPos\-1\
TermYPos\-1\
WindowState\0\
SaveWindowPos\0\
ForegroundOnBell\0\
Password\106vb\
CtrlTabSwitch\0\
Comment\\
SCPAutoPwd\0\
PortKnocking\\
DisableAltGr\0\

**Comment by cyd01** [comment]
I've found the mistake with your config file.
Each line must have at list 2 '**\\**' characters:

* between name and value property
* at the very end of the line

Ex:
```Present\1\
HostName\10.250.250.10\
LogFileName\PuTTY-&H.log\
LogType\1\
...
Comment\\
SCPAutoPwd\0\
PortKnocking\\
DisableAltGr\0\
```

I can'y explain, but there was only one well-formatted setting: the last one **DisableAltGr**.
You must add all the missing '\\'.

**Comment by salamihawk** [comment]
Hi Cyd,

I don't know why, but this appears to be a copy/paste error. I double checked the file and it _does_ have two \ per line.

I have two separate Kitty portable executables in the same directory working with the same config files and the latest one doesn't work.

**Comment by cyd01** [comment]
I don't known what is wrong with your installation, but your setting file
(with the \ at every end of each line) works fine with the last build.
Try it: https://www.9bis.net/kitty/files/kitty-debug.exe


Le mar. 17 déc. 2019 à 06:54, salamihawk <notifications@github.com> a
écrit :

**Comment by salamihawk** [comment]
That'S very strange that it works for you. I've tried several different things just now:

1) I've reduced the amount of config files to just a handful in the root \Sessions\ directory
2) I've downloaded the kitty-debug.exe
3) I've deleted every other file/directory other than the executable and the \Sessions\ directory
4) I've deleted the SimonTatham registry entry from my existing PuTTY installation
5) I've downloaded kitty-debug.exe and copied my \Sessions\ directory to my private notebook (currently on my work machine, managed by my company)

None of this changed the behavior. I can start the .exe, click on a configuration and click "load" (or double-click the configuration) and it unceremoniously crashes on both machines.

I can still use the old version of kitty_portable.exe just fine

**Comment by cyd01** [comment]
You are right, it is strange.
And there is something stranger. If your config box appears, it means you
are able to load the Default config session file. Is it possible for you to
load the default settings file, then enter a Hostname, then start a session.
If no crash, can you send me the memory dump:
http://www.9bis.net/kitty/#!pages/Savedump.md

Le mar. 17 déc. 2019 à 12:04, salamihawk <notifications@github.com> a
écrit :

**Comment by salamihawk** [comment]
Hi Cyd,

I've uploaded a memory dump to wetransfer:
https://we.tl/t-FwWSAhgwpz

Yes, loading the default config works just fine. It's worth noting, I suppose, that these config files were generated using a python script that I wrote in order to migrate my configuration from SuperPuTTy to KiTTy Portable format. I specifically set up the defaults the way I wanted them and then used that default configuration as a template to replace hostname/login/protocol/port with the necessary info. 

Is there maybe something silly like a control symbol, EOF, \r\n or something to that effect that the new versions of KiTTy don't like?

I will try to open a config file and save it again using notepad++ to see if it's some sort of formatting issue.

**Comment by cyd01** [comment]
I've got it. thanks. I'll check it.
Maybe it a issue with the syntax. Effectively I've seen your files lines
end with CRLF. Usually it is LF only. But I don't think it is the problem.
I'll check it.


Le mar. 17 déc. 2019 à 18:41, salamihawk <notifications@github.com> a
écrit :

**Comment by cyd01** [comment]
That's it.
CRLF at the end make the application craches !
I'm sorry for that. I went your send me your previous file I've
copied/pasted it from the mail to my file ... with LF only. That's why I
did not see anything strange.
I'll try fix it tomorrow morning and make a special build for you.

Cyd

Le mar. 17 déc. 2019 à 23:29, Cyril DUPONT <cyrildupont71@gmail.com> a
écrit :

**Comment by cyd01** [comment]
Ok I've made some modifications.
I think KiTTY is now able to read LF *and* CRLF files.
But it continues to write LF files only.
You can check this beta build:
https://www.9bis.net/kitty/files/kitty-debug.exe
I'm doing some more tests, and I will release this new version soon.



Le mar. 17 déc. 2019 à 23:47, Cyril DUPONT <cyrildupont71@gmail.com> a
écrit :

**Comment by salamihawk** [comment]
Awesome, thanks! I just tried it and it seems to work just fine :)
