### ISSUE TITLE
klink does not work with a server where plink does: Cannot assign requested address

### ISSUE THREAD

**Issue by bersbersbers** [cyd01/KiTTY#80]
I have a server where PuTTY works, KiTTY works, plink works, but klink does not: I get

Unable to open connection:
Network error: Cannot assign requested address

I have tried both 0.73.1.2 and 0.70.0.9, same thing.

```
C:\Tools\KiTTY>klink -v server.fqdn.com
Connecting to ip.ip.ip.ip port 0
Failed to connect to ip.ip.ip.ip: Network error: Cannot assign requested address
Unable to open connection:
Network error: Cannot assign requested address
C:\Tools\KiTTY>plink -v server.fqdn.com
Looking up host "server.fqdn.com" for SSH connection
Connecting to ip.ip.ip.ip port 22
We claim version: SSH-2.0-PuTTY_Release_0.73
Remote version: SSH-2.0-OpenSSH_7.9
Using SSH protocol version 2
No GSSAPI security context available
Doing ECDH key exchange with curve Curve25519 and hash SHA-256 (unaccelerated)
Server also has ecdsa-sha2-nistp256/ssh-rsa host keys, but we don't know any of them
Host key fingerprint is:
ssh-ed25519 255 xxx
Initialised AES-256 SDCTR (AES-NI accelerated) outbound encryption
Initialised HMAC-SHA-256 (unaccelerated) outbound MAC algorithm
Initialised AES-256 SDCTR (AES-NI accelerated) inbound encryption
Initialised HMAC-SHA-256 (unaccelerated) inbound MAC algorithm
Pageant is running. Requesting keys.
Pageant has 2 SSH-2 keys
login as: ^C
```

**Comment by bersbersbers** [comment]
This seems to be related to the presence of kitty.ini, specifically, savemode. If I remove kitty.ini, klink does work. If I remove `savemode=dir`, it does work, and if rename the `Sessions` folder, it works, too. Investigating.

**Comment by cyd01** [comment]
I did not reproduce the issue.
That's true I hardly never use portable mode ... so that I don't do many tests.
But I've tried to reproduce it with no success.
With my server the connection is ok:
```
$ klink.exe -v my.server.com
Looking up host "my.server.com" for SSH connection
Connecting to A.B.C.D port 22
We claim version: SSH-2.0-PuTTY_KiTTY
Remote version: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.8
Using SSH protocol version 2
No GSSAPI security context available
Doing ECDH key exchange with curve Curve25519 and hash SHA-256 (unaccelerated)
Server also has ecdsa-sha2-nistp256/ssh-rsa host keys, but we don't know any of them
Host key fingerprint is:
ssh-ed25519 255 xxxxxx
Initialised AES-256 SDCTR (AES-NI accelerated) outbound encryption
Initialised HMAC-SHA-256 (unaccelerated) outbound MAC algorithm
Will enable zlib (RFC1950) compression after user authentication
Initialised AES-256 SDCTR (AES-NI accelerated) inbound encryption
Initialised HMAC-SHA-256 (unaccelerated) inbound MAC algorithm
Will enable zlib (RFC1950) decompression after user authentication
login as:
```

Can you test the very last [official build](https://www.fosshub.com/KiTTY.html?dwl=kitty-0.73.1.4.exe).
There were important fixes in session loading.

**Comment by bersbersbers** [comment]
I updated to 0.73.1.4, and same thing. It even got worse: now, it does not work even when deleting `Sessions` and `kitty.ini`:

```
plink: Release 0.73
Build platform: 64-bit x86 Windows
Compiler: clang 7.0.0 (tags/RELEASE_700/final), emulating Visual Studio 2013 (12.0), _MSC_VER=1800
Source commit: 745ed3ad3beaf52fc623827e770b3a068b238dd5
```

I get this now:

```
C:\>klink -v -v -v fqdn
Looking up host "fqdn" for SSH connection
Connecting to 10.0.0.3 port 22
We claim version: SSH-2.0-PuTTY_KiTTY
Failed to connect to 10.0.0.3: Network error: Connection refused
Network error: Connection refused
FATAL ERROR: Network error: Connection refused

C:\>plink -v -v -v fqdn
Looking up host "fqdn" for SSH connection
Connecting to 10.0.0.3 port 35722
We claim version: SSH-2.0-PuTTY_Release_0.73
Remote version: SSH-2.0-OpenSSH_7.4
Using SSH protocol version 2
[...]
Sending Pageant's response
Access granted
Access granted. Press Return to begin session.
```

Now, interestingly, the same thing happens when I connect by IP using `plink` (I still don't know why):
```
C:\>plink -v -v -v 10.0.0.3
Looking up host "10.0.0.3" for SSH connection
Connecting to 10.0.0.3 port 22
We claim version: SSH-2.0-PuTTY_Release_0.73
Failed to connect to 10.0.0.3: Network error: Connection refused
Network error: Connection refused
FATAL ERROR: Network error: Connection refused
```

I wonder if this is due to dangling PuTTY sessions in the registry; will need to find out.

**Comment by bersbersbers** [comment]
```
I wonder if this is due to dangling PuTTY sessions in the registry; will need to find out.
```

This is it! My SSH server is running on a different port than `22`, and I have an old PuTTY session stored (with the name the exact fqdn and the correct port) in registry that `plink` uses, but `klink` does not. This whole situation is really complicated, but i have an idea that I'll submit as a separate issue .

**Comment by Untitled-Document-1** [comment]
I faced a similar issue with `klink.exe` today: `Cannot assign requested address`. As with you, `plink.exe` worked fine. Firstly I noticed that I had to add `-P 22 -ssh` to the klink command line to make it work. Then I looked at `Default%20Settings` as you mentioned, and changed `Protocol` from `raw` to `ssh` and `Port` from `0` to `22`. This obviates the need for `-P 22 -ssh`.

In my case there were no remnants of PuTTY registry entries lurking, though there was the expected `HKEY_CURRENT_USER\Software\9bis.com\KiTTY` registry key and subkeys/values, from before I set `savemode` to `dir` in `kitty.ini` to make KiTTY portable.

I also fell foul of another issue with the way I was calling `klink.exe`. Despite `savemode` being set to `dir` in `kitty.ini` and the relevant host key already existing on disk, `klink.exe` would still return the message `The server's host key is not cached in the registry` and prompt whether I wanted to add it. It seems obvious now, but the way I was calling klink was using the full path `"C:\Program Files (x86)\KiTTY\klink" [options] [user@]host [command]` and the current working directory not being `"C:\Program Files (x86)\KiTTY"`. If I said `Y` to the prompt to add the host key, `HKEY_CURRENT_USER\Software\9bis.com\KiTTY\SshHostKeys` would be created with a reg value for the host I initiated a connection to.

I don't know if any of this explains your issue at all...

**Comment by cyd01** [comment]
The bug about the default protocol (raw in portable mode) was fixed in
0.73.2.17.
Don't forget: to activate portable mode (
https://www.9bis.net/kitty/#!pages/Portability.md) both software en
configuration file (kitty.ini) must be in the same directory: the starting
directory.

Cyd

**Comment by Untitled-Document-1** [comment]
Before testing yesterday, I updated to KiTTY 0.73.2.18. Before that I was using KiTTy 0.73.2.10.
Also yesterday I didn't have `klink.exe` (only `plink.exe`) so I downloaded/started on the [latest version](http://www.9bis.net/kitty/files/klink.exe). 

I think I'd already done everything required to activate portable mode in KiTTY. My starting point for KiTTY was probably very different from most people's. I didn't run `kitty.exe -convert-dir`. You see, on my old Windows installation — which I had a file-based backup of — I was using PuTTY Portable from [here](http://jakub.kotrla.net/putty/), which stores session data similarly to KiTTY. So I just copied the backed up session files to `C:\Users\<username>\AppData\Local\VirtualStore\Program Files (x86)\KiTTY\Sessions` and KiTTY loaded my old sessions. I did, as you will have read, create `kitty.ini` in the same directory as `kitty.exe` (`C:\Program Files (x86)\KiTTY`) and populate it with `[KiTTY]` and `savemode=dir`.

Do you have more information on the bug about the default protocol? e.g. is there a Github issue for this? I'd like to understand how this relates to my installation, given that I'm running the latest version of KiTTY & klink. It seems like klink is correctly respecting port and protocol from `Default%20Settings`, even if perhaps these are odd defaults.

Thanks for your input!

**Comment by cyd01** [comment]
The bug was a regression between 0.70 and 0.71.
Putty 0.71 was a real big bang (https://www.9bis.net/kitty/#!pages/0.71.md),
and it was very difficult for me to port everything without bug !
Especially for this ugly portable mode I never use ;-)
Most of them were quickly fixed. But that one was reported very recently
(by mail, not with a Github issue) in 0.73. It was easy yo fix.

Cyd
