### ISSUE TITLE
KiTTY does not load kitty.ini from folder where kitty.exe is stored

### ISSUE THREAD

**Issue by bersbersbers** [cyd01/KiTTY#81]
When KiTTY is invoked, `kitty.ini` is searched in a number of folders. However, the directory where the current executable is stored is NOT among these:

https://github.com/cyd01/KiTTY/blob/71d79d4716e7f459c979097b6bdc62e68dd65212/kitty.c#L5153-L5181

So when my current directory is `C:\Windows` and invoke `C:\Tools\kitty.exe` (or just `kitty.exe`, with `C:\Tools` on the PATH), it searches `C:\Windows` and `%APPDATA%`, but not `C:\Tools`. This is highly unexpected, I find.

**Comment by bersbersbers** [comment]
Similar, when using a relative path in `kitty.ini`, e.g., 

```
configdir=.kitty
```

I would expect it to use `C:\Tools\.kitty`, and not `C:\Windows\.kitty` - that is, relative paths in `kitty.ini` file should be resolved relative to the `kitty.ini` file, not to the current directory.

**Comment by bersbersbers** [comment]
There are workarounds, for both issues, of course, `set KITTY_INI_FILE=C:\Tools\kitty.ini` and `configdir=C:\Tools\.kitty`, but I would welcome intuitive default behavior :)

**Comment by lars18th** [comment]
Hi @bersbersbers ,

Please re-check with the last version.

**Comment by bersbersbers** [comment]
@lars18th thanks, I think I can get rid of the `KITTY_INI_FILE` env var now. `configdir` still needs to use an absolute path, but I can live with that. Thanks again!
