### ISSUE TITLE
Shortcuts bug with F7 key (AKA Shortcuts/list doesn't work)

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#82]
Hi,

I'm using last version v0.73.1.2, and inside my `kitty.ini` config file I have:
```
...
[KiTTY]
shortcuts=yes
...
[Shortcuts]
list={SHIFT}{CONTROL}{F1} {SHIFT}{CONTROL}{F2} {SHIFT}{CONTROL}{F3} {SHIFT}{CONTROL}{F4} {SHIFT}{CONTROL}{F5} {SHIFT}{CONTROL}{F6} {SHIFT}{CONTROL}{F7} {SHIFT}{CONTROL}{F8} {SHIFT}{CONTROL}{F9} {SHIFT}{CONTROL}{F10} {SHIFT}{CONTROL}{ALT}{F8} {SHIFT}{CONTROL}{ALT}{F10} {SHIFT}{CONTROL}{ALT}{F11}
print=
printall=
...
```

First of all, please note that:
- I use FUNCTION keys inside the _remote_ server. So I hate that any key calls to _local_ commands.
- But I _need_ to execute some local commands with shortcuts, and for this reason I use _key combinations_. For example: `resetterminal={SHIFT}{CONTROL}{F1}`.

However, with last versions of KiTTY the `<F7>` is assigned to the PRINT local command. And that's annoying! I don't have it configured in my config file. Futhermore, every time I use a tool in a server it's impossible to use the key `<F7>`. And the solution presented in #66 is useless.

So, please can you fix this bug?

**Comment by cyd01** [comment]
Did you try to remap **Print** shortcut to another **key combination**.
Personally I use:
```
printall={CONTROL}p
```
and it works.

**Comment by lars18th** [comment]
> Did you try to remap **Print** shortcut to another **key combination**.
> Personally I use:
> 
> ```
> printall={CONTROL}p
> ```
> 
> and it works.

Thank you for the tip. Yes, it works. Now, I use `printall={SHIFT}{CONTROL}{F7}`.

However, please assume that if the config contains:
```
[KiTTY]
shortcuts=yes
...
[Shortcuts]
printall=
```

This wants to say that the `printall` shortcut is **disabled**. The current implementation instead uses the default `<F7>`, and this can be considered a bug, as the user indicates another choice (aka "disabled").

That's rigth?

**Comment by lars18th** [comment]
Fixed.
