### ISSUE TITLE
Cygwin support: update cygtermd.exe

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#83]
Hi @cyd01 ,

I recommend to compile for every release the `cygtermd.exe` tool form the original source tree. The current binary pointed at https://www.9bis.net/kitty/index.html#!pages/cygtermd.md doesn't work (the loading of the `cygwin1.dll` with the call to `_dll_crt0` fails every time with a current Cygwin install).

I readed all info in https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/cygwin-terminal-window.html and the solution doesn't work because the legacy binary.

So, please can your provide a recent binary?
Thank you!

**Comment by lars18th** [comment]
Hi,

For all people that needs a working `cygtermd.exe` you can do:

- Install Cygwin, with packages `make`, `git` and `gcc`.
- Open the Cygwin shell.
- Run that:
```
mkdir putty
cd putty
git clone https://git.tartarus.org/simon/putty.git
cd putty/contrig/cygtermd
make
cp cygtermd.exe /usr/bin/
```

After that you have a working `cygtermd.exe`.

**Comment by cyd01** [comment]
I've compiled a new version of **cygtermd** binary, and I've made a zip archive with **cygtermd.exe** and the **cygwin1.dll** that was used with.
The archive is [here](https://www.9bis.net/kitty/files/cygtermd.zip).

**Comment by lars18th** [comment]
> The archive is [here](https://www.9bis.net/kitty/files/cygtermd.zip).

Hi, this version is 64bit ready. So it doesn't work for me with Cygwin 32bit. We can't use more than one `cygwin1.dll`, so the `cygtermd.exe` binary requires to be compatible with the _native_ `cygwin1.dll` installed in your environment.

I suggest:

1. First option is to provide 32 and 64 versions.
2. Or document how to compile it inside your installed environment.

I hope it helps!

**Comment by lars18th** [comment]
Please @cyd01 , add some documentation about this info. I feel it's necessary to recompile the `cygtermd.exe` binary inside the user Cygwin environment. In fact your last binary doesn't run in my environment.

When you do it I'll close this issue.
Thank you for this impresive PuTTY fork! :+1:

**Comment by cyd01** [comment]
Hi @lars18th 
I've copied/pasted your compilation process into the [cygtermd documentation page](http://www.9bis.net/kitty/#!pages/cygtermd.md).

**Comment by lars18th** [comment]
> It is also possible to start the Windows command line utility cmd.exe:
>
> `kitty.exe -localproxy 'C:\cygwin64\bin\cygtermd.exe /cygdrive/c/Windows /cygdrive/c/Windows/System32/cmd.exe -login' localhost`

:zipper_mouth_face: I never think on this! :+1: 
Nice to have the CMD interpreter inside the KiTTY. Now only a TAB patch rest! :fearful: 

However, please update the example: you need to use the doubles quotes `"` to start it from the CMD or a Windows Script. And remember to comment to use `C:\cygwin64\` or `C:\cygwin\` based on the installed version of the Cygwin environment.

Regards.

**Comment by lars18th** [comment]
Note @cyd01 : The `-login` is not necessary, so you can remove it. :wink:
