### ISSUE TITLE
Synchronize PuTTY and KiTTY sessions

### ISSUE THREAD

**Issue by bersbersbers** [cyd01/KiTTY#85]
I really like some of the KiTTY features, including portable mode. I also find it smart that it imports PuTTY sessions if no other information can be found (and has an explicit import command for portable mode). However, there are two issues with this:
1. As a new user just opening KiTTY, you have no idea that KiTTY does not keep track, or modify, PuTTY sessions, but pulls a one-time copy and diverges from there. This led to a lot of confusion on my part.
2. As a consequence, even if you become aware of this fact at one point, you run into the issue that other tools relying on PuTTY session storage (e.g., MobaXterm) apparently have never heard of KiTTY and, while offer PuTTY sessions by default, do not do the same for KiTTY sessions. So for me, this creates a need to synchronize KiTTY and PuTTY sessions.

I see two alternative solutions:
1. Store KiTTY sessions in the PuTTY registry key (instead of in a separate KiTTY registry key). I assume that adding additional properties does not hurt PuTTY at all. In portable mode, add an option to save session into into the registry.
2. Add an option to store KiTTY session info (be they in KiTTY registry or portable) to the PuTTY registry.

**Comment by lars18th** [comment]
Hi,

I agree that the current behaviour is quire confusing.
However, I need to comment that KiTTY is not PuTTY. So the idea of _mixing_ the configuration seems to be a bad idea (almost if the user doesn't force it).

In any case, I suggest a more user-friendly approach: When first opening KiTTY, if it doesn't found any KiTTY data but PuTTY data in the registry, then open a Window informing to the user if s/he wants to import the current PuTTY config to KiTTY. Futermore including a warning about that configuration will be _different_ from the PuTTY config after the import process.

And if you agree with the above, then I suggest too to add some button in the UI of the KiTTY to "re-import" at any time the PuTTY configuration (checking for duplicates).

That's my 5¢ !

**Comment by cyd01** [comment]
Try to add these lines to your `%APPDATA%/KiTTY/kitty.ini` configuration file:

```
[PuTTY]
keys=load
```

**Comment by bersbersbers** [comment]
Interesting, this seems to be exactly solution number 2:
https://github.com/cyd01/KiTTY/blob/71d79d4716e7f459c979097b6bdc62e68dd65212/kitty.c#L1150-L1162

I'll try it out for sure, thanks!

**Comment by bersbersbers** [comment]
While this looks promising, I noticed that this copies KiTTY registry to PuTTY registry. However, I am in portable mode. In the code, I have found this section, which seems to copy KiTTY portable to KiTTY registry:
https://github.com/cyd01/KiTTY/blob/71d79d4716e7f459c979097b6bdc62e68dd65212/kitty.c#L4373-L4470

How do I call it? I have called `kitty.exe -convert1reg`, but that does not seem to create `Computer\HKEY_CURRENT_USER\Software\9bis.com` still.

**Comment by cyd01** [comment]
The right option is
`kitty.exe -convert-reg`

**Comment by bersbersbers** [comment]
Thanks, this is now working: `kitty.exe -convert-reg` converts the portable settings into registry settings (into `HKCU\Software\9bis.com\KiTTY`).

Next step was to copy the registry settings from KiTTY to PuTTY. `regln` would be one option (compare https://github.com/mRemoteNG/mRemoteNG/issues/851), and another would be manipulating `.reg` files (see https://djsilenceboy.wordpress.com/2016/01/19/how-to-convert-sessions-between-kitty-and-putty/). But I do prefer the solution
```
[PuTTY]
keys=load
```
and this one does not work yet. What I have tried:
- `kitty.exe -convert` using my regular portable `kitty.ini`
- then replace my regular `kitty.ini` by one that only has the two above lines,
- then call `kitty.exe`.

But I am not seeing any effect - `HKCU\Software\SimonTatham\PuTTY\Sessions` is not touched. What am I doing wrong? I am googling a lot, but the fact that there is no proper documentation, the forum is down and the code is commented in French does not make it easier :)

**Comment by bersbersbers** [comment]
Apparently, I need to save *any* session to force copying *all* sessions from KiTTY reg to PuTTY reg. That was a hell of a ride. Excuse me for saying that, but I was (and still are) close to abandoning KiTTY and going back to PuTTY. The documentation is so sparse and behavior so convoluted that any attempt to actually use the functionality offered by KiTTY costs me more time in trial and error than other solutions.

**Comment by bersbersbers** [comment]
My kitty2putty.bat

```
@echo off
cd /d "%~dp0"

echo Copying portable KiTTY to registry KiTTY.
kitty.exe -convert-reg
echo Done.
echo.

echo Opening registry KiTTY.
echo Please save one session manually once!

set KITTY_INI_FILE=kitty2putty.ini
kitty.exe
echo Done.
echo.

pause
```

**Comment by cyd01** [comment]
But don’t use KiTTY portable binary
It can’t deal with registry
Use classic binary then modify KiTTY.ini to switch save mode


Le dim. 5 janv. 2020 à 20:13, bersbersbers <notifications@github.com> a
écrit :

**Comment by theAkito** [comment]
So, what's the really working solution here?

I have PuTTY with registry entries. I just want to get those registry entries as a KiTTY portable configuration, without modifying any PuTTY related entries.

Do I really need to switch KiTTY into "classic" mode, then switch back, save a session, etc.... ?

**Comment by fedora800** [comment]
I use KiTTY exclusively and have been using this method to convert PuTTY *.reg files available widely on the internet into KiTTY session files.

**To convert Putty .reg files to Kitty format files**

First, fully backup my KiTTY_portable folder.
Open up notepad (not notepad++ due to BOM issues etc) and paste one of the above or any new reg file contents into say ciapre.reg and change ‘Default%20Settings’ to ‘ciapre’ and save. Open powershell as ADMINISTRATOR and run -   reg import ciapre.reg. This we will now see in 
Registry under HKEY_CURRENT_USER\SOFTWARE\SimonTatham\PuTTY\Sessions.
Now before proceeding, make sure you do the above step for all the reg files you need.

Download the classic KiTTY (non-portable version) and put into C:\myapps\KiTTY. 
Create a file there called kitty.ini and put in there below info and save  - 
[KiTTY]
savemode=dir

Now cd to C:\myapps\KiTTY and run - kitty.exe -convert-dir. This will create a number of directions and will save those required sessions from registry into Sessions folder in KiTTY format. Copy these sessions to our KiTTY_portable sessions folder.
We should now delete all the SimonTatham and under registry entries.
We should now delete the KiTTY classic folder and rename the KiTTY_portable folder to what it was.

references :
http://www.9bis.net/kitty/#!pages/Portability.md
https://djsilenceboy.wordpress.com/2016/01/19/how-to-convert-sessions-between-kitty-and-putty/
https://superuser.com/questions/410398/any-simple-way-to-add-putty-settings-to-kitty

**Comment by mauriva** [comment]
I have been using a portable version of KiTTY (the one included among the LiberKey apps) for some time, but I see that the project has not been updated for some time.
Putty, on the other hand, has recently upgraded to version 0.83 and I was thinking of trying it out.
I would also like to use Putty in a completely portable version, i.e. without the settings in the registry, but in the application folder.
It seems that the portable version of Putty released on the PortableApps site allows this (correct me if I'm wrong).
Do you have a method for passing Kitty's settings to Putty, both in portable version?

**Comment by mauriva** [comment]
I have been using a portable version of KiTTY (the one included among the LiberKey apps) for some time, but I see that the project has not been updated for some time.
Putty, on the other hand, has recently upgraded to version 0.83 and I was thinking of trying it out.
I would also like to use Putty in a completely portable version, i.e. without the settings in the registry, but in the application folder.
It seems that the portable version of Putty released on the PortableApps site allows this (correct me if I'm wrong).
Do you have a method for passing Kitty's settings to Putty, both in portable version?
