### ISSUE TITLE
[RFE] Wider config window

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#86]
Hi,

The current size of the configuration window can be improved...

![kitty-wide](https://user-images.githubusercontent.com/9989964/71265452-9011f400-2346-11ea-82d8-8c4d1fb0d938.png)

You can see that the protocols (Connection type:) now uses two rows instead of one (and list list will not change soon, as the pending Cygterm protocol will disappears). So it will be preferable to change the width size of this window. This will provide a more wider space for the names of the sessions, that it isn't resizable or horizontally scrollable. So, this will improve the usability for users (like me) that uses _large_ Session names.

And for the rest of categories, I feel this change will not produce any bad interference.

Please @cyd01 consider this _simple_ enhancement.
Thank you!

**Comment by cyd01** [comment]
I don't think it is a *simple* enhancement.
I can remember that all elements of the configuration box have a static size. Resizing the Windows will have no effect on each of them. This feature will need to rewrite completely the `config.c` file.

I you want the test the effect try to modify the Windows Height:

```
[ConfigBox]
windowheight=1600
```

**Comment by lars18th** [comment]
> I you want the test the effect try to modify the Windows Height:
> 
> ```
> [ConfigBox]
> windowheight=1600
> ```

This changes the _HEIGTH_, not the _WIDTH_, that is the parameter to make the window wider. Futhermore, I already use `[ConfigBox] height=22`.

Perhaps you want to support `[ConfigBox] width=`... You agree?

Regards.

**Comment by cyd01** [comment]
I know Iknow
The is fact I've already need the windowheight setting for another issue.
So that I've made it. But I need not the same for the width.
I've only sent it to you to show the (none) effect on the window elements.

**Comment by andreas-heidelberg** [comment]
This size limit is super annoying. Can't this be changed? Or just make it bigger initially for everyone?
