### ISSUE TITLE
Windows Shell inside KiTTY (CMD/PowerShell)

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#87]
Hi @cyd01 ,

I open this issue based on https://github.com/cyd01/KiTTY/issues/83#issuecomment-569954018

I found two troubles when running the DOS interpreter inside KiTTY which you can help to solve:

1. When using the Windows CMD the codepage requires to be `ISO-8859-1` (or similar) instead of the default `UTF-8`. Any option to select it from the command line?

2. Any option to enable the CURSOR (arrows) keys and TAB inside this shell? I don't know how to use them.

I hope you can help.
Thank you!

**Comment by lars18th** [comment]
And I don't know why the Windows PowerShell doesn't work:

```
kitty.exe -localproxy "C:\cygwin\bin\cygtermd.exe /cygdrive/c/Windows /cygdrive/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" localhost
```

Any idea?

**Comment by cyd01** [comment]
You must change the translation tab to select Win 1252 character set.
May be I can force it when using -localproxy ?

**Comment by lars18th** [comment]
> You must change the translation tab to select Win 1252 character set. May be I can force it when using -localproxy ?

No, please!
The `-localproxy` is used only to start the `cygtermd.exe`. And you can use it to run _any_ shell (bash.exe; cmd.exe; etc.). So, please don't touch it.

However, I feel it will be interesting to have a _new_ command-line parameter to configure a Windows Shell. For example `-charset <page>`. Here the page is the translation charset used. And perhaps this new option can enable/disable other options in the future related to the shell (for example, the key translation that can be required). But first we need to know how to enable/translate them.

You agree?

**Comment by lars18th** [comment]
Hi @cyd01 ,

I found a solution to run CMD inside the KiTTY without touching anything!

Use this:
- Download the WinPTY tool for your Cygwin environment (x32 or x64): https://github.com/rprichard/winpty
- Copy the binary files (`winpty.dll`, `winpty.exe`, `winpty-agent.exe` and `winpty-debugserver.exe`) to your `/usr/bin/` directory (best use your MinTTY/BASH shell to copy to the target directory).
- Then you can use `kitty.exe -localproxy "C:\cygwin\bin\cygtermd.exe C:\ /usr/bin/winpty.exe /cygdrive/c/Windows/System32/cmd.exe" localhost`

And then you can use cursor and tab keys. :wink: 
Regards.

**Comment by lars18th** [comment]
Hi @cyd01 ,

And with the WinPTY the PowerShell works too! :stuck_out_tongue_winking_eye: 

`kitty.exe -localproxy "C:\cygwin\bin\cygtermd.exe C:\ /usr/bin/winpty.exe /cygdrive/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" localhost`

**Comment by lars18th** [comment]
And the good FarManger works too! :angel:

**Comment by cyd01** [comment]
I thought of it just after pressing send :-)

**Comment by lars18th** [comment]
> I thought of it just after pressing send :-) Le mar. 31 déc. 2019 à 18:45, Lars The 

So, I recommend to update the documention. After I'll close this issue.

Regards.

**Comment by lars18th** [comment]
Hy @cyd01 ,

> So, I recommend to update the documention. After I'll close this issue.

It's the documentation updated? If yes, then I'll close this issue.
Thank you for this amazing project! :wink:

**Comment by cyd01** [comment]
I thought I've updated the doc:
http://www.9bis.net/kitty/#!pages/cygtermd.md
Do you think something is missing ?

**Comment by lars18th** [comment]
All OK @cyd01 ! :+1:
