### ISSUE TITLE
Patch to support FocusGained/FocusLost notification

### ISSUE THREAD

**Issue by systemmonkey42** [cyd01/KiTTY#89]
Are there any patches to support Focus notification events?

eg, after sending "esc[?1004h", every time the putty windows is activated or deactivated, it will send an esc[I and esc[0 to the client.

I'm prepared to work on a patch myself, but I want to know if something already exists.

Thanks

**Comment by systemmonkey42** [comment]
If I prepare a patch, should it be against the latest 'Putty' or directly against the latest 'Kitty' ?

**Comment by lars18th** [comment]
Hi @systemmonkey42 ,

I recommend to provide a PR for KiTTY. And if it works, then I feel @cyd01 will merge it.

Regards.

**Comment by systemmonkey42** [comment]
@lars18th, @cyd01 

I've created a pull request #130 with the changes needed to support focus reporting.

Please review.  Thanks

**Comment by systemmonkey42** [comment]
Tested ok in 0.73.2.7

Thanks
