### ISSUE TITLE
Poor man's syntax highlighting

### ISSUE THREAD

**Issue by kellerza** [cyd01/KiTTY#9]
Since the forum seems to be closed, I'l post this here. This is an enhancement request, and a suggestion for a workaround to get syntax highlighting. Very handy when configuring routers and could also help when looking for certain text in logs.

In current versions of Kitty, you can (mis-)use the [URL highlighting feature](https://www.9bis.net/kitty/?page=URL%20hyperlinks&zone=en) to underline words

![image](https://user-images.githubusercontent.com/6756881/57517588-7bcd3980-7317-11e9-81ee-22f3647e87ae.png)

My example pattern highlights Enabled, Up, Down and IP addresses:
```
(Enabled|Up|Down|([0-9]{1,3}\.){3}[0-9]{1,3})
```

It would be even better if you could have a list of regular expressions with colours, for example: Up->green, down->red and IP Addresses->blue.
Hopefully this will inspire someone to implement this... the URL highlighting patch is probably a good place to start :wink:

**Comment by lars18th** [comment]
Hi @cyd01 ,

I suggest to copy/move/link this in the Wiki and close this issue.

What you think?

**Comment by CWempe** [comment]
Like @kellerza wrote, this is an *enhancement request* which is not fulfilled or denied, yet.

But the workaround to highlight keywords as links could be moved to a wiki.

**Comment by CWempe** [comment]
Here is a suggestion:

Another way to implement this "Poor man's syntax highlighting" could be to have multiple RegEx-Filed with individual options.

Example:

field name | user defined Value
------------ | -------------
RegEx 1 |   (((((https?\|ftp\|svn):\/\/)\|www\.)(([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\|localhost\|([a-zA-Z0-9\-]+\.)*[a-zA-Z0-9\-]+\.(com\|net\|org\|info\|biz\|int\|gov\|name\|edu\|[a-zA-Z][a-zA-Z]))(:[0-9]+)?((\/\|\?)[^ "]*[^ ,;\.:">)])?)\|(mailto:\/\/[a-zA-Z0-9\-_\.]+@[a-zA-Z0-9\-_\.]+\.[a-z]{2,}))
font settings 1 | underlined, clickable
RegEx 2 | (up\|enabled)
font settings 2 | green, underlined
RegEx 3 | (down\|disabled)
font settings 3 | red, bold
RegEx 4 | (notconnected\|([0-9]{1,3}\.){3}[0-9]{1,3})
font settings 4 | bright cyan
RegEx 5 | (down\|disabled)
font settings 5 | white, red background

So I would think these options/font settings would make sense:

* clickable (for hyper links)
* font color (the usual 16 colors (including bright), I guess)
  <https://en.wikipedia.org/wiki/ANSI_escape_code#3/4_bit>
* background color
* font style (bold, underlined, blink??)

What I personally do not need (to reduce the effort for the developer):

* 256 colors
* color picker or checkboxes for font style
  The user can just type the name of the colors and styles (e.g. `red, bold, 

If Kitty had this feature it would make managing my switches and routers much more comfortable. 🤩 

What do others think?
Would you need more or less options?
How many RegEx fields would be best?

**Comment by lars18th** [comment]
Hi @CWempe ,

> What do others think?

I think it's an interesting idea.

**Comment by kellerza** [comment]
Indeed @CWempe my idea was multiple RegExes with individual results. Look at [this](https://blog.mobatek.net/post/mobaxterm-new-release-8.6/) screencast to see it in action.

Limited colors is not an issue, just basic ANSI colors should be ok. Even if this is only configurable in config files it will be acceptable. 

Maybe 8 regexes? Will probably have to see when this has a performance hit.

**Comment by CWempe** [comment]
@cyd01 
Any thoughts from your side?

Do you think this would be possible to implement?

> Limited colors is not an issue, just basic ANSI colors should be ok. Even if this is only configurable in config files it will be acceptable.

Maybe it would make sense to link the RegExes to the colors defined under `Window > Colours` instead of custom colors for each RegEx.

![image](https://user-images.githubusercontent.com/1270359/108834313-54b82880-75ce-11eb-823d-52f8ab1573dd.png)

This would make it compatible with [putty color schemes](https://github.com/AlexAkulov/putty-color-themes/blob/master/images/readme.md).

But I would be happy either way.

**Comment by cyd01** [comment]
Issue closed due to inactivity

**Comment by kellerza** [comment]
No worries, I've been using [labctl color](https://labctl.net/reference/color) to do the highlighting.

It works nicely with most terminals: Kitty / Windows Terminal / inside VSCode
