### ISSUE TITLE
AVG Antivirus: IDP.generic detected

### ISSUE THREAD

**Issue by PedroMSantosD** [cyd01/KiTTY#91]
Hi, I´m guess this duplicated issues:

[Bug #4](https://github.com/cyd01/KiTTY/issues/4)
which in turn forwards to:
[Malware and putty comparison](https://forums.malwarebytes.com/topic/243660-why-malware-bytes-is-treating-kittyexe-fork-of-putty-as-quarantinable/)
![avg_exception](https://user-images.githubusercontent.com/17711131/71814644-572f8a00-307d-11ea-893b-739e3cc29064.PNG)

But my AVG free antivirus moves to quarantine kitty.exe and kageant.exe from  release: kitty-bin-0.73.1.5 as soon as I run following config:
- Virtualbox with a NAT network, were ssh port is 127.0.0.1 port 10022 (on host) , default port 22 on Centos7 VM
- kageant, holds the ssh key, I start the new connection, AVG pops up and reports idp.generic virus, moving it to quarantine.

as a workaround, I add an exception to the antivirus... but this is way far from ideal
can anything be done about it?

md5 checksum for binary:

> PS C:\Users\Public\Documents\Kitty> Get-FileHash .\kageant.exe -Algorithm md5
> 
> Algorithm       Hash                                                                   Path
> ---------       ----                                                                   ----
> MD5             8451A31E43E8F7A37E467B54B96B089A                                       C:\Users\Public\Documents\Kit...
> 

zipped file checksum:

> PS C:\Users\xxx\Downloads> Get-FileHash .\kitty-bin-0.73.1.5.zip -Algorithm md5                                 
> Algorithm       Hash                                                                   Path
> ---------       ----                                                                   ----
> MD5             FFBFEAAFEA041AD7DCDA9CA6FD2B59AC

**Comment by PedroMSantosD** [comment]
maybe you can submit the whole suite to [AVG ](https://support.avg.com/SupportArticleView?l=en&urlName=AVG-Threat-Lab-file-whitelist&q=Threat+lab+file+whitelist&supportType=home)

**Comment by lars18th** [comment]
Please, close this issue, and to point to #115 .

**Comment by PedroMSantosD** [comment]
Kindly see 
#115

**Comment by RichardRobinson9** [comment]
I take a genuine key from a reseller https://licencekeep.com/ with a 60% discount [AVG Internet Security 2023 Key](https://licencekeep.com/avg-internet-security-2023-key/) license key for 1 year a very cheap price only $16. They provide Official download link, Activation process and a genuine license key.

That discount coupon code: Flash60

Instantly delivered, It Worked perfectly. I highly recommend that site
