### ISSUE TITLE
Paste issue

### ISSUE THREAD

**Issue by chrisniael** [cyd01/KiTTY#93]
When I paste some text into KiTTY, I will get this prompt:
```bash
bracketed-paste-magic:zle:47: not enough arguments for -U
```
KiTTY - 0.73.1.5
ohmyzsh
zsh 5.7.1

I have tried putty 0.73 to test this issue, it's ok.

Releated issue [https://github.com/ohmyzsh/ohmyzsh/issues/8128](https://github.com/ohmyzsh/ohmyzsh/issues/8128)

**Comment by systemmonkey42** [comment]
Paste has been broken since the beginning of the 0.73 releases

Eg. using putty 0.71.0.6;

```bash
$ printf "\e[?2004h";cat -v
<paste text here>
^[[200~PASTED TEXT^[[201~
```

Putty 0.73.1.1 and above;

```bash
$ printf "\e[?2004h";cat -v
<paste text here>
^[[200~^[[201~PASTED TEXT
```

The lack of content between the begin and end paste codes causes the issue.

Please test an earlier build and see if that helps.

**Comment by systemmonkey42** [comment]
I had a little spare time so I dug into the source.  It appears PASTE calls
"term_keyinput_internal()" with the interactive parameter set to FALSE.

The term_keyinput_internal() function calls 'term_bracketed_paste_stop()' immediately before actually processing the input data.

The patch below fixes the paste issue completely for me.

Note:  HEAD on branch master (0aaafcc)

```diff
diff --git 0.73_My_PuTTY/terminal.c 0.73_My_PuTTY/terminal.c
index 575cb06..84a773c 100644
--- 0.73_My_PuTTY/terminal.c
+++ 0.73_My_PuTTY/terminal.c
@@ -3191,7 +3191,8 @@ static inline void term_keyinput_internal(
         bufchain_add(&term->inbuf, buf, true_len);
         term_added_data(term);
     }
-    term_bracketed_paste_stop(term);
+   if (interactive)
+       term_bracketed_paste_stop(term);
     if (term->ldisc)
         ldisc_send(term->ldisc, buf, len, interactive);
     term_seen_key_event(term);
```

**Comment by systemmonkey42** [comment]
FYI - This is the source of the change in the original Putty REPO dated 5 months ago.

```sh
$ git show 2c279283c
```

```diff
2c279283 - (5 months ago) Don't call term_bracketed_paste_stop before pasted data. - Simon Tatham
diff --git terminal.c terminal.c
index 6f93c78e..60262d24 100644
--- terminal.c
+++ terminal.c
@@ -3089,7 +3089,8 @@ static inline void term_keyinput_internal(
         bufchain_add(&term->inbuf, buf, true_len);
         term_added_data(term);
     }
-    term_bracketed_paste_stop(term);
+    if (interactive)
+        term_bracketed_paste_stop(term);
     if (term->ldisc)
         ldisc_send(term->ldisc, buf, len, interactive);
     term_seen_key_event(term);

```

**Comment by samuelecarpene** [comment]
@cyd01 Is available a downloadable portable version for this fix?

**Comment by cyd01** [comment]
Cet the beta build (https://www.9bis.net/kitty/files/kitty/kitty-debug.exe)
And search in official web site to how to configure it for portable mode.
Basically you will add
[KiTTY]
savemode=dir

to your kitty.ini configuration file

Le jeu. 23 janv. 2020 à 14:37, Samuele Carpene <notifications@github.com> a
écrit :
