### ISSUE TITLE
Missing shrotcuts

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#95]
Hi @cyd01 ,

Today I noticed that is not a key shortcut for opening the New Session menu:
```
[Shortcuts]
print=
printall=
imagechange=
rollup=
tray=
command=
autocommand=
script=
editorclipboard=
resetterminal=
editor=
sendfile=
getfile=
winscp=
protect=
visible=
input=
inputm=
showportforward=
```

I think it will be very useful to have OPEN_NEW and DUPLICATE shortcuts. In fact, all current left menu entries should have one.

What you think?

**Comment by lars18th** [comment]
Hi @cyd01 ,

Thank you for the last version 0.73.2.1. Most of the bugs/issues are gone. However, please can you comment about this idea?

Thank you for your good job!

**Comment by lars18th** [comment]
Hi @cyd01 ,

Please comment about my request of enhancing the current Shortcuts with new values, like OPEN_NEW and DUPLICATE.

I feel is not a complex task. I'm right?
Thank you for this unvaluable PuTTY fork!

**Comment by cyd01** [comment]
Hi
There already is a shortcuts for duplicate session: see this page
https://www.9bis.net/kitty/#!pages/Duplicate.md
Of course I can add new shortcuts entries, and it should not be difficult.
I'll check it very soon.

Thank for helping to improve KiTTY.
Cyd

**Comment by lars18th** [comment]
> Hi There already is a shortcuts for duplicate session: see this page https://www.9bis.net/kitty/#!pages/Duplicate.md 

Nice! However, in some circunstances I prefer to use _keyboard only_ shortcuts.

> Of course I can add new shortcuts entries, and it should not be difficult. I'll check it very soon.

Ok. I hope you want to add to the list all (or nearly all) entries present in the left menu. This will improve a lot the usability. To help you, this is the list of missing shortcuts from my point of view:

- OPEN_NEW
- DUPLICATE
- CHANGE_SETTINGS
- CLEAR_SCROLLBACK
- CLOSE_RESTART
- EVENT_LOG
- FULL_SCREEN
- FONT_UP
- FONT_DOWN
- REPEAT_KEY_EXCHANGE

Regards.

**Comment by cyd01** [comment]
This shortcuts are now available:
```
duplicate=
opennew=
changesettings=
clearscrollback=
closerestart=
eventlog=
```

Get the beta build: [https://www.9bis.net/kitty/files/kitty-debug.exe](https://www.9bis.net/kitty/files/kitty-debug.exe).

> I did not make so meny tests ... I'm sorry.

**Comment by lars18th** [comment]
> Get the beta build: https://www.9bis.net/kitty/files/kitty-debug.exe.

Thank you, @cyd01 !
It works.

However, one issue: When setting one shortcut to the `{SHIFT}{CONTROL}{F2}` keys a new window with "mNotepad" is opened and the command is executed inside this window.

Example:
```
[KiTTY]
shortcuts=yes
[Shortcuts]
list={SHIFT}{CONTROL}{F2}
closerestart={SHIFT}{CONTROL}{F2}
```
Then this annoying window is opened. I checked that the problem isn't the shorcut. As if I change to annother key (F1, F3, etc.) then it works as excepted. So the problem is some "overlap" of this key combination.

So, please, can you fix it?
Regards.

Note: Any reason to not include FULL_SCREEN and REPEAT_KEY_EXCHANGE?

**Comment by cyd01** [comment]
Normal:
{SHIFT}{CONTROL}{F2} is the default for `editorclipboard` : 
```
if( !readINI(KittyIniFile,"Shortcuts","editorclipboard",buffer) || ( (shortcuts_tab.editorclipboard=DefineShortcuts(buffer))<=0 ) )
		shortcuts_tab.editorclipboard = CONTROLKEY+SHIFTKEY+VK_F2 ;
```
If you want to reuse it you must redefine `editorclipboard` shortcuts too. 
I've planed to rewrite the default kitty.ini creation. And I've planed to write all the default shortcuts in there.

Note: Any reason to not include FULL_SCREEN and REPEAT_KEY_EXCHANGE ?
--> Only time :-(

Note 2: I'm also missing the function COPY_ALL_TO_CLIPBOARD. Please, consider to add it. Thank you!
--> No problem

**Comment by lars18th** [comment]
> Normal:
> {SHIFT}{CONTROL}{F2} is the default for `editorclipboard` :
> 
> ```
> if( !readINI(KittyIniFile,"Shortcuts","editorclipboard",buffer) || ( (shortcuts_tab.editorclipboard=DefineShortcuts(buffer))<=0 ) )
> 		shortcuts_tab.editorclipboard = CONTROLKEY+SHIFTKEY+VK_F2 ;
> ```
> 
> If you want to reuse it you must redefine `editorclipboard` shortcuts too.

Please, check my _current_ config previously posted:
```
[KiTTY]
shortcuts=yes
[Shortcuts]
list={SHIFT}{CONTROL}{F2}
editorclipboard=
editor=
closerestart={SHIFT}{CONTROL}{F2}
```

So, I'm removing the editorclipboard from the list. What I'm missing?

> I've planed to rewrite the default kitty.ini creation. And I've planed to write all the default shortcuts in there.
> Note: Any reason to not include FULL_SCREEN and REPEAT_KEY_EXCHANGE ?
> --> Only time :-(
> Note 2: I'm also missing the function COPY_ALL_TO_CLIPBOARD. Please, consider to add it. Thank you!
> --> No problem

Nice! :+1:

**Comment by cyd01** [comment]
Can you try this:

[KiTTY]
shortcuts=yes
[Shortcuts]
list=
editorclipboard=
closerestart={SHIFT}{CONTROL}{F2}

**Comment by lars18th** [comment]
> Can you try this: [KiTTY] shortcuts=yes [Shortcuts] list= editorclipboard= closerestart={SHIFT}{CONTROL}{F2} 

Identical behaviour. The same window opens. :-1:

**Comment by cyd01** [comment]
Here the new shortcuts:
```
fullscreen=
fontup=
fontdown=
copyall=
```
I've finally  reproduced the "default value for shortcut" issue. It should be fixed.

**Comment by lars18th** [comment]
> Here the new shortcuts:
> 
> ```
> fullscreen=
> fontup=
> fontdown=
> copyall=
> ```
> 
> I've finally reproduced the "default value for shortcut" issue. It should be fixed.

Hi @cyd01 ,
Redownloaded the beta and... it works! Problem fixed. And new shortcuts working. Thank you!

And only to complete the list (so missing shortcuts):
- REPEAT_KEY_EXCHANGE: Useful to manual restart the connections before a CLOSE+RESET (I prefer to use the key exchange before).
- SAVED_SESSIONS: In this case the idea is to open the Left Menu in the sub-menu of "Saved sessions" and put the focus in the list. Then with a simple `<UP>`,`<DOWN>` keys will be easy to open any recent session with the `<ENTER>` key. Can you do it, please?
- SPECIAL_COMMANDS and USER_COMMANDS: Idem to the previous one. If it's possible to open the submenu, then it will be interesting to have a shortcut for it.
- SEND_WITH_PSCP: I feel it's different from `sendfile=` and `getfile=` that are related to ZMODEM, right?
- FONT_BLACK_AND_WHITE: I don't use it much, but interesting.

And with this the list is complete. I hope you can release a new version soon.
Thank you and good job! :+1:

**Comment by cyd01** [comment]
Here are the last shortcuts
```
fontnegative=
fontblackandwhite=
keyexchange=
```
SEND_WITH_PSCP already exists, it is `sendfile=`. (ZModem does not anymore).
About the 3 sub-menus, it is quite different and a little more complicated.

**Comment by lars18th** [comment]
Hi @cyd01 ,

OK. I understand the complexity of the sub-menus. Don't worry!

I hope you will publish soon the next release (I'm using the beta). :wink:

**Comment by lars18th** [comment]
Hy @cyd01 ,

I close this issue as the new version 0.73.2.3 is working like a charm.
Thank you! :+1:

**Comment by cyd01** [comment]
You welcome
