### ISSUE TITLE
kageant "Saved Sessions" opens PuTTY instead of KiTTY

### ISSUE THREAD

**Issue by bersbersbers** [cyd01/KiTTY#97]
With kageant.exe running, right-click the systray icon and select one of the "Saved Sessions". (I am not sure whether these are PuTTY or KiTTY sessions, as I am syncing the two, see #85. I believe these are PuTTY sessions, see https://github.com/cyd01/KiTTY/blob/1b0335f66a4df152b3fcf0de9bd96a5c69b26527/0.73_My_PuTTY/windows/winpgnt.c#L95 and https://github.com/cyd01/KiTTY/blob/1b0335f66a4df152b3fcf0de9bd96a5c69b26527/0.73_My_PuTTY/windows/winpgnt.c#L806-L861

Anyway, putty.exe is started while I would expect kitty.exe to be started.

**Comment by lars18th** [comment]
Hi,

I suggest to change the _colour_ of the KiTTY icon. Then it will be very easy to identify it.

I hope you agree.

**Comment by thebodzio** [comment]
I can confirm these are only PuTTY sessions. I'm using KiTTY exclusively and although I have a couple sessions defined, Kageant "Saved sessions" menu stays completely empty. Perhaps it should be submitted as a separate issue, but I'm leaving it here for now.

**Comment by rendo0m** [comment]
Confirmed! wondered why shortcuts not working in some windows.
deleted putty.exe and made a symbolic link

**Comment by cyd01** [comment]
> 
> 
> I can confirm these are only PuTTY sessions. I'm using KiTTY exclusively and although I have a couple sessions defined, Kageant "Saved sessions" menu stays completely empty. Perhaps it should be submitted as a separate issue, but I'm leaving it here for now.

Can you re-check ?  I've deleted all PuTTY entries in registry. I've started `kageant.exe` and all the **KiTTY** sessions were available as expected.

And in the code the value for `PUTTY_REGKEY ` seems coherent:  
https://github.com/cyd01/KiTTY/blob/2c7c0116dac2c49323e7baf56be23507f1124733/0.74_My_PuTTY/windows/winpgnt.c#L88-L92

**Comment by thebodzio** [comment]
Yup! That did it! Thank you very much! 👍 😃
