### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by AndiLeni** [cyd01/KiTTY#98]
Does Kitty provide macros?
I frequently type the same text in my console and it would be nice to have a shortcut to simplify this. 
Basically a feature like conemu provides with its macros.

Regards
Andi

**Comment by systemmonkey42** [comment]
I use [AutoHotKey](https://www.autohotkey.com/) for this.  While it can do menu's, I use it for

* Launch sessions from hot keys (ag, Win-J to launch ```kitty -load jenkins```
* Generate text input from hot keys.  The text can be computed, and not just static and can change based on window title (eg, session name)
* Autocorrect (detects when I misspell words and replaces them (eg, gerp is replaced with 'grep')
* Implement keys which Putty/Kitty cannot recognise (like ctrl-TAB) and generates escape sequences which console applications can understand.  (I use ctrl-tab and ctrl-shift-tab to change panes in TMUX, but kitty recognises neither of those keys directly)

Let me know if you want specific examples.

**Comment by AndiLeni** [comment]
@systemmonkey42 Thanks for your answer. I achieved what I needed :)
