### ISSUE TITLE
[RFE] Sixel support

### ISSUE THREAD

**Issue by lars18th** [cyd01/KiTTY#99]
Hi @cyd01 ,

I comment this only for reference. I'm not requesting that you fully implement this at time. It's only a future idea:

- **Add support for Sixel graphics protocol.**

Read more here:
- https://en.wikipedia.org/wiki/Sixel
- https://github.com/saitoha/PySixel
- https://github.com/saitoha/libsixel

And...
- Good discussion about supporting it in the recent Windows Terminal: https://github.com/microsoft/terminal/issues/448
- Plain C implementation inside MinTTY (Cygterm): https://github.com/mintty/mintty/search?q=sixel&unscoped_q=sixel

I hope someday this will be integrated in KiTTY (or PuTTY directly).

**Comment by cyd01** [comment]
Issue closed due to inactivity
